//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Game Studio.rc
//
#define IDR_MANIFEST                    1
#define ID_BUTTON_ADD                   3
#define IDOK2                           3
#define ID_BUTTON_EDIT                  4
#define IDCANCEL2                       4
#define ID_BUTTON_DEL                   5
#define ID_BUTTON_EDIT2                 6
#define ID_BUTTON_EDIT_COLOR            6
#define IDD_ABOUTBOX                    100
#define IDD_ATTR_PAGE                   107
#define IDR_MAINFRAME                   128
#define IDR_GameStudioTYPE              129
#define ID_VIEW_MENUBAR                 130
#define ID_VIEW_WORKSPACE               131
#define ID_VIEW_PREVIEW                 132
#define IDB_WORKSPACE_TAB               133
#define IDS_RESET_ATTRIBUTE             133
#define IDS_CANCEL_SAVE_HEIGHTMAP       134
#define IDD_DIALOG_PROGRESS             135
#define IDS_PROGRESS_UNIT               135
#define IDS_SAVE_HEIGHTMAPDATA          136
#define IDR_HIDDEN                      137
#define IDS_LOAD_REGION_DATA_TEX        137
#define IDS_SAVE_HEIGHTMAP              138
#define ID_PROGRESS_UPDATE              139
#define IDS_CANCEL_RESET_ATTRIBUTE      139
#define IDS_CANCEL_SAVE_MINIMAP         140
#define ID_PROGRESS_EXIT                141
#define IDS_TEMPFOLDER_GAMESTUDIO       141
#define IDS_SAVE_MINIMAP                142
#define IDS_LOAD_ANI                    143
#define IDS_LOAD_MESH                   144
#define ID_GRID_TOGGLE                  145
#define IDB_TREE_IMAGE                  146
#define IDS_ERR_NODETAILTEXINLIST       146
#define IDD_DIALOG_ATTR                 147
#define ID_NOT_MATCH_COUNT              147
#define IDD_TEXTURE                     148
#define IDS_CANCEL_RESETDETTEX          148
#define IDR_POPUP                       149
#define IDS_STRING149                   149
#define IDS_RESET_DETTEX                149
#define ID_ITEM_NEWPROJECT              150
#define IDR_GRIDTYPE                    151
#define IDS_ERR_SET_TEMPPATH            151
#define IDR_OBJECT                      152
#define IDS_ERR_INIT_TEMPPATH           152
#define IDR_MAPTYPE                     153
#define ID_CANCEL                       154
#define IDS_FMT_NEWPRJ                  155
#define ID_ITEM_NEWFOLDER               156
#define ID_ITEM_ADD                     157
#define ID_ITEM_UPDATE                  158
#define ID_ITEM_DELETE                  159
#define IDS_FMT_NEWFOLDER               160
#define IDD_DIALOG_ADDTEXTURE           161
#define IDS_ERR_NOFOLDERNAME            162
#define IDI_ICON_FOLDER                 163
#define IDS_ERR_INVALID_FILE            164
#define IDS_LOADGSF_CANCEL              165
#define IDS_DELETE_ITEM                 166
#define IDS_LOAD_GSF                    167
#define IDS_ERR_TITLE                   168
#define IDS_CHECKFILE_VALIDITY          169
#define IDS_LOAD_TEX                    170
#define IDS_LOAD_IMG                    171
#define IDS_LOAD_MEDIA                  172
#define IDS_LOAD_OBJ                    173
#define IDS_ERR_NOFILENAME              174
#define IDD_DIALOG_PREVIEW              175
#define IDS_ERR_DUPLICATEITEM           176
#define IDD_DIALOG_PLAYCTRL             177
#define IDI_ICON_PLAY                   178
#define IDI_ICON_STOP                   179
#define IDD_PLAYCTRL_BAR                180
#define IDC_CURSOR_HAND                 181
#define IDD_DIALOG_TIMESET              182
#define IDS_ERR_TOTALFRAME              183
#define IDI_ICON_SPHERE                 184
#define IDD_IMAGE                       185
#define IDS_ERR_TOTAL_TICK              186
#define IDI_ICON_BOX                    187
#define IDB_BITMAP_PREVIEW              188
#define IDD_DIALOG_ADDMEDIA             189
#define IDB_OBJTYPE_TAB                 190
#define IDI_ICON_PLANE                  191
#define IDD_MEDIA_BAR                   192
#define IDI_ICON_SETDIST                193
#define IDS_NOTUSE                      194
#define IDI_ICON_ADDLEVEL               195
#define IDD_DIALOG_ADDANIMATION         196
#define IDI_ICON_DELLEVEL               197
#define IDS_ERR_INVALID_ID              198
#define IDD_ANIMATION                   199
#define IDI_ICON_SELECT_ALL             200
#define IDS_ERR_DUP_ID                  201
#define IDD_DIALOG_TIMESCALE            202
#define IDI_ICON_UNSELECT_ALL           203
#define IDS_ERR_DUP_NAME                204
#define IDD_DIALOG_ADDMESH              205
#define IDI_ICON_INVSELECT              206
#define IDS_FMT_NEWTEXTURE              207
#define IDD_MESH                        208
#define IDI_ICON_LOAD_FROM_TMF          209
#define IDS_ADDTEXTURE                  210
#define IDD_OBJ_PAGE                    211
#define IDS_ADDIMAGE                    212
#define IDD_OBJECT                      213
#define IDS_FMT_NEWIMAGE                214
#define IDS_FMT_NEWANIMATION            215
#define ID_GRID_SHOW                    216
#define ID_GRID_TOP                     217
#define ID_GRID_FRONT                   218
#define ID_GRID_LEFT                    219
#define ID_GRID_PERSPECTIVE             220
#define ID_GRID_NAVIGATE                221
#define ID_GRID_CAMRESET                222
#define IDS_ERR_TIME_SCALE              223
#define IDS_ERR_INVALID_LOD_FILE        224
#define IDD_DIALOG_EDITOBJ              225
#define IDS_FMT_NEWOBJTYPE              226
#define IDI_ICON_DEL                    227
#define IDD_SFX                         228
#define IDS_FMT_NEWOBJECT               229
#define IDD_PARTICLE                    230
#define IDI_ICON_HOTTL                  231
#define IDS_ERR_DUP_ATTRID              232
#define IDD_EXTMAP                      233
#define IDI_ICON_HOTTC                  234
#define ID_OBJ_EDIT_ATTR                235
#define IDD_DIALOG_FRAMESET             236
#define IDI_ICON_HOTTR                  237
#define IDS_FMT_NEWOBJ                  238
#define IDD_MAPOBJ                      239
#define IDI_ICON_HOTCL                  240
#define IDS_FMT_SUBMESH                 241
#define IDD_BSPMAP                      242
#define IDI_ICON_HOTCC                  243
#define IDS_ERR_INVALID_FORMAT          244
#define IDD_DIALOG_ADDMAP               245
#define IDI_ICON_HOTCR                  246
#define IDS_FMT_PIVOT                   247
#define IDD_CONTROL                     248
#define IDI_ICON_HOTBL                  249
#define IDS_FMT_MESH                    250
#define IDD_FRAME                       251
#define IDI_ICON_HOTBC                  252
#define IDS_FMT_ANI                     253
#define IDD_DIALOG_FONT                 254
#define IDI_ICON_HOTBR                  255
#define IDS_FMT_NEWSFX                  256
#define IDD_DIALOG_MENU                 257
#define IDS_FMT_NEWEXTMAP               258
#define IDD_DIALOG_EXTMAP               259
#define IDS_FMT_NEWEXTMAPID             260
#define IDD_DIALOG_BUILDEM              261
#define IDS_BUILD_EXTMAP                262
#define IDD_DIALOG_BUILD_HEIGHT         263
#define IDS_CANCEL_BUILD_EXTMAP         264
#define IDD_MAPSFX                      265
#define IDS_BUILD_GEO                   266
#define IDD_MAPSND                      267
#define IDS_BUILD_SHADE                 268
#define IDD_DIALOG_UPDATE               269
#define IDS_BUILD_SKIN                  270
#define IDD_DIALOG_BSPMAP               271
#define IDS_BUILD_TEX                   272
#define IDD_DIALOG_BSPREBUILD           273
#define IDS_LOAD_MAP                    274
#define IDD_MAPLIGHT                    275
#define IDS_LOAD_SFX                    276
#define IDD_DIALOG_BUILDSHADE           277
#define IDS_SAVE_GSF                    278
#define IDD_DIALOG_BUILDSHADOW          279
#define IDS_SAVEGSF_CANCEL              280
#define IDS_SAVE_IMG                    281
#define IDS_SAVE_TEX                    282
#define IDS_SAVE_ANI                    283
#define IDS_SAVE_MAP                    284
#define IDS_SAVE_MEDIA                  285
#define IDS_SAVE_MESH                   286
#define IDS_SAVE_OBJ                    287
#define IDS_SAVE_SFX                    288
#define ID_BUILD                        289
#define IDS_BUILD_CANCEL                290
#define IDS_BUILD                       291
#define IDS_FMT_TEXIDX                  292
#define IDS_FMT_ANIIDX                  293
#define IDS_FMT_MESHIDX                 294
#define IDS_FMT_OBJIDX                  295
#define IDS_FMT_MAPIDX                  296
#define IDS_BUILD_TEXIDX                297
#define IDS_BUILD_TEXDAT                298
#define IDS_BUILD_ANIDAT                299
#define IDS_BUILD_ANIIDX                300
#define IDS_BUILD_MESHDAT               301
#define IDS_BUILD_MESHIDX               302
#define IDS_BUILD_OBJDAT                303
#define IDS_BUILD_OBJIDX                304
#define IDS_BUILD_MAPDAT                305
#define IDS_BUILD_MAPIDX                306
#define IDS_EXT_TEX                     307
#define IDS_EXT_ACT                     308
#define IDS_EXT_MESH                    309
#define IDS_EXT_OBJ                     310
#define IDS_EXT_MAP                     311
#define IDS_BUILD_HEADER                312
#define IDS_FMT_DEFINE                  313
#define IDS_REGULATE_SHADE              314
#define IDS_BUILD_SHADOW                315
#define IDS_CANCEL_BUILD_GEO            316
#define IDS_CANCEL_BUILD_SHADE          317
#define IDS_BUILD_GEOTEX                318
#define IDS_BUILD_SHADEDATA             319
#define ID_GRID_SHOW_EDGE               320
#define IDS_CANCEL_LOAD_GEOTEX          321
#define IDS_CANCEL_OL_GEOTEX            322
#define IDS_CANCEL_SAVE_GEOTEX          323
#define IDS_LOAD_GEOTEX                 324
#define IDS_OL_GEOTEX                   325
#define IDS_SAVE_GEOTEX                 326
#define ID_MAP_BACK                     327
#define IDS_FMT_NEWBSPMAP               328
#define IDS_FMT_NEWBSPMAPID             329
#define IDS_SAVE_FRAME                  330
#define IDS_SAVE_COMP                   331
#define IDS_LOAD_COMP                   332
#define IDS_LOAD_FRAME                  333
#define IDS_FMT_NEWFRAME                334
#define IDS_FMT_NEWFRAMEID              335
#define IDS_FMT_NEWCOMP                 336
#define IDR_TEXTURE_SFX                 337
#define IDS_FMT_NEWCOMPID               338
#define IDR_TEXTURE_SND                 339
#define IDS_FMT_NEWCTRL                 340
#define IDR_MESH_BOX                    341
#define IDS_FMT_NEWFONT                 342
#define IDS_FMT_NEWMENU                 343
#define IDS_LOAD_GLOBAL                 344
#define IDS_SAVE_GLOBAL                 345
#define IDR_TEXTURE_LIGHT               346
#define IDS_BUILD_IMGDAT                347
#define IDR_TEXTURE_LIGHTTARGET         348
#define IDS_BUILD_IMGIDX                349
#define IDS_FMT_IMGIDX                  350
#define IDS_EXT_IMG                     351
#define IDS_REGULATE_HEIGHT             352
#define IDS_REGULATE_SKIN               353
#define IDR_SHADER_PIXEL                354
#define IDR_PS_STAGE1                   355
#define IDS_BUILD_OBJBUF                356
#define IDS_CANCEL_EXPGEO               357
#define IDR_SHADER_VERTEX               358
#define IDR_VS_WMESH                    359
#define IDS_CANCEL_IMPGEO               360
#define IDS_CANCEL_EXPOBJ               361
#define IDR_VS_MESH                     362
#define IDS_CANCEL_IMPOBJ               363
#define IDR_VS_LVERTEX                  364
#define IDS_EXP_GEO                     365
#define IDR_PS_MODULATE                 366
#define IDS_IMP_GEO                     367
#define IDR_PS_MODULATE2X               368
#define IDS_EXP_OBJ                     369
#define IDR_PS_MODULATE4X               370
#define IDS_IMP_OBJ                     371
#define IDR_PS_ADD                      372
#define ID_MDI_NEXT                     373
#define IDS_BUILD_MEDIADAT              374
#define IDR_PS_ADDSIGNED                375
#define IDS_BUILD_MEDIAIDX              376
#define IDR_PS_ADDSIGNED2X              377
#define IDS_FMT_MEDIAIDX                378
#define IDR_PS_SUBTRACT                 379
#define IDS_BUILD_SFXDAT                380
#define IDR_PS_ADDSMOOTH                381
#define IDS_BUILD_SFXIDX                382
#define IDR_PS_BLENDDIFFUSEALPHA        383
#define IDS_FMT_SFXIDX                  384
#define IDR_PS_BLENDTEXTUREALPHA        385
#define IDS_EXT_MEDIA                   386
#define IDR_PS_BLENDFACTORALPHA         387
#define IDS_EXT_SFX                     388
#define IDR_PS_BLENDTEXTUREALPHAPM      389
#define IDS_UPDATETEXTURE               390
#define IDR_PS_BLENDCURRENTALPHA        391
#define IDS_UPDATEIMAGE                 392
#define IDS_UPDATEMEDIA                 393
#define IDR_PS_MODULATEALPHA_ADDCOLOR   394
#define IDS_UPDATEMESH                  395
#define IDR_PS_MODULATECOLOR_ADDALPHA   396
#define IDS_UPDATEANI                   397
#define IDR_PS_MODULATEINVALPHA_ADDCOLOR 398
#define IDS_EXT_TEXFILE                 399
#define IDR_PS_MODULATEINVCOLOR_ADDALPHA 400
#define IDS_EXT_MEDIAFILE               401
#define IDR_PS_DOTPRODUCT3              402
#define IDS_EXT_MESHFILE                403
#define IDR_PS_MULTIPLYADD              404
#define IDS_EXT_ANIFILE                 405
#define IDR_PS_LERP                     406
#define IDS_FILTER_TEXFILE              407
#define IDR_PS_SHADER                   408
#define IDS_FILTER_MEDIAFILE            409
#define IDR_PS_DETAILMAP                410
#define IDS_FILTER_MESHFILE             411
#define IDR_PS_MAP                      412
#define IDS_FILTER_ANIFILE              413
#define IDS_MERGEGSF_CANCEL             414
#define IDD_DIALOG_HIDE                 415
#define IDS_MERGE_GSF                   416
#define IDD_DIALOG_FREEZE               417
#define IDS_CANCEL_BUILD_BSPMAP         418
#define IDS_BUILD_BSPMAP                419
#define IDS_NODE_NULL                   420
#define IDS_ENABLE                      421
#define IDS_DISABLE                     422
#define IDS_BUILD_PVS                   423
#define IDI_ICON_MOVELEFT               424
#define IDS_CANCEL_BUILD_PVS            425
#define IDI_ICON_MOVERIGHT              426
#define IDS_SAVENEXIT                   427
#define IDD_DIALOG_SELBYNAME            428
#define IDS_NONAME                      429
#define IDS_ATTR_STRING                 430
#define IDS_ATTR_FLOAT                  431
#define IDS_ATTR_INT                    432
#define IDS_IMP_SFX                     433
#define IDD_DIALOG_SAVE_HEIGHTMAP       434
#define IDS_IMP_SND                     435
#define IDS_BUILD_TILETEX               436
#define IDS_CANCEL_BUILD_TILETEX        437
#define IDS_CANCEL_BUILD_SHADOWTEX      438
#define IDS_BUILD_SHADOWTEX             439
#define IDS_SAVE_HIGHTMAP               440
#define IDD_DIALOG_SETFOV               441
#define IDD_DIALOG_EDITFOV              442
#define IDD_DIALOG_FOV                  443
#define IDD_DIALOG_ITEM_ID_SEED         444
#define IDD_DIALOG_SAVE_MINIMAP         445
#define IDD_DIALOG_OBJECT_EXCHANGE      447
#define IDD_DIALOG_IMPORT_OFFSET        453
#define IDD_DIALOG_ADJUST_OBJ_POS       455
#define IDD_DIALOG_LOAD_REGION_TEX      457
#define IDD_DIALOG_FONT_EDIT_COLOR      458
#define IDD_DIALOG_EDIT_ENABLE_UNIT     459
#define IDD_DIALOG_EDIT_UNIT            461
#define IDD_DIALOG_EDIT_CLEAN_UNIT_OBJECT 462
#define IDD_DIALOG_SETBACKIMG           464
#define IDD_DIALOG_DETAILTEXTURE        466
#define IDD_DIALOG_SELECT_FORMAT        467
#define IDD_DIALOG_ITEMFINDER           468
#define IDD_DIALOG_ITEMSCREENSHOT       469
#define IDD_DIALOG_REPLACEDETTEX        470
#define IDC_PROGRESS                    1000
#define IDC_STATIC_PERCENT              1001
#define IDC_STATIC_STATUS               1002
#define IDC_RADIO_DATATYPE_INT          1003
#define IDC_RADIO_DATATYPE_FLOAT        1004
#define IDC_RADIO_STRING                1005
#define IDC_EDIT_VALUE                  1006
#define IDC_EDIT_IMAGEFILE              1007
#define IDC_EDIT_FOLDERNAME             1008
#define IDC_BUTTON_IMAGEFILE            1009
#define IDC_BUTTON_FOLDER               1010
#define IDC_COMBO_LOADTYPE              1011
#define IDC_STATIC_FILE                 1012
#define IDC_STATIC_FOLDER               1013
#define IDC_SLIDER_POSITION             1014
#define IDC_BUTTON_PLAY                 1015
#define IDC_BUTTON_STOP                 1016
#define IDC_CUSTOM_PLAYCTRL             1017
#define IDC_STATIC_TIC                  1018
#define IDC_STATIC_COLOR                1019
#define IDC_STATIC_CLRCTRL              1020
#define IDC_SPIN_KEY                    1021
#define IDC_STATIC_COLOR2               1021
#define IDC_EDIT_U                      1022
#define IDC_STATIC_CLRCTRL2             1022
#define IDC_SPIN_U                      1023
#define IDC_EDIT_V                      1024
#define IDC_SPIN_V                      1025
#define IDC_BUTTON_ADDKEY               1026
#define IDC_BUTTON_DELETEKEY            1027
#define IDC_EDIT_R                      1028
#define IDC_BUTTON_CLEARKEY             1028
#define IDC_SPIN_R                      1029
#define IDC_BUTTON_DELETE_IMAGE         1030
#define IDC_LIST_SPRITE                 1031
#define IDC_BUTTON_DELETE_IMAGE2        1031
#define IDC_BUTTON_ALL_MOVE             1031
#define IDC_BUTTON_MOVEUP               1032
#define IDC_BUTTON_MOVEDOWN             1033
#define IDC_STATIC_FRAME                1034
#define IDC_BUTTON_FIND_CTRL            1034
#define IDC_STATIC_KEY                  1035
#define IDC_BUTTON_FIND_COMP            1035
#define IDC_STATIC_MARKER               1036
#define IDC_BUTTON_FIND_CTRL3           1036
#define IDC_BUTTON_TIMESET              1037
#define IDC_STATIC_TOTAL_TICK           1038
#define IDC_BUTTON_SETPARTICLE          1039
#define IDC_EDIT_LODBIAS                1040
#define IDC_STATIC_TOTAL_FRAME          1041
#define IDC_SPIN_LODBIAS                1042
#define IDC_STATIC_TOTAL_TIME           1042
#define IDC_BUTTON_FIND_DEFIMG          1042
#define IDC_EDIT_TOTAL_TICK             1043
#define IDC_BUTTON_FIND_DISIMG          1043
#define IDC_EDIT_SU                     1044
#define IDC_EDIT_TOTAL_FRAME            1045
#define IDC_SPIN_SU                     1046
#define IDC_CHECK_LOOP                  1047
#define IDC_EDIT_SV                     1048
#define IDC_COMBO_MIPFILTER             1049
#define IDC_CHECK_REVERSE               1050
#define IDC_COMBO_FULLSIZE              1050
#define IDC_EDIT_ITEMID                 1051
#define IDC_COMBO_TEX_FORMAT            1051
#define IDC_CHECK_ANILOOP               1052
#define IDC_SPIN_SV                     1053
#define IDC_STATIC_PREVIEW              1054
#define IDC_STATIC_ID                   1055
#define IDC_RADIO_MESH_SPHERE           1056
#define IDC_RADIO_MESH_BOX              1057
#define IDC_EDIT_A                      1058
#define IDC_RADIO_MESH_PLANE            1059
#define IDC_EDIT_LIFETIME               1060
#define IDC_SPIN_A                      1061
#define IDC_EDIT_G                      1062
#define IDC_SPIN_G                      1063
#define IDC_EDIT_B                      1064
#define IDC_SPIN_B                      1065
#define IDC_EDIT_MEDIAFILE              1066
#define IDC_EDIT_LODLEVEL               1066
#define IDC_SPIN_LIFETIME               1067
#define IDC_BUTTON_MEDIAFILE            1068
#define IDC_SPIN_LODLEVEL               1068
#define IDC_EDIT_PLT                    1069
#define IDC_EDIT_SIZEX                  1070
#define IDC_SLIDER_VOLUME               1071
#define IDC_EDIT_CURLODLEVEL            1071
#define IDC_SPIN_PLT                    1072
#define IDC_EDIT_OPLEVEL                1072
#define IDC_SPIN_SIZEX                  1073
#define IDC_STATIC_VOLUME               1074
#define IDC_SPIN_CURLODLEVEL            1074
#define IDC_EDIT_PGT                    1075
#define IDC_SPIN_OPLEVEL                1075
#define IDC_EDIT_SIZEY                  1076
#define IDC_EDIT_ANIMATIONFILE          1077
#define IDC_EDIT_SETFPS                 1077
#define IDC_SPIN_PGT                    1078
#define IDC_SPIN_SETFPS                 1078
#define IDC_SPIN_SIZEY                  1079
#define IDC_BUTTON_ANIMATIONFILE        1080
#define IDC_EDIT_PGC                    1081
#define IDC_STATIC_TIMESCALE            1082
#define IDC_SPIN_PGC                    1083
#define IDC_EDIT_X                      1084
#define IDC_EDIT_PEPX                   1085
#define IDC_EDIT_Y                      1086
#define IDC_SPIN_PEPX                   1087
#define IDC_EDIT_Z                      1088
#define IDC_EDIT_PEPY                   1089
#define IDC_EDIT_RX                     1090
#define IDC_SPIN_PEPY                   1091
#define IDC_SPIN_X                      1092
#define IDC_EDIT_PEPZ                   1093
#define IDC_SPIN_Y                      1094
#define IDC_SPIN_PEPZ                   1095
#define IDC_SPIN_Z                      1096
#define IDC_EDIT_PERX                   1097
#define IDC_SPIN_RX                     1098
#define IDC_SPIN_PERX                   1099
#define IDC_EDIT_RY                     1100
#define IDC_EDIT_PERY                   1101
#define IDC_SPIN_RY                     1102
#define IDC_SPIN_PERY                   1103
#define IDC_EDIT_RZ                     1104
#define IDC_EDIT_PERZ                   1105
#define IDC_SPIN_RZ                     1106
#define IDC_SPIN_PERZ                   1107
#define IDC_EDIT_SX                     1108
#define IDC_EDIT_PESX                   1109
#define IDC_SPIN_SX                     1110
#define IDC_SPIN_PESX                   1111
#define IDC_EDIT_SY                     1112
#define IDC_EDIT_PESY                   1113
#define IDC_SPIN_SY                     1114
#define IDC_SPIN_PESY                   1115
#define IDC_EDIT_SZ                     1116
#define IDC_EDIT_PESZ                   1117
#define IDC_SPIN_SZ                     1118
#define IDC_SPIN_PESZ                   1119
#define IDC_LIST_ANIMATION              1120
#define IDC_EDIT_PET                    1121
#define IDC_EDIT_EVENT                  1122
#define IDC_SPIN_PET                    1123
#define IDC_EDIT_FOLLOW                 1124
#define IDC_EDIT_ANILOOPID              1125
#define IDC_SPIN_FOLLOW                 1126
#define IDC_BUTTON_DELETE_ANIMATION     1127
#define IDC_EDIT_TIME_SCALE             1128
#define IDC_EDIT_MESHFILE               1129
#define IDC_BUTTON_MESHFILE             1130
#define IDC_RADIO_EDITMODE              1131
#define IDC_RADIO_TESTMODE              1132
#define IDC_STATIC_MESHCOUNT            1133
#define IDC_STATIC_LEVELCOUNT           1134
#define IDC_STATIC_POLYCOUNT            1135
#define IDC_STATIC_SELECTEDCOUNT        1136
#define IDC_STATIC_LEVEL                1137
#define IDC_SPIN_LEVEL                  1138
#define IDC_BUTTON_ADDLEVEL             1139
#define IDC_BUTTON_DELLEVEL             1140
#define IDC_EDIT_DIST                   1141
#define IDC_SPIN_DIST                   1142
#define IDC_SLIDER_POLYGON              1143
#define IDC_BUTTON_SELECT_ALL           1144
#define IDC_BUTTON_SELECT_INV           1145
#define IDC_BUTTON_UNSELECT_ALL         1146
#define IDC_BUTTON_LOAD_FROM_TMF        1147
#define IDC_STATIC_CAMDIST              1148
#define IDC_BUTTON_SETDIST              1149
#define IDC_EDIT_POLY_LEVEL             1150
#define IDC_LIST_ATTR                   1151
#define IDC_SPIN_POLY_LEVEL             1152
#define IDC_LIST_ACTION                 1153
#define IDC_LIST_CLOTHKIND              1154
#define IDC_EDIT_ID                     1155
#define IDC_LIST_CLOTH                  1156
#define IDC_COMBO_TYPE                  1157
#define IDC_LIST_CLOTHDATA              1158
#define IDC_EDIT_ACTION                 1159
#define IDC_LIST_MESHORDER              1160
#define IDC_EDIT_CLOTHKIND              1161
#define IDC_EDIT_CLOTH                  1162
#define IDC_COMBO_PIVOT                 1163
#define IDC_EDIT_PIVOT                  1164
#define IDC_LIST_ECK                    1165
#define IDC_COMBO_EC                    1166
#define IDC_COMBO_ECD                   1167
#define IDC_COMBO_EA                    1168
#define IDC_EDIT_EO                     1169
#define IDC_BUTTON_DELEO                1170
#define IDC_COMBO_EANI                  1171
#define IDC_EDIT_COLORID                1172
#define IDC_COMBO_SOP                   1173
#define IDC_EDIT_MESHORDER              1174
#define IDC_LIST_SFX                    1176
#define IDC_COMBO_OEP                   1177
#define IDC_EDIT_POS_X                  1178
#define IDC_EDIT_POS_Y                  1179
#define IDC_EDIT_POS_Z                  1180
#define IDC_EDIT_ROT_X                  1181
#define IDC_EDIT_ROT_Y                  1182
#define IDC_RADIO_OSFX                  1183
#define IDC_RADIO_ASFX                  1184
#define IDC_RADIO_ANISFX                1185
#define IDC_EDIT_START                  1186
#define IDC_CHECK_DELONSTOP             1187
#define IDC_RADIO_OS                    1188
#define IDC_RADIO_AS                    1189
#define IDC_RADIO_ANIS                  1190
#define IDC_LIST_SOUNDID                1191
#define IDC_EDIT_SSTART                 1192
#define IDC_CHECK_SDELONSTOP            1193
#define IDC_RADIO_STAGE1                1194
#define IDC_RADIO_STAGE2                1195
#define IDC_RADIO_MITEX                 1196
#define IDC_RADIO_MICOLOR               1197
#define IDC_RADIO_MIENV                 1198
#define IDC_CHECK_EDITPIVOT             1199
#define IDC_CHECK_SHOW_SELECTED         1200
#define IDC_CHECK_2SIDE                 1201
#define IDC_SPIN_MESHORDER              1202
#define IDC_SPIN_ALPHA                  1203
#define IDC_SPIN_POSX                   1204
#define IDC_SPIN_POSY                   1205
#define IDC_SPIN_POSZ                   1206
#define IDC_SPIN_SL                     1207
#define IDC_SPIN_STARTAT                1208
#define IDC_SPIN_ROTX                   1209
#define IDC_CHECK_BATCH_REG_SNDFUNC     1209
#define IDC_SPIN_HMARGINE               1210
#define IDC_COPY_SND                    1210
#define IDC_SPIN_SSTARTAT               1211
#define IDC_SPIN_ROTY                   1212
#define IDC_SPIN_VMARGINE               1213
#define IDC_EDIT_ALPHA                  1214
#define IDC_SPIN_ROTZ                   1215
#define IDC_COPY_SND2                   1215
#define IDC_DELETE_CLOTHDATA            1215
#define IDC_SPIN_SCALEX                 1216
#define IDC_SPIN_MINALPHA               1217
#define IDC_EDIT_RVALUE                 1218
#define IDC_RADIO_PARTICLE              1219
#define IDC_FIND_OBJTEXTURE             1219
#define IDC_SPIN_SCALEY                 1220
#define IDC_EDIT_RVALUE2                1220
#define IDC_EDIT_GVALUE                 1221
#define IDC_RADIO_SINGLE                1222
#define IDC_EDIT_GVALUE2                1222
#define IDC_SPIN_SCALEZ                 1223
#define IDC_EDIT_BVALUE                 1224
#define IDC_EDIT_SRC                    1225
#define IDC_EDIT_BVALUE2                1225
#define IDC_RADIO_INSERT                1226
#define IDC_EDIT_ALPHA2                 1226
#define IDC_SPIN_RVALUE                 1227
#define IDC_BUTTON_DELSRC               1228
#define IDC_SPIN_RVALUE2                1228
#define IDC_RADIO_EDIT                  1229
#define IDC_SPIN_GVALUE                 1230
#define IDC_EDIT_ANISRC                 1231
#define IDC_SPIN_GVALUE2                1231
#define IDC_SPIN_RVALUEA                1232
#define IDC_SPIN_BVALUE                 1233
#define IDC_BUTTON_DELANISRC            1234
#define IDC_SPIN_BVALUE2                1234
#define IDC_SPIN_GVALUEA                1235
#define IDC_SPIN_ALPHA2                 1235
#define IDC_COMBO_CLK                   1236
#define IDC_SPIN_ROT_X                  1237
#define IDC_EDIT_BVALUEA                1238
#define IDC_COMBO_CL                    1239
#define IDC_BUTTON_SETBASIC             1240
#define IDC_SPIN_ROT_Y                  1241
#define IDC_SPIN_BVALUEA                1242
#define IDC_COMBO_MESH                  1243
#define IDC_COMBO_SPRAYKIND             1244
#define IDC_EDIT_ROT_Z                  1245
#define IDC_EDIT_LIGHTSRC               1246
#define IDC_COMBO_ACT                   1247
#define IDC_EDIT_MINX                   1248
#define IDC_SPIN_ROT_Z                  1249
#define IDC_BUTTON_DELLIGHTSRC          1250
#define IDC_COMBO_ANI                   1251
#define IDC_SPIN_MINX                   1252
#define IDC_EDIT_FUNCTION               1253
#define IDC_SPIN_RVALUED                1254
#define IDC_EDIT_MINY                   1255
#define IDC_SPIN_FUNCTION               1256
#define IDC_SPIN_GVALUED                1257
#define IDC_COMBO_BLENDOP               1258
#define IDC_SPIN_MINY                   1259
#define IDC_COMBO_BLENDOP2              1259
#define IDC_COMBO_DIROP                 1259
#define IDC_EDIT_OBJFUNC                1260
#define IDC_EDIT_BVALUED                1261
#define IDC_COMBO_BLENDOP3              1261
#define IDC_COMBO_USEDIRLIGHTOP         1261
#define IDC_EDIT_MINZ                   1262
#define IDC_SPIN_OBJFUNC                1263
#define IDC_SPIN_BVALUED                1264
#define IDC_SPIN_MINZ                   1265
#define IDC_EDIT_ACTFUNC                1266
#define IDC_EDIT_MAXX                   1267
#define IDC_SPIN_ACTFUNC                1268
#define IDC_SPIN_MAXX                   1269
#define IDC_EDIT_ANIFUNC                1270
#define IDC_EDIT_MAXY                   1271
#define IDC_SPIN_ANIFUNC                1272
#define IDC_SPIN_MAXY                   1273
#define IDC_EDIT_BIAS                   1274
#define IDC_COMBO_SRCBLEND              1275
#define IDC_EDIT_MAXZ                   1276
#define IDC_SPIN_BIAS                   1277
#define IDC_COMBO_SRCBLEND2             1278
#define IDC_COMBO_DESTBLEND             1279
#define IDC_SPIN_MAXZ                   1280
#define IDC_SPIN_MINALPHA2              1281
#define IDC_SPIN_INTENSITY              1282
#define IDC_EDIT_SANI                   1283
#define IDC_EDIT_SFXFUNCTION            1284
#define IDC_BUTTON_DELSANI              1285
#define IDC_SPIN_SFXFUNCTION            1286
#define IDC_EDIT_OBJSFXFUNC             1287
#define IDC_SPIN_OBJSFXFUNC2            1288
#define IDC_EDIT_ACTSFXFUNC             1289
#define IDC_SPIN_ACTSFXFUNC             1290
#define IDC_EDIT_ANISFXFUNC             1291
#define IDC_SPIN_ANIFUNC2               1292
#define IDC_SPIN_ANISFXFUNC             1293
#define IDC_EDIT_HEIGHT                 1294
#define IDC_LIST_GEOTEX                 1295
#define IDC_EDIT_MAXH                   1296
#define IDC_BUTTON_DELETE_SFX           1297
#define IDC_BUTTON_SHADE                1298
#define IDC_BUTTON_FINDSFX              1298
#define IDC_EDIT_UNIT                   1299
#define IDC_LIST_COMBINE                1300
#define IDC_BUTTON_GEOMETRY             1301
#define IDC_EDIT_TILE                   1302
#define IDC_LIST_UNIT                   1303
#define IDC_EDIT_CELL                   1304
#define IDC_BUTTON_ENABLE_ALL           1305
#define IDC_BUTTON_DISABLE_ALL          1306
#define IDC_BUTTON_BUILD_HEIGHT         1307
#define IDC_LIST_DETAILTEX              1308
#define IDC_SPIN_HEIGHT                 1309
#define IDC_SPIN_MAXH                   1310
#define IDC_BUTTON_EDIT_UNIT            1310
#define IDC_BUTTON_TILETEX              1311
#define IDC_SPIN_UNIT                   1312
#define IDC_BUTTON_EDIT_DETTEX          1312
#define IDC_BUTTON_SHADOWTEX            1313
#define IDC_SPIN_TILE                   1314
#define IDC_SPIN_UNIT2                  1315
#define IDC_SPIN_CELL                   1316
#define IDC_BUTTON_SAVE_GEOTEX          1317
#define IDC_BUTTON_LOAD_GEOTEX          1318
#define IDC_COMBO_SHAPE                 1319
#define IDC_COMBO_ATTENUATION           1320
#define IDC_EDIT_POSX                   1321
#define IDC_CHECK_EDIT_TEXTURE          1322
#define IDC_EDIT_POSY                   1323
#define IDC_CHECK_EDIT_HIDEMAP          1323
#define IDC_CHECK_EDIT_HEIGHT           1324
#define IDC_BUTTON_DELETE               1325
#define IDC_EDIT_TEXT                   1326
#define IDC_EDIT_SL                     1327
#define IDC_BUTTON_EDIT_OBJ             1328
#define IDC_EDIT_POSZ                   1329
#define IDC_RADIO_EXTMAP                1330
#define IDC_EDIT_TOOLTIP                1331
#define IDC_EDIT_HMARGINE               1332
#define IDC_BUTTON_EDIT_SFX             1333
#define IDC_EDIT_ROTX                   1334
#define IDC_RADIO_BSPMAP                1335
#define IDC_EDIT_VMARGINE               1336
#define IDC_EDIT_ROTY                   1338
#define IDC_EDIT_DEFIMG                 1339
#define IDC_BUTTON_OVERLAP              1340
#define IDC_SPIN_DETAIL_SCALE           1341
#define IDC_EDIT_ROTZ                   1342
#define IDC_BUTTON_DELDEFIMG            1343
#define IDC_BUTTON_PVS                  1344
#define IDC_BUTTON_OL_GEOTEX            1345
#define IDC_EDIT_SCALEX                 1346
#define IDC_BUTTON_LOAD_REGIONTEX       1346
#define IDC_EDIT_DISIMG                 1347
#define IDC_BUTTON_EDIT_LIGHT           1348
#define IDC_EDIT_SIZE                   1349
#define IDC_EDIT_SCALEY                 1350
#define IDC_BUTTON_DELDISIMG            1351
#define IDC_SPIN_SIZE                   1352
#define IDC_EDIT_SCALEZ                 1353
#define IDC_COMBO_CTRLTYPE              1354
#define IDC_BUTTON_TEXTFONT             1355
#define IDC_EDIT_FLATH                  1356
#define IDC_BUTTON_BACK                 1357
#define IDC_EDIT_WIDTH                  1358
#define IDC_SPIN_FLATH                  1359
#define IDC_SPIN_WIDTH                  1360
#define IDC_SPIN_FLATH2                 1360
#define IDC_BUTTON_DELETE2              1361
#define IDC_BUTTON_LANDING              1362
#define IDC_SPIN_FLATH3                 1362
#define IDC_SPIN_ADDFLATH               1362
#define IDC_CHECK_FLAT                  1363
#define IDC_BUTTON_OBJECT_EXCHANGE      1363
#define IDC_COMBO_USEAGE                1364
#define IDC_BUTTON_LANDING2             1364
#define IDC_BUTTON_RESETOBJ_ATTRI       1364
#define IDC_CHECK_ADDPLAT               1364
#define IDC_CHECK_ADDFLAT               1364
#define IDC_BUTTON_TIPFONT              1365
#define IDC_BUTTON_ADJUST_OBJECT_POS    1365
#define IDC_LIST_COMP                   1366
#define IDC_BUTTON_LANDING3             1366
#define IDC_EDIT_MENUID                 1367
#define IDC_CHECK_DISABLE_UNIT          1368
#define IDC_BUTTON_DELETE_CTRL          1369
#define IDC_EDIT_MINH                   1370
#define IDC_CHECK_EDIT_REGION           1371
#define IDC_EDIT_SOUND                  1372
#define IDC_LIST_CTRL                   1373
#define IDC_SPIN_MINH                   1374
#define IDC_EDIT_REGION                 1375
#define IDC_BUTTON_DELSOUND             1376
#define IDC_BUTTON_MENUID               1377
#define IDC_LIST_FONT                   1378
#define IDC_EDIT_LX                     1379
#define IDC_SPIN_REGION                 1380
#define IDC_LIST_MENU                   1381
#define IDC_SPIN_LX                     1382
#define IDC_BUTTON_EDIT_SND             1383
#define IDC_RADIO_HOT_TL                1384
#define IDC_EDIT_LY                     1385
#define IDC_CHECK_EDIT_DETAIL           1386
#define IDC_RADIO_HOT_TC                1387
#define IDC_SPIN_LY                     1388
#define IDC_CHECK_HBRUSH                1389
#define IDC_RADIO_HOT_TR                1390
#define IDC_EDIT_LZ                     1391
#define IDC_EDIT_HBRUSH                 1392
#define IDC_RADIO_HOT_CL                1393
#define IDC_SPIN_LZ                     1394
#define IDC_SPIN_HBRUSH                 1395
#define IDC_RADIO_HOT_CC                1396
#define IDC_CHECK_SMOOTH                1397
#define IDC_RADIO_HOT_CR                1398
#define IDC_EDIT_SPECRANGE              1399
#define IDC_RADIO_HOT_BL                1400
#define IDC_SPIN_SPECRANGE              1401
#define IDC_RADIO_HOT_BC                1402
#define IDC_EDIT_MAXCOLOR               1403
#define IDC_RADIO_HOT_BR                1404
#define IDC_SPIN_MAXCOLOR               1405
#define IDC_COMBO_ALIGN                 1406
#define IDC_CHECK_SPECULAR              1407
#define IDC_COMBO_NOTIFY                1408
#define IDC_CHECK_SPECULAR2             1409
#define IDC_BUTTON_SAVE_MINIMAP         1410
#define IDC_CHECK_STATEBTN              1411
#define IDC_BUTTON_SAVE_Shadow          1411
#define IDC_CHECK_PASSWD                1412
#define IDC_BUTTON_LOAD_MINIMAP3        1412
#define IDC_BUTTON_LOAD_SHADOW          1412
#define IDC_CHECK_CUSTOMCLR             1413
#define IDC_BUTTON_SAVE_HEIGHTMAP       1414
#define IDC_EDIT_COUNT_Y                1415
#define IDC_SPIN_COUNT_Y                1416
#define IDC_EDIT_COUNT_X                1417
#define IDC_SPIN_COUNT_X                1418
#define IDC_RADIO_ALL_UNIT              1419
#define IDC_RADIO_SEL_UNIT              1420
#define IDC_BUTTON_SETESTART            1421
#define IDC_BUTTON_SETSSTART            1422
#define IDC_STATIC_SFX                  1423
#define IDC_STATIC_SND                  1424
#define IDC_EDIT_FILE                   1425
#define IDC_BUTTON_FILE                 1426
#define IDC_CHECK_PVS                   1427
#define IDC_STATIC_NODEID               1428
#define IDC_CHECK_TEX                   1429
#define IDC_STATIC_TOTAL                1430
#define IDC_CHECK_OBJ                   1431
#define IDC_STATIC_NODE                 1432
#define IDC_CHECK_SFX                   1433
#define IDC_STATIC_PVS                  1434
#define IDC_CHECK_SND                   1435
#define IDC_STATIC_PVSINFO              1436
#define IDC_CHECK_LIGHT                 1437
#define IDC_BUTTON_REBUILD              1438
#define IDC_BUTTON_ADD                  1439
#define IDC_STATIC_AMBIENT              1440
#define IDC_STATIC_AMBIENTCTRL          1441
#define IDC_STATIC_DIFFUSE              1442
#define IDC_STATIC_DIFFUSECTRL          1443
#define IDC_EDIT_RVALUEA                1444
#define IDC_EDIT_GVALUEA                1445
#define IDC_EDIT_RVALUED                1446
#define IDC_EDIT_GVALUED                1447
#define IDC_EDIT_DIRX                   1448
#define IDC_SPIN_DIRX                   1449
#define IDC_EDIT_DIRY                   1450
#define IDC_SPIN_DIRY                   1451
#define IDC_EDIT_DIRZ                   1452
#define IDC_SPIN_DIRZ                   1453
#define IDC_CHECK_USE_DYNAMIC           1454
#define IDC_CHECK_USE_LIGHTMAP          1455
#define IDC_STATIC_ATTRTYPE             1456
#define IDC_EDIT_RANGE                  1457
#define IDC_CHECK_FOLLOW                1458
#define IDC_SPIN_RANGE                  1459
#define IDC_CHECK_STRICT                1460
#define IDC_EDIT_MINALPHA               1461
#define IDC_EDIT_ROT                    1462
#define IDC_EDIT_INTENSITY              1463
#define IDC_SPIN_PPT                    1464
#define IDC_SPIN_ROT                    1465
#define IDC_CHECK_ZENABLE               1466
#define IDC_EDIT_PPT                    1467
#define IDC_CHECK_ZWRITE                1468
#define IDC_LIST_NONFREEZE              1469
#define IDC_CHECK_USEDIRLIGHT           1469
#define IDC_LIST_FREEZE                 1470
#define IDC_LIST_HIDE                   1471
#define IDC_LIST_NONHIDE                1472
#define ID_BUTTON_NONHIDE               1473
#define ID_BUTTON_HIDE                  1474
#define ID_BUTTON_NONFREEZE             1475
#define ID_BUTTON_FREEZE                1476
#define IDC_LIST_OBJECT                 1477
#define IDC_BUTTON_HIDE                 1478
#define IDC_BUTTON_FREEZE               1479
#define IDC_BUTTON_UNHIDEALL            1480
#define IDC_BUTTON_UNFREEZEALL          1481
#define IDC_EDIT_HEIGHT_MIN             1482
#define IDC_BUTTON_HIDECOLL             1482
#define IDC_EDIT_HEIGHT_MAX             1483
#define IDC_BUTTON_HIDE3                1483
#define IDC_BUTTON_UNHIDECOLL           1483
#define IDC_SPIN_H_MIN                  1484
#define IDC_SPIN_H_MAX                  1485
#define IDC_EDIT_SETFOV                 1486
#define IDC_BUTTON_HIDESILH             1486
#define IDC_EDIT_FOV                    1487
#define IDC_BUTTON_UNHIDESILH           1487
#define IDC_STATIC_ID_ANIMATION         1488
#define IDC_BUTTON_HIDEWATER            1488
#define IDC_STATIC_ID_OBJECTTYPE        1489
#define IDC_BUTTON_UNHIDESILH2          1489
#define IDC_BUTTON_UNHIDEWATER          1489
#define IDC_STATIC_ID_TEXTURE           1490
#define IDC_STATIC_ID_IMAGE             1491
#define IDC_STATIC_ID_MEDIA             1492
#define IDC_STATIC_ID_FRAME             1493
#define IDC_STATIC_ID_COMPONENT         1494
#define IDC_STATIC_ID_MESH              1495
#define IDC_STATIC_ID_MAP               1496
#define IDC_STATIC_OBJECT               1497
#define IDC_STATIC_ID_SFX               1498
#define IDC_EDIT1                       1499
#define IDC_BUTTON1                     1500
#define IDC_EDIT_MOVE_OFFSET_Z          1500
#define IDC_BUTTON_MAKE_SAMPLE_COLOR    1500
#define IDC_BUTTON_MAKE_REGIONTEX       1500
#define IDC_BUTTON_EDIT_UNIT_ENABLE     1500
#define IDC_EDIT2                       1500
#define IDC_EDIT_FONT_VIEW_TIP          1500
#define IDC_EDIT_ENABLEUNIT             1500
#define IDC_EDIT_RECT_STARTZ            1500
#define IDC_BUTTON_UP                   1500
#define IDC_BUTTON_CLEAN_ALL            1500
#define IDC_FINDNEXT                    1500
#define IDC_EDIT_SC_COLORG              1500
#define IDC_CHECK_DELETEANI             1500
#define IDC_BUTTON_SELOBJ_SEL           1501
#define IDC_EDIT_RECT_ENDX              1501
#define IDC_BUTTON_DOWN                 1501
#define IDC_EDIT_SC_COLORB              1501
#define IDC_EDIT_IMAGESIZE              1502
#define IDC_EDIT_RECT_ENDZ              1502
#define IDC_BUTTON_REPLACE              1502
#define IDC_BUTTON2                     1503
#define IDC_BUTTON_CLEAN_UNIT_OBJ       1503
#define IDC_BUTTON_IMPORT               1503
#define IDC_PRINTLIST                   1503
#define IDC_BUTTON_EANBLE_UNIT_LIST     1503
#define IDC_BUTTON_SELOBJ_DELETE        1504
#define IDC_BUTTON_EXPORT               1504
#define IDC_PRINTLIST2                  1504
#define IDC_EXPORTIMGS                  1504
#define IDC_BUTTON3                     1504
#define IDC_RADIO_ENABLEOBJ             1505
#define IDC_BUTTON_EXPORT2              1505
#define IDC_BUTTON_SAVETEX              1505
#define IDC_RADIO2                      1506
#define IDC_RADIO_OBJ_ATTACH            1506
#define IDC_RADIO_DIR_EIGHT             1506
#define IDC_RADIO_IOP_CUSTOM            1506
#define IDC_RADIO_ALLUNIT_OBJ           1506
#define IDC_RADIO_ALLOBJ                1507
#define IDC_RADIO_CURRENT_UNIT          1507
#define IDC_RADIO_CURRENT_UNIT_OBJ      1507
#define IDC_EDIT_OBJBRUSH_SIZE          1508
#define IDC_COMBO_OBJBRUSH_SHAPE        1509
#define IDC_SPIN_OBJBRUSH_SIZE          1510
#define IDC_CHECK_INSERTOBJBYBRUSH      1511
#define IDC_COMBO_OBJBRUSH_SHAPE2       1512
#define IDC_COMBO_OBJXY_SHAPE2          1512
#define IDC_RADIO_OBJ_REPLACE           1514
#define IDC_EDIT_OBJCOUNT               1515
#define IDC_SPIN_OBJBRUSH_SIZE2         1516
#define IDC_SPIN_OBJCOUNT               1516
#define IDC_EDIT_OBJCOUNT2              1518
#define IDC_EDIT_OBJSCALE_MAX           1518
#define IDC_EDIT_SELOBJ_COUNT           1519
#define IDC_EDIT_OBJSCALE_MIN           1520
#define IDC_CHECK1                      1523
#define IDC_CHECK_ANG_1                 1523
#define IDC_CHECK_CUSTOM_OBJHEIGHT      1523
#define IDC_CHECK_ALLOBJ                1523
#define IDC_CHECK_OBJ_MOVE_OFFSET       1523
#define IDC_CHECK_SCREENFIX             1523
#define IDC_CHECK_MINIMAP_OBJ_COLLISION_AREA 1523
#define IDC_CHECK_CUSTOM_AREA           1523
#define IDC_CHECK_SHOW_TILING           1523
#define IDC_GROUP                       1523
#define IDC_CHECK_SECLECT_OBJECT        1524
#define IDC_CHECK2                      1524
#define IDC_CHECK_ANG_2                 1524
#define IDC_CHECK_CONSTRAIN             1524
#define IDC_CHECK3                      1525
#define IDC_CHECK_ANG_3                 1525
#define IDC_CHECK_FIXPOS                1525
#define IDC_CHECK4                      1526
#define IDC_CHECK_ANG_4                 1526
#define IDC_CHECK5                      1527
#define IDC_CHECK_ANG_17                1527
#define IDC_CHECK6                      1528
#define IDC_CHECK_ANG_18                1528
#define IDC_CHECK7                      1529
#define IDC_CHECK_ANG_19                1529
#define IDC_CHECK8                      1530
#define IDC_CHECK_ANG_20                1530
#define IDC_CHECK9                      1531
#define IDC_CHECK_ANG_5                 1531
#define IDC_CHECK10                     1532
#define IDC_CHECK_ANG_6                 1532
#define IDC_CHECK11                     1533
#define IDC_CHECK_ANG_7                 1533
#define IDC_CHECK12                     1534
#define IDC_CHECK_ANG_8                 1534
#define IDC_CHECK13                     1535
#define IDC_CHECK_ANG_21                1535
#define IDC_CHECK14                     1536
#define IDC_CHECK_ANG_22                1536
#define IDC_CHECK15                     1537
#define IDC_CHECK_ANG_23                1537
#define IDC_CHECK16                     1538
#define IDC_CHECK_ANG_24                1538
#define IDC_CHECK17                     1539
#define IDC_CHECK_ANG_9                 1539
#define IDC_CHECK18                     1540
#define IDC_CHECK_ANG_10                1540
#define IDC_CHECK19                     1541
#define IDC_CHECK_ANG_11                1541
#define IDC_CHECK20                     1542
#define IDC_CHECK_ANG_12                1542
#define IDC_CHECK21                     1543
#define IDC_CHECK_ANG_25                1543
#define IDC_CHECK22                     1544
#define IDC_CHECK_ANG_26                1544
#define IDC_CHECK23                     1545
#define IDC_CHECK_ANG_27                1545
#define IDC_CHECK24                     1546
#define IDC_CHECK_ANG_28                1546
#define IDC_CHECK25                     1547
#define IDC_CHECK_ANG_13                1547
#define IDC_CHECK26                     1548
#define IDC_CHECK_ANG_14                1548
#define IDC_CHECK27                     1549
#define IDC_CHECK_ANG_15                1549
#define IDC_CHECK28                     1550
#define IDC_CHECK_ANG_16                1550
#define IDC_CHECK29                     1551
#define IDC_CHECK_ANG_29                1551
#define IDC_CHECK30                     1552
#define IDC_CHECK_ANG_30                1552
#define IDC_CHECK31                     1553
#define IDC_CHECK_ANG_31                1553
#define IDC_CHECK32                     1554
#define IDC_CHECK_ANG_32                1554
#define IDC_CHECK_ANG_33                1555
#define ID_MAKE_FAR_IMAGE               1555
#define IDC_RADIO_DIR_FOUR              1556
#define IDC_RADIO_DIR_SIXTEEN           1557
#define IDC_RADIO_THIRTYTWO             1558
#define IDC_RADIO_DIR_FOURX             1559
#define IDC_RADIO_IOP_ORIGINAL          1560
#define IDC_EDIT_IOP_HEIGHT             1562
#define IDC_EDIT_IOP_POSX               1566
#define ID_IMP_OK                       1567
#define IDC_RADIO_CURUNIT_OBJ           1568
#define IDC_RADIO_SPECIFY_OBJ           1568
#define IDC_COMBO_UNIT_X                1569
#define IDC_COMBO_UNIT_Z                1570
#define IDC_EDIT_MOVE_OFFSET_X          1571
#define IDC_RADIO_REPLACE               1573
#define IDC_RADIO3                      1574
#define IDC_RADIO_ATTACH                1574
#define IDC_STATIC_FONT_CLRCTRL         1575
#define IDC_EDIT_FONT_BVALUE            1576
#define IDC_EDIT_FONT_GVALUE            1577
#define IDC_EDIT_FONT_RVALUE            1578
#define IDC_FONT_SPIN_RVALUE            1579
#define IDC_FONT_SPIN_GVALUE            1580
#define IDC_FONT_SPIN_BVALUE            1581
#define IDC_STATIC_FONT_COLOR           1582
#define IDC_EDIT_FONT_COLOR_DWORD       1583
#define IDC_EDIT_FONT_COLOR_HEX         1583
#define IDC_LIST_ENABLE_EXPORT          1592
#define IDC_LIST_DISABLE_EXPORT         1593
#define ID_BUTTON_DISABLE               1594
#define ID_BUTTON_ENABLE                1596
#define IDC_COMBO_UNIT_POS_X            1597
#define IDC_COMBO_UNIT_POS_Z            1598
#define ID_BUTTON_CLEAN_UNIT_OBJ        1599
#define IDC_EDIT_FONT_VIEW_TEXT         1600
#define IDC_CHECK_USEVB                 1601
#define IDC_EDIT_DISABLEUNIT            1602
#define IDC_SCROLL_DIST                 1605
#define IDC_SCROLL_SIZEX                1606
#define IDC_SCROLL_SIZEY                1607
#define IDC_EDIT_RATE_SIZEX             1610
#define IDC_EDIT_RATE_SIZEY             1611
#define IDC_EDIT_RECT_STARTX            1613
#define IDC_EDIT3                       1614
#define IDC_LIST_DETTEX                 1616
#define IDC_EDIT_SCALE                  1618
#define IDC_COMBO_IMG_FORMAT            1623
#define IDC_COMBO1                      1624
#define IDC_COMBO_GROUPROT              1625
#define IDC_COMBO_SC_SAVEMODE           1625
#define IDC_BUTTON_FINDOBJ              1626
#define IDC_COMBO_SC_TEXTURESIZE        1626
#define IDC_COMBO_SC_TEXTURETYPE        1627
#define IDC_FINDITEMNAME                1628
#define IDC_STATIC_FINDITEM             1629
#define IDC_COMBO_ITEM                  1631
#define IDC_COMBO_SC_ITEMTYPE           1634
#define IDC_SPIN_SC_COLORR              1641
#define IDC_SPIN_SC_COLORG              1642
#define IDC_SPIN_SC_COLORB              1643
#define IDC_EDIT_SC_COLORR              1644
#define IDC_EDIT_SC_CAMDIST             1645
#define IDC_SPIN_SC_CAMDIST             1646
#define IDC_EDIT_SC_CAMROTX             1647
#define IDC_SPIN_SC_CAMROTX             1648
#define IDC_SC_PREVIEW                  1649
#define IDC_PROGRESS_SC                 1651
#define IDC_STATIC_SC_OPDIR             1652
#define IDC_RADIO_FINDNAME              1653
#define IDC_RADIO_FINDID                1654
#define IDC_RADIO_FNDALL                1655
#define IDC_RADIO_FNDFOLDWER            1656
#define IDC_RADIO_UNIQUEID              1657
#define IDC_CHECK_DELSOUND              1660
#define IDC_CHECK_DELEFFECT             1661
#define ID_BUTTON_CDATAUP               1662
#define ID_BUTTON_CDATAUP2              1663
#define ID_BUTTON_CDATADOWN             1663
#define IDC_EDIT_ADDFLATH               1663
#define IDC_EDIT_LEFT_FROM              1664
#define IDC_EDIT_TOP_FROM               1665
#define IDC_LIST1                       1665
#define IDC_LIST_HEBA                   1665
#define IDC_EDIT_WIDTH_FROM             1666
#define IDC_BUTTON_SFXUP                1666
#define IDC_EDIT_HEIGHT_FROM            1667
#define IDC_BUTTON_SFXDOWN              1667
#define IDC_EDIT_LEFT_TO                1668
#define IDC_COMBO_HEBA_ACT              1668
#define IDC_EDIT_TOP_TO                 1669
#define IDC_BUTTON_HEBA_DELETE          1669
#define IDC_BUTTON_HEBA_ADD             1670
#define IDC_LIST3                       1672
#define IDC_STATIC_DETAILTEX            1673
#define ID_EXP_OBJ                      32793
#define ID_IMP_OBJ                      32794
#define ID_EXP_GEO                      32795
#define ID_IMP_GEO                      32796
#define ID_EDITMENU                     32797
#define ID_EDITFONT                     32798
#define ID_FILE_MERGE                   32799
#define ID_EXP_BSP                      32800
#define ID_IMP_BSP                      32801
#define ID_EXP_BSPOBJ                   32802
#define ID_IMP_BSPOBJ                   32803
#define ID_FREEZEMODE_DIALOG            32804
#define ID_SELBYNAME_DIALOG             32805
#define ID_HIDEMODE_DIALOG              32806
#define ID_OBJECTALLLIST_DIALOG         32807
#define ID_EDIT_FOV                     32808
#define ID_HOTKEY_EDIT_TEXTURE          32809
#define ID_HOTKEY_EDIT_DETAIL           32810
#define ID_HOTKEY_EDIT_HEIGHT           32811
#define ID_HOTKEY_MAKE_FLAT             32812
#define ID_HOTKEY_MAKE_SMOOTH           32813
#define ID_HOTKEY_HEIGHT_BRUSH          32814
#define ID_HOTKET_EDIT_OBJECT           32815
#define ID_GROUP_OBJECT_KEY_1           32816
#define ID_GROUP_OBJECT_KEY_2           32817
#define ID_GROUP_OBJECT_KEY_3           32818
#define ID_GROUP_OBJECT_KEY_4           32819
#define ID_GROUP_OBJECT_KEY_5           32820
#define ID_GROUP_OBJECT_KEY_6           32821
#define ID_GROUP_OBJECT_KEY_7           32822
#define ID_GROUP_OBJECT_KEY_8           32823
#define ID_GROUP_OBJECT_KEY_9           32824
#define ID_GROUP_OBJECT_KEY_0           32825
#define ID_SELECT_EQUALOBJ              32827
#define ID_CLEAR_SELOBJ                 32829
#define ID_Menu                         32831
#define ID_REGULATE_ITEM_TEX            32835
#define ID_REGULATE_TEX                 32836
#define ID_EXTMAPITEM_REGULATE_TEX      32837
#define ID_EXTMAPITEM_SS                32838
#define ID_RESET_VB                     32841
#define ID_NOTUSE_VB                    32844
#define ID_BUTTON32845                  32845
#define ID_MAP_ENABLEUNIT               32847
#define ID_GRID_BACKIMAGE               32848
#define ID_BACKIMG_SET                  32851
#define ID_BACKIMG_SHOW                 32852
#define ID_BACKIMG_LOAD                 32854
#define ID_BACKIMAGE_SETBACKIMAGE       32855
#define ID_MENU_OPTIONSIZE              32860
#define ID_MENU_FULLSIZE                32861
#define ID_MENU_TEXHI                   32864
#define ID_MENU_TEXMID                  32865
#define ID_MENU_TEXLOW                  32867
#define ID_MAP_EDITDETAIL               32871
#define ID_ITEM_EXPORT                  32873
#define ID_MENU_AUTOLOD                 32876
#define ID_TOGGLE_BRUSHSHAPE            32881
#define ID_EXT_BUILDTEXTURESHADOW       32885
#define ID_ITEM_BATCHFORMATCHANGE       32888
#define ID_MENU_LOCEXP                  32889
#define ID_MENU_LOCIMP                  32890
#define ID_EXPORTITEMINFOLDER           32893
#define ID_FOLDER_LISTUP                32894
#define ID_BUTTON32896                  32896
#define ID_MENU_LISTUPDATE              32896
#define ID_FINDER                       32898
#define ID_Menu32904                    32904
#define ID_ITEM_SCREENSHOT              32905
#define ID_MENU_UPDATE_SIZE             32914
#define ID_BTN_EXPLORER                 32917
#define ID_GRID_EXPLORER                32918
#define ID_FILE_SET_TEMPPATH            32920

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        471
#define _APS_NEXT_COMMAND_VALUE         32921
#define _APS_NEXT_CONTROL_VALUE         1674
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
