//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TTranslator.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TTRANSLATOR_DIALOG          102
#define IDS_FMT_LIST_FILE               102
#define IDS_FMT_PATH                    103
#define IDS_FMT_REPLACE                 104
#define IDS_ERROR_INVALID_SRC_DATA      105
#define IDS_FMT_LOG_FILE                106
#define IDS_LOG_BEGIN_BUILD             107
#define IDS_LOG_END_BUILD               108
#define IDS_LOG_BEGIN_LOAD_DB           109
#define IDS_LOG_END_LOAD_DB             110
#define IDS_LOG_FMT_START_TXT           111
#define IDS_LOG_FMT_END_TXT             112
#define IDS_LOG_TEXT_PATH               113
#define IDS_LOG_SOURCE_PATH             114
#define IDS_LOG_TARGET_PATH             115
#define IDS_LOG_TEXT_KIND               116
#define IDS_LOG_ERR_DUP_WORD            117
#define IDS_LOG_FIELD_COUNT             118
#define IDS_LOG_ROW_COUNT               119
#define IDS_LOG_ERR_DUP_STRING_ID       120
#define IDS_LOG_ERR_DUP_DWORD_ID        121
#define IDS_FILE_IDH                    122
#define IDS_ERROR_LOAD_IDH              123
#define IDS_LOG_ERR_INVALID_FORMAT_STRING 124
#define IDS_FMT_PAIR_ID                 125
#define IDS_FMT_ACCESSID_DB_NAME        126
#define IDS_FMT_TRIPLE_ID               127
#define IDR_MAINFRAME                   128
#define IDS_FMT_FILE_PORTAL_REGION_TCD  128
#define IDI_ICON_FOLDER                 129
#define IDS_FMT_FILE_MONSTER_SHOP_TCD   129
#define IDD_PROGRESS_DIALOG             129
#define IDS_FMT_FILE_ITEM_MAGIC_TCD     130
#define IDR_MENU_COMMAND                130
#define IDS_FMT_FILE_MONTH_RANK_TCD     131
#define IDS_FMT_FILE_GOD_TOWER_TCD      132
#define IDS_FMT_FILE_GOD_BALL_TCD       133
#define IDS_FMT_FILE_AUCTION_TCD        134
#define IDS_FMT_FILE_MONSTER_TCD        135
#define IDS_FMT_FILE_PORTAL_TCD         136
#define IDS_FMT_FILE_SKILL_TCD          137
#define IDS_FMT_FILE_ITEM_TCD           138
#define IDS_FMT_FILE_NPC_TCD            139
#define IDS_FMT_FILE_ACTION_DEFINE_TCD  140
#define IDS_FMT_FILE_REGION_TCD         141
#define IDS_FMT_FILE_COUNTRY_INFO_TCD   142
#define IDS_FMT_FILE_DYNAMIC_HELP_TCD   143
#define IDS_FMT_FILE_INFO_TCD           144
#define IDS_FMT_FILE_CLASS_INFO_TCD     145
#define IDS_FMT_FILE_MENU_ITEM_TCD      146
#define IDS_FMT_FILE_RACE_INFO_TCD      147
#define IDS_FMT_FILE_HELP_TCD           148
#define IDS_FMT_FILE_TGAME_SQL          149
#define IDS_FMT_FILE_TQUEST_SQL         150
#define IDS_LOG_BEGIN_CONVERT           151
#define IDS_LOG_END_CONVERT             152
#define IDS_LOG_FMT_START_CLIENT_FILE   153
#define IDS_LOG_FMT_END_CLIENT_FILE     154
#define IDS_FMT_FILE_MPQ                155
#define IDS_FMT_FILE_TIF                156
#define IDS_LOG_ERROR_FILE_OPEN         157
#define IDS_FMT_PATH_CLIENT             158
#define IDS_FMT_PATH_SERVER             159
#define IDS_FMT_PATH_TCD                160
#define IDS_LOG_ERROR_CANNOT_FIND_STRING 161
#define IDS_LOG_SUCCESS_COUNT           162
#define IDS_LOG_ERROR_CANNOT_FIND_TID   163
#define IDS_FMT_MONSTER_ID              164
#define IDS_FMT_INTERFACE_ID            165
#define IDS_FMT_MONSTER_SQL             166
#define IDS_FMT_SKILL_SQL               167
#define IDS_FMT_ITEM_SQL                168
#define IDS_FMT_NPC_SQL                 169
#define IDS_LOG_ERROR_INVALID_SOURCE_TEXT 170
#define IDS_LOG_ERROR_CANNOT_FIND_STR_ID 171
#define IDS_LOG_ERROR_CANNOT_FIND_DWORD_ID 172
#define IDS_LOG_ERROR_INFO_TITLE_IS_EMPTY 173
#define IDS_FMT_TQCATEGORY_SQL          174
#define IDS_FMT_TERM_ID                 175
#define IDS_LOG_ERROR_CANNOT_FIND_TERM_ID 176
#define IDS_LOG_ERROR_CANNOT_FIND_MISSION 177
#define IDS_FMT_QUEST_SQL               178
#define IDS_FMT_TERM_SQL                179
#define IDS_LOG_ERROR_CANNOT_FIND_TSTRING 180
#define IDS_FMT_FILE_TSTRING_TCD        181
#define IDS_LOG_FMT_START_SQL_FILE      182
#define IDS_LOG_FMT_END_SQL_FILE        183
#define IDS_FMT_FILE_TEVENT_SQL         184
#define IDS_FMT_TBATTLEZONE_SQL         185
#define IDS_FMT_START_BATTLE_ZONE       186
#define IDS_FMT_START_MONSTER           187
#define IDS_FMT_START_SKILL             188
#define IDS_FMT_START_ITEM              189
#define IDS_FMT_START_NPC               190
#define IDS_FMT_START_QTITLE            191
#define IDS_FMT_START_QTERM             192
#define IDS_FMT_START_QCLASS            193
#define IDS_FMT_START_TEVENT            194
#define IDS_FMT_TEVENT_SQL              195
#define IDS_FMT_WAIT                    196
#define IDS_FMT_ACTION_LOAD             197
#define IDS_FMT_ACTION_BUILD            198
#define IDS_FMT_ACTION_LOAD_SUB         199
#define IDS_FMT_ACTION_BUILD_SUB        200
#define IDS_FMT_BUILD_COMPLETED         201
#define IDS_ERROR_CANNOT_CREATE_THREAD  202
#define IDS_FMT_PROGRESS                203
#define IDS_FMT_CANCEL_BUILD            204
#define IDS_FMT_ACTION_CANCEL           205
#define IDS_LOG_BUILD_CANCEL            206
#define IDS_FMT_BUILD_CANCEL            207
#define IDS_FMT_START_DHELP             208
#define IDS_FMT_THELPMESSAGETABLE_SQL   209
#define IDS_FMT_NPC_NAME                210
#define IDS_FMT_START_SVRMSG            211
#define IDS_FMT_SVRMSG_SQL              212
#define IDS_FMT_START_TOURNAMENT        213
#define IDS_FMT_TOURNAMENT_SQL          214
#define IDS_FMT_START_TOURNAMENTSCHEDULE 215
#define IDS_FMT_TOURNAMENTSCHEDULE_SQL  216
#define IDS_STRING217                   217
#define IDC_BUTTON_BUILD                1000
#define IDC_COMBO_LANGUAGE_TO           1001
#define IDC_EDIT_TARGET                 1002
#define IDC_PROGRESS_TOTAL              1003
#define IDC_BUTTON_TARGET               1004
#define IDC_PROGRESS_CURRENT            1005
#define IDC_EDIT_TEXT_FOLDER            1006
#define IDC_BUTTON_TEXT_FOLDER          1007
#define IDC_EDIT_SOURCE                 1008
#define IDC_BUTTON_SOURCE               1009
#define IDC_STATIC_ACTION               1010
#define IDC_COMBO_LANGUAGE_FROM         1011
#define IDC_STATIC_TOTAL                1011
#define IDC_STATIC_CURRENT              1012
#define ID_MENU_UPDATE                  32773
#define ID_MENU_CLOSE                   32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
