#include "StdAfx.h"

BEGIN_INIT_QUERY(TLoginSvr)
	PREDEFINE_QUERY(CTBLChannel)
	PREDEFINE_QUERY(CTBLGroup)
	PREDEFINE_QUERY(CTBLGroupList)

	PREDEFINE_QUERY(CSPCheckPasswd)
	PREDEFINE_QUERY(CSPLogout)
	PREDEFINE_QUERY(CSPLogin)
	PREDEFINE_QUERY(CSPCheckIP)
	PREDEFINE_QUERY(CSPRoute)	
	PREDEFINE_QUERY(CSPLoadService)
	PREDEFINE_QUERY(CSPTestLogin) // Çö½Â·æ CS_TESTLOGIN_REQ
	PREDEFINE_QUERY(CSPAgreement)
	PREDEFINE_QUERY(CTBLUserCount)
	PREDEFINE_QUERY(CSPClearLoginUser)
	PREDEFINE_QUERY(CSPGetNation)
	PREDEFINE_QUERY(CSPLoginJP)
END_INIT_QUERY()

BEGIN_INIT_QUERY(TGameSvr)
	PREDEFINE_QUERY(CTBLChar)
	PREDEFINE_QUERY(CTBLItem)

	PREDEFINE_QUERY(CSPGetGuildInfo)
	PREDEFINE_QUERY(CSPFindServerID)
	PREDEFINE_QUERY(CSPCreateChar)
	PREDEFINE_QUERY(CSPDeleteChar)
END_INIT_QUERY()
