//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Happy.rc
//
#define IDC_BTN_HSEND                   2
#define IDOK2                           3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_SERVICETREE                 103
#define IDD_SERVICELIST                 104
#define IDD_HAPPYGROUP                  107
#define IDD_AUTOPATCH                   108
#define IDD_PATCHLIST                   109
#define IDD_SERVICEGRAPH                110
#define IDD_ANNOUNCE                    112
#define IDD_USERKICKOUT                 113
#define IDD_USERMOVE                    114
#define IDD_MACHINE                     115
#define IDD_MACHINEGRAPH                116
#define IDD_MONSTERSPAWN                117
#define IDD_DLGSERVICELOG               118
#define IDD_GMTOOLDLG                   119
#define IDD_CHARMSG                     121
#define IDD_GUILDCHANGE                 122
#define IDD_LOCALINIT                   123
#define IDR_MAINFRAME                   128
#define IDR_HappyTYPE                   129
#define IDR_BAR_CONTROL                 130
#define IDS_CONNECT_FAIL                130
#define IDS_CONNECT_CLOSE               131
#define IDS_STRING132                   132
#define IDD_SERVERCONNECT               133
#define IDR_WAVE_BEEP                   139
#define IDR_SERVICE_RUN                 147
#define IDR_SERVICE_STOP                149
#define IDR_GROUP_NOMAL                 153
#define IDR_GROUP_SELECT                154
#define IDR_SERVICE_PENDING             155
#define IDR_SERVICE_NOTCONTROL          156
#define IDD_DIALOG_UPLOAD               157
#define IDD_DIALOG_UPLOADPROGRESS       160
#define IDR_WORLD_NOMAL                 165
#define IDD_DIALOG_PATCHBAR             166
#define IDR_WORLD_SELECT                170
#define IDD_DIALOG_PATCHPROGRESS        175
#define IDB_BITMAP1                     184
#define IDD_SAVEPOS                     185
#define IDD_POSLISTDLG                  188
#define IDB_AUTOON                      189
#define IDB_BITMAP2                     191
#define IDD_CHATBAN                     192
#define IDD_ITEMSTATE                   197
#define IDD_CHATBANLIST                 198
#define IDD_RET                         200
#define IDD_CASTLE                      201
#define IDD_EVENT                       202
#define IDD_EVENTINFO                   203
#define IDD_LUCKYEVENT                  204
#define IDD_TOURNAMENTINFO              206
#define IDD_HELPINFO                    207
#define IDD_VERSION                     208
#define IDD_RPSGAME                     209
#define IDD_GIFTTOOL                    210
#define IDD_GIFTSET                     211
#define IDC_CLEARBUTTON                 500
#define IDC_ADDGRAPHLIST                501
#define IDC_TREE_SERVICE                1000
#define IDC_LIST2                       1002
#define IDC_EDIT_PORT                   1008
#define IDC_IPADDRESS_IP                1009
#define IDC_EDIT_USER                   1010
#define IDC_EDIT_PASSWORD               1011
#define IDC_TAB_GROUP                   1012
#define IDC_COMBO_MACHINE               1014
#define IDC_LIST_MACHINESERVICE         1015
#define IDC_BUTTON_BROWSE               1016
#define IDC_EDIT_FILENAME               1017
#define IDC_PROGRESS_SERVICEUPLOAD      1020
#define IDC_EDIT_CURFILENAME            1021
#define IDC_TREE_PREVFILE               1022
#define IDC_TREE_NEXTFILE               1023
#define IDC_BUTTON_PREVFILE             1024
#define IDC_BUTTON_NEXTFILE             1025
#define IDC_LIST1                       1026
#define IDC_BUTTON_COMPARE              1027
#define IDC_LIST3                       1027
#define IDC_LC_TPREVERSION              1027
#define IDC_BUTTON_PATCHUP              1028
#define IDC_BUTTON_PREPATCHUP           1029
#define IDC_IPADDRESS_FTP               1030
#define IDC_EDIT_FTP_ACCOUNT            1032
#define IDC_EDIT_FTP_PASSWD             1033
#define IDC_EDIT_PATCHFILENAME          1037
#define IDC_PROGRESS_PATCH              1038
#define IDC_EDIT_PATCHSTATUS            1039
#define IDC_EDIT_FTP_PORT               1039
#define IDC_BUTTON1                     1040
#define IDC_BUTTON_TIMEREND             1040
#define IDC_EDIT1                       1041
#define IDC_BUTTON_ANNOUNCE             1041
#define IDC_GIFTADD                     1041
#define IDC_COMBO1                      1042
#define IDC_EDIT5                       1042
#define IDC_BUTTON_MONSTERSPAWN         1042
#define IDC_GIFTDEL                     1042
#define IDC_BUTTON_TIMER                1043
#define IDC_BUTTON_USERKICK             1043
#define IDC_BTN_LOTDEL                  1043
#define IDC_GIFT_GID                    1043
#define IDC_BUTTON5                     1043
#define IDC_GIFTUP                      1043
#define IDC_TREE_MACHINE                1044
#define IDC_EDIT2                       1045
#define IDC_EDIT3                       1046
#define IDC_CHECK1                      1047
#define IDC_EB_HEND_HOUR                1047
#define IDC_EDIT4                       1048
#define IDC_EDIT_TIMER                  1048
#define IDC_EDIT7                       1049
#define IDC_COMBO2                      1050
#define IDC_BUTTON2                     1051
#define IDC_EDIT6                       1052
#define IDC_COMBO3                      1053
#define IDC_BUTTON_LOCALINIT            1054
#define IDC_BUTTON_CHARMSG              1056
#define IDC_BUTTON_GUILDCHANGE          1057
#define IDC_BUTTON_USERMOVE             1058
#define IDC_SAVE_POS                    1061
#define IDC_SAVE_POS2                   1062
#define IDC_DEL_POS                     1062
#define IDC_RADIO_COORD                 1064
#define IDC_RADIO_CHAR                  1065
#define IDC_EDIT_SAVENAME               1066
#define IDC_STATIC_SAVENAME             1067
#define IDC_RADIO_CHAR2                 1067
#define IDC_LOADPOS                     1068
#define IDC_DELETE                      1069
#define IDC_EDIT_TARGET                 1070
#define IDC_EB_ENDALARM                 1070
#define IDC_BTN_CHATBAN                 1071
#define IDC_CHATBAN_CHAR                1072
#define IDC_CHATBAN_MIN                 1073
#define IDC_POSFIND                     1074
#define IDC_EDIT_POSFIND                1075
#define IDC_BTN_ITEMSTATE               1076
#define IDC_EB_ITINPUT                  1077
#define IDC_BTN_FINDITEM                1078
#define IDC_RA_ITID                     1079
#define IDC_RB_ITNAME                   1080
#define IDC_LC_ITLIST                   1081
#define IDC_EB_BANREASON                1082
#define IDC_BTN_CLEARBANLIST            1083
#define IDC_BTN_DELETEBAN               1084
#define IDC_LC_BANLIST                  1085
#define IDC_BTN_VIEWBANLIST             1086
#define IDC_LB_BANRE                    1088
#define IDC_LB_RET                      1090
#define IDC_BTN_CASTLE                  1091
#define IDC_BTN_CASTLEINFO              1092
#define IDC_LC_CASTLE                   1093
#define IDC_ED_DEFGUILD                 1094
#define IDC_EB_ATKGUILD                 1095
#define IDC_BTN_CHGGUILD                1096
#define IDC_CB_CASTLEID                 1097
#define IDC_EB_C_SECOND                 1099
#define IDC_BTN_CHGSTATUS               1100
#define IDC_CB_WORLD                    1101
#define IDC_EB_HOUR                     1106
#define IDC_EB_MINUTE                   1107
#define IDC_DATETIMEPICKER2             1109
#define IDC_EB_STATUS                   1110
#define IDC_BTN_ADDEVENT                1111
#define IDC_BTN_DELEVENT                1112
#define IDC_CB_EVENT                    1114
#define IDC_CB_SVR                      1115
#define IDC_DT_START                    1116
#define IDC_EB_STARTHOUR                1117
#define IDC_EB_STARTMIN                 1118
#define IDC_EB_ENDHOUR                  1119
#define IDC_EB_ENDMIN                   1120
#define IDC_EB_STARTALARM               1121
#define IDC_EB_STARTMSG                 1122
#define IDC_EB_ENDMSG                   1123
#define IDC_DT_END                      1124
#define IDC_BTN_EVENT                   1125
#define IDC_DT_START2                   1125
#define IDC_EB_EVENTVALUE               1126
#define IDC_EB_EVENTTITLE               1127
#define IDC_CB_CASHITEM                 1128
#define IDC_EB_CASHSALE                 1129
#define IDC_LB_CASHITEM                 1130
#define IDC_BTN_CASHADD                 1131
#define IDC_BTN_CASHDEL                 1132
#define IDC_EB_SPAWNID                  1133
#define IDC_BTN_SPAWNADD                1134
#define IDC_BTN_SPAWNDEL                1135
#define IDC_LB_SPAWNID                  1136
#define IDC_EB_MAPID                    1137
#define IDC_EB_MONID                    1139
#define IDC_EB_POSX                     1140
#define IDC_EB_POSY                     1141
#define IDC_EB_POSZ                     1142
#define IDC_EB_MONDELAY                 1143
#define IDC_LB_REGENLIST                1144
#define IDC_BTN_REGENDEL                1145
#define IDC_EB_REGENMAPID               1146
#define IDC_BTN_ADDREGEN                1147
#define IDC_LC_LUCKYEVENT               1148
#define IDC_DT_END2                     1148
#define IDC_CB_LKDAY                    1149
#define IDC_EB_STARTHOUR2               1149
#define IDC_EB_LKHOUR                   1150
#define IDC_EB_STARTMIN2                1150
#define IDC_EB_LKMIN                    1151
#define IDC_EB_ENDHOUR2                 1151
#define IDC_EB_LKITEM1                  1152
#define IDC_EB_ENDMIN2                  1152
#define IDC_EB_LKITEM2                  1153
#define IDC_EB_LKITEM3                  1154
#define IDC_EB_LKITEM4                  1155
#define IDC_EB_LKITEM5                  1156
#define IDC_EB_LKCOUNT                  1157
#define IDC_EB_LKPRESENT                1158
#define IDC_BTN_LKUPDATE                1161
#define IDC_EB_LKANNOUNCE               1162
#define IDC_BTN_LKREFRESH               1163
#define IDC_BTN_LUCKYEVENT              1164
#define IDC_EB_LKTITLE                  1164
#define IDC_BTN_HELP                    1165
#define IDC_EB_LKMESSAGE                1165
#define IDC_BTN_LKADD                   1166
#define IDC_BTN_LKUPDATE3               1167
#define IDC_BTN_LKDEL                   1167
#define IDC_CB_TWEEK                    1273
#define IDC_CB_TDAY                     1274
#define IDC_EB_THOUR                    1275
#define IDC_EB_TMINUTE                  1276
#define IDC_LC_TEVENT                   1277
#define IDC_BTN_TONAMENT                1278
#define IDC_BTN_ADDTEVENT               1279
#define IDC_BTN_RPS                     1279
#define IDC_BTN_DELTEVENT               1280
#define IDC_BTN_GIFT                    1280
#define IDC_EB_ENTRYNAME                1281
#define IDC_BTN_ADDENTRY                1282
#define IDC_BTN_DELENTRY                1283
#define IDC_LC_TSTEP                    1284
#define IDC_BTN_NEWT                    1286
#define IDC_EB_TITLE                    1288
#define IDC_CB_WORLDTO                  1289
#define IDC_BTN_DELT                    1290
#define IDC_LC_CHARINFO                 1292
#define IDC_LC_REWARD                   1293
#define IDC_BTN_ADDREWARD               1294
#define IDC_BTN_DELREWARD               1295
#define IDC_BTN_UPDATETEVENT            1296
#define IDC_BTN_UPDATESCHEDULE          1297
#define IDC_BTN_ENDCHAR                 1298
#define IDC_BTN_TREGISTER               1299
#define IDC_BTN_TUPDATEDATE             1300
#define IDC_LC_STATIC                   1301
#define IDC_LC_TLIST                    1302
#define IDC_STATIC1                     1307
#define IDC_STATIC2                     1308
#define IDC_STATIC3                     1309
#define IDC_STATIC_V1                   1310
#define IDC_STATIC_V2                   1311
#define IDC_STATIC_M                    1312
#define IDC_STATIC_M1                   1313
#define IDC_STATIC_M2                   1314
#define IDC_STATIC_M3                   1315
#define IDC_STATIC_M4                   1316
#define IDC_STATIC_M5                   1317
#define IDC_STATIC_M6                   1318
#define IDC_RADIO1                      1321
#define IDC_RADIO2                      1322
#define IDC_STATIC_T1                   1323
#define IDC_STATIC_T2                   1324
#define IDC_STATIC_T3                   1325
#define IDC_STATIC_T4                   1326
#define IDC_STATIC_T5                   1327
#define IDC_STATIC_T6                   1328
#define IDC_STATIC_TT1                  1329
#define IDC_STATIC_TT2                  1330
#define IDC_STATIC_TT4                  1332
#define IDC_STATIC_TT5                  1333
#define IDC_BTN_UPDATE                  1334
#define IDC_DT_HSTART                   1335
#define IDC_DT_HEND                     1336
#define IDC_EB_HTEXT                    1337
#define IDC_CB_HWORLD                   1338
#define IDC_CB_HTYPE                    1339
#define IDC_EB_HSTART_HOUR              1340
#define IDC_EB_HSTART_MIN               1341
#define IDC_EB_HEND_MIN                 1342
#define IDC_STATIC_PR                   1343
#define IDC_GROUP_PR                    1344
#define IDC_DT_LOT                      1346
#define IDC_EVESET                      1347
#define IDC_DATESET                     1348
#define IDC_EVESET2                     1349
#define IDC_LOT_STATIC1                 1350
#define IDC_LOT_STATIC2                 1351
#define IDC_LOT_STATIC4                 1353
#define IDC_LOT_STATIC5                 1354
#define IDC_LOT_STATIC6                 1355
#define IDC_LOT_STATIC7                 1356
#define IDC_CB_LOTTYPE                  1357
#define IDC_EB_LOTNUM                   1358
#define IDC_LOT_STATIC9                 1359
#define IDC_EB_LOTMAIL                  1360
#define IDC_LC_LOT                      1361
#define IDC_EB_LOTH                     1362
#define IDC_EB_LOTM                     1363
#define IDC_BTN_LOTADD                  1364
#define IDC_CK_LOT                      1365
#define IDC_LOT_STATIC8                 1366
#define IDC_EB_LOTNUM2                  1367
#define IDC_REWSET                      1368
#define IDC_EB_LOTITEMID                1369
#define IDC_LC_RPSLIST                  1369
#define IDC_EB_LOTMAIL2                 1370
#define IDC_CB_RPSWORLD                 1370
#define ID_BT_RPSUPDATE                 1371
#define IDC_CB_RPSTYPE                  1372
#define ID_BTN_PREUPDATE                1372
#define IDC_BTN_TVERMOVE                1373
#define IDC_BTN_PREDELETE               1374
#define IDC_LC_TVERSION                 1375
#define IDC_CHK_LKANN                   1376
#define IDC_MVLIST                      1377
#define IDC_GROUP_NAME                  1378
#define IDC_ST_CHARNAME                 1379
#define IDC_MV_STATIC1                  1380
#define IDC_MV_STATIC2                  1381
#define IDC_MV_STATIC3                  1382
#define IDC_MV_STATIC4                  1383
#define IDC_MV_STATIC5                  1384
#define IDC_LOT_STATIC10                1385
#define IDC_LOT_STATIC11                1386
#define IDC_EB_MINL                     1387
#define IDC_EB_MAXL                     1388
#define IDC_GIFT_WORLD                  1389
#define IDC_GIFT_NAME                   1390
#define IDC_GIFT_SET                    1391
#define IDC_LC_GIFTSET                  1392
#define IDC_GIFTRE                      1393
#define IDS_MAPSVRCONNECT               2000
#define IDS_MAPSVRDISCONNECT            2001
#define ID_BUTTON_START                 32772
#define ID_BUTTON_STOP                  32777
#define ID_BUTTON32779                  32779
#define ID_SERVER_CONNECT               32780
#define ID_SERVICE_START                32783
#define ID_SERVICE_STOP                 32784
#define ID_32786                        32786
#define ID_SERVER_DISCONNECT            32788
#define ID_SERVICE_ALERT                32792
#define ID_SERVICE_ALL_VIEW             32794
#define ID_SERVICE_UPLOAD               32796
#define ID_CURUSER_GRAPH                32800
#define ID_SERVCIE_LOG                  32818
#define ID_USERWEB                      32820
#define ID_GMTOOL                       32823
#define ID_VIEW_SERVICEAUTOSTART        32824
#define ID_SDATACLEAR                   32826
#define ID_USERADMIN_EXPORTHAPPYDATA    32829
#define ID_USERADMIN_CHATBANLIST        32830

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         32831
#define _APS_NEXT_CONTROL_VALUE         1394
#define _APS_NEXT_SYMED_VALUE           126
#endif
#endif
