#pragma once

#define TBUILD_NUMBER					(0x00000130)		// RELEASE MODE

///////////////////////////////////////////////////////////////////////////
// TClient Development Flag
///////////////////////////////////////////////////////////////////////////
#include "TNationOption.h"
#include "TChart.h"

//#define MODIFY_CNP_NAME

//#define ADD_SNOW // 눈 이벤트
//#define ADD_TEXTOOL // 망토텍스쳐 좌표설정 In-game 툴
#define ADD_MISSION
#define EVENT_LOTTERT
#define ADD_WEB_CASHSHOP
#define ADD_CAUTION15
#define ADD_TOURNAMENT
#define ADD_RPS
#define ADD_RPS_RL
#define MODIFY_TT
#define MODIFY_GUILD
#define KEYHOOK_CTRLALTDEL		// Ctrl + Alt + Del 키 후킹처리.

///////////////////////////////////////////////////////////////////////////
// TClient macro
///////////////////////////////////////////////////////////////////////////
#define GM_STOPTHECLOCK							(0x00000267)
#define TTIMER_REDRAW_WEBCASHSHOP		(WM_USER+0x0001)

#define GM_NETCABLE_DISCONNECTED			(0xFAFAFAFA)
#define TTOURNAMENT_CHEER_ITEM_ID			0

#define TSTART_D_CAM_POSITION				D3DXVECTOR3( 2867.042480f, 66.653175f, 5030.846191f)
#define TSTART_D_CAM_TARGET					D3DXVECTOR3( 2865.921631f, 67.071465f, 5030.940430f)

#define TSTART_C_CAM_POSITION				D3DXVECTOR3( 5367.124512f, 95.627701f, 4657.712402f)
#define TSTART_C_CAM_TARGET					D3DXVECTOR3( 5366.884277f, 96.010452f, 4658.824219f)

#define TSTART_D_CHAR_DIR					((WORD) 450)
#define TSTART_C_CHAR_DIR					((WORD) 865)

#define TSTART_CAM_PITCH					((FLOAT) 200.0f)
#define TSTART_CAM_YAW						((FLOAT) 225.0f)
#define TSTART_CAM_DIST						((FLOAT) 7.5f)

#define TSTART_D_PORTAL_ID					((WORD) 15001)
#define TSTART_C_PORTAL_ID					((WORD) 15002)

#define TSIEGE_D_PORTAL_ID					((WORD) 1002)
#define TSIEGE_C_PORTAL_ID					((WORD) 1102)

#define TSCENE_OUTLINE_COLOR				((DWORD) 0x90C0C0B0)
#define TSCENE_TEXT_COLOR					((DWORD) 0xF0101010)

#define TTUTORIAL_EXIT_QUEST_ID				((DWORD) 7256)
#define TTUTORIAL_CAM_PITCH					((WORD) 1782)
#define TTUTORIAL_CAM_DIR					((WORD) 1664)
#define TTUTORIAL_CHAR_DIR					((WORD) 1690)

#define TTOURNAMENT_LOUNGE_ID				((WORD) 500)
#define TTOURNAMENT_STADIUM_1				((WORD) 501)
#define TTOURNAMENT_STADIUM_32				((WORD) 532)

#define TTOURNAMENT_TEAM_NONE				((BYTE) -1)
#define TOURNAMENT_ARENA_COUNT				4

#define TMAX_CHARLEVEL						90
#define MANTLE_FINAL_SIZE					256

#define TITEM_INDEX_WRAP_SKIN				1488
#define TITEM_INDEX_GRADE_SKIN				1500
#define TITEM_INDEX_MAGIC_SKIN				1525
#define TITEM_INDEX_RARE_SKIN				1526

#define ADJACENCY_COUNT						16

#define COLOR_CASTLE_HESED					D3DCOLOR_ARGB( 255, 50, 100, 200 )
#define COLOR_CASTLE_ARDRI					D3DCOLOR_ARGB( 255, 100, 50, 200 )
#define COLOR_CASTLE_TYCON					D3DCOLOR_ARGB( 255, 231, 199, 0 )
#define COLOR_CASTLE_GEHBRA					D3DCOLOR_ARGB( 255, 200, 100, 100 )
#define COLOR_CASTLE_NONE					D3DCOLOR_ARGB( 255, 210, 210, 210 )

#define COLOR_TACTICS						D3DCOLOR_ARGB( 255, 100, 100, 100 )

#define TSTATCOLOR_WHITE					D3DCOLOR_ARGB(255, 210, 210, 210)
#define TSTATCOLOR_BLUE						D3DCOLOR_ARGB(255, 128, 204, 253)

#define TLIMITATION_TIME					(600000)

#define TNATION_GERMANY										(0xF001)
#define TNATION_ENGLISH										(0xF002)
#define TNATION_JAPAN										(0xF003)
#define TNATION_POLAND										(0xF004)
#define TNATION_FRANCE										(0xF005)
#define TNATION_TAIWAN										(0xF006)
#define TNATION_CZECH										(0xF007)
#define TNATION_ITALY										(0xF008)
#define TNATION_SPAIN										(0xF009)
#define TNATION_UNITEDKINGDOM								(0xF00A)
#define TNATION_GREECE										(0xF00B)
#define TNATION_RUSSIA										(0xF00C)
#define TNATION_ROMANIA										(0xF00D)
#define TNATION_UNITEDSTATE									(0xF00E)
#define TNATION_HUNGARY										(0xF00F)
#define TNATION_TURKEY										(0xF010)
#define TNATION_PORTUGAL									(0xF011)
// Arab Ver.
#define TNATION_EGYPT										(0xF012)
#define TNATION_KOREA										(0x0000)

#define GL_DISABLEUI_FRAME_QUEST_IN_FIRST					(0xA001)
#define GL_MOUSEWHEEL_IN_FIRST								(0xA002)
#define GL_QUEST_ADD_IN_FIRST								(0xA003)
#define GL_QUEST_ACCEPT_IN_FIRST							(0xA004)
#define GL_QUEST_GIVEUP_IN_FIRST							(0xA005)
#define GL_QUEST_COMPLETE_IN_FIRST							(0xA006)

#define CASHSHOPDLGMODE_NORMAL								0
#define CASHSHOPDLGMODE_PERIOD_EXTENSION					1

#define CASHSHOPITEM_KIND_NONE								0
#define CASHSHOPITEM_KIND_NEW								1
#define CASHSHOPITEM_KIND_BEST								2

#define NOTIFYMAIL_TICK					1300

#define CASHCABINET_ID					7629
#define CASHCABINET_MAX_ITEM_ON_PR		30		// PR: Period Rental

#define TDEF_SKILL_NPC					((WORD) 22047)
#define TID_HIDING_SKILL				221

#define GM_START_4STORY					(0x00000000)
#define TREGISTRY_KEY					_T("Keys")

#define TBASE_SCREEN_X					1024
#define TBASE_SCREEN_Y					768

#define TCMDTARGET_OBJ					ID_RSCS_TARGET
#define TCMDTARGET_CLK					ID_CLK_DEFAULT
#define TCMDTARGET_CL					ID_CL_DEFAULT
#define TCMDTARGET_CMDMESH				ID_MESH_DEFAULT
#define TCMDTARGET_MESH					ID_MESH_DEFAULT
#define TCMDTARGET_ACT					ID_ACT_DEFAULT
#define TCMDTARGET_ANI					ID_ANI_DEFAULT

#define TCMDTARGET_SIZE_X				((FLOAT) 1.0f)
#define TCMDTARGET_SIZE_Y				((FLOAT) 1.0f)
#define TCMDTARGET_SIZE_Z				((FLOAT) 1.0f)

#define TCMDDIR_OBJ						ID_RSCS_ARROW
#define TCMDDIR_CLK						ID_CLK_DEFAULT
#define TCMDDIR_CL						ID_CL_DEFAULT
#define TCMDDIR_MESH					ID_MESH_DEFAULT
#define TCMDDIR_ACT						ID_ACT_DEFAULT
#define TCMDDIR_ANI						ID_ANI_DEFAULT

#define TCMDDIR_SIZE_X					((FLOAT) 1.0f)
#define TCMDDIR_SIZE_Y					((FLOAT) 1.0f)
#define TCMDDIR_SIZE_Z					((FLOAT) 1.0f)
#define TCMDDIR_SCALE					((FLOAT) 0.2f)

#define TRSCSOBJ_RANGE					((FLOAT) 100000.0f)
#define TCMDDIR_POS_Z					((FLOAT) -5.0f)
#define TCMDDIR_POS_Y					((FLOAT) 3.8f)
#define TCMDDIR_POS_X					((FLOAT) 0.0f)

#define TCLIENT_ZERO					((FLOAT) 0.0000001f)
#define THEIGHT_ZERO					((FLOAT) 0.01f)
#define TCOLL_EPSILON					((FLOAT) 0.1f)

#define TNETCAM_ZOOMSPEED				((FLOAT) 0.001f)
#define TNETCAM_ROTSPEED				((BYTE) 1)
#define TNETCAM_PITCH					((WORD) 46)

#define TNETCAM_POS_X					((FLOAT) -19.19f)
#define TNETCAM_POS_Y					((FLOAT) 3.18f)
#define TNETCAM_POS_Z					((FLOAT) -31.57f)

#define TNETCAM_ROT_Y					((FLOAT) 37.41f)
#define TNETCAM_ROT_X					((FLOAT) 25.13f)

#define TNETCAM_DEFNEAR					((FLOAT) 5.0f)
#define TNETCAM_DEFFAR					((FLOAT) 500.0f)

#define TNETCAM_NEAR					((FLOAT) 0.01f)
#define TNETCAM_FAR						((FLOAT) 120.0f)
#define TNETCAM_FOV						((FLOAT) 46.5f)
#define TNETCAM_CULL					((FLOAT) 4.7f)

#define TDROPDAMAGE_HEIGHT				((FLOAT) 20.0f)
#define TTALKLINE_HEIGHT				((FLOAT) 16.0f)
#define TMARKER_HEIGHT					((FLOAT) 1.1f)
#define TTEXT_HEIGHT					((FLOAT) 5.0f)
#define TCAM_SIZE						((FLOAT) 1.4f)
#define TRSCSMOVE_BOUND					((FLOAT) 2.0f)
#define TRSCSPICK_RANGE					((FLOAT) 3.0f)
#define TWATER_ESCAPE					((FLOAT) 0.2f)
#define TCAM_MARGINE					((FLOAT) 0.2f)

#define TUNITLERP_LENGTH				((FLOAT) 64.0f)
#define TPOS_SCALE						((FLOAT) 0.078f)
#define TLIGHT_SCALE					((FLOAT) 0.64f)
#define TREVIVAL_DIST					((FLOAT) 16.0f)
#define TGHOSTCAM_DIST					((FLOAT) 32.0f)
#define TGHOST_DIST						((FLOAT) 24.0f)
#define TALPHA_DIST						((FLOAT) 3.0f)
#define POPUP_DIST						((FLOAT) 3.0f)
#define TSWITCH_DIST					((FLOAT) 4.0f)
#define TARGETUI_DIST					((FLOAT) 5.0f)
#define TARGET_DIST						((FLOAT) 48.0f)
#define TPICK_DIST						((FLOAT) 30.0f)
#define TSTANDHIDE_SIGHT_DIST			((FLOAT) 8.0f)
#define TCAMFIX_DIST					((FLOAT) 5.0f)
#define FIX_DIST						((FLOAT) 0.5f)
#define TTRANS_HEIGHT					((FLOAT) 2.0f)
#define TTRANS_BOUND					((FLOAT) 0.8f)
#define TSKILL_HEIGHT					((FLOAT) 6.0f)
#define TPATH_HEIGHT					((FLOAT) 0.3f)
#define TPATH_RADIUS					((FLOAT) 1.2f)
#define TPATH_LONG						((FLOAT) 5.0f)
#define TENVSND_RANGE					((FLOAT) 5.0f)
#define GODBALL_DIST					((FLOAT) 2.0f)
#define GODTOWER_DIST					((FLOAT) 3.0f)

#define TPARASHUTE_SPEED				((FLOAT) 1.5f)
#define TMINFALL_SPEED					((FLOAT) 5.7f)

#define TSELECT_WEIGHT_ALLI				((FLOAT) 1.0f)
#define TSELECT_WEIGHT_NPC				((FLOAT) 2.0f)

#define TCAMOUT_SPEED					((FLOAT) 0.05f)
#define TPUSH_SPEED						((FLOAT) 6.0f)
#define TPUSH_BUST						((FLOAT) 7.0f)

#define TMAX_VITAL						((BYTE) 100)
#define MAX_DRAGSLOT					((BYTE) 20)
#define MAX_INVEN						((BYTE) 7)
#define MAX_SUBINVEN					((BYTE) 5)

#define QTREEBTN_COUNT					((BYTE) 5)
#define MAX_PARTY						((BYTE) 6)
#define MAX_SLOT						((BYTE) 6)
#define MAX_CON							((BYTE) 9)

#define TPATHFLAG_NULL					((DWORD) 0x00000000)
#define TSELECT_COLOR					((BYTE) 0x80)
#define TNETMAP_ID						((WORD) 0xFFFF)

#define TGRADE_COLOR_0					(0)
#define TGRADE_COLOR_1					D3DCOLOR_ARGB(255, 0,61,40)
#define TGRADE_COLOR_2					D3DCOLOR_ARGB(255, 61,0,0)
#define TGRADE_COLOR_3					D3DCOLOR_ARGB(255, 6,0, 61)
#define TGRADE_COLOR_4					D3DCOLOR_ARGB(255, 60,61,0)

#define TFLASHCOLOR_WHITE				D3DCOLOR_ARGB(0, 255,255,255)
#define TFLASHCOLOR_BLACK				D3DCOLOR_ARGB(0, 0,0,0)

#define TCOLOR_TXT_NORMAL				D3DCOLOR_ARGB(255, 200,200,200)
#define TCOLOR_TXT_WARN					D3DCOLOR_ARGB(255, 242,108, 78)

#define TCOLOR_LIGHT					D3DCOLOR_ARGB(255, 170,221, 85)
#define TCOLOR_MIDDLE					D3DCOLOR_ARGB(255, 255,232, 76)
#define TCOLOR_HEAVY					D3DCOLOR_ARGB(255, 242,108, 78)

#define TCOLOR_SENDER_ME				D3DCOLOR_ARGB(255, 219,214,202)
#define TCOLOR_SENDER					D3DCOLOR_ARGB(255, 244,195,156)

#define TCOLOR_MSG_CHATLIST				(0xFFEEEEEE)
#define TCOLOR_SERVER_HEADER			(0xFF63A4FC)

#define TCOLOR_LEVELUP					D3DCOLOR_ARGB(255, 128,255,128)
#define TCOLOR_ERROR					D3DCOLOR_ARGB(255, 249,173,129)
#define TCOLOR_INFO						D3DCOLOR_ARGB(255, 209,189,135)
#define TCOLOR_EXP						D3DCOLOR_ARGB(255, 255,177, 42)
#define TCOLOR_MONEY					D3DCOLOR_ARGB(255, 209,189,135)
#define TCOLOR_DEAD						D3DCOLOR_ARGB(255, 171,160,153)
#define TCOLOR_ATTACK					D3DCOLOR_ARGB(255, 255,255,128)
#define TCOLOR_DEFEND					D3DCOLOR_ARGB(255, 242,108, 78)
#define TCOLOR_MPATTACK					D3DCOLOR_ARGB(255, 108, 78,242)
#define TCOLOR_SKILL_ATTACK				D3DCOLOR_ARGB(255, 255,232, 76)
#define TCOLOR_SKILL_DEFEND				D3DCOLOR_ARGB(255, 252, 84, 41)

#define TCOLOR_LIGHTQUEST				TCOLOR_LIGHT
#define TCOLOR_MIDDLEQUEST				TCOLOR_MIDDLE
#define TCOLOR_HAVYQUEST				TCOLOR_HEAVY
#define TCOLOR_QUESTCLASS				(0xFFFDFDFD)

#define TCOLOR_QTERM_TITLE				(0xFFFFFF9C)
#define TCOLOR_QTERM_TEXT				(0xFFBAB3AA)

#define TCOLOR_QUEST_BLUE				D3DCOLOR_ARGB(255, 108, 204, 253)

#define TCOLOR_GUILD_TITLE				(0xFFBAB3AA)
#define TCOLOR_GUILD_STRESS				(0xFFFAD202)

#define TCOLOR_ALLIANCE_NORMAL			D3DCOLOR_ARGB(255, 219,214,202)
#define TCOLOR_ALLIANCE_PARTY			D3DCOLOR_ARGB(255,  68,169,255)
#define TCOLOR_ALLIANCE_PET				D3DCOLOR_ARGB(255,  87,195,223)
#define TCOLOR_ALLIANCE_NPC				D3DCOLOR_ARGB(255,  68,169,255)
#define TCOLOR_ALLIANCE_FORCE			D3DCOLOR_ARGB(255, 208,206, 20)
#define TCOLOR_ALLIANCE_OTHERPARTY		D3DCOLOR_ARGB(255, 168,207,234)
#define TCOLOR_ENEMY_LIGHT				TCOLOR_LIGHT
#define TCOLOR_ENEMY_MIDDLE				TCOLOR_MIDDLE
#define TCOLOR_ENEMY_HEAVY				TCOLOR_HEAVY
#define TCOLOR_ENEMY_NOREWARD			D3DCOLOR_ARGB(255, 171,160,153)
#define TCOLOR_NEUTRALITY				D3DCOLOR_ARGB(255,  68,169,255)

#define TCOLOR_SQUAD_NORMAL				D3DCOLOR_ARGB(255, 200,200,200)
#define TCOLOR_SQUAD_COMMANDER			D3DCOLOR_ARGB(255, 255,150,150)

#define TCOLOR_CHAT_WHISPER				D3DCOLOR_ARGB( 255, 244, 195, 156);
#define TCOLOR_CHAT_NEAR				D3DCOLOR_ARGB( 255, 219, 214, 202);
#define TCOLOR_CHAT_MAP					D3DCOLOR_ARGB( 255, 246, 142,  85);
#define TCOLOR_CHAT_WORLD				D3DCOLOR_ARGB( 255,  16, 240,  32);
#define TCOLOR_CHAT_PARTY				D3DCOLOR_ARGB( 255,  87, 195, 223);
#define TCOLOR_CHAT_GUILD				D3DCOLOR_ARGB( 255, 170, 221,  85);
#define TCOLOR_CHAT_TACTICS				D3DCOLOR_ARGB( 255, 0, 160,  0);
#define TCOLOR_CHAT_FORCE				D3DCOLOR_ARGB( 255, 208, 206,  20);
#define TCOLOR_CHAT_OPERATOR			D3DCOLOR_ARGB( 255, 150, 240, 170);
#define TCOLOR_CHAT_COMMANDER			D3DCOLOR_ARGB( 255, 240, 170, 240);

#define TCOLOR_TXT_YELLOW				D3DCOLOR_ARGB( 255, 230, 230, 153);

#define TCOLOR_GUILDCMD_CMD				TCOLOR_LIGHT
#define TCOLOR_GUILDCMD_DESC			TCOLOR_TXT_NORMAL

#define TCOLOR_TOURNAMENT_RED			D3DCOLOR_ARGB(255, 254, 208, 0)
#define TCOLOR_TOURNAMENT_BLUE			D3DCOLOR_ARGB(255, 128, 204, 253)

#define TLOADING_TEXT_CLR				(0xFFFFFFFF)
#define TLOADING_IMAGE_COUNT			((BYTE) 1)
#define TLOADING_GAUGE_X				(0)
#define TLOADING_GAUGE_Y				(745)

#define TBGM_VOLUME						(5000)
#define TBGM_TIMER						(5000)
#define TBGM_RATE						(3)

#define TRUNE_LENGTH					(8)
#define TLUNA_LENGTH					(3)
#define TCRON_LENGTH					(3)

#define TLEVEL_LENGTH                   (3)

#define TLOWLEVEL_COUNT					(50)
#define TMEDLEVEL_COUNT					(25)


#define TDYNAMICHELP_TICK				(10000)
#define TEXCEPTSKILL_TICK				(1000)

#define TCMDDIR_SCALE_TICK				(300)
#define TDETAIL_INFO_TICK				(500)
#define TDETAIL_NAME_TICK				(500)
#define QUESTUI_FADE_TICK				(200)
#define TBOX_CHARGE_TICK				(2500)
#define TBREATH_TICK					(30000)
#define TMCHECK_TICK					(500)
#define TBREATH_TIMER					(1000)
#define TBREATH_FACTOR					(3)
#define TBREATH_DAMAGE					(5)
#define TSTR_MAX						(1024)
#define ALPHA_MAX						(255)
#define ALPHA_MIN						(0)
#define TSCREENHEIGHT_OFFSET			(100)

#define TLEVELUP_SFX					(801)
#define THPITEM_SFX						(407)
#define TMPITEM_SFX						(408)

#define TNUMPANNEL_HEIGHT				((FLOAT) 128.0f)
#define TNUMPANNEL_WIDTH				((FLOAT) 256.0f)
#define TNPCICON_SIZE					((FLOAT) 16.0f)
#define TMOUNTTEXT_SCALE				((FLOAT) 0.7f)

#define TNUMBER_SPEED_X					((FLOAT) 60.0f)
#define TNUMBER_SPEED_Y					((FLOAT) 65.0f)
#define TNUMBER_SCALE					((FLOAT) 0.35f)

#define TNUMBER_CRITICAL_SCALE			((FLOAT) 1.3f)
#define TNUMBER_SPEED_RATE				((FLOAT) 1.4f)

#define THITR_SCALE						((FLOAT) 2.0f)
#define THIT_SCALE						((FLOAT) 1.2f)
#define TSKY_SCALE						((FLOAT) 0.9f)

#define TNUMBERPOS_COUNT				(5)
#define TMINUS_SIGN_INDEX				(10)
#define TTICK_INTERVAL					(200)
#define TSERVICECHECK_INTERVAL			(2000)
#define TNUMBER_HEIGHT					(64)
#define TNUMBER_TICK					(1000)
#define TFLASH_TICK						(500)
#define TGHOST_TICK						(2000)
#define TDOT_TICK						(1000)

#define TSLIDE_DIST						((FLOAT) 2.0f)
#define TSLIDE_TICK						(220)

#define TATKQUAKE_DIST					((FLOAT) 0.15f)
#define TDEFQUAKE_DIST					((FLOAT) 0.1f)
#define TQUAKE_TICK						(150)

#define MAKE_TDAMAGE( dwDamage, bType)	DWORD(((DWORD(bType) << 24) & 0xFF000000) | (DWORD(dwDamage) & 0x00FFFFFF))
#define GET_TDAMAGE_TYPE(dwDamage)		BYTE((DWORD(dwDamage) & 0xFF000000) >> 24)
#define GET_TDAMAGE(dwDamage)			DWORD(DWORD(dwDamage) & 0x00FFFFFF)

#define TCRITICAL_NUMBER				(0xFFFFFFFF)
#define TMISS_NUMBER					(0xFFFFFFFE)
#define TBLOCK_NUMBER					(0xFFFFFFFD)
#define TDAMAGE_TICK					(300)

#define TMAXSHADOW_TICK					(200)
#define TMAXALPHA_TICK					(800)
#define TMAXPASS_TICK					(1000)
#define TMAXSKY_TICK					(1000)

#define TCHAT_DWORD_SIZE				(8)
#define TCHAT_CHAR_MAX					(512)
#define TCHAT_TIMER						(15000)
#define TTALK_TIMER						(10000)
#define TNOTIFYCHAT_TIME				(20000)

#define TRELOGIN_DELAY					((DWORD) 3000)
#define TSCRCAPTURE_DELAY				((DWORD) 500)
#define CLICK_DELAY						(180)
#define SYNC_TICK						(8000)
#define TPOS_TICK						(200)
#define PATH_TICK						(500)
#define SYNC_DIST						(8.0f)

#define TRUNE_DIVIDER					(1000000)
#define TLUNA_DIVIDER					(1000)

#define TPOPUPMAX_COUNT					(20)
#define TRSCSHOTKEY_COUNT				(7)
#define TSKILLSLOT_COUNT				(14)
#define TSHOP_COUNT						(5)
#define TINVENSLOT_COUNT				(20)

#define TINFOTEXT_MARGINE				(8)
#define TCHAT_MARGINE					(10)
#define TCHAT_SIZE						(50)
#define TMSG_MARGINE					(3)

#define FRONT_DIR_RANGE					(225)
#define FOLLOW_RANGE					(100)
#define DIR_RANGE						(50)

#define TSHOTPIVOT_COUNT				(2)

#define TREPLACE_COUNT					(11)
#define TCLEAR_COUNT					(5)
#define TWEAPON_COUNT					(3)

#define DEF_INDEXCNT					(36000)
#define DEF_LODBOUND					(58)
#define DEF_DIFFUSECNT					(10)
#define DEF_MAXLEVEL					(1)
#define DEF_MAXLENGTH					(4)

#define TCAM_LENGTH						((FLOAT) 110.0f)
#define TSWVP_DEF_LODBOUND				(24)

#define TTOURNAMENT_STADIUM_LODBOUND	(87)
#define TTOURNAMENT_STADIUM_MAXLENGTH	(2)

#define TMINIMAPMARK_DIST				((FLOAT) 0.40f)
#define TMINIMAPTEX_SIZE				(192)
#define TMINIMAPOBJTEX_SIZE				(16)
#define TMONINVEN_ID					(10)
#define TMAINTAIN_COUNT					(6)

#define TWORLDMAP_SQUAD_CHIEF			(1)
#define TWORLDMAP_SQUAD_UNIT			(2)
#define TWORLDMAP_HOST_CHAR				(0)
#define TWORLDMAP_SIZE					(980)

#define TOBJSHADOW_BIAS					((FLOAT) 0.0000002f)
#define TOBJSELECT_BIAS					((FLOAT) 0.0000001f)

#define TSLASH_STEP						(30)
#define TSLASH_INTER					(5)

#define TMAXRANGE_RATIO					((FLOAT) 0.9f)
#define TDEF_SPEED						((FLOAT) 0.9f)
#define TMON_SPEED						((FLOAT) 0.99f)

#define TOBJSHADOW_SCALE				((FLOAT) 1.8f)
#define TOBJSELECT_SCALE				((FLOAT) 2.8f)

#define TPITCH_MAX						(1575)
#define TPITCH_MIN						(300)

#define OM_TSUBACTENDING				(0x10000002)
#define OM_TSUBACTENDED					(0x10000003)

#define TOBJCELL_LENGTH					((FLOAT) 8.0f)
#define TOBJCELL_WIDTH					(128)
#define TOBJCELL_COUNT					(16384)

#define TDRAWCELL_COUNT					(361)
#define TDRAWCELL_WIDTH					(19)

#define TWATERSTEP_SND					(10009)
#define TDEFSTEP_SND					(10000)

#define TMIN_RANGEOPTION				((FLOAT) 0.7f)
#define TMAX_RANGEOPTION				((FLOAT) 1.0f)

#define TARGET_BOUND					((FLOAT) 18.0f)
#define TROAM_BOUND						((FLOAT) 0.3f)

#define TLOWCULL_BOUND					((FLOAT) 1.0f)
#define TMIDCULL_BOUND					((FLOAT) 2.0f)
#define THICULL_BOUND					((FLOAT) 4.0f)

#define TSELCULL_FACTOR					((FLOAT) 0.47f)
#define TLOWCULL_FACTOR					((FLOAT) 0.18f)
#define TMIDCULL_FACTOR					((FLOAT) 0.29f)
#define THICULL_FACTOR					((FLOAT) 0.41f)
#define TNOCULL_FACTOR					((FLOAT) 0.59f)

#define TARGETKIND_NONE					((BYTE) 0)
#define TARGETKIND_TARGET				((BYTE) 1)
#define TARGETKIND_BOUND				((BYTE) 2)
#define TQLEVEL_BOUND					((BYTE) 3)
#define TLEVEL_BOUND					((BYTE) 10)

#define TRECALL_STAND_BOUND				((FLOAT) 3.0f)
#define TRECALL_WALK_BOUND				((FLOAT) 5.0f)
#define TRECALL_MAX						((BYTE) 5)

#define TCMDALARM_SCALE					((FLOAT) 0.5f)
#define TCMDALARM_TICK					500

#define TCMDARROW_VELOCITY				((FLOAT) 0.04f)
#define TCMDARROW_HEIGHT				((FLOAT) 0.5f)
#define TCMDARROW_GRAVITY				((FLOAT) 576.0f)

#define TFATIGUETEXT_COLOR				((DWORD) 0xFF51CEAE)
#define TTEXTSHADOW_COLOR				((DWORD) 0xFF000000)
#define TBREATHTEXT_COLOR				((DWORD) 0xFF5561DA)
#define TCHARGETEXT_COLOR				((DWORD) 0xFFE94D2E)
#define TNAMETEXT_COLOR					((DWORD) 0xFFDFD2CB)
#define THPTEXT_COLOR					((DWORD) 0xFFAADD55)
#define TTITLEMSG_COLOR					D3DCOLOR_ARGB(255,255,232, 76)
#define TMPTEXT_COLOR					D3DCOLOR_ARGB(255, 68,169,255)
#define TTIMETEXT_COLOR					D3DCOLOR_ARGB(255,219,214,202)
#define TMONEYTEXT_COLOR				D3DCOLOR_ARGB(255,219,214,202)
#define TNORMAL_COLOR					D3DCOLOR_ARGB(255,219,214,202)

#define TSQUADARROW_COLOR				((DWORD) 0xFF10C010)
#define TCMDARROW_COLOR					((DWORD) 0xFFC0A010)
#define TCMDARROW_WIDTH					((FLOAT) 1.5f)
#define TCMDARROW_BOUND					((FLOAT) 0.5f)

#define TMINIMAP_SCALE_FACTOR			((FLOAT) 1.2f)
#define TMINIMAP_SCALE_COUNT			((FLOAT) 5.0f)
#define TMINIMAP_INIT_SCALE				((FLOAT) 7.0f)
#define TWORLDMAP_MINSCALE				((FLOAT) 1.0f)

#define TMONSKILL_DEFAULT				((BYTE) 0)
#define TMONSKILL_LEVEL					((BYTE) 1)

#define TSKILL_DEFAULT_TYPE				((BYTE) 0)

#define TMAINCHARMENU_COUNT				((BYTE) 9)
#define TSQUADMENU_COUNT				((BYTE) 3)
#define TFARPARTYMENU_COUNT				((BYTE) 5)
#define TMAINTAINMENU_COUNT				((BYTE) 2)

#define TNETFOG_MAPID_D_H				((WORD) 0)
#define TNETFOG_MAPID_D_B				((WORD) 0)
#define TNETFOG_MAPID_D_N				((WORD) 0)
#define TNETFOG_MAPID_C_H				((WORD) 0)
#define TNETFOG_MAPID_C_B				((WORD) 0)
#define TNETFOG_MAPID_C_N				((WORD) 0)
#define TNETFOG_MAPID_B_H				((WORD) 0)
#define TNETFOG_MAPID_B_B				((WORD) 0)
#define TNETFOG_MAPID_B_N				((WORD) 0)

#define TNETFOG_UNITX_D_H				((BYTE) 2)
#define TNETFOG_UNITY_D_H				((BYTE) 4)
#define TNETFOG_UNITX_D_B				((BYTE) 2)
#define TNETFOG_UNITY_D_B				((BYTE) 4)
#define TNETFOG_UNITX_D_N				((BYTE) 2)
#define TNETFOG_UNITY_D_N				((BYTE) 4)
#define TNETFOG_UNITX_C_H				((BYTE) 2)
#define TNETFOG_UNITY_C_H				((BYTE) 4)
#define TNETFOG_UNITX_C_B				((BYTE) 2)
#define TNETFOG_UNITY_C_B				((BYTE) 4)
#define TNETFOG_UNITX_C_N				((BYTE) 2)
#define TNETFOG_UNITY_C_N				((BYTE) 4)
#define TNETFOG_UNITX_B_H				((BYTE) 2)
#define TNETFOG_UNITY_B_H				((BYTE) 4)
#define TNETFOG_UNITX_B_B				((BYTE) 2)
#define TNETFOG_UNITY_B_B				((BYTE) 4)
#define TNETFOG_UNITX_B_N				((BYTE) 2)
#define TNETFOG_UNITY_B_N				((BYTE) 4)

#define TCHECK_WEAPON( x, y)			(((y) ? (x) & (1 << ((y) - 1)) : 0) ? TRUE : FALSE)
#define TCHECK_CLASS( x, y)				((x) & (1 << (y)) ? TRUE : FALSE)

#define T_INVALID						(-1)

#define TCHAT_FLAG_WHISPER				((DWORD)(1))
#define TCHAT_FLAG_NEAR					((DWORD)(1 << 1))
#define TCHAT_FLAG_MAP					((DWORD)(1 << 2))
#define TCHAT_FLAG_WORLD				((DWORD)(1 << 3))
#define TCHAT_FLAG_PARTY				((DWORD)(1 << 4))
#define TCHAT_FLAG_GUILD				((DWORD)(1 << 5))
#define TCHAT_FLAG_TACTICS				((DWORD)(1 << 8))
#define TCHAT_FLAG_GUILD_TACTICS		( TCHAT_FLAG_GUILD | TCHAT_FLAG_TACTICS )
#define TCHAT_FLAG_INFO					((DWORD)(1 << 6))
#define TCHAT_FLAG_FORCE				((DWORD)(1 << 7))
#define TCHAT_FLAG_SHOW					((DWORD)(1 << 9))
#define TCHAT_FLAG_ALL_CHAT				((DWORD)(TCHAT_FLAG_WHISPER|TCHAT_FLAG_NEAR|TCHAT_FLAG_MAP|TCHAT_FLAG_PARTY|TCHAT_FLAG_GUILD_TACTICS|TCHAT_FLAG_FORCE))
#define TCHAT_FLAG_ALL_CHAT_WITH_INFO	((DWORD)(TCHAT_FLAG_ALL_CHAT | TCHAT_FLAG_INFO))
#define TCHAT_FLAG_COUNT				8

#define TCHAT_WROLD_MIN_LEVEL			5

#define TCHAT_DETAIL_INFO_MARGINE		8
#define TDRAG_START_OFFSET2				64
#define TGUILD_ESTABLISH_LEVEL			20
#define TMAIL_ITEM_MAX					3

#define TITEM_UP_DELAY					8000
#define TSOULMATE_REG_DELAY				5000
#define TDURATIONREP_PERIOD				2000
#define TGAMBLE_PERIOD					2000
#define TREFINE_PERIOD					5000
#define TCRAFT_PERIOD					5000

#define TPORTAL_IMAGEID					1

#define TPARTYITEMLOTTERY_INIT_X		20
#define TPARTYITEMLOTTERY_INIT_Y		50
#define TPARTYITEMLOTTERY_SPACE_X		5
#define TPARTYITEMLOTTERY_SPACE_Y		5
#define TPARTYITEMLOTTERY_COUNT_Y		3

#define TLEVEL_CHANGE_MIN_DELAY			1000
#define TCHANGE_CHANNEL_DELAY			8000
#define TSELECT_CHARACTER_DELAY			8000
#define TSELECT_EXITGAME_DELAY			8000
#define TKICKOUTMAP_DELAY				8000
#define TNOTIFY_PERIOD					1000

#define TREG_CUSTOMUI					_T("CustomUI")
#define TREG_CUSTOM_UI_RESET_IDENTITY	((DWORD)(0x0004))
#define TREG_CUSTOMUI_RESET				_T("Reset")
#define TREG_CUSTOMUI_MY_GAUGE			_T("MyGauge")
#define TREG_CUSTOMUI_RECALL_GAUGE		_T("RecallGauge")
#define TREG_CUSTOMUI_TARGET_GAUGE		_T("TargetGauge")
#define TREG_CUSTOMUI_PARTY_GAUGE		_T("PartyGauge")
#define TREG_CUSTOMUI_HOTKEY			_T("HotKeyDef")
#define TREG_CUSTOMUI_HOTKEY_SUB1		_T("HotKeySub1")
#define TREG_CUSTOMUI_RECALLAI			_T("RecallAi")
#define TREG_CUSTOMUI_NOTIFY			_T("Notify")
#define TREG_CUSTOMUI_QUEST				_T("Quest")
#define TREG_CUSTOMUI_DEFINVEN			_T("DefInven")
#define TREG_CUSTOMUI_SUBINVEN			_T("SubInven%d")
#define TREG_CUSTOMUI_POS_X				_T("X")
#define TREG_CUSTOMUI_POS_Y				_T("Y")
#define TREG_CUSTOMUI_BASIS				_T("BASIS")

#define TLOADMSG_POS_X					(10)
#define TLOADMSG_POS_Y					(620)
#define TLOADMSG_BASE_WIDTH				(1024)
#define TLOADMSG_BASE_HEIGHT			(768)

#define TMAX_CABINET_CNT				(3)
#define TMAX_SMS_CHARACTER				(80)

#define TMAXGUILDMARK_MAKETICK			((DWORD) 10)
#define TMAXGUILDMARK_BASETICK			((DWORD) 2)
#define TGUILDMARK_TEXEXTCNT			((DWORD) 3)
#define TGUILDMARK_TEXSIZE				((FLOAT) 32.0f)

#define TGMARK(mark, back)				((DWORD)(((((mark)+1)&0xFF)<<16) | (((back)+1)&0xFF)))
#define TGMCOLOR(mark, back1, back2)	((DWORD)((((mark)&0xFF)<<16) | (((back1)&0xFF)<<8) | ((back2)&0xFF)))

#define TGMARK_MARK(l)					((BYTE)(((l) >> 16) & 0xFF) - 1)		
#define TGMARK_BACK(l)					((BYTE)((l) & 0xFF) - 1)

#define TGMCOLOR_MARK(val)				((BYTE)(((val)>>16)&0xFF))
#define TGMCOLOR_BACK1(val)				((BYTE)(((val)>>8)&0xFF))
#define TGMCOLOR_BACK2(val)				((BYTE)((val)&0xFF))

#define MIN_EXP_DONATIONRATE			(0.01f)
#define MAX_EXP_DONATIONRATE			(0.1f)

#define MIN_MONEY_DONATION				(1000)
#define MAX_MONEY_DONATION				(1000000)

#define TMAXGUILD_MARK_COLOR			(38)

#define	TMAX_GUILDMSG_TITLE				(50)
#define TMAX_FRIENDGROUP_NAME			(20)

#define MAX_LOADING_PCROOM_TEXT			(6)

#define TWATERGRID_SIZE					(8)
#define TGRID_SIZE						(1)

#define TMAGICLEVEL_UNIT				(10)
#define TMAGICLEVEL_MAX					(9)

#define TRUNAWAYPOINT_COUNT				(10)
#define TRUNAWAYTIME_MIN				(1000)
#define TRUNAWAYTIME_MAX				(3000)

#define TATTRLEVELNAME_MAX				(13)
#define TATTRLEVELNAME_UNIT				(10)
#define TATTRLEVEL_SEPERATE				(34)
#define TATTRLEVEL_LOWUNIT				(3)
#define TATTRLEVEL_HIGHUNIT				(2)

#define TMAX_HEIGHT_OFFSET				(3.0f)
#define TMAX_RAND_POS					(10)

#define TSTART_EVENT_NPCID_D			(20001)
#define TSTART_EVENT_NPCID_C			(20058)
#define TFIRST_CONNET_EVENT_TRY			(10)
#define TFIRST_CONNET_EVENT_KEY			(2)

#define TUNIT_BOUND						(32)

#define TFLY_MAX						((FLOAT) 11.0f)
#define TFLY_MIN						((FLOAT) 3.5f)

#define TREWARDITEMCOUNT				2

#define TBASISPOINT_LEFT_TOP			0
#define TBASISPOINT_CENTER_TOP			1
#define TBASISPOINT_RIGHT_TOP			2

#define TBASISPOINT_LEFT_MIDDLE			3
#define TBASISPOINT_CENTER_MIDDLE		4
#define TBASISPOINT_RIGHT_MIDDLE		5

#define TBASISPOINT_LEFT_BOTTOM			6
#define TBASISPOINT_CENTER_BOTTOM		7
#define TBASISPOINT_RIGHT_BOTTOM		8
#define TBASISPOINT_COUNT				9

#define TAUCTION_SLOT_COUNT				9
#define TAUCTION_MAXPAGE_COUNT			5

#define FAMERANKCOUNT					9
#define TFAMERANK_DEF_SIZE				248

#define TIMAGELIST_FACE_NULL			168
#define TIMAGELIST_COUNTRY_NULL			3
#define TIMAGELIST_CLASS_NULL			6

// Arab Ver.
static BYTE TBASISPOINT_TRANSFER[TBASISPOINT_COUNT] = {
	TBASISPOINT_RIGHT_TOP,
	TBASISPOINT_CENTER_TOP,
	TBASISPOINT_LEFT_TOP,
	TBASISPOINT_RIGHT_MIDDLE,
	TBASISPOINT_CENTER_MIDDLE,
	TBASISPOINT_LEFT_MIDDLE,
	TBASISPOINT_RIGHT_BOTTOM,
	TBASISPOINT_CENTER_BOTTOM,
	TBASISPOINT_LEFT_BOTTOM	};

///////////////////////////////////////////////////////////////////////////
// TClient enum define

typedef enum TPICK
{
	TPICK_ALIVE_ALL=0,
	TPICK_DEAD_ALL,
	TPICK_ALIVE_MONSTER,
	TPICK_ALIVE_PLAYER,
	TPICK_DEAD_MONSTER,
	TPICK_DEAD_PLAYER,
	TPICK_COUNT
};

typedef enum TSHOPPHURCHASETYPE
{
	TSHOP_PHURCHASE_TYPE_MONEY = 0,
	TSHOP_PHURCHASE_TYPE_POINT = 1,
	TSHOP_PHURCHASE_COUNT
};

typedef enum TPVPM
{
	TPVPM_REGULAR=0,
	TPVPM_TACTICS,
	TPVPM_LATEST_PVPR,
	TPVPM_WEEK_PVPR,
	TPVPM_COUNT
};

typedef enum TGM_PBTN
{
	TGM_PBTN_WHISPER,						///< 귓말
	TGM_PBTN_MAIL,							///< 편지
	TGM_PBTN_POINT_REWARD,			///< 포인트 포상
	TGM_PBTN_PARTY,							///< 파티초대
	TGM_PBTN_FRIEND,						///< 친구초대
	TGM_PBTN_KICK,							///< 추방
	TGM_PBTN_SET_GM,						///< 길드장 위임
	TGM_PBTN_SET_GSM,						///< 부길드장 위임
	TGM_PBTN_CANCEL_GSM,					///< 부길드장 해임
	TGM_PBTN_PEER_BARON,					///< 남작 임명
	TGM_PBTN_PEER_VISCOUNT,					///< 자작 임명	
	TGM_PBTN_PEER_COUNT,					///< 백작 임명
	TGM_PBTN_PEER_MARQUIS,					///< 후작 임명
	TGM_PBTN_PEER_DUKE,						///< 공작 임명
	TGM_PBTN_CANCEL_PEER,					///< 작위 취소
	TGM_PBTN_CANCEL,						///< 팝업닫기
	TGM_PBTN_VOLUNTEER_HESED,				///< 헤세드지원
	TGM_PBTN_VOLUNTEER_ARDRI,				///< 아르드리지원
	TGM_PBTN_VOLUNTEER_TYCON,				///< 타이콘테로가지원
	TGM_PBTN_VOLUNTEER_GEHBRA,				///< 게브라지원
	TGM_PBTN_VOLUNTEER_CANCEL,				///< 지원취소
	TGM_PBTN_TACTICS_RE_CONTRACT,			///< 용병 재계약
	TGM_PBTN_TACTICS_KICK,						///< 용병 계약 파기
	TGM_PBTN_TACTICS_REWARD_POINT,			///< 용병 포상
	TGM_PBTN_COUNT
};

typedef enum RegularInfo
{
	RINFO_NAME,							///< 캐릭터 이름
	RINFO_CLASS,						///< 직업
	RINFO_LEVEL,						///< 레벨
	RINFO_SERVICE,						///< 기여도
	RINFO_DUTY,							///< 직위
	RINFO_PEER,							///< 작위
	RINFO_POSITION,						///< 위치
	RINFO_COUNT,
};

typedef enum TacticsInfo
{
	TACTICS_INFO_NAME=0, //캐릭터 이름 : m_strName
	TACTICS_INFO_CLASS, //직업 : m_bClass
	TACTICS_INFO_LEVEL, //레벨 : m_bLevel
	TACTICS_INFO_GOTPOINT, //전투기여도 : m_dwGotPoint
	TACTICS_INFO_POINT, //수당 : m_dwPoint
	TACTICS_INFO_DAY, //계약기간 : m_bDay;
	TACTICS_INFO_REGION, //현재위치 : m_dwRegion
	TACTICS_INFO_COUNT,
};

typedef enum WeekInfo
{
	WEEK_INFO_NAME,
	WEEK_INFO_JOB,
	WEEK_INFO_LEVEL,
	WEEK_INFO_KILLPOINT_H,
	WEEK_INFO_KILLPOINT_E,
	WEEK_INFO_KILLPOINT_L,
	WEEK_INFO_GODMONKILLPOINT,
	WEEK_INFO_ENTRYPOINT,
	WEEK_INFO_RESULT,
	WEEK_INFO_KILLCOUNT,
	WEEK_INFO_DIECOUNT,
	WEEK_INFO_COUNT
};

typedef enum LatestInfo
{
	LATEST_INFO_NAME,
	LATEST_INFO_JOB,
	LATEST_INFO_LEVEL,
	LATEST_INFO_KILLPOINT_H,
	LATEST_INFO_KILLPOINT_E,
	LATEST_INFO_KILLPOINT_L,
	LATEST_INFO_GODMONKILLPOINT,
	LATEST_INFO_ENTRYPOINT,
	LATEST_INFO_RESULT,
	LATEST_INFO_KILLCOUNT,
	LATEST_INFO_DIECOUNT,
	LATEST_INFO_COUNT
};

typedef enum PREMIUM_MAINTAIN
{
	PREMIUM_MAINTAIN1 = 900,	//4S골드 프리미엄(30일)
	PREMIUM_MAINTAIN2 = 901,	//4S골드 프리미엄(10시간)
	PREMIUM_MAINTAIN3 = 902,	//4S골드 프리미엄(3시간)
	PREMIUM_MAINTAIN4 = 903,	//PC방 혜택
	PREMIUM_MAINTAIN5 = 914,	//4S골드 프리미엄
	PREMIUM_MAINTAIN6 = 915,	//4S실버 프리미엄
	PREMIUM_MAINTAIN7 = 916,	//4S 프리미엄		
	PREMIUM_MAINTAIN_COUNT = 7
};

typedef enum TERROR_CODE
{
	TERR_NONE = 0,
	TERR_CONNECT_FAILED,
	TERR_LOGIN_NOID,
	TERR_DUP_CONNECT,
	TERR_NETCABLE_DISCONNECTED,
	TERR_INVALID_VERSION,
	TERR_INVALID_PASSWD,
	TERR_INVALID_CHAR,
	TERR_INVALID_USER,
	TERR_INVALID_SLOT,
	TERR_INVALID_NAME,
	TERR_IPBLOCK,
	TERR_NAME_TOO_LONG,
	TERR_DUPNAME,
	TERR_NOCHANNEL,
	TERR_NOSERVER,
	TERR_NOGROUP,
	TERR_NONAME,
	TERR_NOCHAR,
	TERR_NOSLOT,
	TERR_NEEDCREATECARD,
	TERR_ITEM_NO_MONEY,
	TERR_ITEM_NOT_FOUND,
	TERR_ITEM_NO_SLOT,
	TERR_ITEM_DEALING,
	TERR_ITEM_CANNOT_SELL,
	TERR_INTERNAL,
	TERR_DELCHAR_INGUILD,
	TERR_SERVER_BUSY,
	TERR_CHANNEL_BUSY,
	TERR_MAIL_REGION,
	TERR_CABINET,
	TERR_CABINET_NO_SLOT,
	TERR_MAX_CABINET,
	TERR_CURSE_STR,
	TERR_ITEM_INTERNAL,
	TERR_SND_TARGET,
	TERR_NO_GUILD,
	TERR_NEED_CASH,
	TERR_NOTARGET_CASH,
	TERR_SOULMATE_SILENCE,
	TERR_SOULMATE_NEEDMONEY,
	TERR_SOULMATE_NOTFOUND,
	TERR_SOULMATE_FAIL,
	TERR_DURATIONREP_NOTNEED,
	TERR_DURATIONREP_NOMONEY,
	TERR_DURATIONREP_DISALLOW,
	TERR_DURATIONREP_FAIL,
	TERR_REFINE_NOMONEY,
	TERR_REFINE_MAXREFINE,
	TERR_REFINE_LEVELDIFF,
	TERR_REFINE_FAIL,
	TERR_CASHSHOP_NOTFOUND,
	TERR_CASHSHOP_MAXCOUNT,
	TERR_CASHSHOP_NEEDEXTEND,
	TERR_CASHSHOP_NOTARGET,
	TERR_CASHSHOP_NOCASHINFO,
	TERR_EXTEND_PERIOD_FAIL,
	TERR_FAILED_STOREOPEN,
	TERR_GUILD_REWARD_NEEDPOINT,
	TERR_GUILD_REWARD_NOMEMBER,
	TERR_GUILD_REWARD_INVALID,
	TERR_ITEM_NO_POINT,
	TERR_GUILD_NOINPUT_ARTICLE_TITLE,
	TERR_GUILD_NOINPUT_ARTICLE_CONTENTS,
	TERR_GUILD_NOINPUT_ARTICLE_MINLEVEL,
	TERR_GUILD_NOINPUT_ARTICLE_MAXLEVEL,
	TERR_GUILD_NOINPUT_ARTICLE_DAY,
	TERR_GUILD_NOINPUT_ARTICLE_POINT,
	TERR_GUILD_NOINPUT_ARTICLE_MONEY,
	TERR_GUILD_NOTDUTY_WANTED_ADD_DEL,
	TERR_GUILD_NOT_OWN_WANTED,
	TERR_GUILD_ONLY_MASTER,
	TERR_GUILD_SELECT_WANTED,
	TERR_NEED_JOIN_GUILD,
	TERR_NOITEM,
	TERR_COUNT
} *LPTERROR_CODE;


typedef enum TLIGHT_SET
{
	TLIGHTSET_MAIN = 0,
	TLIGHTSET_MAPCOLOR,
	TLIGHTSET_SHADOW,
	TLIGHTSET_MTRL,
	TLIGHTSET_OBJMTRL,
	TLIGHTSET_COUNT
} *LPTLIGHT_SET;

typedef enum TTARGET_DIST
{
	TD_NONE = 0,
	TD_LB,
	TD_AB,
	TD_COUNT
} *LPTTARGET_DIST;

typedef enum TNET_FRAME
{
	TNETFRAME_LOGIN,
	TNETFRAME_AGREEMENT,
	TNETFRAME_SERVER,
	TNETFRAME_CONTRY,
	TNETFRAME_CHAR,
	TNETFRAME_NEWCHAR,
	TNETFRAME_LOADING,
	TNETFRAME_COUNT
} *LPTNET_FRAME;

typedef enum TGAME_FRAME
{
	TFRAME_DEFINVEN = 0,
	TFRAME_INVEN_1,
	TFRAME_INVEN_2,
	TFRAME_INVEN_3,
	TFRAME_INVEN_4,
	TFRAME_INVEN_5,
	TFRAME_CHAR_INFO,
	TFRAME_TARGET_INFO,
	TFRAME_DETAIL_INFO,
	TFRAME_CHAT_DETAIL_INFO,
	TFRAME_MONINVEN,
	TFRAME_GAUGE,
	TFRAME_ITEM_SHOP,
	TFRAME_RENT_SKILL,
	TFRAME_PORTAL_SHOP,
	TFRAME_TRADE,
	TFRAME_SKILL,
	TFRAME_QUEST,
	TFRAME_NPCDIALOG,
	TFRAME_CRAFT,
	TFRAME_MAIN,
	TFRAME_MAIN_MENU,
	TFRAME_SETTING,
	TFRAME_WORLDMAP,
	TFRAME_ITEM_UP,
	TFRAME_ITEM_UP_GAUGE,
	TFRAME_ITEM_REPAIR,
	TFRAME_ITEM_REFINE,
	TFRAME_ITEM_GAMBLE,
	TFRAME_COMMUNITY,
	TFRAME_PRIVATE_SELL,
	TFRAME_PRIVATE_BUY,
	TFRAME_MESSENGER,
	TFRAME_MAIL,
	TFRAME_MAIL_SEND,
	TFRAME_MAIL_RECV,
	TFRAME_MAIL_ASK_MONEY,
	TFRAME_PET_MAKE,
	TFRAME_PET_MANAGE,
	TFRAME_ITEM_REGBOX,
	TFRAME_CABINET,
	TFRAME_KEYSETTING,
	TFRAME_SMS,
	TFRAME_DONATE_EXP,
	TFRAME_DONATE_MONEY,
	TFRAME_GUILDNOTIFY,
	TFRAME_GUILDMARK,
	TFRAME_GUILDAPP,
	TFRAME_GUILDCMD,
	TFRAME_GUILDCABINET,
	TFRAME_CASHCABINET,
	TFRAME_CASHCHARGE,
	TFRAME_PROGRESS_REG,
	TFRAME_CINEMATIC,
	TFRAME_ITEM_EXTPERIOD,
	TFRAME_DETAIL_NAME,
	TFRAME_HELP,
	TFRAME_CASHSHOP_NEW,
	TFRAME_CHAR_PVP_INFO,
	TFRAME_GUILDPOINTLOG,
	TFRAME_GUILDPOINTREWARD,
	TFRAME_SIEGEUI,
	TFRAME_SIEGEEND,
	TFRAME_MONSHOP,
	TFRAME_WARN_NOTUSE_CASHITEM,
	TFRAME_WARN_UPITEM_SELL,
	TFRAME_PORTAL_SHOP_NEW,
	TFRAME_AUCTION,
	TFRAME_BIDON,
	TFRAME_GUILD_REGULAR_OFFER,
	TFRAME_GUILD_TACTICS_OFFER,
#ifdef ADD_TEXTOOL
	TFRAME_TEXTOOL,
#endif
	TFRAME_INVITE_TACTICS,
	TFRAME_ITEM_REGGM,
	TFRAME_COLOR_PICKER,
	TFRAME_FAME_BASE,
	TFRAME_RANK_INFO,
#ifdef ADD_WEB_CASHSHOP
	TFRAME_WEB_CASHSHOP,
#endif
#ifdef ADD_TOURNAMENT
	TFRAME_TOURNAMENT_EVENT,
	TFRAME_TOURNAMENT_GAGE,
	TFRAME_TOURNAMENT_SELECT_TARGET,
	TFRAME_TOURNAMENT,
	TFRAME_TOURNAMENT_RESULT,
#endif
	TFRAME_WELCOME,
#ifdef ADD_RPS
	TFRAME_RPS,
	TFRAME_RPS_REWARD,
#ifdef ADD_RPS_RL
	TFRAME_RPS_REWARD_LIST,
#endif
#endif
	TFRAME_COUNT
} *LPTGAME_FRAME;

typedef enum TCHAT_SET
{
	TCHAT_SET_ALL,					// 전체
	TCHAT_SET_NORMAL,				// 일반
	TCHAT_SET_WHISPER,				// 귓말
	TCHAT_SET_PARTY,				// 일행
	TCHAT_SET_GUILD,				// 길드
	TCHAT_SET_FORCE,				// 부대
	TCHAT_SET_RESULT,				// 결과
	TCHAT_SET_COUNT
} *LPTCHAT_SET;

typedef enum TCHAT_POPUP
{
	TCHAT_POPUP_WHISPER,			// 귓말
	TCHAT_POPUP_NEAR,				// 일반
	TCHAT_POPUP_MAP,				// 전체
	TCHAT_POPUP_PARTY,				// 파티
	TCHAT_POPUP_GUILD,				// 길드
	TCHAT_POPUP_FORCE,				// 전대
	TCHAT_POPUP_GM,					// 운영자(GM문의)
	TCHAT_POPUP_COUNT
} *LPTCHAT_POPUP;

typedef enum TGAUGE_SET
{
	TGAUGE_PLAYER_HP = 0,
	TGAUGE_PLAYER_MP,
	TGAUGE_PLAYER_EXP,
	TGAUGE_SUMMON_HP,
	TGAUGE_SUMMON_MP,
	TGAUGE_TARGET_HP,
	TGAUGE_BREATH,
	TGAUGE_CHARGE,
	TGAUGE_VITAL,
	TGAUGE_PARTY1_HP,
	TGAUGE_PARTY1_MP,
	TGAUGE_PARTY2_HP,
	TGAUGE_PARTY2_MP,
	TGAUGE_PARTY3_HP,
	TGAUGE_PARTY3_MP,
	TGAUGE_PARTY4_HP,
	TGAUGE_PARTY4_MP,
	TGAUGE_PARTY5_HP,
	TGAUGE_PARTY5_MP,
	TGAUGE_PARTY6_HP,
	TGAUGE_PARTY6_MP,
	TGAUGE_TARGET_VITAL,
	TGAUGE_COUNT
} *LPTGAUGE_SET;


typedef enum TTEXT_SET
{
	TTEXT_PLAYER_EXP,
	TTEXT_PLAYER_RUNE,
	TTEXT_PLAYER_LUNA,
	TTEXT_PLAYER_CRON,
	TTEXT_PLAYER_NAME,
	TTEXT_PLAYER_LEVEL,
	TTEXT_PLAYER_CLASS,
	TTEXT_PLAYER_HP,
	TTEXT_PLAYER_MP,
	TTEXT_SUMMON_NAME,
	TTEXT_SUMMON_LEVEL,
	TTEXT_SUMMON_HP,
	TTEXT_SUMMON_MP,
	TTEXT_SUMMON_TIME,
	TTEXT_TARGET_NAME,
	TTEXT_TARGET_LEVEL,
	TTEXT_TARGET_HP,
	TTEXT_TARGET_CLASS,
	TTEXT_PARTY1_NAME,
	TTEXT_PARTY2_NAME,
	TTEXT_PARTY3_NAME,
	TTEXT_PARTY4_NAME,
	TTEXT_PARTY5_NAME,
	TTEXT_PARTY6_NAME,
	TTEXT_PARTY1_LEVEL,
	TTEXT_PARTY2_LEVEL,
	TTEXT_PARTY3_LEVEL,
	TTEXT_PARTY4_LEVEL,
	TTEXT_PARTY5_LEVEL,
	TTEXT_PARTY6_LEVEL,
	TTEXT_PARTY1_HP,
	TTEXT_PARTY2_HP,
	TTEXT_PARTY3_HP,
	TTEXT_PARTY4_HP,
	TTEXT_PARTY5_HP,
	TTEXT_PARTY6_HP,
	TTEXT_PARTY1_CLASS,
	TTEXT_PARTY2_CLASS,
	TTEXT_PARTY3_CLASS,
	TTEXT_PARTY4_CLASS,
	TTEXT_PARTY5_CLASS,
	TTEXT_PARTY6_CLASS,
	TTEXT_COUNT
} *LPTTEXT_SET;


typedef enum TPANNEL_SET
{
	TPANNEL_PLAYER = 0,
	TPANNEL_SUMMON,
	TPANNEL_TARGET,
	TPANNEL_PARTY1,
	TPANNEL_PARTY2,
	TPANNEL_PARTY3,
	TPANNEL_PARTY4,
	TPANNEL_PARTY5,
	TPANNEL_PARTY6,
	TPANNEL_COUNT
} *LPTPANNEL_SET;


typedef enum TLEADERMARK_SET
{
	TLEADERMARK_PLAYER = 0,
	TLEADERMARK_TARGET,
	TLEADERMARK_PARTY1,
	TLEADERMARK_PARTY2,
	TLEADERMARK_PARTY3,
	TLEADERMARK_PARTY4,
	TLEADERMARK_PARTY5,
	TLEADERMARK_PARTY6,
	TLEADERMARK_COUNT
} *LPTLEADERMARK_SET;


typedef enum TFACEIMG_SET
{
	TFACEIMG_PLAYER = 0,
	TFACEIMG_SUMMON_N,
	TFACEIMG_SUMMON_S,
	TFACEIMG_TARGETMON_N,
	TFACEIMG_TARGETMON_S,
	TFACEIMG_TARGETPC,
	TFACEIMG_PARTY1,
	TFACEIMG_PARTY2,
	TFACEIMG_PARTY3,
	TFACEIMG_PARTY4,
	TFACEIMG_PARTY5,
	TFACEIMG_PARTY6,
	TFACEIMG_COUNT
} *LPTFACEIMG_SET;

typedef enum TLEVELIMG_SET
{
	TLEVELIMG_PLAYER = 0,
	TLEVELIMG_SUMMON,
	TLEVELIMG_TARGET,
	TLEVELIMG_PARTY1,
	TLEVELIMG_PARTY2,
	TLEVELIMG_PARTY3,
	TLEVELIMG_PARTY4,
	TLEVELIMG_PARTY5,
	TLEVELIMG_PARTY6,
	TLEVELIMG_COUNT
} *LPTLEVELIMG_SET;

typedef enum TFACEBACKIMG_SET
{
	TFACEBACKIMG_PLAYER = 0,
	TFACEBACKIMG_SUMMON,
	TFACEBACKIMG_TARGET,
	TFACEBACKIMG_PARTY1,
	TFACEBACKIMG_PARTY2,
	TFACEBACKIMG_PARTY3,
	TFACEBACKIMG_PARTY4,
	TFACEBACKIMG_PARTY5,
	TFACEBACKIMG_PARTY6,
	TFACEBACKIMG_COUNT
} *LPFACEBACKIMG_SET;

typedef enum TGAUGE_FRAME
{
	TGAUGE_FRAME_PLAYER,
	TGAUGE_FRAME_SUMMON,
	TGAUGE_FRAME_TARGET,
	TGAUGE_FRAME_PARTY,
	TGAUGE_FRAME_NOTIFY,
	TGAUGE_FRAME_COUNT
} *LPTGAUGE_FRAME;

typedef enum THUDBASE_SET
{
	THUD_BASE_MY_HP,
	THUD_BASE_OP_HP,
	THUD_BASE_MY_MP,
	THUD_BASE_OP_MP,
	THUD_BASE_COUNT
} *LPTHUDBASE_SET;

typedef enum THUDGAUGE_SET
{
	THUD_GAUGE_MY_HP,
	THUD_GAUGE_OP_HP,
	THUD_GAUGE_MY_MP,
	THUD_GAUGE_OP_MP,
	THUD_GAUGE_COUNT
} *LPTHUDGAUGE_SET;

typedef enum THUDTEXT_SET
{
	THUD_TEXT_MY_HP,
	THUD_TEXT_OP_HP,
	THUD_TEXT_MY_MP,
	THUD_TEXT_OP_MP,
	THUD_TEXT_COUNT
} *LPTHUDTEXT_SET;

typedef enum TCOLLISION_TYPE
{
	TCOLLISION_NONE = 0,
	TCOLLISION_BOX,
	TCOLLISION_CYLINDER,
	TCOLLISION_POLY,
	TCOLLISION_COUNT
} *LPTCOLLISION_TYPE;

typedef enum TINFO_CHAR
{
	TINFO_BASIC = 0,
	TINFO_MORE,
	TINFO_WAR,
	TINFO_PVP,
	TINFO_RANK,
	TINFO_COUNT
} *LPTINFO_CHAR;

typedef enum TMAINMOVE_TYPE
{
	TMAINMOVE_NORMAL = 0,
	TMAINMOVE_CLICK,
	TMAINMOVE_TARGET,
	TMAINMOVE_GROUND,
	TMAINMOVE_FOLLOW,
	TMAINMOVE_COUNT
} *LPTMAINMOVE_TYPE;


typedef enum TMINIMAP_COMP
{
	TMINIMAPCOMP_MAX = 0,
	TMINIMAPCOMP_WORLD,
	TMINIMAPCOMP_TOGGLE_RSCS,
	TMINIMAPCOMP_ZOOM,
	TMINIMAPCOMP_COUNT
} *LPTMINIMAP_COMP;

typedef enum TRSCS_COMP
{
	TRSCSCOMP_MAX = 0,
	TRSCSCOMP_WORLD,
	TRSCSCOMP_TOGGLE_RSCS,
	TRSCSCOMP_ZOOM,
	TRSCSCOMP_TOGGLE_SQUAD,
	TRSCSCOMP_SEL_SQUAD,
	TRSCSCOMP_COUNT
} *LPTRSCS_COMP;

typedef enum THASQUEST_LEVEL
{
	THASQUEST_NONE = 0,
	THASQUEST_MISSION_X,
	THASQUEST_COMPLETE_X,
	THASQUEST_MISSION,
	THASQUEST_ROUTING,
	THASQUEST_COMPLETE,
	THASQUEST_CRAFT,
	THASQUEST_COUNT
} *LPTHASQUEST_LEVEL;


typedef enum TTERMRESULT_TYPE
{
	TTERMRESULT_COMPLETE = 0,
	TTERMRESULT_INCOMPLETE,
	TTERMRESULT_FAILED,
	TTERMRESULT_TIMEOUT,
	TTERMRESULT_COUNT
} *LPTTERMRESULT_TYPE;


typedef enum TCHAR_STAT
{
	TCHARSTAT_STR = 0,	// 힘
	TCHARSTAT_DEX,		// 민첩
	TCHARSTAT_CON,		// 체력
	TCHARSTAT_INT,		// 지능
	TCHARSTAT_WIS,		// 지혜
	TCHARSTAT_MEN,		// 정신
	TCHARSTAT_COUNT
} *LPTCHAR_STAT;


typedef enum TCHAR_BASIC
{
	TCHARBASIC_PAP = 0,	// 물리 공격력
	TCHARBASIC_PDP,		// 물리 방어력
	TCHARBASIC_PSP,		// 물리 원거리 공격력
	TCHARBASIC_PAL,		// 물리 공격등급
	TCHARBASIC_PDL,		// 물리 방어등급
	TCHARBASIC_PCR,		// 물리 치명확률
	TCHARBASIC_MAP,		// 마법 공격력
	TCHARBASIC_MDP,		// 마법 방어력
	TCHARBASIC_STA,		// 마법 시전 유지확률
	TCHARBASIC_MAL,		// 마법 공격등급
	TCHARBASIC_MDL,		// 마법 방어등급
	TCHARBASIC_MCR,		// 마법 치명확률
	TCHARBASIC_COUNT
} *LPTCHAR_BASIC;


typedef enum TCHAR_ADV
{
	TCHARADV_NATION=0,
	TCHARADV_RACE,
	TCHARADV_CLASS,
	TCHARADV_GRADE,
	TCHARADV_PVPTOTALPOINT,
	TCHARADV_PVPUSEABLEPOINT,
	TCHARADV_COUNT
} *LPTCHAR_ADV;

typedef enum TCHARINFO_FRAME
{
	TCHARFRAME_BASIC = 0,
	TCHARFRAME_ADV,
	TCHARFRAME_STAT,
	TCHARFRAME_COUNT
} *LPTCHARINFO_FRAME;


typedef enum TCHARINFO_PANE
{
	TCHARPANE_LEFT = 0,
	TCHARPANE_RIGHT,
	TCHARPANE_COUNT
} *LPTCHARINFO_PANE;


typedef enum TDETAILINFO_ICON
{
	TDETAILINFO_ICON_ITEM = 0,
	TDETAILINFO_ICON_SKILL,
	TDETAILINFO_ICON_COUNT,
	TDETAILINFO_ICON_NONE = TDETAILINFO_ICON_COUNT
} *LPTDETAILINFO_ICON;

typedef enum TINFOKEY_TYPE
{
	TINFOKEY_TYPE_INFO,
	TINFOKEY_TYPE_ITEM, 
	TINFOKEY_TYPE_SKILL,
	TINFOKEY_TYPE_COUNT
} *LPTINFOKEY_TYPE;

typedef enum TMAINTAIN_TYPE
{
	TMTYPE_P = 0,
	TMTYPE_N,
	TMTYPE_COUNT
} *LPTMAINTAIN_TYPE;


typedef enum TEQUIP_MODE
{
	TEM_NORMAL = 0,
	TEM_WEAPON,
	TEM_LONG,
	TEM_COUNT
} *LPTEQUIP_MODE;


typedef enum TSLASH_SFX
{
	TSLASHSFX_RHAND = 0,
	TSLASHSFX_LHAND,
	TSLASHSFX_COUNT
} *LPTSLASH_SFX;


typedef enum TANICHANNEL
{
	TANICH_PRM = 0,
	TANICH_2ND,
	TANICH_COUNT
} *LPTANICHANNEL;


typedef enum TRECALL_AI
{
	TRECALLAI_MANUAL = 0,
	TRECALLAI_ACTIVE,
	TRECALLAI_PASSIVE,
	TRECALLAI_BACK,
	TRECALLAI_STAY,
	TRECALLAI_COUNT
} *LPTRECALL_AI;


typedef enum TSKILL_POINT
{
	TPOINT_TAB1 = 0,
	TPOINT_TAB2,
	TPOINT_TAB3,
	TPOINT_TAB4,
	TPOINT_MINE,
	TPOINT_COUNT
} *LPTSKILL_POINT;


typedef enum TSKYOBJ_TYPE
{
	TSKYOBJ_FAR = 0,
	TSKYOBJ_SKY,
	TSKYOBJ_COUNT
} *LPTSKYOBJ_TYPE;


typedef enum TCORPSMOVE_TYPE
{
	TCORPSMOVE_NONE = 0,
	TCORPSMOVE_UNIT,
	TCORPSMOVE_ENEMY,
	TCORPSMOVE_COUNT
} *LPTCORPSMOVE_TYPE;

typedef enum TINFOTOKEN_TYPE
{
	TINFOTOKEN_VALUE1 = 0,
	TINFOTOKEN_VALUE2,
	TINFOTOKEN_VALUE3,
	TINFOTOKEN_VALUE4,
	TINFOTOKEN_VALUE5,
	TINFOTOKEN_VALUE6,
	TINFOTOKEN_LEVEL,
	TINFOTOKEN_DURATION,
	TINFOTOKEN_HP,
	TINFOTOKEN_MP,
	TINFOTOKEN_UPGRADE_TITLE,
	TINFOTOKEN_CLASS_POINT,
	TINFOTOKEN_SKILL_POINT,
	TINFOTOKEN_NEXT_LEVEL,
	TINFOTOKEN_PRICE,
	TINFOTOKEN_REUSE0,
	TINFOTOKEN_REUSE1,
	TINFOTOKEN_REUSE2,
	TINFOTOKEN_REUSE3,
	TINFOTOKEN_REUSE4,
	TINFOTOKEN_SECVALUE,
	TINFOTOKEN_GRADE,
	TINFOTOKEN_SETITEMNAME,
	TINFOTOKEN_GRASETNAMEDE,
	TINFOTOKEN_UNIQUEITEMNAME,
	TINFOTOKEN_OPTIONNAME1,
	TINFOTOKEN_OPTIONNAME2,
	TINFOTOKEN_OPTIONNAME3,
	TINFOTOKEN_OPTIONNAME4,
	TINFOTOKEN_OPTIONNAME5,
	TINFOTOKEN_OPTIONNAME6,
	TINFOTOKEN_OPTIONDATA1,
	TINFOTOKEN_OPTIONDATA2,
	TINFOTOKEN_OPTIONDATA3,
	TINFOTOKEN_OPTIONDATA4,
	TINFOTOKEN_OPTIONDATA5,
	TINFOTOKEN_OPTIONDATA6,
	TINFOTOKEN_ITEMMINAP,
	TINFOTOKEN_ITEMMAXAP,
	TINFOTOKEN_ITEMAPSEC,
	TINFOTOKEN_ITEMDP,
	TINFOTOKEN_ITEMMINMAP,
	TINFOTOKEN_ITEMMAXMAP,
	TINFOTOKEN_ITEMMAPSEC,
	TINFOTOKEN_ITEMMDP,
	TINFOTOKEN_ITEMBLOCK,
	TINFOTOKEN_COUNT
} *LPTINFOTOKEN_TYPE;

typedef enum TINFOTOKEN_LINE_TYPE
{
	TINFOTOKEN_LINE_ITEMNORMAL,
	TINFOTOKEN_LINE_ITEMGRADE,
	TINFOTOKEN_LINE_ITEMMAGIC,
	TINFOTOKEN_LINE_ITEMSET,
	TINFOTOKEN_LINE_ITEMRARE,
	TINFOTOKEN_LINE_ITEMUNIQUE,
	TINFOTOKEN_LINE_COUNT
} *LPTINFOTOKEN_LINE_TYPE;

typedef enum TINFOTOKEN_COUNT_TYPE
{
	TINFOTOKEN_VALUE_COUNT = 6,
	TINFOTOKEN_OPTION_COUNT = 6
} *LPTINFOTOKEN_COUNT_TYPE;

typedef enum TDETAIL_LEVEL
{
	TDETAIL_LOW = 0,
	TDETAIL_MED,
	TDETAIL_HI,
	TDETAIL_COUNT
} *LPTDETAIL_LEVEL;


typedef enum TOPTION_LEVEL
{
	TOPTIONLEVEL_LOW = 0,
	TOPTIONLEVEL_MED,
	TOPTIONLEVEL_HI,
	TOPTIONLEVEL_COUNT
} *LPTOPTION_LEVEL;


typedef enum TSYSTEM_CHECK_OPTION
{
	TSYSTEM_CHECK_SCREEN_MODE = 0,
	TSYSTEM_CHECK_MAP_SHADOW,
	TSYSTEM_CHECK_MAP_SFX,
	TSYSTEM_CHECK_D_LIGHTMAP,
	TSYSTEM_CHECK_F_LIGHTMAP,
	TSYSTEM_CHECK_FAR_IMAGE,
	TSYSTEM_CHECK_COUNT
} *LPTSYSTEM_CHECK_OPTION;

typedef enum TGAME_CHECK_OPTION
{
	TGAME_CHECK_NPC_NAME = 0,
	TGAME_CHECK_MON_NAME,
	TGAME_CHECK_CHAR_NAME,
	TGAME_CHECK_AUTO_HELP,
	TGAME_CHECK_TALK_BOX,
	TGAME_CHECK_DENY_WHISPER,
	TGAME_CHECK_DENY_COMMUNITY,
	TGAME_CHECK_HUD,
	TGAME_CHECK_CONTINUALCHAT,
	TGAME_CHECK_MOUSECLICKMOVE,
	TGAME_CHECK_COUNT
} *LPTGAME_CHECK_OPTION;

typedef enum TSOUND_OPTION
{
	TSOUND_OPTION_MASTER,
	TSOUND_OPTION_BGM,
	TSOUND_OPTION_SFX,
	TSOUND_OPTION_COUNT
} *LPTSOUND_OPTION;


typedef enum TCURSOR_TYPE
{
	TCURSOR_HAND = 0,
	TCURSOR_SWORD,
	TCURSOR_TALK,
	TCURSOR_ALLIANCE,
	TCURSOR_DEADMON,
	TCURSOR_SIZE,
	TCURSOR_COUNT
} *LPTCURSOR_TYPE;


typedef enum TTRADE_HOST_TYPE
{
	TTRADE_HOST_MAIN = 0,
	TTRADE_HOST_TARGET,
	TTRADE_HOST_COUNT
} *LPTTRADE_HOST_TYPE;


typedef enum TMONEY_TYPE
{
	TMONEY_RUNE = 0,
	TMONEY_LUNA,
	TMONEY_CRON,
	TMONEY_COUNT
} *LPTMONEY_TYPE;


typedef enum TTRADE_OPTION
{
	TTRADEOP_TRADE = 0,
	TTRADEOP_SELL,
	TTRADEOP_CABINET
} *LPTTRADE_OPTION;


typedef enum TDRAWMARK_OPTION
{
	TDRAWMARK_QUEST = 0,
	TDRAWMARK_WORLDMAP
} *LPTDRAWMARK_OPTION;


typedef enum THOTKEY_BASE
{
	THOTKEYBASE_DEF = 0,
	THOTKEYBASE_SUB1,
	THOTKEYBASE_COUNT,
} *LPTHOTKEY_BASE;

typedef enum TMAINSLOTID_TYPE
{
	TMAINSLOTID_HOTKEY_DEF,
	TMAINSLOTID_HOTKEY_SUB1,
	TMAINSLOTID_INVEN,
	TMAINSLOTID_MAX
} *LPTMAINSLOTID_TYPE;

typedef enum THOTKEY_CTRL
{
	THOTKEYCTRL_BASE = 0,
	THOTKEYCTRL_UP,
	THOTKEYCTRL_DOWN,
	THOTKEYCTRL_NUM,
	THOTKEYCTRL_COUNT
} *LPTHOTKEY_CTRL;

typedef enum TCASHMENU_TYPE
{
	TCASHMENU_ITEM,
	TCASHMENU_CAB,
	TCASHMENU_CHARGE,
	TCASHMENU_COUNT
} *LPTCASHMENU_TYPE;

typedef enum TMAINBUTTON
{
	TMAINBUTTON_CHAR,
	TMAINBUTTON_SKILL,
	TMAINBUTTON_QUEST,
	TMAINBUTTON_COMMUNITY,
	TMAINBUTTON_SYSTEM,
	TMAINBUTTON_INVEN_SLOT,
	TMAINBUTTON_PET,
	TMAINBUTTON_FAMERANK,
	TMAINBUTTON_HELP,
	TMAINBUTTON_COUNT
} *LPTMAINBUTTON;

typedef enum TMSGBUTTON
{
	TMSGBUTTON_MSG,
	TMSGBUTTON_MAIL,
	TMSGBUTTON_LOCK,
	TMSGBUTTON_COUNT
} *LPTMSGBUTTON;

typedef enum TTEXT_LINK_TYPE
{
	TTEXT_LINK_TYPE_ITEM_OLD,
	TTEXT_LINK_TYPE_QUEST,
	TTEXT_LINK_TYPE_ITEM,
	TTEXT_LINK_TYPE_COUNT
} *LPTTEXT_LINK_TYPE;

typedef enum TITEM_QUALITY
{
	TITEM_QUALITY_NORMAL	= 1,
	TITEM_QUALITY_GRADE		= 1<<1,
	TITEM_QUALITY_MAGIC		= 1<<2,
	TITEM_QUALITY_SET		= 1<<3,
	TITEM_QUALITY_RARE		= 1<<4,
	TITEM_QUALITY_UNIQUE	= 1<<5,
	TITEM_QUALITY_COUNT,
} *LPTITEM_QUALITY;

typedef enum TCOMMUNITY_FRAME
{
	TCOMMUNITY_FRAME_GUILDNORMAL,			///< 요약
	TCOMMUNITY_FRAME_GUILDMEMBER,			///< 명부
	TCOMMUNITY_FRAME_GUILDTERRITORY,		///< 영토
	TCOMMUNITY_FRAME_GUILDVOLUNTEER,		///< 지원자
	TCOMMUNITY_FRAME_COUNT
} *LPTCOMMUNITY_FRAME;

typedef enum TGUILDAPP_FRAME
{
	TGUILDAPP_FRAME_OFFER,					///< 길드원모집
	TGUILDAPP_FRAME_SEEK,					///< 지원등록
	TGUILDAPP_FRAME_COUNT,
} *LPTGUILDAPP_FRAME;

typedef enum TMESSENGER_FRAME
{
	TMESSENGER_FRAME_MESSENGER,
	TMESSENGER_FRAME_BLOCKLIST,
	TMESSENGER_FRAME_COUNT
} *LPTMESSENGER_FRAME;

typedef enum TMAIL_FRAME
{
	TMAIL_FRAME_MAILBOX,
	TMAIL_FRAME_COUNT
} *LPTMAIL_FRAME;

typedef enum TSETTING_FRAME
{
	TSETTING_FRAME_GAME,
	TSETTING_FRAME_SYSTEM,
	TSETTING_FRAME_COUNT
} *LPTSETTING_FRAME;

typedef enum TSHOP_TYPE
{
	TSHOP_TYPE_NPC_ITEM,
	TSHOP_TYPE_NPC_PORTAL,
	TSHOP_TYPE_NPC_MONSTER,
	TSHOP_TYPE_COUNT
} *LPTSHOP_TYPE;

typedef enum TNPCICON_TYPE
{
	TNPCICON_NONE = 0,
	TNPCICON_SKILL,
	TNPCICON_ITEM,
	TNPCICON_REVIVAL,
	TNPCICON_PORTAL,
	TNPCICON_ITEMUP,
	TNPCICON_AUCTION,
	TNPCICON_GUILD,
	TNPCICON_WEAPON,
	TNPCICON_ARMOR,
	TNPCICON_CASTLE,
	TNPCICON_REPAIR,
	TNPCICON_ITEMMAKE,
	TNPCICON_BANK,
	TNPCICON_CASH,
	TNPCICON_COUNT
} *LPTNPCICON_TYPE;

typedef enum TENVSND_TYPE
{
	TENVSND_LOOP = 0,
	TENVSND_RAND1,
	TENVSND_COUNT
} *LPTENVSND_TYPE;

typedef enum TLOAD_CMD
{
	TLOADCMD_NONE = 0,
	TLOADCMD_RES,
	TLOADCMD_OBJ
} *LPTLOAD_CMD;

typedef enum TWORLDMAP_LEVEL
{
	TWORLDMAP_LEVEL_NONE,
	TWORLDMAP_LEVEL_UNIT,
	TWORLDMAP_LEVEL_ALL,
	TWORLDMAP_LEVEL_COUNT
} *LPTWORLDMAP_LEVEL;

typedef enum TUISND_TYPE
{
	TUISND_TYPE_NONE,
	TUISND_TYPE_INFO,
	TUISND_TYPE_ERROR,
	TUISND_TYPE_COUNT
} *LPTUISND_TYPE;

typedef enum TGUI_POS_TYPE
{
	TGUI_POS_ABSOLUTE,
	TGUI_POS_RELATIVE,
	TGUI_POS_EXTEND,
	TGUI_POS_CENTER,
	TGUI_POS_LEFT_CENTER,
	TGUI_POS_RIGHT_CENTER,
	TGUI_POS_COUNT
} *LPTGUI_POS_TYPE;

typedef enum TGUI_XBASE
{
	TGUI_XBASE_LEFT,
	TGUI_XBASE_CENTER,
	TGUI_XBASE_RIGHT,
	TGUI_XBASE_COUNT
} *LPTGUI_XBASE;

typedef enum TGUI_YBASE
{
	TGUI_YBASE_TOP,
	TGUI_YBASE_CENTER,
	TGUI_YBASE_BOTTOM,
	TGUI_YBASE_COUNT
} *LPTGUI_YBASE;

typedef enum TGUILD_MEMBER
{
	TGM_REGULAR,					///< 정규군
	TGM_TACTICS,					///< 지원병 (용병)
	TGM_COUNT
} *LPTGUILD_MEMBER;

typedef enum TITEMMAGIC_RV
{
	TITEMMAGIC_RV_NONE,				///< 보정없음
	TITEMMAGIC_RV_AP,				///< 물리공격력
	TITEMMAGIC_RV_MAP,				///< 마법공격력
	TITEMMAGIC_RV_FM,				///< 물리성능
	TITEMMAGIC_RV_MFM,				///< 마법성능
	TITEMMAGIC_RV_SKILL,			///< 스킬지정
	TITEMMAGIC_RV_COUNT
} *LPTITEMMAGIC_RV;

typedef enum TREGIONINFO_KIND
{
	TREGIONINFO_NONE,
	TREGIONINFO_D,
	TREGIONINFO_C,
	TREGIONINFO_B,
	TREGIONINFO_BATTLE,
	TREGIONINFO_NORMAL,
	TREGIONINFO_PEACE,
	TREGIONINFO_COUNT
} *LPTREGIONINFO_KIND;

typedef enum TCHATCOL_KIND
{
	TCHATCOL_NAME = 0,
	TCHATCOL_MSG = 1,
	TCHATCOL_INFO = 2
} *LPTCHATCOL_KIND;

typedef enum TMSGBOXOPEN_TYPE
{
	TMSGBOXOPEN_NONE,					// 기존에 떠 있는 메시지 박스가 있으면 아무것도 하지 않는다.
	TMSGBOXOPEN_CLOSEALL_ALREADY,		// 기존에 떠 있는 메시지 박스가 있으면 모두 닫는다.
	TMSGBOXOPEN_OVERLAP					// 기존에 떠 있는 메시지 박스 위에 덮어서 출력한다. 닫으면 예전께 복원 된다.
} *LPTMSGBOXOPEN_TYPE;

typedef enum TCHARGETYPE
{
	TCHARGETYPE_UNKNOWN=0,
	TCHARGETYPE_SKILL=1,
	TCHARGETYPE_OPEN,
} *LPTCHARGETYPE;

typedef enum TQUAKE_TYPE
{
	TQUAKE_NONE = 0,
	TQUAKE_DEFEND,
	TQUAKE_ATTACK,
	TQUAKE_COUNT
} *LPTQUAKE_TYPE;

typedef enum TCASTLE_TYPE
{
	TCASTLE_HESED = 4,
	TCASTLE_ARDRI = 8,
	TCASTLE_GEHBRA = 12,
	TCASTLE_TYCON = 16,
	TCASTLE_COUNT = 4
} *LPTCASTLE_TYPE;

typedef enum TAUCTION_FRAME_TYPE
{
	TAUCTION_SEARCH,
	TAUCTION_REGIST,
	TAUCTION_BID,
	TAUCTION_BASKET,
	TAUCTION_FRAME_COUNT
} *LPTAUCTION_FRAME_TYPE;

typedef enum TTMODE
{
	TT_ENTRY=0,
	TT_JOIN=1,
	TT_MATCH=2
} *LPTTMODE;

typedef enum TTGATE_LOGIC
{
	TTGATE_LOGIC_NONE = 0,
	TTGATE_LOGIC_ENTER,
	TTGATE_LOGIC_END,
	TTGATE_LOGIC_COUNT
} *LPTTGATE_LOGIC;

typedef enum TSCENE_PLAYER_CODE
{
	TSCENE_PLAYER_CODE_NONE=0,
	TSCENE_PLAYER_CODE_DRAW_COLOR,
	TSCENE_PLAYER_CODE_DRAW_TEXTURE,
	TSCENE_PLAYER_CODE_FADE_IN_TEXTURE,
	TSCENE_PLAYER_CODE_FADE_OUT_TEXTURE,
	TSCENE_PLAYER_CODE_FADE_TEXTURE,
	TSCENE_PLAYER_CODE_SHOW_UI,
	TSCENE_PLAYER_CODE_HIDE_UI,
	TSCENE_PLAYER_CODE_SHOW_DIALOG,
	TSCENE_PLAYER_CODE_SHOW_TEXT,
	TSCENE_PLAYER_CODE_START_CAMERA,
	TSCENE_PLAYER_CODE_CALC_CAMERA,
	TSCENE_PLAYER_CODE_DRAW_COLOR_FADEIN,
	TSCENE_PLAYER_CODE_TELEPORT,
	TSCENE_PLAYER_CODE_PAUSE_TICK,
	TSCENE_PLAYER_CODE_RESUME_TICK,
	TSCENE_PLAYER_CODE_SHOW_SKIP,
	TSCENE_PLAYER_CODE_HIDE_SKIP,
	TSCENE_PLAYER_CODE_WAIT,
	TSCENE_PLAYER_CODE_COUNT
} *LPTSCENE_PLAYER_CODE;

typedef enum TSCENE_SCRIPT
{
	TSCENE_SCRIPT_LEAVE_TUTORIAL=0,
	TSCENE_SCRIPT_ENTER_WORLD,
	TSCENE_SCRIPT_SKIP,
	TSCENE_SCRIPT_COUNT
} *LPTSCENE_SCRIPT;


///////////////////////////////////////////////////////////////////////////
// TClient structure type

typedef struct tagTLATESTPVPINFO		TLATESTPVPINFO, *LPTLATESTPVPINFO;
typedef struct tagTSTATINFO				TSTATINFO, *LPTSTATINFO;

typedef struct tagTLOADCMD				TLOADCMD, *LPTLOADCMD;
typedef struct tagTLOADOBJ				TLOADOBJ, *LPTLOADOBJ;
typedef struct tagTBSPINFO				TBSPINFO, *LPTBSPINFO;

typedef struct tagTCHARINFO				TCHARINFO, *LPTCHARINFO;
typedef struct tagTGROUP				TGROUP, *LPTGROUP;

typedef struct tagTSIEGETOWER			TSIEGETOWER, *LPTSIEGETOWER;

typedef struct tagTCORPS				TCORPS, *LPTCORPS;
typedef struct tagTSQUAD				TSQUAD, *LPTSQUAD;
typedef struct tagTENEMY				TENEMY, *LPTENEMY;
typedef struct tagTUNIT					TUNIT, *LPTUNIT;

typedef struct tagTHIDEPART				THIDEPART, *LPTHIDEPART;
typedef struct tagTHOTKEY				THOTKEY, *LPTHOTKEY;
typedef struct tagTPARTY				TPARTY, *LPTPARTY;

typedef struct tagTMAGIC				TMAGIC, *LPTMAGIC;
typedef struct tagTDRAG					TDRAG, *LPTDRAG;

typedef struct tagTOBJBLOCK				TOBJBLOCK, *LPTOBJBLOCK;
typedef struct tagTSFXBLOCK				TSFXBLOCK, *LPTSFXBLOCK;
typedef struct tagTSNDBLOCK				TSNDBLOCK, *LPTSNDBLOCK;

typedef struct tagTSKILLTARGET			TSKILLTARGET, *LPTSKILLTARGET;
typedef struct tagTSKILLDATA			TSKILLDATA, *LPTSKILLDATA;

typedef struct tagTCHATINFO				TCHATINFO, *LPTCHATINFO;
typedef struct tagTITEM_SLOT			TITEM_SLOT, *LPTITEM_SLOT;
typedef struct tagTDROPINFO				TDROPINFO, *LPTDROPINFO;

typedef struct tagTOPTION				TOPTION, *LPTOPTION;

typedef struct tagPRVSHOP_ITEM			PRVSHOP_ITEM, *LPPRVSHOP_ITEM;
typedef struct tagMSGCHAT_TARGET		MSGCHAT_TARGET, *LPMSGCHAT_TARGET;

typedef struct tagTMAIL_SIMPLE			TMAIL_SIMPLE, *LPTMAIL_SIMPLE;
typedef struct tagTMAIL					TMAIL, *LPTMAIL;

typedef struct tagTTEXT_LINK_LINE		TTEXT_LINK_LINE, *LPTTEXT_LINK_LINE;
typedef struct tagTLINK_LINE_SETTING	TLINK_LINE_SETTING, *LPTLINK_LINE_SETTING;

typedef struct tagTCHANNEL_INFO			TCHANNEL_INFO, *LPTCHANNEL_INFO;
typedef struct tagBUTTON_STATE			BUTTON_STATE, *LPBUTTON_STATE;
typedef struct tagTINVENITEM			TINVENITEM, *LPTINVENITEM;
typedef struct tagTRUNAWAY				TRUNAWAY, *LPTRUNAWAY;
typedef struct tagTSKILLTARGET_PARAM	TSKILLTARGET_PARAM, *LPTSKILLTARGET_PARAM;

typedef struct tagTMESSAGEBOX			TMESSAGEBOX, *LPTMESSAGEBOX;
typedef struct tagTCAMPOINT				TCAMPOINT, *LPTCAMPOINT;

typedef struct tagTSCRCAPTURE_PARAM		TSCRCAPTURE_PARAM, *LPTSCRCAPTURE_PARAM;
typedef struct tagTRESOLUTIONMODE		TRESOLUTIONMODE, *LPTRESOLUTIONMODE;
typedef struct tagTFRAMEOFFSET			TFRAMEOFFSET, *LPTFRAMEOFFSET;
typedef struct tagTOPENBYCASH			TOPENBYCASH, *LPTOPENBYCASH;
typedef struct tagMONMOVE				TMONMOVE, *LPTMONMOVE;

typedef struct tagTWEAPONEQUIPINFO		TWEAPONEQUIPINFO, *LPTWEAPONEQUIPINFO;

typedef struct tagTAUCTIONFINDINFO		TAUCTIONFINDINFO, *LPTAUCTIONFINDINFO;
typedef struct tagTAUCTIONREGINFO		TAUCTIONREGINFO, *LPTAUCTIONREGINFO;
typedef struct tagTAUCTIONTREE			TAUCTIONTREE, *LPTAUCTIONTREE;

typedef struct tagTTOURNAMENTSCHEDULE	TTOURNAMENTSCHEDULE, *LPTTOURNAMENTSCHEDULE;
typedef struct tagTTOURNAMENTPLAYER		TTOURNAMENTPLAYER, *LPTTOURNAMENTPLAYER;
typedef struct tagTTOURNAMENTTEAM		TTOURNAMENTTEAM, *LPTTOURNAMENTTEAM;

typedef struct tagTTEVENTTARGETPARTY	TTEVENTTARGETPARTY, *LPTTEVENTTARGETPARTY;
typedef struct tagTTEVENTTARGET			TTEVENTTARGET, *LPTTEVENTTARGET;
typedef struct tagTTEVENTMATCH			TTEVENTMATCH, *LPTTEVENTMATCH;

typedef struct tagTMATCHREWARD			TMATCHREWARD, *LPTMATCHREWARD;
typedef struct tagTMATCHPLAYER			TMATCHPLAYER, *LPTMATCHPLAYER;
typedef struct tagTMATCHPARTY			TMATCHPARTY, *LPTMATCHPARTY;
typedef struct tagTMATCH				TMATCH, *LPTMATCH;


///////////////////////////////////////////////////////////////////////////
// TClient key structure

struct TOBJTEXCOLORKEY
{
	LPOBJTEX m_pTEX;
	DWORD m_dwCOLOR;
	LPTEXTURESET m_pSkinTEX;
	BYTE m_bPSTYPE;

	bool operator < (const TOBJTEXCOLORKEY& l) const
	{
		if( m_pTEX == l.m_pTEX )
		{
			if( m_dwCOLOR == l.m_dwCOLOR )
			{
				if( m_pSkinTEX == l.m_pSkinTEX )
					return m_bPSTYPE < l.m_bPSTYPE;

				return m_pSkinTEX < l.m_pSkinTEX;
			}

			return m_dwCOLOR < l.m_dwCOLOR;
		}
		else
			return m_pTEX < l.m_pTEX;
	}
};

struct TMAGICOPTION
{
	CString	m_strOption;
	WORD	m_wValue;
};

typedef CString (*FP_CHATCMDPROC)(const CString& strMSG, const VECTORSTRING& vPARAM, DWORD dwUSER);

struct ChatCmdData
{
	FP_CHATCMDPROC	pfProc;
	DWORD			dwUser;
};

struct TOP3
{
	CString m_strName;
	WORD m_wPoint;
	TOP3( CString strName, WORD wPoint)
		: m_strName(strName), m_wPoint(wPoint) {}
};

///////////////////////////////////////////////////////////////////////////
// TClient class type

class CTClientMaintain;
class CTClientWebCtrl;
class CTClientSession;
class CTClientObjBase;
class CTClientMoveObj;
class CTClientMonster;
class CTClientRecall;
class CTClientNumber;
class CTClientObject;
class CTClientQClass;
class CTClientUIBase;
class CTClientSwitch;
class CTClientArrow;
class CTClientSkill;
class CTClientQuest;
class CTClientInven;
class CTClientFlag;
class CTClientTerm;
class CTClientItem;
class CTClientChar;
class CTClientGate;
class CTClientNpc;
class CTClientBSP;
class CTClientSFX;
class CTClientMAP;
class CTClientKEY;
class CTClientCAM;
class CTRSCSDlg;
class CTChatFrame;
class CTNotifyFrame;
class CTChatList;
class CTChatTabButton;
class CTClientGame;
class CTClientWnd;
class CTMiniPopupDlg;
class CTItemSlotBaseDlg;
class CTItemUpDlg;
class CTItemRepairDlg;
class CTItemRefineDlg;
class CTItemUpGaugeDlg;
class CTCommunityDlg;
class CTGuildRTTypeFrame;
class CTGuildNormalFrame;
class CTGuildMemberFrame;
class CTGuildTerritoryFrame;
class CTGuildVolunteerFrame;
class CTGuildCommander;
class CTPrivateShopDlg;
class CTMessengerBase;
class CTMsgGroupList;
class CTSoulmateFrame;
class CTMsgChatMemberList;
class CTMessengerChat;
class CTMessengerChatFrame;
class CTMailListFrame;
class CTClientApp;
class CPacketSpyDlg;
class CTGodBall;
class CTGodTower;
class CTSiegeManager;
class CTDurationFrame;
class CTCashShopCategory;
class CTCraftCategory;
class CTFameRank;
class CTScenePlayer;
class CTSpCode;


///////////////////////////////////////////////////////////////////////////
// TClient map type

typedef map< BYTE, SOCKADDR_IN >						MAPTPENDINGMAPSESSION, *LPMAPTPENDINGMAPSESSION;
typedef map< CTClientObjBase *, CTClientObjBase *>		MAPTSELECTOBJ, *LPMAPTSELECTOBJ;

typedef map< DWORD, CTClientMonster *>					MAPMONSTER, *LPMAPMONSTER;
typedef map< DWORD, CTClientRecall *>					MAPRECALL, *LPMAPRECALL;
typedef map< DWORD, CTClientChar *>						MAPPLAYER, *LPMAPPLAYER;
typedef map< DWORD, CTClientBSP *>						MAPTBSP, *LPMAPTBSP;

typedef map< DWORD, CTClientQClass *>					MAPTQCLASS, *LPMAPTQCLASS;
typedef map< DWORD, CTClientQuest *>					MAPTQUEST, *LPMAPTQUEST;
typedef map< DWORD, CTClientFlag *>						MAPTPATHFLAG, *LPMAPTPATHFLAG;

typedef map< DWORD, CTClientSwitch *>					MAPTSWITCH, *LPMAPTSWITCH;
typedef map< DWORD, CTClientGate *>						MAPTGATE, *LPMAPTGATE;

typedef map< WORD, CTClientMaintain *>					MAPTMAINTAIN, *LPMAPTMAINTAIN;
typedef map< WORD, CTClientSkill *>						MAPTSKILL, *LPMAPTSKILL;
typedef map< BYTE, CTClientInven *>						MAPTINVEN, *LPMAPTINVEN;
typedef map< BYTE, CTClientItem *>						MAPTITEM, *LPMAPTITEM;
typedef map< WORD, CTClientItem *>						MAPTQUESTCLNTITEM, *LPMAPTQUESTCLNTITEM;

typedef map< DWORD, LPTENEMY>							MAPTENEMY, *LPMAPTENEMY;
typedef map< WORD, LPTSKILL>							MAPTSKILLTEMP, *LPMAPTSKILLTEMP;
typedef map< BYTE, LPTMAGIC>							MAPTMAGIC, *LPMAPTMAGIC;
typedef map< BYTE, LPTGROUP>							MAPTGROUP, *LPMAPTGROUP;

typedef map< CTachyonObject*, LPVECTOROBJSFX>			MAPTOBJSFXS, *LPMAPTOBJSFXS;
typedef map< DWORD, CTachyonBSPMAP *>					MAPTBSPMAP, *LPMAPTBSPMAP;

typedef map< WORD, CTGodBall *>							MAPSIEGEGODBALL, *LPMAPSIEGEGODBALL;
typedef map< WORD, CTGodTower *>						MAPSIEGEGODTOWER, *LPMAPSIEGEGODTOWER;

typedef map< DWORD, LPVECTORDWORD>						MAPTHEIGHTINFO, *LPMAPTHEIGHTINFO;

typedef map< TOBJTEXCOLORKEY, LPOBJTEX>					MAPTOBJTEXCOLORPAIR, *LPMAPTOBJTEXCOLORPAIR;
typedef map< DWORD, CTCashShopCategory *>				MAPTCASHSHOPCATEGORY, *LPMAPTCASHSHOPCATEGORY;
typedef map< DWORD, CTCraftCategory *>					MAPTCRAFTCATEGORY, *LPMAPTCRAFTCATEGORY;

typedef map< DWORD, CTMessengerChat *>					TMAPMSGTOCHAT;
typedef map< CString, ChatCmdData>						TMAPCHATCMD;
typedef map< DWORD, TWEAPONEQUIPINFO>					TMAPWEAPONEQUIPINFO, *LPTMAPWEAPONEQUIPINFO;
typedef map< DWORD, CString>							TMAPPACKET, *LPTMAPPACKET;

typedef map< DWORD, CTFameRank *>						TMAPFAMERANK, *LPTMAPFAMERANK;

///////////////////////////////////////////////////////////////////////////
// TClient vector type

typedef vector<CTClientMaintain *>						VTMAINTAIN, *LPVTMAINTAIN;
typedef vector<CTClientObjBase *>						VTOBJBASE, *LPVTOBJBASE;
typedef vector<CTClientNumber *>						VTNUMBER, *LPVTNUMBER;
typedef vector<CTClientArrow *>							VTARROW, *LPVTARROW;
typedef vector<CTClientTerm *>							VTTERM, *LPVTTERM;
typedef vector<CTClientFlag *>							VTPATHFLAG, *LPVTPATHFLAG;
typedef vector<CTClientBSP *>							VTBSP, *LPVTBSP;
typedef vector<CD3DLight *>								VTLIGHT, *LPVTLIGHT;

typedef vector<CTClientMonster *>						VTMONSTER, *LPVTMONSTER;
typedef vector<CTClientRecall *>						VTRECALL, *LPVTRECALL;

typedef vector<LPTCHARINFO>								VTCHARINFO, *LPVTCHARINFO;
typedef vector<LPTPARTY>								VTPARTY, *LPVTPARTY;

typedef vector<LPTSQUAD>								VTSQUAD, *LPVTSQUAD;
typedef vector<LPTUNIT>									VTUNIT, *LPVTUNIT;

typedef vector<LPTQUEST>								VTQUESTTEMP, *LPVTQUESTTEMP;


typedef vector<LPTSKILLTARGET>							VTSKILLTARGET, *LPVTSKILLTARGET;

typedef vector<LPTBSPINFO>								VTBSPINFO, *LPVTBSPINFO;
typedef vector<LPMAPOBJ>								VTMAPOBJ, *LPVTMAPOBJ;
typedef vector<LPMAPSFX>								VTMAPSFX, *LPVTMAPSFX;
typedef vector<LPMAPSND>								VTMAPSND, *LPVTMAPSND;
typedef vector<LPSNDIDX>								VTSNDIDX, *LPVTSNDIDX;
typedef vector<LPTNPC>									VTNPC, *LPVTNPC;

typedef vector<MSGCHAT_TARGET>							MCTARGET_ARRAY, *LPMCTARGET_ARRAY;

typedef vector<TMAIL_SIMPLE *>							TMAIL_SIMPLE_ARRAY, *LPTMAIL_SIMPLE_ARRAY;
typedef vector<TMAIL *>									TMAIL_ARRAY, *LPTMAIL_ARRAY;

typedef vector<TPET>									TPET_ARRAY, *LPTPET_ARRAY;
typedef vector<TTEXT_LINK_LINE>							TTLINKLINE_ARRAY, *LPTTLINKLINE_ARRAY;
typedef vector<TLINK_LINE_SETTING>						TLLINESETTING_ARRAY, *LPTLLINESETTING_ARRAY;
typedef vector<TLLINESETTING_ARRAY>						TLLINESETTING_ARRAY2D, *LPTLLINESETTING_ARRAY2D;

typedef vector<LPTGROUP>								TGROUPARRAY, *LPTGROUPARRAY;
typedef vector<TCHANNEL_INFO>							TCHANNEL_ARRAY, *LPTCHANNEL_ARRAY;
typedef vector<TINVENITEM>								TINVENITEM_ARRAY, *LPTINVENITEM_ARRAY;
typedef vector<TRUNAWAY>								TRUNAWAY_ARRAY, *LPTRUNAWAY_ARRAY;

typedef vector<LPTMONMOVE>								VTMONMOVE, *LPVTMONMOVE;
typedef vector<TFRAMEOFFSET>							VTFRAMEOFFSET, *LPVTFRAMEOFFSET;
typedef vector<TRESOLUTIONMODE>							VTRESOLUTIONMODE, *LPVTRESOLUTIONMODE;

typedef vector<CString>									VTSTRING, *LPTSTRING;
typedef vector<BYTE>									VTBYTE, *LPTBYTE;
typedef vector<DWORD>									VTDWORD, *LPVTDWORD;

typedef vector<TMAGICOPTION>							VTMAGICOPTION, *LPVTMAGICOPTION;
typedef vector<CTCashShopCategory *>					VTCASHSHOPCATEGORY, *LPVTCASHSHOPCATEGORY;
typedef vector<CTCraftCategory *>						VTCRAFTCATEGORY, *LPVTCRAFTCATEGORY;

typedef vector<CTMessengerChat*>						VTMSGCHATARRAY;
typedef vector<LPTLATESTPVPINFO>						VTLATESTPVPINFO;
typedef vector<LPTAUCTIONTREE>							VTAUCTIONTREE;

typedef vector<CTFameRank *>							VTFAMERANK, *LPVTFAMERANK;
typedef vector<CTSpCode *>								VTSPCODE, *LPVTSPCODE;

typedef vector<LPTTOURNAMENTPLAYER>						VTTOURNAMENTPLAYER, *LPVTTOURNAMENTPLAYER;
typedef vector<LPTTOURNAMENTTEAM>						VTTOURNAMENTTEAM, *LPVTTOURNAMENTTEAM;
typedef vector<LPTTOURNAMENTSCHEDULE>					VTTOURNAMENTSCHEDULE, *LPVTTOURNAMENTSCHEDULE;
typedef vector<LPTMATCHREWARD>							VTMATCHREWARD;
typedef vector<LPTMATCHPLAYER>							VTMATCHPLAYER;
typedef vector<LPTMATCHPARTY>							VTMATCHPARTY;
typedef vector<LPTMATCH>								VTMATCH;
typedef vector<LPTTEVENTMATCH>							VTTEVENTMATCH;
typedef vector<LPTTEVENTTARGET>							VTTEVENTTARGET;
typedef vector<LPTTEVENTTARGETPARTY>					VTTEVENTTARGETPARTY;
typedef std::vector<TOP3>								VTOP3;

///////////////////////////////////////////////////////////////////////////
// TClient list type

typedef list<CTClientObjBase *>							LISTTOBJBASE, *LPLISTTOBJBASE;
typedef list<CTClientQClass *>							LISTTQCLASS, *LPLISTTQCLASS;
typedef list<CTClientQuest *>							LISTTQUEST, *LPLISTTQUEST;
typedef list<CTClientMaintain *>						LISTTMAINTAIN, *LPLISTTMAINTAIN;

typedef list<LPTQUEST>									LISTTQUESTTEMP, *LPLISTTQUESTTEMP;


///////////////////////////////////////////////////////////////////////////
// TClient list type

typedef queue<LPTLOADCMD>								QTLOADCMD, *LPQTLOADCMD;
typedef deque<CString>									STRINGQUEUE, *LPSTRINGQUEUE;

///////////////////////////////////////////////////////////////////////////
// TClient stack type

typedef stack<TMESSAGEBOX>								TMESSAGEBOX_STACK, *LPTMESSAGEBOX_STACK;

///////////////////////////////////////////////////////////////////////////
// TClient structure define

struct tagTBSPINFO
{
	D3DXVECTOR3 m_vSCALE;
	D3DXVECTOR3 m_vROT;
	D3DXVECTOR3 m_vPOS;

	DWORD m_dwHouseID;
	DWORD m_dwBspID;
	BYTE m_bINDEX;

	FLOAT m_fRadius;
};

struct tagTLOADCMD
{
	LPVOID m_pTBUF;
	DWORD m_dwTCMD;
};

struct tagTLOADOBJ
{
	VECTORDWORD m_vUnitID;
	VTBSPINFO m_vTBSPINFO;

	tagTLOADOBJ()
	{
		m_vTBSPINFO.clear();
		m_vUnitID.clear();
	};

	~tagTLOADOBJ()
	{
		while(!m_vTBSPINFO.empty())
		{
			delete m_vTBSPINFO.back();
			m_vTBSPINFO.pop_back();
		}

		m_vUnitID.clear();
	};
};

struct tagTGROUP
{
	CString m_strNAME;

	BYTE m_bNumber;
	BYTE m_bGroupID;
	BYTE m_bType;
	BYTE m_bStatus;
	BYTE m_bCharCnt;

	DWORD m_dwRandomPriority;

	tagTGROUP() :m_dwRandomPriority(0) {}
};

struct tagTOBJBLOCK
{
	VTOBJBASE m_vTOBJ;
	WORD m_wCount;

	tagTOBJBLOCK()
	{
		m_vTOBJ.clear();
		m_wCount = 0;
	};
};

struct tagTSFXBLOCK
{
	VECTORTSFX m_vTSFX;
	WORD m_wCount;

	tagTSFXBLOCK()
	{
		m_vTSFX.clear();
		m_wCount = 0;
	};
};

struct tagTSNDBLOCK
{
	VTSNDIDX m_vTSND;
	WORD m_wCount;

	tagTSNDBLOCK()
	{
		m_vTSND.clear();
		m_wCount = 0;
	};
};

struct tagTSIEGETOWER
{
	DWORD 	m_dwID;

	LPTITEM m_pTITEM[ES_COUNT];

	FLOAT 	m_fScaleX;
	FLOAT 	m_fScaleY;
	FLOAT 	m_fScaleZ;

	FLOAT 	m_fPosX;
	FLOAT 	m_fPosY;
	FLOAT 	m_fPosZ;
	FLOAT 	m_fDIR;

	DWORD	m_dwOBJ;

	tagTSIEGETOWER()
	:	m_dwID(0)
	{}
};

struct tagTHIDEPART
{
	BYTE m_bHideSlotID;
	BYTE m_bHidePartID;
	BYTE m_bHideRaceID;
};

struct tagTMAGIC
{
	SHORT m_wValue;
};

struct tagTDRAG
{
	TImageList *m_pIMAGE;

	BYTE m_bFrameID;
	BYTE m_bSlotID;
	DWORD m_dwParam;
};

struct tagTDROPINFO
{
	BYTE m_bTargetID;
	BYTE m_bSlotID;
	BYTE m_bDrop;

	tagTDROPINFO()
	{
		m_bTargetID = TFRAME_COUNT;
		m_bSlotID = 0;

		m_bDrop = FALSE;
	};
};

struct tagTPARTY
{
	CString m_strGUILD;
	CString m_strNAME;

	DWORD m_dwCharID;

	DWORD m_dwMaxHP;
	DWORD m_dwHP;
	DWORD m_dwMaxMP;
	DWORD m_dwMP;

	BYTE m_bRaceID;
	BYTE m_bSexID;
	BYTE m_bLevel;

	BYTE m_bFaceID;
	BYTE m_bHairID;
	BYTE m_bClass;
};

struct tagTHOTKEY
{
	BYTE m_bType;
	WORD m_wID;
};

struct tagTSKILLTARGET
{
	DWORD m_dwID;
	BYTE m_bType;

	tagTSKILLTARGET()
	{
		m_bType = OT_NONE;
		m_dwID = 0;
	};
};

struct tagTSKILLDATA
{
	D3DXVECTOR3 m_vTGROUND;

	WORD m_wID;		
	WORD m_wAL;
	WORD m_wSTR;
	WORD m_wINT;

	DWORD m_dwMinAP;
	DWORD m_dwMinMP;

	DWORD m_dwMaxAP;
	DWORD m_dwMaxMP;

	BYTE m_bAtkCountryID;
	BYTE m_bAtkLevel;
	BYTE m_bLevel;
	BYTE m_bHIT;
	BYTE m_bSpecial;
	BYTE m_bAglow;
	BYTE m_bCURSE;

	tagTSKILLDATA()
	{
		m_vTGROUND = D3DXVECTOR3( 0.0f, 0.0f, 0.0f);

		m_wID = 0;
		m_wAL = 0;
		m_wSTR = 0;
		m_wINT = 0;

		m_dwMinAP = 0;
		m_dwMinMP = 0;

		m_dwMaxAP = 0;
		m_dwMaxMP = 0;

		m_bAtkCountryID = TCONTRY_N;
		m_bSpecial = FALSE;

		m_bAtkLevel = 0;
		m_bLevel = 0;
		m_bHIT = 0;
		m_bAglow = 0;
		m_bCURSE = 0;
	};
};

struct tagTITEM_SLOT
{
	BYTE		bInven;
	BYTE		bInvenSlot;
	LPTITEM		pItem;
};

struct tagTCHATINFO
{
	TTEXT_LINK_TYPE m_Type;
	LPTQUEST		m_pQuest;
	LPTITEM			m_pItem;
	CTClientItem*	m_pClientItem;

	tagTCHATINFO()
	{
		m_Type = TTEXT_LINK_TYPE_COUNT;
		m_pQuest = NULL;
		m_pItem = NULL;
		m_pClientItem = NULL;
	}
};

struct tagTOPTION
{
	BYTE m_bMapDETAIL;
	BYTE m_bObjDETAIL;

	BYTE m_bMapSHADOW;
	BYTE m_bObjSHADOW;
	BYTE m_bMapSFX;

	BYTE m_bNpcNAME;
	BYTE m_bMonNAME;
	BYTE m_bPcNAME;

	BYTE m_bDungeonLIGHTMAP;
	BYTE m_bFieldLIGHTMAP;
	BYTE m_bFarIMAGE;
	BYTE m_bHUD;

	BYTE m_bDenyCommunity;
	BYTE m_bDenyWhisper;
	BYTE m_bAutoHelp;
	BYTE m_bTalkBox;
	BYTE m_bContinualChat;
	BYTE m_bMouseClickMove;
	BYTE m_bAutoTargeting;
	BYTE m_bShowCaution15;

	FLOAT m_fOBJRange;

	tagTOPTION( BYTE bMapDETAIL,
				BYTE bObjDETAIL,
				BYTE bMapSHADOW,
				BYTE bObjSHADOW,
				BYTE bMapSFX,
				BYTE bNpcNAME,
				BYTE bMonNAME,
				BYTE bPcNAME,
				BYTE bDungeonLIGHTMAP,
				BYTE bFieldLIGHTMAP,
				BYTE bFarIMAGE,
				BYTE bHUD,
				BYTE bAutoHelp,
				BYTE bTalkBox,
				BYTE bDenyWhisper,
				BYTE bDenyCommunity,
				BYTE bContinualChat,
				BYTE bMouseClickMove,
				FLOAT fOBJRange,
				BYTE bShowCaution15,
				BYTE bAutoTargeting )
	{
		m_bMapDETAIL = bMapDETAIL;
		m_bObjDETAIL = bObjDETAIL;
		m_fOBJRange = fOBJRange;

		m_bDungeonLIGHTMAP = bDungeonLIGHTMAP;
		m_bFieldLIGHTMAP = bFieldLIGHTMAP;
		m_bDenyCommunity = bDenyCommunity;
		m_bDenyWhisper = bDenyWhisper;
		m_bMapSHADOW = bMapSHADOW;
		m_bObjSHADOW = bObjSHADOW;
		m_bFarIMAGE = bFarIMAGE;
		m_bAutoHelp = bAutoHelp;
		m_bTalkBox = bTalkBox;
		m_bNpcNAME = bNpcNAME;
		m_bMonNAME = bMonNAME;
		m_bPcNAME = bPcNAME;
		m_bMapSFX = bMapSFX;
		m_bHUD = bHUD;
		m_bContinualChat = bContinualChat;
		m_bMouseClickMove = bMouseClickMove;
		m_bShowCaution15 = bShowCaution15;
		m_bAutoTargeting = bAutoTargeting;
	};

	tagTOPTION()
	{
		m_bMapDETAIL = TDETAIL_HI;
		m_bObjDETAIL = TDETAIL_HI;

		m_bDenyCommunity = FALSE;
		m_bDenyWhisper = FALSE;
		m_fOBJRange = 1.0f;

		m_bDungeonLIGHTMAP = TRUE;
		m_bFieldLIGHTMAP = TRUE;
		m_bMapSHADOW = TRUE;
		m_bObjSHADOW = TRUE;
		m_bFarIMAGE = TRUE;
		m_bAutoHelp = TRUE;
		m_bTalkBox = TRUE;
		m_bNpcNAME = TRUE;
		m_bMonNAME = TRUE;
		m_bPcNAME = TRUE;
		m_bMapSFX = TRUE;
		m_bHUD = TRUE;
		m_bContinualChat = TRUE;
		m_bMouseClickMove = TRUE;
		m_bShowCaution15 = TRUE;
		m_bAutoTargeting = TRUE;
	};
};

struct tagPRVSHOP_ITEM
{
	BYTE	bItem;
	DWORD 	dwRune;
	DWORD 	dwLuna;
	DWORD 	dwCron;
	BYTE 	bInvenID;
	BYTE 	bItemID;
	BYTE 	bItemCount;
};

struct tagMSGCHAT_TARGET
{
	DWORD	dwCharID;
	CString	strName;
	BYTE	bClass;
	BYTE	bLevel;

	tagMSGCHAT_TARGET() 
		: dwCharID(0), bClass(0), bLevel(0)
	{}
};

struct tagTMAIL_SIMPLE
{
	DWORD			m_dwPostID;
	BYTE 			m_bRead;
	BYTE 			m_bType;
	CString 		m_strSender;
	CString 		m_strTitle;
	__int64 		m_nTime;
};

struct tagTMAIL
{
	DWORD			m_dwPostID;
	BYTE			m_bRead;
	CString			m_strMessage;
	DWORD			m_dwRune;
	DWORD			m_dwLuna;
	DWORD			m_dwCron;
	
	CTClientItem*	m_vItems[TMAIL_ITEM_MAX];
};

struct tagTTEXT_LINK_LINE
{
	INT				nTrimCnt;
	INT				nStart;
	INT				nEnd;
	CString			strMSG;

	tagTTEXT_LINK_LINE(INT s, INT e, INT tcnt, const CString& msg)
		: nStart(s), nEnd(e), nTrimCnt(tcnt), strMSG(msg)
	{}
};

struct tagTLINK_LINE_SETTING
{
	INT				nStart;
	INT				nEnd;
	DWORD			dwColor;
	DWORD			dwInfo;

	tagTLINK_LINE_SETTING(INT s, INT e, DWORD c, DWORD i)
		: nStart(s), nEnd(e), dwColor(c), dwInfo(i)
	{}
};

struct tagTCHANNEL_INFO
{
	BYTE			bNUMBER;
	BYTE			bID;
	BYTE			bSTATUS;
	CString			strNAME;

	tagTCHANNEL_INFO()
		: bSTATUS(TSTATUS_NORMAL)
	{}
};

struct tagBUTTON_STATE
{
	BYTE	m_bShow;
	BYTE	m_bEnable;
	DWORD 	m_dwBtnGM;
	DWORD 	m_dwBtnTitle;
};

struct tagTINVENITEM
{
	BYTE	m_bInven;
	BYTE	m_bItem;
};

struct tagTRUNAWAY
{
	CPoint	m_ptScreen;
	DWORD	m_dwTime;
};

struct tagTSKILLTARGET_PARAM
{
	BOOL m_bRANGE;
	BOOL m_bPOINT;
	VTOBJBASE m_vTBOUND;
	VTOBJBASE m_vTARGET;
};

struct binary_quest : public binary_function< LPTQUEST, LPTQUEST, bool>
{
	bool operator () ( const LPTQUEST &_Left, const LPTQUEST &_Right) const
	{
		if( _Left->m_bMAIN )
			return false;

		if( _Left->m_bLevel < _Right->m_bLevel )
			return true;

		return false;
	};
};

struct tagTMESSAGEBOX
{
	CString strMSG;
	CString strEditTitle;
	CString strEditText;
	DWORD dwYesTextID;
	DWORD dwNoTextID;
	DWORD dwFrameID;
	TCOMMAND vYesID;
	TCOMMAND vNoID;
	TCOMMAND vIgnoreID; // 창을 강제 종료 당할 경우 실행한 메뉴
	BYTE bEdit;
	BYTE bModal;
	CString strTitle;
	DWORD dwImageIndex;
	CString strImageTitle;
	DWORD dwSound;
	BYTE bSoundType;

	tagTMESSAGEBOX()
	{
		strMSG = "";
		strEditTitle = "";
		strEditText = "";
		dwYesTextID = 0;
		dwNoTextID = 0;
		dwFrameID = 0;
		vYesID = (DWORD) 0;
		vNoID = (DWORD) 0;
		vIgnoreID = (DWORD) 0;
		bEdit = 0;
		bModal = 0;
		strTitle = "";
		dwImageIndex = 0;
		strImageTitle = "";
		dwSound = ID_SND_INFO;
		bSoundType = MEDIA_TSOUND;
	}

	~tagTMESSAGEBOX()
	{}
};

struct tagTCAMPOINT
{
	INT		m_nDirS;
	INT		m_nDirE;

	INT		m_nPitchS;
	INT		m_nPitchE;

	FLOAT	m_fDistS;
	FLOAT	m_fDistE;
};

struct tagMONMOVE
{
	CTClientObjBase *m_pTMON;

	BYTE m_bChannel;
	WORD m_wMapID;

	FLOAT m_fPosX;
	FLOAT m_fPosY;
	FLOAT m_fPosZ;

	WORD m_wPITCH;
	WORD m_wDIR;

	BYTE m_bMouseDIR;
	BYTE m_bKeyDIR;
	BYTE m_bAction;

	tagMONMOVE()
	{
		m_pTMON = NULL;

		m_bChannel = 0;
		m_wMapID = 0;

		m_fPosX = 0.0f;
		m_fPosY = 0.0f;
		m_fPosZ = 0.0f;

		m_wPITCH = 0;
		m_wDIR = 0;

		m_bMouseDIR = 0;
		m_bKeyDIR = 0;
		m_bAction = TA_STAND;
	};

	tagMONMOVE(
		CTClientObjBase *pTMON,
		BYTE bChannel,
		WORD wMapID,
		FLOAT fPosX,
		FLOAT fPosY,
		FLOAT fPosZ,
		WORD wPITCH,
		WORD wDIR,
		BYTE bMouseDIR,
		BYTE bKeyDIR,
		BYTE bAction)
	{
		m_pTMON = pTMON;

		m_bChannel = bChannel;
		m_wMapID = wMapID;

		m_fPosX = fPosX;
		m_fPosY = fPosY;
		m_fPosZ = fPosZ;

		m_wPITCH = wPITCH;
		m_wDIR = wDIR;

		m_bMouseDIR = bMouseDIR;
		m_bKeyDIR = bKeyDIR;
		m_bAction = bAction;
	};
};

struct tagTFRAMEOFFSET
{
	DWORD m_dwFRAME;
	BYTE m_bBasisPoint;
	CPoint m_vOffset;

	struct tagTFRAMEOFFSET() {}
	struct tagTFRAMEOFFSET( DWORD dwFrame, BYTE bBasisPoint, CPoint vOffset )
		: m_dwFRAME(dwFrame), m_bBasisPoint(bBasisPoint), m_vOffset(vOffset) {}
};

struct tagTRESOLUTIONMODE
{
	CString m_strMode;
	INT m_nWidth;
	INT m_nHeight;

	tagTRESOLUTIONMODE()
		: m_strMode(""), m_nWidth(0), m_nHeight(0) {}
	tagTRESOLUTIONMODE( CString strMode, INT nWidth, INT nHeight )
		: m_strMode(strMode), m_nWidth(nWidth), m_nHeight(nHeight) {}
};

struct tagTSCRCAPTURE_PARAM
{
	LPDIRECT3DSURFACE9 m_pIMAGE;
	CString m_strFileName;

	tagTSCRCAPTURE_PARAM()
	{
		m_strFileName.Empty();
		m_pIMAGE = NULL;
	};

	~tagTSCRCAPTURE_PARAM()
	{
		if(m_pIMAGE)
			m_pIMAGE->Release();
	};
};

struct tagTOPENBYCASH
{
	WORD m_wNPCID;
	BYTE m_bInvenID;
	BYTE m_bSlotID;

	tagTOPENBYCASH()
	{
		m_wNPCID = -1;
		m_bInvenID = 255;
		m_bSlotID = 255;
	}

	tagTOPENBYCASH( WORD wNPCID, BYTE bInvenID, BYTE bSlotID )
		: m_wNPCID(wNPCID), m_bInvenID(bInvenID), m_bSlotID(bSlotID)
	{}

	~tagTOPENBYCASH()
	{
	}
};

struct tagTSTATINFO
{
	WORD m_wSTR;
	WORD m_wDEX;
	WORD m_wCON;
	WORD m_wINT;
	WORD m_wWIS;
	WORD m_wMEN;
	DWORD m_dwMinPysAtkPower;
	DWORD m_dwMaxPysAtkPower;
	DWORD m_dwPysDefPower;
	DWORD m_dwMinLongAtkPower;
	DWORD m_dwMaxLongAtkPower;
	DWORD m_dwAttackDelay[ TAD_COUNT ];
	DWORD m_dwAttackDelayRate[ TAD_COUNT ];
	WORD m_wAtkLevel;
	WORD m_wDefLevel;
	BYTE m_bPysCriticalProb;
	DWORD m_dwMinMagicAP;
	DWORD m_dwMaxMagicAP;
	DWORD m_dwMagicDefPower;
	WORD m_wMagicAtkLevel;
	WORD m_wMagicDefLevel;
	BYTE m_bChargeSpeed;
	BYTE m_bChargeProb;
	BYTE m_bMagicCriticalProb;
	WORD m_wSkillPoint;

	BYTE m_bColorSTAT[ TCHARSTAT_COUNT ];
	BYTE m_bColorBASIC[ TCHARBASIC_COUNT ];
};

struct tagTLATESTPVPINFO
{
	CString m_strName;
	BYTE m_bWin;
	BYTE m_bClass;
	BYTE m_bLevel;
	DWORD m_dwPoint;
	CTime m_dlDate;
};

struct tagTWEAPONEQUIPINFO
{
	BYTE m_bMode;
	LPTITEMVISUAL m_pItemVisual;

	tagTWEAPONEQUIPINFO()
	{}

	tagTWEAPONEQUIPINFO( BYTE bMode, LPTITEMVISUAL pIV )
		: m_bMode(bMode), m_pItemVisual(pIV) {}
};

struct tagTAUCTIONFINDINFO
{
	WORD			wNpcID;
	BYTE			bType;
	BYTE			bMinWearLv;
	BYTE			bMaxWearLv;
	BYTE			bMinPowerLv;
	BYTE			bMaxPowerLv;
	BYTE			bOption;
	WORD			wPageNum;
	BYTE			bCountPerPage;
	BYTE			bAlignKind;
	VTDWORD			vItemID;
	VTDWORD			vAuctionCode;

	tagTAUCTIONFINDINFO()
		:wNpcID( 0 ), bType( 0 ),
		bMinWearLv( 0 ), bMaxWearLv( 0 ),
		bMinPowerLv( 0 ), bMaxPowerLv( 0 ),
		bOption( 0 ), wPageNum( 1 ),
		bCountPerPage( TAUCTION_SLOT_COUNT ),
		bAlignKind( AAK_REGASC )
	{
		ClearCodeList();
	}

	void			Clear()
	{
		wNpcID = bOption = bCountPerPage = 0;

		bMinWearLv = 0;
		bMaxWearLv = 80;

		bMinPowerLv = 0;
		bMaxPowerLv = 24;

		bType = 1;
		bAlignKind = AAK_REGDESC;
		wPageNum = 1;
		bCountPerPage = TAUCTION_SLOT_COUNT;

		ClearCodeList();
	}

	void			PushCode( DWORD dwCode, DWORD dwItemID = 0 )
	{
		vAuctionCode.push_back( dwCode );
		vItemID.push_back( dwItemID );
	}

	void			ClearCodeList()
	{
		vAuctionCode.clear();
		vItemID.clear();
	}
};

struct tagTAUCTIONREGINFO
{
	WORD			wNpcID;
	WORD			wHour;
	BYTE			bInvenID;
	BYTE			bItemID;
	BYTE			bCount;
	__int64			ldwDirectPrice;
	__int64			ldwStartPrice;
	DWORD			dwCode;

	tagTAUCTIONREGINFO()
		:wNpcID( 0 ), wHour( 0 ), bInvenID( 0 ), bItemID( 0 ),
		bCount( 0 ), ldwDirectPrice( 0 ), ldwStartPrice( 0 ),
		dwCode( 0 )
	{
	}

	void			Clear()
	{
		wNpcID = wHour = bInvenID = bItemID = bCount = 0;
		ldwStartPrice = 0;
		ldwDirectPrice = 0;
		dwCode = 0;
	}
};

struct tagTTOURNAMENTPLAYER
{
	DWORD m_dwCharID;
	BYTE m_bCountry;
	CString m_strName;
	BYTE m_bLevel;
	BYTE m_bClass;
	DWORD m_dwChiefID;
};

struct tagTTOURNAMENTTEAM
{
	BYTE m_bSlotID;
	WORD m_wKillCount;
	VTTOURNAMENTPLAYER m_vMembers;

	~tagTTOURNAMENTTEAM()
	{
		ClearMember();
	}

	void ClearMember()
	{
		VTTOURNAMENTPLAYER::iterator it, end;
		for( it=m_vMembers.begin(), end=m_vMembers.end(); it != end ; ++it )
			delete (*it);
		m_vMembers.clear();
	}

	LPTTOURNAMENTPLAYER FindPlayer( DWORD dwCharID )
	{
		VTTOURNAMENTPLAYER::iterator it, end;
		for( it=m_vMembers.begin(), end=m_vMembers.end(); it != end ; ++it )
		{
			if( (*it)->m_dwCharID == dwCharID )
				return (*it);
		}
		return NULL;
	}

	LPTTOURNAMENTPLAYER GetChiefPlayer()
	{
		VTTOURNAMENTPLAYER::iterator it, end;
		for( it=m_vMembers.begin(), end=m_vMembers.end(); it != end ; ++it )
		{
			if( (*it)->m_dwCharID == (*it)->m_dwChiefID )
				return (*it);
		}
		return NULL;
	}

	LPTTOURNAMENTPLAYER GetRandPlayer()
	{
		if( m_vMembers.empty() )
			return NULL;

		size_t n = m_vMembers.size();
		return m_vMembers[ rand() % n ];
	}

	DWORD FindPlayer( CString strName )
	{
		VTTOURNAMENTPLAYER::iterator it, end;
		for( it=m_vMembers.begin(), end=m_vMembers.end(); it != end ; ++it )
		{
			if( (*it)->m_strName == strName )
				return (*it)->m_dwCharID;
		}
		return 0;
	}
};

struct tagTTOURNAMENTSCHEDULE
{
	BYTE m_bStep;
	CTime m_StartTime;
};

struct tagTTEVENTTARGETPARTY
{
	DWORD m_dwCharID;
	BYTE m_bCountry;
	CString m_strGuildName;
	CString m_strName;
	BYTE m_bLevel;
	BYTE m_bClass;
	DWORD m_dwRank;
	DWORD m_dwMonthRank;
};

struct tagTTEVENTTARGET
{
	DWORD m_dwCharID;
	BYTE m_bCountry;
	CString m_strGuildName;
	CString m_strName;
	BYTE m_bLevel;
	BYTE m_bClass;
	DWORD m_dwRank;
	DWORD m_dwMonthRank;
	FLOAT m_fRate;
	BYTE m_bPartyCount;
	VTTEVENTTARGETPARTY m_vParty;
	
	~tagTTEVENTTARGET()
	{
		ClearParty();
	}

	void ClearParty()
	{
		VTTEVENTTARGETPARTY::iterator it, end;
		it = m_vParty.begin();
		end = m_vParty.end();
		for(; it != end ; ++it )
			delete (*it);
		m_vParty.clear();
	}
};

struct tagTTEVENTMATCH
{
	BYTE m_bEntryID;
	CString m_strEntry;
	BYTE m_bType;
	CString m_strChoice;
	BYTE m_bCountry;
	FLOAT m_fRate; //비율
	DWORD m_dwAmount;
	VTTEVENTTARGET m_vList;

	~tagTTEVENTMATCH()
	{
		ClearList();
	}

	void ClearList()
	{
		VTTEVENTTARGET::iterator it, end;
		it = m_vList.begin();
		end = m_vList.end();

		for(; it != end ; ++it )
			delete (*it);
		
		m_vList.clear();
	}
};

struct tagTMATCHREWARD
{
	BYTE m_bCheckShield;
	BYTE m_bChartType;
	WORD m_wItemID;
	BYTE m_bCount;
};

struct tagTMATCHPARTY
{
	DWORD m_dwCharID;
	BYTE m_bCountry;
	CString m_strGuildName;
	CString m_strName;
	BYTE m_bLevel;
	BYTE m_bClass;
	DWORD m_dwRank;
	DWORD m_dwMonthRank;
};

struct tagTMATCHPLAYER
{
	BYTE m_bSlotID;
	DWORD m_dwCharID;
	BYTE m_bCountry;
	CString m_strName;
	BYTE m_bLevel;
	BYTE m_bClass;
	DWORD m_dwRank;
	DWORD m_dwMonthRank;
	BYTE m_bQfWin; // 8강 승패
	BYTE m_bSfWin; // 4강 승패
	BYTE m_bFWin; // 결승 승패

	VTMATCHPARTY m_vParty;

	~tagTMATCHPLAYER()
	{
		ClearParty();
	}

	void ClearParty()
	{
		VTMATCHPARTY::iterator it, end;
		it = m_vParty.begin();
		end = m_vParty.end();
		for(; it != end ; ++it )
			delete (*it);
		m_vParty.clear();
	}
};

struct tagTMATCH
{
	BYTE m_bGroup;
	BYTE m_bEntryID; //종목
	CString m_strEntry; //종목이름
	BYTE m_bType; //구분
	DWORD m_dwClass; // 종족
	BYTE m_bStep; // 진행상황
	BYTE m_bMyApplied; // 지원
	DWORD m_dwFee; // 수수료
	DWORD m_dwBackFee; // 환불료
	BYTE m_bPermitCount; // 허가서 갯수
	BYTE m_bNeed; // 일반정원
	WORD m_wTotalApplicant; // 일반지원자수
	BYTE m_bRewardCount; // 상품수

	VTMATCHREWARD m_vReward;
	VTMATCHPLAYER m_vPlayer;

	~tagTMATCH()
	{
		{
			VTMATCHREWARD::iterator it, end;
			it = m_vReward.begin();
			end = m_vReward.end();
			for(; it != end ; ++it )
				delete (*it);
		}
		{
			VTMATCHPLAYER::iterator it, end;
			it = m_vPlayer.begin();
			end = m_vPlayer.end();
			for(; it != end ; ++it )
				delete (*it);
		}
	}
};


///////////////////////////////////////////////////////////////////////////
// Utility class define

#include "TSharedPtr.h"
#include "TDetailInfo.h"
#include "TDetailInfoManager.h"
#include "TKeySettingDefines.h"

///////////////////////////////////////////////////////////////////////////
// TClient base class define

#include "TClientWebCtrl.h"
#include "TClientSession.h"
#include "TClientTalkBox.h"
#include "TClientObjBase.h"
#include "TClientMoveObj.h"
#include "TClientQClass.h"
#include "TClientArrow.h"
#include "TClientSkill.h"
#include "TClientInven.h"
#include "TClientQuest.h"
#include "TClientItem.h"
#include "TClientFlag.h"
#include "TClientTerm.h"
#include "TClientBSP.h"
#include "TClientSFX.h"
#include "TClientMAP.h"
#include "TClientKEY.h"
#include "TClientCAM.h"
#include "TClientGuildMark.h"
#include "TClientNICEventSink.h"

///////////////////////////////////////////////////////////////////////////
// TClient base class define
#include "TClientMaintain.h"
#include "TClientMonster.h"
#include "TClientRecall.h"
#include "TClientPet.h"
#include "TClientObject.h"
#include "TClientSwitch.h"
#include "TClientNumber.h"
#include "TClientChar.h"
#include "TClientFake.h"
#include "TClientGate.h"
#include "TClientNpc.h"
#include "TSiegeGodTower.h"
#include "TSiegeGodBall.h"

///////////////////////////////////////////////////////////////////////////
// Utility
#include "TGuildCommander.h"
#include "TMessengerCommander.h"
#include "TPartyCommander.h"
#include "TAuctionCommander.h"
#include "TTextLinkData.h"
#include "TTextLinker.h"
#include "TSiegeManager.h"

///////////////////////////////////////////////////////////////////////////
// TClient UI base class define

#include "TNumberEdit.h"
#include "TCtrlList.h"
#include "TClientUIBase.h"
#include "TInnerFrame.h"
#include "TFrameGroupBase.h"
#include "TListEx.h"
#include "TItemSlotBaseDlg.h"

///////////////////////////////////////////////////////////////////////////
// TClient UI class define

#include "TInvenDlg.h"
#include "TNewQuestDlg.h"
#include "TGameSettingFrame.h"
#include "TSystemSettingFrame.h"
#include "TMaintainPannel.h"
#include "TDynamicHelpDlg.h"
#include "TDetailInfoDlg.h"
#include "TGaugePannel.h"
#include "TWorldmapDlg.h"
#include "TCharInfoDlg.h"
#include "TNPCTalkDlg.h"
#include "TMinimapDlg.h"
#include "TDurationFrame.h"
#include "TPopupMenu.h"
#include "TSkillDlg.h"
#include "TShopBaseDlg.h"
#include "TRSCSDlg.h"
#include "TMainUI.h"
#include "TShopItem.h"
#include "TShopDlg.h"
#include "TPrivateShopDlg.h"
#include "TNewCashShopDlg.h"
#include "TTradeDlg.h"
#include "TItemRegBox.h"
#include "TPartyItemLottery.h"
#include "TCabinetDlg.h"
#include "TNormalCabinetDlg.h"
#include "TGuildCabinetDlg.h"
#include "TCashCabinetDlg.h"
#include "TKeySettingDlg.h"
#include "TSMSDlg.h"
#include "TGuildRTTypeFrame.h"
#include "TGuildExpDonDlg.h"
#include "TGuildMoneyDonDlg.h"
#include "TGuildMarkMakeDlg.h"
#include "TGuildNotifyDlg.h"
#include "TGuildApplicationDlg.h"
#include "TGuildAppInnerFrame.h"
#include "TGuildOfferFrame.h"
#include "TGuildSeekFrame.h"
#include "TGuildCmdHelpDlg.h"
#include "TProgressRegDlg.h"
#include "TCinematicDlg.h"
#include "TChatFrame.h"
#include "TChatList.h"
#include "TChatTabButton.h"
#include "TSiegeUI.h"
#include "TSiegeEnd.h"
#include "TClientMsgBox.h"
#include "TAuctionInnerFrame.h"
#include "TAuctionMainFrame.h"
#include "TAuctionSearch.h"
#include "TAuctionRegist.h"
#include "TAuctionMyBid.h"
#include "TAuctionBasket.h"
#include "TAuctionCategory.h"
#include "TAuctionCtrlList.h"
#include "TAuctionMsgBox.h"
#include "TMiniPopupDlg.h"
#include "TBlockListDlg.h"
#include "TScenePlayer.h"
#include "..\TEngine\TChatFilter\ChatFilterType.h"
#include "..\TEngine\TChatFilter\ChatFilterFile.h"
#include "..\TEngine\TChatFilter\ChatFilterSys.h"
#include "TStrFilter.h"