#pragma once


#define ON_MAPVIEWER_CMD(x)			case x	: dwERROR = On##x(strParam); break;

typedef enum TMapViewer_CMD
{
	TCMD_EXIT = 0,
	TCMD_LOADCHAR,
	TCMD_LOADMAP,
	TCMD_MOVE,
	TCMD_FPS,
	TCMD_MINIMAP,
	TCMD_SPEED,
	TCMD_POS,
	TCMD_HELP,
	TCMD_BUILD,
	TCMD_FINDPATH,
	TCMD_PATH,
	TCMD_LIGHT,
	TCMD_MAPCOLOR,
	TCMD_SHADOW,
	TCMD_MATERIALA,
	TCMD_MATERIALD,
	TCMD_LANDCOLLISION,
	TCMD_LIGHTMODE,
	TCMD_LIGHTA,
	TCMD_LIGHTD,
	TCMD_LIGHTDIR,
	TCMD_PATHMODE,
	TCMD_DELRANGE,
	TCMD_CLIMB,
	TCMD_FOGRANGE,
	TCMD_FOGCOLOR,
	TCMD_FOGDENSITY,
	TCMD_COUNT
} *LPTMapViewer_CMD;
