#pragma once


typedef enum TEXPLORER_ERROR
{
	TERROR_NONE = 0,
	TERROR_UNKNOWN_CMD,
	TERROR_LOADMAP,
	TERROR_MOVE,
	TERROR_SPEED,
	TERROR_LOADMAP_NOTFOUND,
	TERROR_MATERIALA,
	TERROR_MATERIALD,
	TERROR_BUILD_NOMAP,
	TERROR_FINDPATH_NOMAP,
	TERROR_SHADOW,
	TERROR_MAPCOLOR,
	TERROR_AMBIENT,
	TERROR_DIFFUSE,
	TERROR_LIGHTDIR,
	TERROR_DELRANGE,
	TERROR_COUNT
} *LPTEXPLORER_ERROR;
