#pragma once


// define
#define T_INVALID						(-1)

#define TSHOTTYPE_COUNT					(2)
#define TFACE_COUNT						(4)
#define THAIR_COUNT						(7)
#define TPANTS_COUNT						(2)
#define TBODY_COUNT						(2)
#define THAND_COUNT						(2)
#define TFOOT_COUNT						(2)
#define TMAINRACE_COUNT					(3)
#define TSKILLTAB_COUNT					(4)
#define TMAGIC_SFXKIND_COUNT			(15)
#define TMONSKILL_COUNT					((BYTE) 4)
#define TNPC_RNDACT_COUNT				(2)
#define TDRAWMARK_DEFAULT				((BYTE) 3)
#define TMAXGUILD_MARK					(19)
#define TMAXGUILD_MARKBACK				(19)
#define TMAXGUILD_MARK_COLOR			(38)
#define MANTLECOORD_VER					0xFF00FF01
#define MANTLECOORD_VER_OLD			0xFF00FF00

// enum
typedef enum TSTRING
{
	TSTR_NONE=0,
	TSTR_QUIT_TITLE,
	TSTR_QUIT_MSG,
	TSTR_YES,
	TSTR_NO,
	TSTR_LOGIN_ID,
	TSTR_ERROR_TITLE,
	TSTR_OK,
	TSTR_CANCEL,
	TSTR_CONNECT_FAILED,
	TSTR_INVALID_PASSWD,
	TSTR_DUPLICATE_CONNECT,
	TSTR_INVALID_VERSION,
	TSTR_INTERNAL,
	TSTR_INVALID_USER,
	TSTR_NOGROUP,
	TSTR_DUPNAME,
	TSTR_INVALID_SLOT,
	TSTR_NOCHANNEL,
	TSTR_NOCHAR,
	TSTR_NOSERVER,
	TSTR_NEW_CHAR,
	TSTR_NONAME,
	TSTR_DELCHAR,
	TSTR_INVALID_CHAR,
	TSTR_FILE_MONCHART,
	TSTR_FILE_ITEMCHART,
	TSTR_FILE_RACECHART,
	TSTR_FILE_HEADCHART,
	TSTR_FILE_BODYCHART,
	TSTR_FILE_PANTSCHART,
	TSTR_FILE_HANDCHART,
	TSTR_FILE_FOOTCHART,
	TSTR_ERROR_ITEM_NODESTINVEN,
	TSTR_ERROR_ITEM_NOSRCINVEN,
	TSTR_ERROR_ITEM_NOSRCITEM,
	TSTR_ERROR_ITEM_CANNOTEQUIP,
	TSTR_ERROR_ITEM_INVENFULL,
	TSTR_FILE_ACTIONCHART,
	TSTR_NOSLOT,
	TSTR_FMT_LEVEL,
	TSTR_FMT_GAUGE,
	TSTR_FMT_NUMBER,
	TSTR_FILE_SKILLCHART,
	TSTR_DELCHAR_TITLE,
	TSTR_DELCHAR_MSG,
	TSTR_FMT_PARTY_REQ,
	TSTR_PARTY_REQ,
	TSTR_NOT_PARTYCHIEF,
	TSTR_NOPARTY,
	TSTR_FMT_ALREADY_PARTY,
	TSTR_FMT_PARTY_WAITERS,
	TSTR_FMT_PARTY_NOUSER,
	TSTR_FMT_PARTY_DENY,
	TSTR_PARTY_FULL,
	TSTR_REVIVAL_MSG,
	TSTR_REVIVAL_TITLE,
	TSTR_REVIVAL,
	TSTR_CHAT_NORMAL,
	TSTR_CHAT_WHISPER,
	TSTR_CHAT_NATION,
	TSTR_CHAT_WORLD,
	TSTR_CHAT_PARTY,
	TSTR_CHAT_GUILD,
	TSTR_FMT_CHAT_NAME,
	TSTR_KEYWORD_CHAT_NORMAL,
	TSTR_KEYWORD_CHAT_NATION,
	TSTR_MBOX_GUILD_BUILD,
	TSTR_KEYWORD_CHAT_PARTY,
	TSTR_KEYWORD_CHAT_GUILD,
	TSTR_KEYWORD_CHAT_WHISPER,
	TSTR_PASSWORD,
	TSTR_FMT_BUYITEM,
	TSTR_EA,
	TSTR_BUYITEM,
	TSTR_FMT_BUYSTACK,
	TSTR_FMT_BUYONE,
	TSTR_SELLITEM,
	TSTR_FMT_SELLITEM,
	TSTR_FMT_SELLALL,
	TSTR_FMT_SELLONE,
	TSTR_SKILLTAB_PASSIVE,
	TSTR_SKILLTAB_ATTACK,
	TSTR_SKILLTAB_DEFENSE,
	TSTR_SKILLTAB_STATE,
	TSTR_SKILLTAB_BATTLE,
	TSTR_SKILLTAB_ASSASSIN,
	TSTR_SKILLTAB_TRAP,
	TSTR_SKILLTAB_SHOOT,
	TSTR_SKILLTAB_SURVIVAL,
	TSTR_SKILLTAB_FIRE,
	TSTR_SKILLTAB_ICE,
	TSTR_SKILLTAB_ELEC,
	TSTR_SKILLTAB_DIVINE,
	TSTR_SKILLTAB_DARK,
	TSTR_SKILLTAB_SACRIFICE,
	TSTR_SKILLTAB_SUPPORT,
	TSTR_SKILLTAB_SUMMON,
	TSTR_SKILLTAB_CONTROL,
	TSTR_FILE_SKILLTREECHART,
	TSTR_FMT_REALPERCENT,
	TSTR_ACCEPT,
	TSTR_CLOSE,
	TSTR_FILE_QUEST,
	TSTR_COMPLETE,
	TSTR_FMT_TERM,
	TSTR_FMT_REWARD,
	TSTR_ERROR_SILENCE,
	TSTR_FMT_REWARD_EXP,
	TSTR_FMT_NAME,
	TSTR_QRESULT_COMPLETE,
	TSTR_QRESULT_INCOMPLETE,
	TSTR_QRESULT_FAILED,
	TSTR_QUEST_STATUS,
	TSTR_FMT_COUNT,
	TSTR_GIVEUP,
	TSTR_QUEST_CONTENT,
	TSTR_QUEST_SUMMARY,
	TSTR_QUEST_TERM,
	TSTR_FMT_QUEST_STATUS,
	TSTR_TCHARINFO_PHYSIC,
	TSTR_TCHARINFO_MAGIC,
	TSTR_TCHARINFO_REG,
	TSTR_TCHARINFO_RANK,
	TSTR_FILE_REGIONCHART,
	TSTR_FILE_SKILLFUNCTION,
	TSTR_FMT_BASIC_STAT,
	TSTR_FMT_CHARINFO_RANGE,
	TSTR_FILE_INFOCHART,
	TSTR_FILE_MINIMAP,
	TSTR_FILE_NPCCHART,
	TSTR_FILE_MAPNPC,
	TSTR_FMT_FIELDNAME,
	TSTR_FMT_FIELDTITLE,
	TSTR_SERVER_LOW,
	TSTR_SERVER_NORMAL,
	TSTR_SERVER_FULL,
	TSTR_NORMAL_SERVER,
	TSTR_BATTLE_SERVER,
	TSTR_ERROR_NEEDWEAPON,
	TSTR_ERROR_TOOCLOSE,
	TSTR_ERROR_LOOKAT,
	TSTR_ERROR_TOOFAR,
	TSTR_INFO_TITLE,
	TSTR_ERROR_SKILL,
	TSTR_FILE_SFXCHART,
	TSTR_FILE_STEPCHART,
	TSTR_FILE_MAPCHART,
	TSTR_FILE_NODECHART,
	TSTR_FMT_PATHFILE,
	TSTR_GOTO_THUMB_MSG,
	TSTR_GOTO_THUMB_TITLE,
	TSTR_FMT_DEAD,
	TSTR_FILE_SWITCHCHART,
	TSTR_FILE_GATECHART,
	TSTR_FILE_LIGHTCHART,
	TSTR_FILE_BGMCHART,
	TSTR_FILE_ACTIONDEFCHART,
	TSTR_ERROR_NEEDSKILLPOINT,
	TSTR_ERROR_NEEDPREVACT,
	TSTR_FILE_ENVCHART,
	TSTR_VK_SNAPSHOT,
	TSTR_GAMBLING_TITLE,
	TSTR_GAMBLING_MSG,
	TSTR_ITEM_ERR_GAMBLE,
	TSTR_FMT_SKILL_REWARD,
	TSTR_FMT_DURATIONDEL,
	TSTR_EXTENSION_PERIOD,
	TSTR_FMT_DATE_YMD,
	TSTR_LIMIT_PERIOD,
	TSTR_BUY,
	TSTR_CASH_WOULDBUY,
	TSTR_ERR_CASHSHOP_NOTFOUND,
	TSTR_ERR_CASHSHOP_MAXCOUNT,
	TSTR_ERR_CASHSHOP_NEEDEXTEND,
	TSTR_FMT_DATE_YMDHM,
	TSTR_ERROR_MAXLEVEL,
	TSTR_ERROR_NEEDLEVELUP,
	TSTR_ERROR_WRONGTARGET,
	TSTR_ERROR_NEEDPARENT,
	TSTR_ERROR_WRONGREGION,
	TSTR_ERROR_MATCHCLASS,
	TSTR_ERROR_NEEDMONEY,
	TSTR_ERROR_SPEEDYUSE,
	TSTR_ERROR_NOTFOUND,
	TSTR_ERROR_NEEDMP,
	TSTR_ERROR_NEEDHP,
	TSTR_ERROR_TRANS,
	TSTR_ERROR_HIDE,
	TSTR_ERROR_STUN,
	TSTR_ERROR_DEAD,
	TSTR_FMT_SQUAD_NAME,
	TSTR_ERROR_NEED_PARTY,
	TSTR_ERROR_TARGET_NO_PARTY,
	TSTR_ERROR_NOT_COMMANDER,
	TSTR_ERROR_WRONG_TARGET,
	TSTR_FMT_CORPS_ASK,
	TSTR_FMT_CORPS_DENY,
	TSTR_ERROR_CORPS_ALREADY,
	TSTR_TCMD_NONE,
	TSTR_TCMD_MOVE,
	TSTR_TCMD_ATTACK,
	TSTR_TCMD_PROTECT,
	TSTR_UNKNOWN,
	TSTR_MENU_CHARINFO,
	TSTR_MENU_SKILLINFO,
	TSTR_MENU_EXITPARTY,
	TSTR_MENU_GUILDINFO,
	TSTR_MENU_EXITGUILD,
	TSTR_MENU_EXITCORPS,
	TSTR_MENU_PC_TRADE,
	TSTR_MENU_PARTY_REQ,
	TSTR_MENU_PARTY_KICK,
	TSTR_MENU_GUILD_REQ,
	TSTR_MENU_CORPS_REQ,
	TSTR_MENU_CORPS_KICK,
	TSTR_MENU_SETCOMMANDER,
	TSTR_MENU_SETCHIEF,
	TSTR_FILE_SKYCHART,
	TSTR_FILE_POPUPITEMCHART,
	TSTR_FILE_POPUPMENUCHART,
	TSTR_FILE_FOGCHART,
	TSTR_TCLASS_WARRIOR,
	TSTR_TCLASS_RANGER,
	TSTR_TCLASS_ARCHER,
	TSTR_TCLASS_WIZARD,
	TSTR_TCLASS_PRIEST,
	TSTR_TCLASS_SORCERER,
	TSTR_INVALID_NAME,
	TSTR_NAME_TOO_LONG,
	TSTR_FMT_REVIVAL_REQ,
	TSTR_FMT_REVIVAL_REJECT,
	TSTR_FILE_LEVELCHART,
	TSTR_FMT_RUNE,
	TSTR_SKILLUPGRADEINFO_TITLE,
	TSTR_TEXT_MASTER,
	TSTR_FMT_LUNA,
	TSTR_FMT_CRON,
	TSTR_EXITGAME_MSG,
	TSTR_ERROR_CANNOT_OPEN_WORLDMAP,
	TSTR_FMT_WORLDMAP_TITLE,
	TSTR_FMT_WORLDMAP_NAME,
	TSTR_FILE_TCOUNTRYINFO,
	TSTR_FILE_TCLASSINFO,
	TSTR_FILE_TRACEINFO,
	TSTR_CONTRY_D,
	TSTR_CONTRY_C,
	TSTR_CONTRY_B,
	TSTR_RACE_HUMAN,
	TSTR_RACE_BEAST,
	TSTR_RACE_NYMPH,
	TSTR_DROP_ITEM,
	TSTR_SET_HOME,
	TSTR_SET_RETURNPOS,
	TSTR_ERROR_SET_RETURNPOS,
	TSTR_ERROR_ITEM_DEAD,
	TSTR_TEXT_SELREWARD,
	TSTR_FMT_PROBREWARD,
	TSTR_ERROR_SKILLMODE,
	TSTR_FILE_LOADINGIMG,
	TSTR_FILE_GAUGE,
	TSTR_FMT_TRADE_REQ,
	TSTR_ERROR_ITEM_BLOCK,
	TSTR_ERROR_ITEM_NOSKILL,
	TSTR_ERROR_ITEM_TRADE,
	TSTR_ERROR_ITEM_LEVEL,
	TSTR_ERROR_ITEM_NOMATCHCLASS,
	TSTR_ERROR_ITEM_BOTHHANDWEAPON,
	TSTR_ERROR_TRADE_INVALIDITEM,
	TSTR_ERROR_TRADE_TARGET,
	TSTR_ERROR_TRADE_NOMONEY,
	TSTR_ERROR_TRADE_NOITEM,
	TSTR_ERROR_TRADE_ALREADY,
	TSTR_ERROR_TRADE_CANCEL,
	TSTR_ERROR_TRADE_DENY,
	TSTR_ERROR_TRADE_ENEMY,
	TSTR_ERROR_TRADE_CANTRECV,
	TSTR_ERROR_TRADE_SUCCESS,
	TSTR_NPC_REVIVAL,
	TSTR_FMT_QUEST_SPEEKER,
	TSTR_ERROR_CORPS_DEAD,
	TSTR_FILE_ARROWDIR,
	TSTR_ERROR_PEACEZONE,
	TSTR_ERROR_NOTARGET,
	TSTR_ERROR_NOTMOVESKILL,
	TSTR_FMT_EXP,
	TSTR_GETMONEY,
	TSTR_FMT_DEFENDMA,
	TSTR_FMT_DEFENDM,
	TSTR_FMT_ATTACK,
	TSTR_FMT_DEFENDA,
	TSTR_FMT_DEFEND,
	TSTR_FMT_ATTACKA,
	TSTR_FMT_LEVELUPM,
	TSTR_FMT_LEVELUP,
	TSTR_FMT_DIE,
	TSTR_ERROR_ACTIONLOCK,
	TSTR_FILE_TDYNAMICHELP,
	TSTR_ITEM_NOT_FOUND,
	TSTR_ITEM_NO_MONEY,
	TSTR_ITEM_NO_SLOT,
	TSTR_ITEM_DEALING,
	TSTR_FMT_TIMMER,
	TSTR_QRESULT_TIMEOUT,
	TSTR_FMT_NPCNAME,
	TSTR_ITEM_CANNOT_SELL,
	TSTR_ITEM_CANNOT_TRADE,
	TSTR_FMT_FLOAT_NUMBER,
	TSTR_TEXT_PRMWEAPON,
	TSTR_TEXT_SNDWEAPON,
	TSTR_TEXT_LONGWEAPON,
	TSTR_TEXT_HEAD,
	TSTR_TEXT_BACK,
	TSTR_TEXT_BODY,
	TSTR_TEXT_PANTS,
	TSTR_TEXT_FOOT,
	TSTR_TEXT_HAND,
	TSTR_TEXT_NECK,
	TSTR_TEXT_RING,
	TSTR_TEXT_EARING,
	TSTR_TEXT_FACE,
	TSTR_MENU_CHAR,
	TSTR_MENU_SKILL,
	TSTR_MENU_COMMUNITY,
	TSTR_MENU_QUEST,
	TSTR_MENU_HELP,
	TSTR_MENU_SYSTEM,
	TSTR_MENU_MESSENGER,
	TSTR_MENU_MAIL,
	TSTR_MENU_ACTLIST,
	TSTR_CHAT_TAB_ALL,
	TSTR_CHAT_TAB_NORMAL,
	TSTR_CHAT_TAB_WHISPER,
	TSTR_CHAT_TAB_PARTY,
	TSTR_CHAT_TAB_GUILD,
	TSTR_CHAT_TAB_FORCE,
	TSTR_CHAT_TAB_RESULT,
	TSTR_CHAT_FORCE,
	TSTR_KEYWORD_CHAT_FORCE,
	TSTR_REPRESENTATION_WHISPER,
	TSTR_REPRESENTATION_FORCE,
	TSTR_REPRESENTATION_GUILD,
	TSTR_REPRESENTATION_NATION,
	TSTR_REPRESENTATION_NORMAL,
	TSTR_REPRESENTATION_PARTY,
	TSTR_MBOX_GUILD_BUILD_LOWLEVEL,
	TSTR_TITLE_CLOSE,
	TSTR_ITEMUP_WARN_UP,
	TSTR_ITEMUP_WARN_DOWN,
	TSTR_ITEMUP_WARN_NOITEM,
	TSTR_ITEMUP_WARN_NOMAT,
	TSTR_ITEMUP_SUCCESS,
	TSTR_ITEMUP_FAIL,
	TSTR_FILE_ITEMMAGIC,
	TSTR_FMT_ITEMMAGIC,
	TSTR_CANNOT_REVIVALPOS,
	TSTR_ERROR_FILE,
	TSTR_ERROR_MEMORY,
	TSTR_CHATFLAG_WHISPER,
	TSTR_CHATFLAG_NEAR,
	TSTR_CHATFLAG_MAP,
	TSTR_CHATFLAG_WORLD,
	TSTR_CHATFLAG_PARTY,
	TSTR_CHATFLAG_GUILD,
	TSTR_CHATFLAG_INFO,
	TSTR_CHATFLAG_FORCE,
	TSTR_FMT_CAPTURE,
	TSTR_FMT_CAPTUREMSG,
	TSTR_MBOX_GUILD_BUILD_FAIL,
	TSTR_MBOX_GUILD_BUILD_SUCC,
	TSTR_CMD_GUILD_INVITE,
	TSTR_CMD_GUILD_ALLINFO,
	TSTR_CMD_GUILD_OUT,
	TSTR_CMD_GUILD_KICK,
	TSTR_CMD_GUILD_DISORG,
	TSTR_CMD_GUILD_DISORGCANCEL,
	TSTR_CMD_GUILD_MASTER,
	TSTR_CMD_GUILD_SUBMASTER,
	TSTR_MBOX_GUILD_ALREADYGUILDNAME,
	TSTR_MBOX_GUILD_DISORG_SUCC,
	TSTR_MBOX_GUILD_INVITE,
	TSTR_MBOX_GUILD_DISORGCANCLE_SUCC,
	TSTR_MBOX_GUILD_NEWMEMBER,
	TSTR_MBOX_GUILD_JOIN_DENY,
	TSTR_MBOX_GUILD_JOIN_SUCC,
	TSTR_MBOX_GUILD_LEAVE_SELF,
	TSTR_MBOX_GUILD_LEAVE_DISORG,
	TSTR_MBOX_GUILD_LEAVE_KICK,
	TSTR_MBOX_GUILD_KICK_SUCC,
	TSTR_GUILD_DUTY_NONE,
	TSTR_GUILD_DUTY_VICECHIEF,
	TSTR_GUILD_DUTY_CHIEF,
	TSTR_GUILD_PEER_NONE,
	TSTR_GUILD_PEER_BARON,
	TSTR_GUILD_PEER_VISCOUNT,
	TSTR_GUILD_PEER_COUNT,
	TSTR_GUILD_PEER_MARQUIS,
	TSTR_GUILD_PEER_DUKE,
	TSTR_MBOX_GUILD_DUTY,
	TSTR_MBOX_GUILD_DUTY_ACK,
	TSTR_MBOX_GUILD_PEER,
	TSTR_DELCHAR_ERR_INGUILD,
	TSTR_CMD_GUILD_BARON,
	TSTR_CMD_GUILD_PEER_CANCEL,
	TSTR_CMD_GUILD_VISCOUNT,
	TSTR_CMD_GUILD_COUNT,
	TSTR_CMD_GUILD_MARQUIS,
	TSTR_CMD_GUILD_DUKE,
	TSTR_MBOX_GUILD_PEER_ACK,
	TSTR_CMSG_FRIEND_CONNECT,
	TSTR_COMMMSG_NOGUILD,
	TSTR_ITEMUP_WARN_MAGIC,
	TSTR_ITEMUP_WARN_RARE,
	TSTR_PRIVATE_SHOP_START,
	TSTR_PRIVATE_SHOP_END,
	TSTR_PRIVATE_SHOP_BUY,
	TSTR_MENU_PRIVSHOP_FOR_SELL,
	TSTR_MENU_PRIVSHOP_FOR_BUY,
	TSTR_PRVSHOP_BUY_SUCC,
	TSTR_PRVSHOP_BUY_NOITEM,
	TSTR_PRVSHOP_BUY_NEEDMONEY,
	TSTR_PRVSHOP_BUY_NOITEMCOUNT,
	TSTR_PRVSHOP_BUY_INVENFULL,
	TSTR_PRVSHOP_SELL_NOSHOPNAME,
	TSTR_PRVSHOP_SELL_ACK,
	TSTR_PRVSHOP_REQBUY_MSG,
	TSTR_PRVSHOP_REQBUY_EDIT,
	TSTR_STATE_CONNECT,
	TSTR_FMT_PRVSHOP_TITLE,
	TSTR_STATE_DISCONNECT,
	TSTR_MBOX_ADD_FRIEND,
	TSTR_MBOX_FRIEND_INVITE,
	TSTR_MBOX_FRIENDREPLY_YES,
	TSTR_MBOX_FRIENDREPLY_NO,
	TSTR_CMSG_ERASEFRIEND,
	TSTR_CMSG_ALEADYFRIEND,
	TSTR_CMD_MSG_ADD_FRIEND,
	TSTR_CMD_MSG_DEL_FRIEND,
	TSTR_CMSG_MAKEGROUP_SUCC,
	TSTR_CMD_MSG_MAKE_GROUP,
	TSTR_CMSG_MAKEGROUP_MAX,
	TSTR_CMSG_ALEADYGROUP,
	TSTR_CMD_MSG_CHANGE_GROUP,
	TSTR_CMD_MSG_DEL_GROUP,
	TSTR_CMSG_ERASEFRIENDGROUP,
	TSTR_CMSG_FRIEND_DISCONNECT,
	TSTR_CMD_MSG_NAME_GROUP,
	TSTR_FMT_MSGHAT_TITLE,
	TSTR_MPOPUP_CHAT,
	TSTR_MPOPUP_SENDMAIL,
	TSTR_MBOX_ADDTOBLOCKLIST,
	TSTR_CMD_MSG_ADD_BLOCK,
	TSTR_CMD_MSG_DEL_BLOCK,
	TSTR_MAILTYPE_NORMAL,
	TSTR_MAILTYPE_PACKATE,
	TSTR_MAILTYPE_BILLS,
	TSTR_MAILTYPE_RETURN,
	TSTR_MAILTYPE_PAYMENT,
	TSTR_MAILTYPE_NPC,
	TSTR_MAILTYPE_OPERATOR,
	TSTR_CMSG_POST_FULL,
	TSTR_FMT_DATE,
	TSTR_MAILTYPE_CASH,
	TSTR_CMSG_RECVMAIL,
	TSTR_FMT_POST_COST,
	TSTR_FMT_MAIL_REPLY,
	TSTR_CMSG_POST_SUCCESS,
	TSTR_CMSG_POST_NORECEIVER,
	TSTR_CMSG_POST_NEEDMONEY,
	TSTR_CMSG_POST_NOTITLE,
	TSTR_MAIL_TITLE_BLANK,
	TSTR_MIALERR_NORECEIVER,
	TSTR_FILE_PET,
	TSTR_PETKIND_ONE,
	TSTR_PETKIND_TWO,
	TSTR_GUILD_EXIT_WARN,
	TSTR_PETKIND_TELE,
	TSTR_MBOX_GUILD_ALREADYMEMBER,
	TSTR_PETKIND_INVEN,
	TSTR_PETKIND_EXP,
	TSTR_MBOX_GUILD_LEAVE_SELF_ERR,
	TSTR_MBOX_GUILD_LEAVE_DISO_ERR,
	TSTR_GUILD_LEAVE_SELF_CHIEF_ERR,
	TSTR_CAPTURE_FOLDER,
	TSTR_PETCON_LEVEL,
	TSTR_CMD_PARTY_INVITE,
	TSTR_FMT_PET_ENDTIME,
	TSTR_IPBLOCK,
	TSTR_FMT_PET_USETIME,
	TSTR_PETMAKE_NONAME,
	TSTR_PETCON_NO,
	TSTR_PETMAKE_ACK_FULL,
	TSTR_PETMAKE_ACK_SUCC,
	TSTR_PETMAKE_ACK_EXPTIME,
	TSTR_FMT_PETLISTITEM_RECALL,
	TSTR_FMT_PETLISTITEM_READY,
	TSTR_FMT_PETMNGBTN_DORECALL,
	TSTR_FMT_PETMNGBTN_CANCELRECALL,
	TSTR_PETRECALL_ACK_USETIME,
	TSTR_MENU_PC_PETTAKEDOWN,
	TSTR_FMT_PETMNGBTN_RECALLING,
	TSTR_FMT_EXPTEXT,
	TSTR_MENU_MAIN_MENU,
	TSTR_MENU_INVEN_SLOT,
	TSTR_MENU_FRIEND_REQ,
	TSTR_FILE_PORTAL,
	TSTR_CMSG_NOMENYPORTAL,
	TSTR_FMT_MSGSENDER_ME,
	TSTR_FMT_MSGSENDER,
	TSTR_MPOPUP_MOVEGROUP,
	TSTR_MPOPUP_BLOCK,
	TSTR_MPOPUP_DELETE,
	TSTR_MPOPUP_NEWGROUP,
	TSTR_GPOPUP_CHAT,
	TSTR_GPOPUP_CHANGENAME,
	TSTR_GPOPUP_DELETE,
	TSTR_GPOPUP_NEWGROUP,
	TSTR_MBOX_NEWFRIENDGROUP,
	TSTR_MBOX_CHANGEFRIENDGROUP,
	TSTR_FMT_GUILDCOUNTTXT,
	TSTR_MENU_PC_PETMANAGE,
	TSTR_DEFAULT_MSGBOX_TITLE,
	TSTR_FILE_ITEMATTR,
	TSTR_FILE_ITEMGRADE,
	TSTR_SHOPTITLE_PORTAL,
	TSTR_SHOPBUTTON_PORTAL,
	TSTR_SHOPTITLE_ITEM,
	TSTR_SHOPBUTTON_ITEM,
	TSTR_NEED_RESTART_OPTION,
	TSTR_PET_NAMEBOX_MSG,
	TSTR_ITEMUP_ERR_GRADEMAGIC,
	TSTR_ITEMUP_ERR_DOWNGRADE,
	TSTR_ITEMUP_ERR_MAGICMAGIC,
	TSTR_ITEMUP_ERR_MAGICRARE,
	TSTR_ITEMUP_ERR_MAGICGRADE,
	TSTR_ITEMUP_ERR_RARE,
	TSTR_ITEMUP_ERR_INVALIDITEM,
	TSTR_PET_NAMEBOX_EDIT,
	TSTR_PETMAKE_BTN_MAKE,
	TSTR_PETMAKE_BTN_EXT,
	TSTR_PETMAKE_KINDNAME,
	TSTR_CMD_PARTY_KICK,
	TSTR_CMD_PARTY_OUT,
	TSTR_FMT_SELLITEMS,
	TSTR_NAME,
	TSTR_FMT_SERVERNAME,
	TSTR_FMT_PARTY_ITEM_FREE,
	TSTR_FMT_PARTY_ITEM_HUNTER,
	TSTR_FMT_PARTY_ITEM_LOTTERY,
	TSTR_FMT_PARTY_ITEM_CHIEF,
	TSTR_FMT_TPARTYITEMTAKE,
	TSTR_FMT_ADDITEM,
	TSTR_FMT_TIME_HOUR,
	TSTR_FMT_TIME_MINUTE,
	TSTR_CMSG_CHGPARTYTYPE_FREE,
	TSTR_CMSG_CHGPARTYTYPE_HUNTER,
	TSTR_CMSG_CHGPARTYTYPE_LOTTERY,
	TSTR_CMSG_CHGPARTYTYPE_CHIEF,
	TSTR_FMT_TIME_SECOND,
	TSTR_FMT_LEVELCLASS,
	TSTR_AUTOCHANNEL,
	TSTR_FMT_CHANNELBUTTON,
	TSTR_SERVER_SLEEP,
	TSTR_ERR_SERVER_BUSY,
	TSTR_ERR_CHANNEL_BUSY,
	TSTR_FMT_PARTY_ITEM_SEQ,
	TSTR_CMSG_CHGPARTYTYPE_SEQ,
	TSTR_ERR_MAIL_REGION,
	TSTR_NEEDCREATECARD,
	TSTR_FMT_CHARTYPE,
	TSTR_MPOPUP_BLOCKLIST,
	TSTR_NPOPUP_INVITE,
	TSTR_MBOX_GUILD_MEMBER_FULL,
	TSTR_FMT_PETLISTITEM_TIME,
	TSTR_FMT_PC_COMMANDER,
	TSTR_FMT_PC_CHIEF,
	TSTR_STARTCMD_FORCECON,
	TSTR_NOTIFY_CHANGE_CHANNEL,
	TSTR_NOTIFY_SELECT_CHARACTER,
	TSTR_MBOX_DUPLICATEDID,
	TSTR_MBOX_CANCELQUIT,
	TSTR_MBOX_CANCELCH,
	TSTR_ERR_FAILINITDEVICE,
	TSTR_LOADMSG_WAITFORSTART,
	TSTR_CHAT_OPERATOR,
	TSTR_LOADMSG_WAITFORCON,
	TSTR_LOADMSG_SUCCESSCON,
	TSTR_LOADMSG_LOADDATA,
	TSTR_REPRESENTATION_GM,
	TSTR_GM_NAME,
	TSTR_MOVEITEM_COUNT,
	TSTR_FMT_UPGRADE_SUCCESS,
	TSTR_STRING704,
	TSTR_MIALERR_TRADING,
	TSTR_CABINET_OPEN_WARN,
	TSTR_CABINET_NAME,
	TSTR_CABINET_COST,
	TSTR_ERR_CABINET,
	TSTR_ERR_CABINET_NO_SLOT,
	TSTR_ERR_MAX_CABINET,
	TSTR_CABINET_BTN_OPEN,
	TSTR_CABINET_BTN_USE,
	TSTR_FMT_QUESTLEVEL,
	TSTR_FMT_QUESTLEVEL_LIM,
	TSTR_QUEST_CANNOTPERF,
	TSTR_ERR_CURSE_STR,
	TSTR_ITEMUP_ERR_CANNOTGRADE,
	TSTR_ITEMUP_ERR_CANNOTMAGIC,
	TSTR_ITEMUP_ERR_CANNOTRARE,
	TSTR_FOLLOW_TARGET,
	TSTR_TKEY_FORWARD,
	TSTR_REGIONINFO_D,
	TSTR_REGIONINFO_C,
	TSTR_REGIONINFO_B,
	TSTR_REGIONINFO_BATTLE,
	TSTR_REGIONINFO_NORMAL,
	TSTR_TKEY_BACK,
	TSTR_TKEY_LEFT,
	TSTR_TKEY_RIGHT,
	TSTR_TKEY_LSIDEE,
	TSTR_TKEY_RSIDE,
	TSTR_TKEY_JUMP,
	TSTR_TKEY_AUTORUN,
	TSTR_TKEY_RUN,
	TSTR_TKEY_CAM_LEFT,
	TSTR_TKEY_CAM_RIGHT,
	TSTR_TKEY_CAM_UP,
	TSTR_TKEY_CAM_DOWN,
	TSTR_TKEY_ZOOM_IN,
	TSTR_TKEY_ZOOM_OUT,
	TSTR_TKEY_PICK_NEXT,
	TSTR_TKEY_SKILL_1,
	TSTR_TKEY_SKILL_2,
	TSTR_TKEY_SKILL_3,
	TSTR_TKEY_SKILL_4,
	TSTR_TKEY_SKILL_5,
	TSTR_TKEY_SKILL_6,
	TSTR_TKEY_SKILL_7,
	TSTR_TKEY_SKILL_8,
	TSTR_TKEY_SKILL_9,
	TSTR_TKEY_SKILL_10,
	TSTR_TKEY_SKILL_11,
	TSTR_TKEY_SKILL_12,
	TSTR_TKEY_CHAT,
	TSTR_TKEY_INVEN,
	TSTR_TKEY_CHAR_INFO,
	TSTR_TKEY_MODE,
	TSTR_TKEY_RECALL_BACK,
	TSTR_TKEY_RECALL_STAY,
	TSTR_TKEY_RECALL_SKILL_1,
	TSTR_TKEY_RECALL_SKILL_2,
	TSTR_TKEY_RECALL_SKILL_3,
	TSTR_TKEY_RECALL_SKILL_4,
	TSTR_TKEY_RECALL_ACTIVE,
	TSTR_TKEY_RECALL_PASSIVE,
	TSTR_TKEY_RECALL_MANUAL,
	TSTR_TKEY_TRSCS_ME,
	TSTR_TKEY_TRSCS_F1,
	TSTR_TKEY_TRSCS_F2,
	TSTR_TKEY_TRSCS_F3,
	TSTR_TKEY_TRSCS_F4,
	TSTR_TKEY_TRSCS_F5,
	TSTR_TKEY_TRSCS_F6,
	TSTR_TKEY_TRSCS_F7,
	TSTR_TKEY_HOTKEY_F1,
	TSTR_TKEY_HOTKEY_F2,
	TSTR_TKEY_HOTKEY_F3,
	TSTR_TKEY_HOTKEY_F4,
	TSTR_TKEY_HOTKEY_F5,
	TSTR_TKEY_HOTKEY_F6,
	TSTR_TKEY_HOTKEY_F7,
	TSTR_TKEY_HOTKEY_F8,
	TSTR_TKEY_HOTKEY_F9,
	TSTR_TKEY_HOTKEY_F10,
	TSTR_TKEY_HOTKEY_PREV,
	TSTR_TKEY_HOTKEY_NEXT,
	TSTR_TKEY_HOTKEY_ACTION,
	TSTR_TKEY_CLOSE_UI,
	TSTR_TKEY_WORLDMAP,
	TSTR_TKEY_SKILL_INFO,
	TSTR_TKEY_QUEST_INFO,
	TSTR_TKEY_GET_ALL,
	TSTR_TKEY_SHOW_UI,
	TSTR_TKEY_SCRCAP,
	TSTR_TKEY_HUD,
	TSTR_TKEY_FOLLOW,
	TSTR_VK_LBUTTON,
	TSTR_VK_RBUTTON,
	TSTR_VK_CANCEL,
	TSTR_VK_MBUTTON,
	TSTR_VK_BACK,
	TSTR_VK_TAB,
	TSTR_VK_CLEAR,
	TSTR_VK_RETURN,
	TSTR_VK_SHIFT,
	TSTR_VK_MENU,
	TSTR_VK_PAUSE,
	TSTR_VK_ESCAPE,
	TSTR_VK_SPACE,
	TSTR_VK_END,
	TSTR_VK_HOME,
	TSTR_VK_LEFT,
	TSTR_VK_UP,
	TSTR_VK_RIGHT,
	TSTR_VK_DOWN,
	TSTR_VK_INSERT,
	TSTR_VK_DELETE,
	TSTR_VK_NUMPAD0,
	TSTR_VK_NUMPAD1,
	TSTR_VK_NUMPAD2,
	TSTR_VK_NUMPAD3,
	TSTR_VK_NUMPAD4,
	TSTR_VK_NUMPAD5,
	TSTR_VK_NUMPAD6,
	TSTR_VK_NUMPAD7,
	TSTR_VK_NUMPAD8,
	TSTR_VK_NUMPAD9,
	TSTR_VK_MULTIPLY,
	TSTR_VK_ADD,
	TSTR_VK_SEPARATOR,
	TSTR_VK_SUBTRACT,
	TSTR_VK_DECIMAL,
	TSTR_VK_DIVIDE,
	TSTR_VK_F1,
	TSTR_VK_F2,
	TSTR_VK_F3,
	TSTR_VK_F4,
	TSTR_VK_F5,
	TSTR_VK_F6,
	TSTR_VK_F7,
	TSTR_VK_F8,
	TSTR_VK_F9,
	TSTR_VK_F10,
	TSTR_VK_F11,
	TSTR_VK_F12,
	TSTR_VK_NUMLOCK,
	TSTR_VK_SCROLL,
	TSTR_VK_LSHIFT,
	TSTR_VK_RSHIFT,
	TSTR_VK_A,
	TSTR_VK_B,
	TSTR_VK_C,
	TSTR_VK_D,
	TSTR_VK_E,
	TSTR_VK_F,
	TSTR_VK_G,
	TSTR_VK_H,
	TSTR_VK_I,
	TSTR_VK_J,
	TSTR_VK_K,
	TSTR_VK_L,
	TSTR_VK_M,
	TSTR_VK_N,
	TSTR_VK_O,
	TSTR_VK_P,
	TSTR_VK_Q,
	TSTR_VK_R,
	TSTR_VK_S,
	TSTR_VK_T,
	TSTR_VK_U,
	TSTR_VK_V,
	TSTR_VK_W,
	TSTR_VK_X,
	TSTR_VK_Y,
	TSTR_VK_Z,
	TSTR_VK_0,
	TSTR_VK_1,
	TSTR_VK_2,
	TSTR_VK_3,
	TSTR_VK_4,
	TSTR_VK_5,
	TSTR_VK_6,
	TSTR_VK_7,
	TSTR_VK_8,
	TSTR_VK_9,
	TSTR_VK_CONTROL,
	TSTR_KEY_CANNOTUSE,
	TSTR_MENU_DUEL,
	TSTR_VK_OEM_1,
	TSTR_VK_OEM_2,
	TSTR_VK_OEM_3,
	TSTR_VK_OEM_4,
	TSTR_VK_OEM_5,
	TSTR_VK_OEM_6,
	TSTR_VK_OEM_PLUS,
	TSTR_VK_OEM_COMMA,
	TSTR_VK_OEM_MINUS,
	TSTR_VK_OEM_PERIOD,
	TSTR_KEYRT_NONE,
	TSTR_KEYRT_SUCCESS,
	TSTR_KEYRT_WAITINPUT,
	TSTR_KEYRT_CANNOTUSE,
	TSTR_KEYRT_REPLACE,
	TSTR_DUELINVITE_MSG,
	TSTR_DUEL_START,
	TSTR_DUEL_REFUSE,
	TSTR_DUEL_ERROR,
	TSTR_DUEL_WIN,
	TSTR_DUEL_LOSE,
	TSTR_DUEL_AREAOUT,
	TSTR_DUEL_DRAW,
	TSTR_CMD_GUILD_DISUBMASTER,
	TSTR_DUEL_WAIT,
	TSTR_DUEL_TIMEOUT_MIN,
	TSTR_DUEL_TIMEOUT_SEC,
	TSTR_TKEY_PICK_NEXT_DEAD,
	TSTR_ERR_ITEM_INTERNAL,
	TSTR_ERR_SND_TARGET,
	TSTR_SMS_SUCCESS,
	TSTR_SMS_TXTLEN,
	TSTR_SMS_SEND,
	TSTR_ERR_NO_GUILD,
	TSTR_ERR_TARGET_BUSY,
	TSTR_TKEY_WHISPER_REPLY,
	TSTR_FMT_SMSTITLE,
	TSTR_FMT_SMSWARN,
	TSTR_CHATCMD_ERROR,
	TSTR_FMT_NUMPERCENT,
	TSTR_TACKIND_FREELANCE,
	TSTR_FMT_TACTICSCOUNTTXT,
	TSTR_ERR_NOTENOUGHDNEXP,
	TSTR_FMT_NUMPERNUM,
	TSTR_WRAN_DONATE_EXP,
	TSTR_WRAN_DONATE_MONEY,
	TSTR_DONERR_NOTENOUGH_EXP,
	TSTR_DONERR_MAXGUILDLEVEL,
	TSTR_DONERR_UNKNOWN,
	TSTR_DONATION_SUCCESS,
	TSTR_DONERR_NOTENOUGH_MONEY,
	TSTR_NEW_NOTIFY,
	TSTR_MODIFY,
	TSTR_FMT_TIME_ONEHOUR,
	TSTR_FMT_PCROOM,
	TSTR_FMT_TIME_ONEMINUTE,
	TSTR_FMT_PCROOM_1,
	TSTR_FMT_PCROOM_2,
	TSTR_FMT_PCROOM_3,
	TSTR_FMT_PCROOM_4,
	TSTR_ERROR_ITEM_CANTDROP,
	TSTR_FMT_GUILDMARKREG_SUCC,
	TSTR_FMT_GUILDMARKREG_FAIL,
	TSTR_FMT_TYPE,
	TSTR_GINV_APP,
	TSTR_FMT_GUILDMEMBER,
	TSTR_FMT_TACTICS,
	TSTR_GINV_EDIT,
	TSTR_GINV_NEW,
	TSTR_GINV_DEL,
	TSTR_GERR_GUILDWANTEDWORK,
	TSTR_GSEEK_INV,
	TSTR_ERR_GUILDAPPLICATIONADD,
	TSTR_GSEEK_EDIT,
	TSTR_GSEEK_NEW,
	TSTR_GSEEK_DEL,
	TSTR_FMT_GUILDSEEKER,
	TSTR_ERR_GUILDWANTEDADD,
	TSTR_CMDESC_GUILD_INVITE,
	TSTR_CMDESC_GUILD_OUT,
	TSTR_CMDESC_GUILD_KICK,
	TSTR_CMDESC_GUILD_DISORG,
	TSTR_CMDESC_GUILD_DISORGCANCEL,
	TSTR_CMDESC_GUILD_MASTER,
	TSTR_CMDESC_GUILD_SUBMASTER,
	TSTR_CMDESC_GUILD_PEER_CANCEL,
	TSTR_CMDESC_GUILD_BARON,
	TSTR_CMDESC_GUILD_VISCOUNT,
	TSTR_CMDESC_GUILD_COUNT,
	TSTR_CMDESC_GUILD_MARQUIS,
	TSTR_CMDESC_GUILD_DUKE,
	TSTR_CMDESC_GUILD_DISUBMASTER,
	TSTR_FMT_GUILDCMD,
	TSTR_FMT_GUILDCMDESC,
	TSTR_GERR_GUILDOFFERDUPL,
	TSTR_GERR_GUILDSEEKDUPL,
	TSTR_DELETE,
	TSTR_GMP_WHISPER,
	TSTR_GMP_MAIL,
	TSTR_GMP_KICK,
	TSTR_GMP_ET_GM,
	TSTR_GMP_SET_GSM,
	TSTR_GMP_CANCEL_GSM,
	TSTR_GMP_PEER_BARON,
	TSTR_GMP_PEER_VISCOUNT,
	TSTR_GMP_PEER_COUNT,
	TSTR_GMP_PEER_MARQUIS,
	TSTR_GMP_PEER_DUKE,
	TSTR_GMP_CANCEL_PEER,
	TSTR_GMP_CANCEL,
	TSTR_GMP_DISORG_TACTICS,
	TSTR_GUILD_CABINET_FULL,
	TSTR_GUILD_CABINET_PUTINFAIL,
	TSTR_GUILD_CABINET_ITEMNOTFOUND,
	TSTR_GUILD_CABINET_INVENFULL,
	TSTR_GUILD_CABINET_TAKEOUTFAIL,
	TSTR_GUILD_CABINET_LEVEL,
	TSTR_GUILD_CABINET_TITLE,
	TSTR_GUILD_CABINET_NOTDUTY,
	TSTR_ITEMUP_MONEYFAIL,
	TSTR_SKILLINITERR_TRADING,
	TSTR_WARN_SKILLINIT_ALL,
	TSTR_WARN_SKILLINIT_ONE,
	TSTR_SKILLINIT_ONE_SUCCESS,
	TSTR_SKILLINIT_FAIL,
	TSTR_SKILLINIT_ALL_SUCCESS,
	TSTR_GUILDVOLUNTEERING_SUCC,
	TSTR_GUILDVOLUNTEERING_HAVEGUILD,
	TSTR_GUILDVOLUNTEERING_FAIL,
	TSTR_FILE_QUESTITEM,
	TSTR_GVP_WHISPER,
	TSTR_GVP_MAIL,
	TSTR_GVP_INVITE_YES,
	TSTR_GVP_INVITE_NO,
	TSTR_GVP_CANCEL,
	TSTR_WARN_GUILDKICKOUT,
	TSTR_FMT_LUCKNUMBER,
	TSTR_CMD_SHOW_GUILDAPPDLG,
	TSTR_CMDESC_SHOW_GUILDAPPDLG,
	TSTR_TKEY_TOGGLE_GUILD_UI,
	TSTR_TKEY_TOGGLE_MENU_UI,
	TSTR_MBOX_GUILD_PEERMAX,
	TSTR_EXE_PRMPC_URL,
	TSTR_FMT_NOTITLE,
	TSTR_GET_ITEM,
	TSTR_FMT_CASH,
	TSTR_FMT_CASHNBONUS,
	TSTR_MENU_PARTYMEMBERRECALL,
	TSTR_IU_SUCCESS,
	TSTR_ERR_IU_RIDING,
	TSTR_ERR_IU_DEALING,
	TSTR_ERR_IU_NOTFOUND,
	TSTR_ERR_IU_BUSY,
	TSTR_URL_CASHCHARGE,
	TSTR_CASHITEMBUY_SUCCESS,
	TSTR_ERR_DOSKILLDISGUISE,
	TSTR_ERR_NEED_CASH,
	TSTR_MENU_END_MAINTAIN,
	TSTR_SOULMATEBOX_SELREG,
	TSTR_SOULMATEBOX_NAME,
	TSTR_SOULMATEBOX_SEARCH,
	TSTR_SOULMATEBOX_NO,
	TSTR_SOULMATEBOX_REG,
	TSTR_ERR_SOULMATE_SILENCE,
	TSTR_ERR_SOULMATE_NEEDMONEY,
	TSTR_ERR_SOULMATE_FAIL,
	TSTR_ERR_SOULMATE_NOTFOUND,
	TSTR_SOULMATE_REG_SUCCESS,
	TSTR_SOULMATE_SEARCH_SUCCESS,
	TSTR_ITRF_ERR_DUPLICATE,
	TSTR_DETMSG_SEALEDITEM,
	TSTR_SOULMATEEND_SUCCESS,
	TSTR_SOULMATE_MARK,
	TSTR_GAMBLE_NO,
	TSTR_GAMBLE_ASK,
	TSTR_GAMBLE_SUCC,
	TSTR_GAMBLE_FAIL_NEEDMONEY,
	TSTR_GAMBLE_FAIL_REP,
	TSTR_GAMBLE_FAIL_OCC,
	TSTR_GAMBLE_FAIL,
	TSTR_GAMBLE_CHECK_FAIL,
	TSTR_FMT_ITEMMAGIC_TITLE,
	TSTR_FMT_ITEMATTRLEVEL_0,
	TSTR_FMT_ITEMATTRLEVEL_1,
	TSTR_FMT_ITEMATTRLEVEL_2,
	TSTR_FMT_ITEMATTRLEVEL_3,
	TSTR_FMT_ITEMATTRLEVEL_4,
	TSTR_FMT_ITEMATTRLEVEL_5,
	TSTR_FMT_ITEMATTRLEVEL_6,
	TSTR_FMT_ITEMATTRLEVEL_7,
	TSTR_FMT_ITEMATTRLEVEL_8,
	TSTR_FMT_ITEMATTRLEVEL_9,
	TSTR_FMT_ITEMATTRLEVEL_10,
	TSTR_FMT_ITEMATTRLEVEL_11,
	TSTR_FMT_ITEMATTRLEVEL_12,
	TSTR_FMT_HEIGHTFILE,
	TSTR_MBOX_TACTICS_INVITE,
	TSTR_MBOX_TACTICS_MONEY_INVITE,
	TSTR_USEITEM_REVIVAL,
	TSTR_IU_ERR_OVERLAPPREMIUM,
	TSTR_CASHITEMPRESENT_SUCCESS,
	TSTR_ERR_IU_TARGETNOTFOUND,
	TSTR_ERR_MOVETO,
	TSTR_WORLDUNIFY_URL,
	TSTR_USEITEM_MEMBERRECALL,
	TSTR_MEMBERRECALL_INVALIDTARGET,
	TSTR_USEITEM_MOVETOCHAR,
	TSTR_CHAR_NAME,
	TSTR_FMT_TIME_ONEDAY,
	TSTR_FMT_PRESENTITEM,
	TSTR_NEEDWORLDUNIFY,
	TSTR_FILE_AGREEMENT,
	TSTR_ERR_NOTARGET_CASH,
	TSTR_FMT_PARTYMEMBERRECALLANS,
	TSTR_FMT_DURATIONEND,
	TSTR_DURATIONREP_COST,
	TSTR_SOULMATESEARCH_TITLE,
	TSTR_SOULMATESEARCH_MSG,
	TSTR_DURATIONREP_SUCC,
	TSTR_ERR_DURATIONREP_FAIL,
	TSTR_ERR_DURATIONREP_NOTNEED,
	TSTR_ERR_DURATIONREP_NOMONEY,
	TSTR_REFINE_COST,
	TSTR_DURATIONREPAIRING_TITLE,
	TSTR_DURATIONREPAIRING_MSG,
	TSTR_REFINING_TITLE,
	TSTR_REFINING_MSG,
	TSTR_REFINE_SUCC,
	TSTR_REFINE_FAIL,
	TSTR_ERR_DURATIONREP_DISALLOW,
	TSTR_ERR_REFINE_NOMONEY,
	TSTR_ERR_REFINE_MAXREFINE,
	TSTR_ERR_REFINE_LEVELDIFF,
	TSTR_ERR_REFINE_FAIL,
	TSTR_FILE_ITEMVISUALCHART,
	TSTR_FILE_ITEMGRADESFXCHART,
	TSTR_FILE_ITEMMAGICSFXCHART,
	TSTR_ITEMREP_ERR_NOTNEED,
	TSTR_ITEMREP_ERR_CANNOT,
	TSTR_ITRF_ERR_CANNOTREFINE,
	TSTR_ITRF_ERR_MAXREFINE,
	TSTR_FILE_SKILLPOINT,
	TSTR_FILE_TFORMULA,
	TSTR_FORMAT_HOUR,
	TSTR_FORMAT_MIN,
	TSTR_FORMAT_FSEC,
	TSTR_FMT_LEVELB,
	TSTR_ITEMGAMBLE_ERR,
	TSTR_TKEY_SKILL2_1,
	TSTR_TKEY_SKILL2_2,
	TSTR_TKEY_SKILL2_3,
	TSTR_TKEY_SKILL2_4,
	TSTR_TKEY_SKILL2_5,
	TSTR_TKEY_SKILL2_6,
	TSTR_TKEY_SKILL2_7,
	TSTR_TKEY_SKILL2_8,
	TSTR_TKEY_SKILL2_9,
	TSTR_TKEY_SKILL2_10,
	TSTR_TKEY_SKILL2_11,
	TSTR_TKEY_SKILL2_12,
	TSTR_TKEY_VERSION,
	TSTR_MENU_CHAT_LOCK,
	TSTR_FCEVENT_D,
	TSTR_FCEVENT_C,
	TSTR_ERR_CASHSHOP_NOTARGET,
	TSTR_ERR_CASHSHOP_NOCASHINFO,
	TSTR_ITEM_CANNOT_CABINET,
	TSTR_FILE_JOINTCHART,
	TSTR_FILE_GRADEVISUALCHART,
	TSTR_FMT_BUYITEM_AS_PRICE,
	TSTR_REFINE_COST_SALE,
	TSTR_TKEY_CHAR_ROT180,
	TSTR_DURATIONREP_COST_SALE,
	TSTR_GAMBLE_ASK_SALE,
	TSTR_SHOPTITLE_ITEM_SALE,
	TSTR_SHOPTITLE_PORTAL_SALE,
	TSTR_SKILLNEXTPRICE_SALE,
	TSTR_CHANGE_NAME,
	TSTR_PERIOD_EXTENSION,
	TSTR_PRESENT,
	TSTR_FMT_EXTEND_PERIOD,
	TSTR_FMT_EXTPERIOD,
	TSTR_FMT_DAYS,
	TSTR_ISNT_EXTPERIOD_ITEM,
	TSTR_ITEM_NAME_PERIOD,
	TSTR_EXTENDED_PERIOD,
	TSTR_ERR_EXTEND_PERIOD_FAIL,
	TSTR_CHANGECHARBASE_FAIL,
	TSTR_TKEY_CAM_ROT180,
	TSTR_SM_BATTLE_NORMAL,
	TSTR_SM_BATTLE_START,
	TSTR_SM_BATTLE_START_ALARM,
	TSTR_SM_BATTLE_END_ALARM,
	TSTR_SM_BATTLE_PEACE,
	TSTR_SM_BATTLE_OPENGATE,
	TSTR_SM_BATTLE_BOSSDIE,
	TSTR_SM_DUAL_WIN,
	TSTR_SM_EVENT_QUARTER,
	TSTR_SM_CHAT_BAN,
	TSTR_SM_BATTLE_END_ALARM_SEC,
	TSTR_SM_BATTLE_START_ALARM_SEC,
	TSTR_SM_CHAT_BAN_SEC,
	TSTR_PETKIND_ONE_CONTRACT,
	TSTR_PETKIND_TWO_CONTRACT,
	TSTR_PETKIND_TELE_CONTRACT,
	TSTR_PETKIND_INVEN_CONTRACT,
	TSTR_PETKIND_EXP_CONTRACT,
	TSTR_PETCON_LEVEL_CONTRACT,
	TSTR_FMT_PET_EXTPERIOD,
	TSTR_FMT_PET_PERIOD_FIRED,
	TSTR_MENU_PET,
	TSTR_TKEY_PET_INFO,
	TSTR_OPENMONEY,
	TSTR_GUILD_JOB,
	TSTR_GUILD_LEVEL,
	TSTR_GUILD_CONTRIBUTION,
	TSTR_CASHCABINET_PUTIN_PR,
	TSTR_CASHCABINET_PUTIN,
	TSTR_CASHCABINET_REMAIN_COUNT,
	TSTR_CASHCABINET_REMAIN_COUNT_ON_PR,
	TSTR_GUILD_RANK,
	TSTR_GUILD_PEERAGE,
	TSTR_GUILD_NOWPOS,
	TSTR_GUILD_EARNESTMONEY,
	TSTR_GUILD_JOININGYESORNO,
	TSTR_GUILD_APPDAY,
	TSTR_GUILD_APPTYPE,
	TSTR_GUILD_OCCUPATIONGUILD,
	TSTR_GUILD_BELONGNATION,
	TSTR_GUILD_CASTLE,
	TSTR_GUILD_VILLAGE,
	TSTR_FMT_LEVEL_IN_LOBY,
	TSTR_FMT_RESOLUTION,
	TSTR_MY_POS,
	TSTR_CURSOR_POS,
	TSTR_FMT_TERRITORYTIME,
	TSTR_FMT_HERO,
	TSTR_DONTHAVEINITSKILL,
	TSTR_TEST,
	TSTR_FMT_WHISPER,
	TSTR_BUGREPORTER_TITLE,
	TSTR_BUGREPORTER_MESSAGE,
	TSTR_BUGREPORTER_CONTENTS,
	TSTR_BUGREPORTER_MESSAGE2,
	TSTR_BUGREPORTER_BTN_OK,
	TSTR_BUGREPORTER_BTN_CLOSE,
	TSTR_DIRECT_DELCHAR_MSG,
	TSTR_CONNET_RETRY,
	TSTR_VK_OEM_7,
	TSTR_FAILED_STOREOPEN,
	TSTR_CANTUSEINPLACE,
	TSTR_FILE_THELPCHART,
	TSTR_FILE_THELPLINKCHART,
	TSTR_IU_OVERLAPEXPBONUS,
	TSTR_FILE_TNPCGLOBAL,
	TSTR_URL_CASHCHARGE_CH1,
	TSTR_DEF_ID,
	TSTR_TKEY_HELP,
	TSTR_POST_SAMEACCOUNT,
	TSTR_MENU_WHISPER,
	TSTR_KEYWORD_CHAT_TITLE,
	TSTR_MENU_COPYNAME,
	TSTR_MENU_PASTENAME,
	TSTR_CRAFT_TITLE,
	TSTR_CRAFT_MSG,
	TSTR_NOINPUT_LIMITATION,
	TSTR_SHOPTITLE_RENT,
	TSTR_SHOPHELP_RENT,
	TSTR_FMT_BUYITEM_STACK,
	TSTR_FMT_PET_EXTPERIOD_HOUR_MIN,
	TSTR_FMT_PET_EXTPERIOD_MIN,
	TSTR_FMT_PET_USETIME_HOUR,
	TSTR_GMP_POINT_REWARD,
	TSTR_PVPE_KILL_H_WIN,
	TSTR_PVPE_KILL_H_LOSE,
	TSTR_PVPE_KILL_E_WIN,
	TSTR_PVPE_KILL_E_LOSE,
	TSTR_PVPE_KILL_L_WIN,
	TSTR_PVPE_KILL_L_LOSE,
	TSTR_PVPE_GODMONKILL,
	TSTR_PVPE_ENTRY,
	TSTR_POINT_REWARD_CONTINUE,
	TSTR_GUILD_KILL_H,
	TSTR_GUILD_KILL_E,
	TSTR_GUILD_KILL_L,
	TSTR_GUILD_KILL_GODMON,
	TSTR_GUILD_ENTRY,
	TSTR_GUILD_SUM,
	TSTR_GUILD_SUM_KILL,
	TSTR_GUILD_SUM_DIE,
	TSTR_GUILD_REGULAR,
	TSTR_GUILD_TACTICS,
	TSTR_GUILD_LATEST_PVP,
	TSTR_GUILD_WEEK_PVP,
	TSTR_PVP_DET_WIN,
	TSTR_PVP_DET_LOSE,
	TSTR_PVP_DET_NAME,
	TSTR_PVP_DET_CLASS,
	TSTR_PVP_DET_LEVEL,
	TSTR_PVP_DET_DATE,
	TSTR_PVP_DET_POINT,
	TSTR_CHARPVP_CLASS,
	TSTR_CHARPVP_KILL,
	TSTR_CHARPVP_DIE,
	TSTR_CHARPVP_LATEST_RECORD,
	TSTR_CHARPVP_WAR_SUMMARY,
	TSTR_CHARPVP_PVP_SUMMARY,
	TSTR_CHARPVP_RANK,
	TSTR_CHARPVP_FAME,
	TSTR_CHARPVP_POFV,
	TSTR_GUILD_REWARD_NEEDPOINT,
	TSTR_GUILD_REWARD_NOMEMBER,
	TSTR_GUILD_REWWARD_INVALID,
	TSTR_CHARPVP_WIN,
	TSTR_CHARPVP_LOSE,
	TSTR_CHARPVP_TOTAL_RECORD,
	TSTR_ITEMUP_DOWNGRADE,
	TSTR_FMT_SIEGE_TIMER,
	TSTR_FMT_SIEGE_ATK,
	TSTR_FMT_SIEGE_DEF,
	TSTR_FMT_SIEGE_KEEPTIME,
	TSTR_GMP_VOLUNTEER_HESED,
	TSTR_GMP_VOLUNTEER_ARDRI,
	TSTR_GMP_VOLUNTEER_TYCON,
	TSTR_GMP_VOLUNTEER_GEHBRA,
	TSTR_GMP_VOLUNTEER_CANCEL,
	TSTR_FMT_CASTLE_ATKGUILD,
	TSTR_FMT_CASTLE_DEFGUILD,
	TSTR_PVP_DET_PLUS_POINT,
	TSTR_PVP_DET_MINUS_POINT,
	TSTR_SIEGEBALL_NONE,
	TSTR_MONBUY_SUCCESS,
	TSTR_MONBUY_INVALIDNPC,
	TSTR_MONBUY_NOTFOUND,
	TSTR_MONBUY_NEEDMONEY,
	TSTR_MONBUY_CAMPMISMATCH,
	TSTR_MONBUY_AUTHORITY,
	TSTR_MONBUY_ALREADY,
	TSTR_FMT_PVPPOINT,
	TSTR_FMT_BUYITEM_AS_PVPPOINT,
	TSTR_ITEM_NO_POINT,
	TSTR_ERROR_CANNOT_OPEN_WORLDMAP_IN_SIEGEMAP,
	TSTR_CASTLEAPPLY_FULL,
	TSTR_CASTLEAPPLY_NOTFOUND,
	TSTR_CASTLEAPPLY_NOTREADY,
	TSTR_CASTLEAPPLY_CANTAPPLY,
	TSTR_ITEMUP_ERR_DONT_HAVE_MAGIC,
	TSTR_ITEMUP_ERR_MAGICFAIL,
	TSTR_ITEMUP_WARN_CLEARMAGIC,
	TSTR_ITEMUP_SUCCESS_MAGICCLEAR,
	TSTR_HONOR,
	TSTR_MERIT,
	TSTR_FMT_CHARPVP_RANK,
	TSTR_GROUP_ETC,
	TSTR_GROUP_SOULMATE,
	TSTR_GROUP_NONAME,
	TSTR_RELEASE_SOULMATE,
	TSTR_CANT_USE_WRAPED_ITEM,
	TSTR_ALREADY_WRAP,
	TSTR_MAXELD,
	TSTR_WRAP_FOOTER,
	TSTR_ITEMCHANGE_SUCCESS,
	TSTR_ITEMCHANGE_FAIL,
	TSTR_ITEMCHANGE_INVALID,
	TSTR_ITEMCHANGE_STATUS,
	TSTR_ITEMCHANGE_FULL,
	TSTR_ITEMUP_WARN_WRAP,
	TSTR_ITEMUP_WARN_ELD,
	TSTR_ITEMUP_WRAP_SUCCESS,
	TSTR_ITEMUP_ELD_SUCCESS,
	TSTR_CANT_WRAP_ITEM,
	TSTR_ERROR_ITEM_WRAP,
	TSTR_FMT_CHAT_INFO_HEADER,
	TSTR_INSERT_BASKET,
	TSTR_ERASE_BASKET,
	TSTR_CANCEL_REG,
	TSTR_AUCTION_REGIST,
	TSTR_AUCTION_BUY,
	TSTR_AUCTION_BID,
    TSTR_TEXT_WEAPON,
    TSTR_TEXT_DEFENSIVE,
    TSTR_TEXT_ACCESSORY,
    TSTR_TEXT_1HAND,
    TSTR_TEXT_LHAND,
    TSTR_TEXT_2HAND,
    TSTR_TEXT_CAKRAM,
    TSTR_TEXT_AX,
    TSTR_TEXT_BOW,
    TSTR_TEXT_ARBALEST,
    TSTR_TEXT_MBAR,
    TSTR_TEXT_MSTICK,
    TSTR_TEXT_VAJRA,
    TSTR_TEXT_MULTIVAJRA,
    TSTR_TEXT_SHIELD,
    TSTR_TEXT_CLOTH,
    TSTR_TEXT_UNIFORM,
    TSTR_TEXT_LLEATHER,
    TSTR_TEXT_HLEATHER,
    TSTR_TEXT_LARMOR,
    TSTR_TEXT_HARMOR,
    TSTR_TEXT_EXPENDNETC,
	TSTR_FMT_AMOUNT,
	TSTR_CHANNEL,
	TSTR_ITEMUP_WARN_UP_NOTUSE_CASHITEM_MESSAGE_1,
	TSTR_ITEMUP_WARN_UP_NOTUSE_POTIONOFFORTUNE,
	TSTR_ITEMUP_WARN_UP_NOTUSE_PROTECTIONOFUPGRADING,
	TSTR_ITEMUP_WARN_UP_NOTUSE_CASHITEM_MESSAGE_2,
	TSTR_ITEMUP_WARN_MAGIC_NOTUSE_CASHITEM_MESSAGE_1,
	TSTR_ITEMUP_WARN_MAGIC_NOTUSE_LEGENDENCHARTBOOK,
	TSTR_ITEMUP_WARN_MAGIC_NOTUSE_CASHITEM_MESSAGE_2,
	TSTR_ITEMUP_WARN_RARE_NOTUSE_CASHITEM_MESSAGE_1,
	TSTR_ITEMUP_WARN_RARE_NOTUSE_CASHITEM_MESSAGE_2,
	TSTR_ITEMUP_WARN_REFINE_NOTUSE_CASHITEM_MESSAGE_1,
	TSTR_ITEMUP_WARN_REFINE_SALE_NOTUSE_CASHITEM_MESSAGE_1,
	TSTR_ITEMUP_WARN_RARE_NOTUSE_LEGENDREFINEBOOK,
	TSTR_ITEMUP_WARN_RARE_NOTUSE_MAGICTRANSFERSPELL,
	TSTR_ITEMUP_WARN_REFINE_NOTUSE_CASHITEM_MESSAGE_2,
	TSTR_WARN_UPITEM_SELL,
	TSTR_WARN_UPITEM_DROP,
	TSTR_WARN_UPITEM_SELL_DIFFERENT_ID,
	TSTR_FMT_CHECK_PRESENTCASHITEM,
	TSTR_MENU_BLOCK,
	TSTR_MENU_UNBLOCK,
	TSTR_MAILMSG_PRESENTCASHITEM,
	TSTR_SENDMSG_PRESENTCASHITEM,
	TSTR_GMP_PARTY,
	TSTR_GMP_FRIEND,
	TSTR_ITEMUP_WARN_NOTUSE_PROTECTIONOFUPGRADING,
	TSTR_ITEMUP_SUCCESS_CLEARREFINE,
	TSTR_ITEMUP_ERR_NOREFINE,
	TSTR_ITEMUP_WARN_CLEARREFINE,
	TSTR_ITEMUP_SUCCESS_CHANGEEFFECT,
	TSTR_ITEMUP_ERR_UNDER17,
	TSTR_ITEMUP_WARN_CHANGEEFFECT,
	TSTR_WARN_CHANGE_REFINE,
	TSTR_WASTEREFINE_SUCCESS,
	TSTR_WASTEREFINE_NOTFOUND,
	TSTR_WASTEREFINE_NOREFINE,
	TSTR_ERROR_CORPS_MAX,
	TSTR_SM_BATTLE_BOSSDIE_NULL,
	TSTR_GVFPM_MAIL,
	TSTR_GVFPM_REGULAR_ACCEPT,
	TSTR_GVFPM_REGULAR_REJECT,
	TSTR_GVFPM_TACTICS_ACCEPT,
	TSTR_GVFPM_TACTICS_REJECT,
	TSTR_GVFPM_CLOSE,
	TSTR_TITLE_MONSHOP,
	TSTR_WARN_UPITEM_SELL_SECURITYCODE,
	TSTR_WARN_UPITEM_DROP_SECURITYCODE,
	TSTR_WARN_UPITEM_SECURITYCODE,
	TSTR_WARN_UPITEM_SELL_DIFFERENT_SECURITYCODE,
	TSTR_GMP_TACTICS_RE_CONTRACT,	
	TSTR_GMP_TACTICS_KICK,				
	TSTR_GMP_TACTICS_REWARD_POINT,
	TSTR_GUILDOFFER_COL_GUILDNAME,
	TSTR_GUILDOFFER_COL_TITLE,
	TSTR_GUILDOFFER_COL_LEVEL,
	TSTR_GUILDOFFER_COL_TIME,
	TSTR_GUILDOFFER_COL_STATE,
	TSTR_GUILDOFFER_COL_BENEFIT,
	TSTR_GUILDOFFER_COL_EARNEST_MONEY,
	TSTR_GUILDOFFER_COL_EARNEST_PERIOD,
	TSTR_GUILDOFFER_APPLYED,
	TSTR_GUILDOFFEREDIT_MODIFY,
	TSTR_GUILDOFFEREDIT_OK,
	TSTR_GUILDOFFEREDIT_WRITE,
	TSTR_FMT_PARTY_COUNTRY,
	TSTR_ERROR_LOADMPC,
	TSTR_ERROR_HACKTOOL_FOUND,
	TSTR_ERROR_HACKTOOL_WARN,
	TSTR_AUCTION_NEED_STARTPRICE,
	TSTR_AUCTION_BIDPRICE_OVER,
	TSTR_AUCTIONLIST_NPCNOTFOUND,
	TSTR_AUCTIONLIST_NOLIST,
	TSTR_AUCTIONLIST_NOPAGE,
	TSTR_AUCTIONLIST_FAIL,
	TSTR_AUCTIONBID_SUCCESS,
	TSTR_AUCTIONBID_FAIL,
	TSTR_AUCTION_NPCNOTFOUND,
	TSTR_AUCTIONBID_ITEMNOTFOUND,
	TSTR_AUCTIONBID_SELF,
	TSTR_AUCTIONBID_LOWPRICE,
	TSTR_AUCTIONBID_NEEDMONEY,
	TSTR_AUCTIONBID_COUNTERROR,
	TSTR_AUCTIONBID_DUPLICATE,
	TSTR_AUCTIONBID_INVALIDCHAR,
	TSTR_AUCTIONBUY_SUCCESS,
	TSTR_AUCTIONBUY_FAIL,
	TSTR_AUCTIONBUY_ITEMNOTFOUND,
	TSTR_AUCTIONBUY_DROP,
	TSTR_AUCTIONBUY_NEEDMONEY,
	TSTR_AUCTIONBUY_COUNTERROR,
	TSTR_AUCTIONREG_FAIL,
	TSTR_AUCTIONREG_INVALIDCHAR,
	TSTR_AUCTIONREG_INVALIDPRICE,
	TSTR_AUCTIONREG_INVALIDSTARTPRICE,
	TSTR_AUCTIONREG_ITEMNOTFOUND,
	TSTR_AUCTIONREG_INVALIDITEM,
	TSTR_AUCTIONREG_INVALIDAUCTION,
	TSTR_AUCTIONREGCANCEL_FAIL,
	TSTR_AUCTIONREGCANCEL_ITEMNOTFOUND,
	TSTR_AUCTIONREGCANCEL_INVALIDITEM,
	TSTR_AUCTIONREGCANCEL_INVALIDAUCTION,
	TSTR_AUCTIONREGCANCEL_ASK,
	TSTR_AUCTIONERROR_NAMESEARCH,
	TSTR_AUCTIONBASKET_ADD,
	TSTR_AUCTIONBASKET_ADDFAIL,
	TSTR_AUCTIONBASKET_DELETE,
	TSTR_AUCTIONBASKET_DELETEFAIL,
	TSTR_AUCTIONREG_TEXTSTARTPRICE,
	TSTR_AUCTIONREG_TEXTBUYPRICE,
	TSTR_AUCTIONREG_TEXTUNITPRICE,
	TSTR_AUCTIONREG_TEXTTOTALPRICE,
	TSTR_AUCTIONMSG_NONE_DELITEM,
	TSTR_AUCTIONMSG_NONE_BIDITEM,
	TSTR_AUCTIONMSG_NONE_BUYITEM,
	TSTR_AUCTIONMSG_ALREADYINBASKET,
	TSTR_FMT_AUCTIONREG_ASK,
	TSTR_AUCTIONMSG_NONE_REGITEM,
	TSTR_AUCTIONBASKET_NONE_DELTITEM,
	TSTR_AUCTIONBASKET_NONE_ADDITEM,
	TSTR_KICKOUTMAP_BECAUSE_LEVELLIMIT,
	TSTR_NOTIFY_KICKOUTMAP,
	TSTR_AUCTIONLIST_HEAD_NAME,
	TSTR_AUCTIONBUY_ASK_OVERPRICE,
	TSTR_AUCTIONREG_NEEDMONEY,
	TSTR_GUILD_INVITATION_FINISH,
	TSTR_GUILD_INVITATION_ING,
	TSTR_GUILD_WAR_CONTRIBUTION,
	TSTR_GUILD_REWARD_POINT,
	TSTR_GUILD_REGULAR_VOL,
	TSTR_GUILD_TACTICS_VOL,
	TSTR_GUILD_OFFER_BBS_DELETE_WARN,
	TSTR_CHAT_TACTICS,
	TSTR_KEYWORD_CHAT_TACTICS,
	TSTR_REPRESENTATION_TACTICS,
	TSTR_GUILD_MAXWANTED,
	TSTR_GUILD_MISMATCHLEVEL,
	TSTR_GUILD_SAMEGUILDTACTICS,
	TSTR_GUILD_MEMBER_FULL,
	TSTR_GUILD_NOMONEY,
	TSTR_GUILD_NOPOINT,
	TSTR_GUILD_PEER_TACTICS,
	TSTR_GUILD_TACTICSREPLY_SUCCESS,
	TSTR_GUILD_ALREADY_TACTICS,
	TSTR_GUILD_ENDTIME,
	TSTR_MENU_TACTICS_REQ,
	TSTR_MBOX_TACTICS_INVITE_COND,
	TSTR_MBOX_TACTICS_REINVITE_COND,
	TSTR_MBOX_TACTICS_TITLE_INVITE,
	TSTR_MBOX_TACTICS_TITLE_REINVITE,
	TSTR_MBOX_TACTICS_TITLE_ACCEPT,
	TSTR_TACTICS_WORD_INVITE,
	TSTR_TACTICS_WORD_CANCEL,
	TSTR_TACTICS_WORD_REINVITE,
	TSTR_TACTICS_WORD_ACCEPT,
	TSTR_TACTICS_WORD_REJECT,
	TSTR_GUILD_WANTEDEND,
	TSTR_GUILD_VOLUNTEERING_FAIL,
	TSTR_GUILD_TACTICS_REJECT,
	TSTR_GUILD_TACTICS_BUSY,
	TSTR_GUILD_TACTICS_ACCEPT,
	TSTR_FMT_CASTLE_MYGUILD,
	TSTR_SM_CASTLE_NORMAL,
	TSTR_SM_CASTLE_START,
	TSTR_SM_CASTLE_START_ALARM_MIN,
	TSTR_SM_CASTLE_START_ALARM_SEC,
	TSTR_SM_CASTLE_END_ALARM_MIN,
	TSTR_SM_CASTLE_END_ALARM_SEC,
	TSTR_SM_CASTLE_PEACE,
	TSTR_GUILD_VOL_SUCCESS,
	TSTR_GUILD_AREADYAPPLY,
	TSTR_GUILD_NOT_ONLINE,
	TSTR_GUILD_SM_CASTLE_END,
	TSTR_GUILD_ONLY_MASTER,
	TSTR_GUILD_MAX_WEEK,
	TSTR_GUILD_NOT_OWN_WANTED,
	TSTR_GUILD_NOTDUTY_WANTED_ADD_DEL,
	TSTR_GUILD_SAME,
	TSTR_GUILD_SAMEGUILDTACTICS2,
	TSTR_GUILD_SAMEGUILDTACTICS3,
	TSTR_GUILD_SAMEGUILDTACTICS4,
	TSTR_GUILD_MAX_DAYS,
	TSTR_GUILD_DO_VOLUNTEERING,
	TSTR_GUILD_DO_VOLUNTEERING_CANCEL,
	TSTR_GUILD_DO_TACTICS_VOLUNTEERING,
	TSTR_GUILD_DO_TACTICS_VOLUNTEERING_CANCEL,
	TSTR_GUILD_SELECT_WANTED,
	TSTR_GUILD_MAX_CONTRACT,
	TSTR_GUILD_WANTED_NEW,
	TSTR_GUILD_WANTED_MODIFY,
	TSTR_GUILD_WANTED_DEL,
	TSTR_GUILD_COUNTRY_POINT,
	TSTR_GUILD_GUILDPOINT,
	TSTR_GUILD_VOL_COUNT,
	TSTR_AUCTION_ARROW_UP,
	TSTR_AUCTION_ARROW_DOWN,
	TSTR_AUCTION_ARROW_UP2,
	TSTR_AUCTION_ARROW_DOWN2,
	TSTR_FMT_CASHNBONUS_FLOAT,
	TSTR_FMT_CASH_FLOAT,
	TSTR_GUILD_NOINPUT_ARTICLE_TITLE,
	TSTR_GUILD_NOINPUT_ARTICLE_CONTENTS,
	TSTR_GUILD_NOINPUT_ARTICLE_MINLEVEL,
	TSTR_GUILD_NOINPUT_ARTICLE_MAXLEVEL,
	TSTR_GUILD_NOINPUT_ARTICLE_DAY,
	TSTR_GUILD_NOINPUT_ARTICLE_POINT,
	TSTR_GUILD_NOINPUT_ARTICLE_MONEY,
	TSTR_FAMERANKDEF_NAME,
	TSTR_FAMERANKDEF_CLASS,
	TSTR_FAMERANKDEF_COUNTRY,
	TSTR_FAMERANKDEF_TOTALPOINT,
	TSTR_FAMERANKDEF_BATTLE,
	TSTR_FAMERANKDEF_LEVEL,
	TSTR_FAMERANKDEF_SAY,
	TSTR_FAMERANK_MONTH,
	TSTR_FMT_FIELDRANKNAME,
	TSTR_FMT_FIELDRANKTITLE,
	TSTR_CHARPVP_WAR_MONTH_SUMMARY,
	TSTR_CHARPVP_WAR_TOTAL_SUMMARY,
	TSTR_MENU_FAMERANK,
	TSTR_FAME_WARLORD_RANK,
	TSTR_FAME_WARLORD_FAME,
	TSTR_FAME_WARLORD_BATTLE,
	TSTR_ERR_SAY_SIZE,
	TSTR_WARLORD_SAY_MSG,
	TSTR_MONTH_FAME_LIST_TITLE,
	TSTR_FIRST_FAME_LIST_TITLE,
	TSTR_COLOR_SELECTING,
	TSTR_COLOR_RANDOM_SELECTING,
	TSTR_REGGUILDDLG_BTN_REG,
	TSTR_REGGUILDDLG_TEXT_REG,
	TSTR_REGGUILDDLG_BTN_UNREG,
	TSTR_REGGUILDDLG_TEXT_UNREG,
	TSTR_ITEMUP_SUCCESS_COLOR,
	TSTR_GUILDFAME_NO_POINT,
	TSTR_SM_ITEM_EXPIRE,
	TSTR_REGGUILDCLOAK_SUCCESS,
	TSTR_REGGUILDCLOAK_UNREG_SUCCESS,
	TSTR_ITEMUP_WARN_CHANGECOLOR,
	TSTR_ONLY_USE_GUILDMASTER,
	TSTR_REGGUILDDLG_NO_TARGET_ITEM,
	TSTR_TKEY_FAMERANK,
	TSTR_FAMERANK_LIST_MONTH_BTN1,
	TSTR_FAMERANK_LIST_MONTH_BTN2,
	TSTR_REGGUILDDLG_NO_UNREG_TARGET_ITEM,
	TSTR_NEED_JOIN_GUILD,
	TSTR_UPGRADE_TARGET_TOOLTIP,
	TSTR_UPGRADE_SCROLL_TOOLTIP,
	TSTR_REFINE_TARGET_TOOLTIP,
	TSTR_REFINE_OFFERING_TOOLTIP,
	TSTR_UPGRADE_FRAME_TOOLTIP,
	TSTR_REFINE_FRAME_TOOLTIP,
	TSTR_GAMBLE_TARGET_TOOLTIP,
	TSTR_GAMBLE_FRAME_TOOLTIP,
	TSTR_REPAIR_TARGET_TOOLTIP,
	TSTR_REPAIR_FRAME_TOOLTIP,
	TSTR_FMT_REPAIRCOST_NORMAL,
	TSTR_FMT_REPAIRCOST_EQUIP,
	TSTR_FMT_REPAIRCOST_ALL,
	TSTR_REGGUILD_TARGET_TOOLTIP,
	TSTR_REGGUILD_FRAME_TOOLTIP,
	TSTR_ERROR_HACKTOOL_TIMEOUT,
	TSTR_CMD_GUILD_INVITE_TACTICS,
	TSTR_CMDESC_GUILD_INVITE_TACTICS,
	TSTR_CMD_CHAT_BAN,
	TSTR_CMD_CHAT_BAN_SUCCESS,
	TSTR_CMD_CHAT_BAN_NOTOPERATOR,
	TSTR_CMD_CHAT_BAN_INVALIDCHAR,
	TSTR_CMD_CHAT_BAN_MAXMIN,
	TSTR_ITEMUP_ERR_CANNOTREMOVEMAGIC,
	TSTR_REGIONINFO_PEACE,
	TSTR_ERROR_WRONGREGION_ITEM,
	TSTR_CASHCABINET_TOOLTIP,
	TSTR_CHAT_SHOW,
	TSTR_TKEY_CAUTION15,
	TSTR_CABINET,
	TSTR_AUCTIONREG_MAXPOST,
	TSTR_AUCTIONBID_MAXPOST,
	TSTR_MAIL_TITLE,
	TSTR_MAIL_PREVPAGE,
	TSTR_MAIL_NEXTPAGE,
	TSTR_REMAIN_PERIOD,
	TSTR_CANT_DELETE_MAIL,
	TSTR_CASHSHOP_TITLE,
	TSTR_GLOBAL_CHANNEL,
	TSTR_TCLASS_ALL,
	TSTR_GODDESS,
	TSTR_SIEGE_ALARM_TITLE,
	TSTR_SIEGE_ALARM_MSG,
	TSTR_GOTO_CAPITAL,
	TSTR_TOURNAMENT_STEP_1ST,
	TSTR_TOURNAMENT_STEP_NORMAL,
	TSTR_TOURNAMENT_STEP_PARTY,
	TSTR_TOURNAMENT_STEP_MATCH,
	TSTR_TOURNAMENT_STEP_ENTER,
	TSTR_TOURNAMENT_STEP_QFINAL,
	TSTR_TOURNAMENT_STEP_QFEND,
	TSTR_TOURNAMENT_STEP_SFENTER,
	TSTR_TOURNAMENT_STEP_SFINAL,
	TSTR_TOURNAMENT_STEP_SFEND,
	TSTR_TOURNAMENT_STEP_FENTER,
	TSTR_TOURNAMENT_STEP_FINAL,
	TSTR_TOURNAMENT_STEP_END,
	TSTR_TOURNAMENT_WIN,
	TSTR_TOURNAMENT_NEED_PAGE,
	TSTR_TOURNAMENT_COUNT,
	TSTR_TOURNAMENT_ARENA,
	TSTR_TOURNAMENT_JOIN_ENTRY,
	TSTR_TOURNAMENT_TOTAL_PRIZE_MONEY,
	TSTR_TOURNAMENT_DEFAULT_PRIZE_MONEY,
	TSTR_TOURNAMENT_ENTRY_1,
	TSTR_TOURNAMENT_ENTRY_2,
	TSTR_TOURNAMENT_ENTRY_3,
	TSTR_TOURNAMENT_ENTRY_4,
	TSTR_TOURNAMENT_ENTRY_5,
	TSTR_TOURNAMENT_ENTRY_6,
	TSTR_TOURNAMENT_ENTRY_7,
	TSTR_TOURNAMENT_ENTRY_8,
	TSTR_TOURNAMENT_ENTRY_9,
	TSTR_TOURNAMENT_JOIN,
	TSTR_TOURNAMENT_PRIVATE,
	TSTR_TOURNAMENT_PARTY,
	TSTR_TOURNAMENT_JOIN_OK,
	TSTR_TOURNAMENT_JOIN_FAILED,
	TSTR_TOURNAMENT_JOIN_EXPIRED,
	TSTR_TOURNAMENT_JOIN_EXCESS,
	TSTR_TOURNAMENT_JOIN_1ST,
	TSTR_TOURNAMENT_CHEER,
	TSTR_TOURNAMENT_REMAIN_TIME,
	TSTR_TOURNAMENT_DRAW_NOTICE,
	TSTR_TOURNAMENT_LEFT_TEAM,
	TSTR_TOURNAMENT_RIGHT_TEAM,
	TSTR_TOURNAMENT_USE,
	TSTR_TOURNAMENT_FRIEND,
	TSTR_TOURNAMENT_ADD,
	TSTR_TOURNAMENT_DONT_HAVE_CHEER_ITEM,
	TSTR_TOURNAMENT_STEP_1ST_MSG,
	TSTR_TOURNAMENT_STEP_NORMAL_MSG,
	TSTR_TOURNAMENT_STEP_PARTY_MSG,
	TSTR_TOURNAMENT_STEP_MATCH_MSG,
	TSTR_TOURNAMENT_STEP_ENTER_MSG,
	TSTR_TOURNAMENT_STEP_QFINAL_MSG,
	TSTR_TOURNAMENT_STEP_QFEND_MSG,
	TSTR_TOURNAMENT_STEP_SFENTER_MSG,
	TSTR_TOURNAMENT_STEP_SFINAL_MSG,
	TSTR_TOURNAMENT_STEP_SFEND_MSG,
	TSTR_TOURNAMENT_STEP_FENTER_MSG,
	TSTR_TOURNAMENT_STEP_FINAL_MSG,
	TSTR_TOURNAMENT_STEP_END_MSG,
	TSTR_TOURNAMENT_STARTTIME,
	TSTR_TOURNAMENT_START,
	TSTR_TOURNAMENT_STEP_QFINAL_TIME_MSG,
	TSTR_TOURNAMENT_STEP_SFINAL_TIME_MSG,
	TSTR_TOURNAMENT_STEP_FINAL_TIME_MSG,
	TSTR_TOURNAMENT_STEP_MIN,
	TSTR_TOURNAMENT_STEP_SEC,
	TSTR_TOURNAMENT_STEP_BEFORE,
	TSTR_TOURNAMENT_CANT_USE,
	TSTR_TOURNAMENT_CANT_USE_CASHITEM,
	TSTR_TOURNAMENT_CANT_USE_SKILL,
	TSTR_TOURNAMENT_AUTO_REVIVAL,
	TSTR_TOURNAMENT_CANT_WORLDMAP,
	TSTR_TOURNAMENT_GIVE_UP,
	TSTR_TOURNAMENT_UNJOIN_PARTY,
	TSTR_TOURNAMENT_BATTING,
	TSTR_TOURNAMENT_NEED_MONEY,
	TSTR_TOURNAMENT_NEED_ITEM,
	TSTR_TOURNAMENT_NOT_CLASS,
	TSTR_ITEMCHANGE_COUNT_SUCCESS,
	TSTR_TOURNAMENT_PARTY_SUCCESS,
	TSTR_TOURNAMENT_PARTY_NOTFOUND,
	TSTR_TOURNAMENT_PARTY_ALREADY,
	TSTR_TOURNAMENT_PARTY_FULL,
	TSTR_FCEVENT_D2,
	TSTR_FCEVENT_C2,
	TSTR_DO_NOT_USE_ITEM_ON_RIDING,
	TSTR_DO_NOT_USE_SKILL_ON_RIDING,
	TSTR_ARE_YOU_SURE_SKIP_TUTORIAL,
	TSTR_TUTORIAL_SKIP_TITLE,
	TSTR_TUTORIAL_SKIP_MSG_D,
	TSTR_TUTORIAL_SKIP_MSG_C,
	TSTR_TUTORIAL_ERROR_MSG,
	TSTR_HS_ERR_FUNCTION,
	TSTR_HS_ERR_DETECT_GAMEHACK,
	TSTR_HS_ERR_DETECT_AUTOMACRO,
	TSTR_HS_ERR_DETECT_SPEEDHACK,
	TSTR_HS_ERR_DETECT_KDTRACE,
	TSTR_HS_ERR_DETECT_OTHER,
	TSTR_TOURNAMENT_LOBBY,
	TSTR_TOURNAMENT_UNJOIN_PARTY_SELF,
	TSTR_TOURNAMENT_REWARD_1,
	TSTR_TOURNAMENT_REWARD_2,
	TSTR_NPGAMEMON_INIT_ERROR,
	TSTR_NPGAMEMON_SPEEDHACK,
	TSTR_NPGAMEMON_GAMEHACK,
	TSTR_NPGAMEMON_GAMEHACK_DOUBT,
	TSTR_NPGAMEMON_ERROR_EXIST,
	TSTR_NPGAMEMON_ERROR_GAME_EXIST,
	TSTR_NPGAMEMON_ERROR_INIT,
	TSTR_NPGAMEMON_ERROR_NFOUND,
	TSTR_NPGAMEMON_ERROR_CRYPTOAPI,
	TSTR_NPGAMEMON_ERROR_EXECUTE,
	TSTR_NPGAMEMON_ERROR_ILLEGAL_PRG,
	TSTR_NPGMUP_ERROR_ABORT,
	TSTR_NPGMUP_ERROR_CONNECT,
	TSTR_NPGAMEMON_ERROR_GAMEGUARD,
	TSTR_NPGMUP_ERROR_PARAM,
	TSTR_NPGMUP_ERROR_INIT,
	TSTR_NPGMUP_ERROR_DOWNCFG,
	TSTR_NPGMUP_ERROR_AUTH,
	TSTR_NPGAMEMON_ERROR_NPSCAN,
	TSTR_NPGG_ERROR_COLLISION,
	TSTR_NPGG_ERROR,
	TSTR_NPGG_ERROR_TITLE,
	TSTR_MISSION_COL_LOCAL,
	TSTR_MISSION_COL_COUNTRY,
	TSTR_MISSION_COL_STATUS,
	TSTR_MISSION_NEUTRAL,
	TSTR_MISSION_NORMAL,
	TSTR_MISSION_WAR,
	TSTR_MISSION_WAR_CLOSE,
	TSTR_MISSION_COUNTRY,
	TSTR_MISSION_COUNTRY_NEUTRAL,
	TSTR_MISSION_STATUS_NORMAL,
	TSTR_MISSION_STATUS_WAR,
	TSTR_MISSION_STATUS_WAR_CLOSE,
	TSTR_MISSION_WAR_START_EVENNUMBER,
	TSTR_MISSION_WAR_START_ODDNUMBER,
	TSTR_MISSION_WAR_CLOSE_EVENNUMBER,
	TSTR_MISSION_WAR_CLOSE_ODDNUMBER,
	TSTR_MISSION_OCCUPATION,
	TSTR_MISSION_WAR_START_ODDNUMBER_MIN,
	TSTR_MISSION_WAR_START_ODDNUMBER_SEC,
	TSTR_MISSION_WAR_START_EVENNUMBER_MIN,
	TSTR_MISSION_WAR_START_EVENNUMBER_SEC,
	TSTR_MISSION_WAR_CLOSE_EVENNUMBER_MIN,
	TSTR_MISSION_WAR_CLOSE_EVENNUMBER_SEC,
	TSTR_MISSION_WAR_CLOSE_ODDNUMBER_MIN,
	TSTR_MISSION_WAR_CLOSE_ODDNUMBER_SEC,
	TSTR_MISSION_TIMEOUT,
	TSTR_ITEM_LOTTERY_BEGIN,
	TSTR_ITEM_LOTTERY_NIM,
	TSTR_ITEM_LOTTERY_GET,
	TSTR_GOTO_THUMB_MSG_SEC,
	TSTR_PETMAKE_ACK_USETIME,
	TSTR_GAMEOPTION_SHOW_NPC_NAME,
	TSTR_GAMEOPTION_SHOW_PLAYER_NAME,
	TSTR_GAMEOPTION_SHOW_MONSTER_NAME,
	TSTR_GAMEOPTION_AUTO_HELP,
	TSTR_GAMEOPTION_SHOW_TALK_BOX,
	TSTR_GAMEOPTION_DENY_WHISPER,
	TSTR_GAMEOPTION_DENY_COMMUNITY,
	TSTR_GAMEOPTION_SHOW_HUD,
	TSTR_GAMEOPTION_CONTINUOUS_CHAT,
	TSTR_GAMEOPTION_MOUSE_CLICK_MOVE,
	TSTR_GAMEOPTION_AUTO_TARGETING,
	TSTR_RPS_CLOSE,
	TSTR_RPS_GIVEUP,
	TSTR_RPS_COUNT,
	TSTR_RPS_ASK_COST,
	TSTR_RPS_MSG_DRAW,
	TSTR_RPS_NOTICE_WIN,
	TSTR_RPS_NOTICE_LOSE,
	TSTR_RPS_MSG_RETRY,
	TSTR_CONTINUOUS_WIN,
	TSTR_FMT_CASTLE_C_TOP3,
	TSTR_FMT_CASTLE_D_TOP3,
	TSTR_FMT_CASTLE_TOP3,
	TSTR_TOURNAMENT_HIDETICK,
	TSTR_TOURNAMENT_HIDETIME,
	TSTR_USE_FOBIDDEN_WORDS,
	TSTR_TEXT_COSTUME_HAT,
	TSTR_TEXT_COSTUME_DRESS,
	TSTR_TEXT_COSTUME_ACCESSARY,
	TSTR_TEXT_COSTUME_RACE,
	TSTR_RPSGAME_DONOT_OPEN_DLG,
	TSTR_RPSGAME_NEED_A_ITEM,
	TSTR_RPSGAME_ITEM_TRY,
	TSTR_RPSGAME_LIST_WIN,
	TSTR_RPSGAME_TYPE_1,
	TSTR_RPSGAME_TYPE_2,
	TSTR_RPSGAME_TYPE_3,
	TSTR_KEYDOWN_CAD,
	TSTR_NETCABLE_DISCONNECTED,
	TSTR_CANT_USE_NOW_CHANNEL,
	TSTR_FMT_ASK_EXTEND_PERIOD,
	TSTR_CHAT_WORLD_ERROR_MIN_LEVEL,
	TSTR_COUNT
};

typedef enum TNATIONOPTION
{
	TNATIONOPTION_CODE=0,
	TNATIONOPTION_MODIFY_WORD_BREAK,
	TNATIONOPTION_CAMERA_QUAKE,
	TNATIONOPTION_ADD_SLIDE,
	TNATIONOPTION_USE_STATE_FRAME_WIDE,
	TNATIONOPTION_JAPAN_IME,
	TNATIONOPTION_MODIFY_DIRECTLOGIN,
	TNATIONOPTION_PASSWORD_MD5,
	TNATIONOPTION_INSTALL_XTRAP,
	TNATIONOPTION_COUNT
} *LPTNATIONOPTION;

typedef enum TLIGHT_POS
{
	TLIGHT_CENTER = 0,
	TLIGHT_SIDE,
	TLIGHT_BACK,
	TLIGHT_COUNT
} *LPTLIGHT_POS;

typedef enum THELPLINK_TRIGGER
{
	THELPLINK_TRIGGER_ACCEPT=0,
	THELPLINK_TRIGGER_COMPLETE,
	THELPLINK_TRIGGER_COUNT,
} *LPTHELPLINK_TRIGGER;

typedef enum TSKILLACTION_TYPE
{
	TSKILLACTION_SPELL = 0,
	TSKILLACTION_ACTIVATE,
	TSKILLACTION_MOVEACTIVATE,
	TSKILLACTION_DEFEND,
	TSKILLACTION_COUNT
} *LPTSKILLACTION_TYPE;

typedef enum TSKILLSFX_TYPE
{
	TSKILLSFX_SPELL = 0,
	TSKILLSFX_ACT,
	TSKILLSFX_DEFEND,
	TSKILLSFX_DEFENDACT,
	TSKILLSFX_LOOP,
	TSKILLSFX_END,
	TSKILLSFX_ARROW,
	TSKILLSFX_COUNT
} *LPTSKILLSFX_TYPE;

typedef enum TGRADE_LEVEL
{
	TGRADE_LEVEL_0		= 0,		// Grade 0 ~ 4
	TGRADE_LEVEL_1		= 5,		// Grade 5 ~ 9
	TGRADE_LEVEL_2		= 10,		// Grade 10 ~ 14
	TGRADE_LEVEL_3		= 15,		// Grade 15 ~ 19
	TGRADE_LEVEL_4		= 20,		// Grade 20 ~
	TGRADE_LEVEL_COUNT	= 5
} *LPTGRADE_LEVEL;

typedef enum TMAGIC_LEVEL
{
	TMAGIC_LEVEL_NOR,
	TMAGIC_LEVEL_MAGIC,
	TMAGIC_LEVEL_RARE,
	TMAGIC_LEVEL_COUNT
} *LPTMAGIC_LEVEL;

enum TCOLOR
{
	TCOLOR_NONE = 0, // NONE
	TCOLOR001,
	TCOLOR002,
	TCOLOR003,
	TCOLOR004,
	TCOLOR005,
	TCOLOR006,
	TCOLOR007,
	TCOLOR008,
	TCOLOR009,
	TCOLOR010,
	TCOLOR011,
	TCOLOR012,
	TCOLOR013,
	TCOLOR014,
	TCOLOR015,
	TCOLOR016,
	TCOLOR017,
	TCOLOR018,
	TCOLOR019,
	TCOLOR020,
	TCOLOR021,
	TCOLOR022,
	TCOLOR023,
	TCOLOR024,
	TCOLOR025,
	TCOLOR026,
	TCOLOR027,
	TCOLOR028,
	TCOLOR029,
	TCOLOR030,
	TCOLOR031,
	TCOLOR032,
	TCOLOR033,
	TCOLOR034,
	TCOLOR035,
	TCOLOR036,
	TCOLOR037,
	TCOLOR038,
	TCOLOR039,
	TCOLOR040,
	TCOLOR041,
	TCOLOR042,
	TCOLOR043,
	TCOLOR044,
	TCOLOR045,
	TCOLOR046,
	TCOLOR047,
	TCOLOR048,
	TCOLOR049,
	TCOLOR_COUNT
};

#define TCOLOR_MANTLE_DEFAULT			TCOLOR030
extern DWORD dwTCOLOR[TCOLOR_COUNT];
// declaration

class CTClientItem;

typedef struct tagTSKILL				TSKILL, *LPTSKILL;
typedef struct tagTSKILLUPGRADEINFO		TSKILLUPGRADEINFO, *LPTSKILLUPGRADEINFO;
typedef struct tagTSKILLFUNCTION		TSKILLFUNCTION, *LPTSKILLFUNCTION;
typedef struct tagTDETAILINFO			TDETAILINFO, *LPTDETAILINFO;
typedef struct tagTACTION				TACTION, *LPTACTION;
typedef struct tagTREGIONINFO			TREGIONINFO, *LPTREGIONINFO;
typedef struct tagTACTIONDATA			TACTIONDATA, *LPTACTIONDATA;
typedef struct tagTCLOTH				TCLOTH, *LPTCLOTH;
typedef struct tagTQUEST				TQUEST, *LPTQUEST;
typedef struct tagTQCLASS				TQCLASS, *LPTQCLASS;
typedef struct tagTREWARD				TREWARD, *LPTREWARD;
typedef struct tagTTERM					TTERM, *LPTTERM;
typedef struct tagTPOPUPITEM			TPOPUPITEM, *LPTPOPUPITEM;
typedef struct tagTPOPUPMENU			TPOPUPMENU, *LPTPOPUPMENU;
typedef struct tagTMAPJOINT				TMAPJOINT, *LPTMAPJOINT;
typedef struct tagTMAPINFO				TMAPINFO, *LPTMAPINFO;
typedef struct tagTMINIMAP				TMINIMAP, *LPTMINIMAP;
typedef struct tagTPORTAL				TPORTAL, *LPTPORTAL;
typedef struct tagTITEM					TITEM, *LPTITEM;
typedef struct tagTQUESTITEM			TQUESTITEM, *LPTQUESTITEM;
typedef struct tagTITEMVISUAL			TITEMVISUAL, *LPTITEMVISUAL;
typedef struct tagTITEMGRADESFX			TITEMGRADESFX, *LPTITEMGRADESFX;
typedef struct tagTITEMMAGICSFX			TITEMMAGICSFX, *LPTITEMMAGICSFX;
typedef struct tagTSFXTEMP				TSFXTEMP, *LPTSFXTEMP;
typedef struct tagTMONTEMP				TMONTEMP, *LPTMONTEMP;
typedef struct tagTNPCTEMP				TNPCTEMP, *LPTNPCTEMP;
typedef struct tagTNPC					TNPC, *LPTNPC;
typedef struct tagTFORMULA				TFORMULA, *LPTFORMULA;
typedef struct tagTSWITCH				TSWITCH, *LPTSWITCH;
typedef struct tagTSKYBOX				TSKYBOX, *LPTSKYBOX;
typedef struct tagTLIGHT				TLIGHT, *LPTLIGHT;
typedef struct tagTLIGHTPOS				TLIGHTPOS, *LPTLIGHTPOS;
typedef struct tagTLEVEL				TLEVEL, *LPTLEVEL;
typedef struct tagTUNITFOG				TUNITFOG, *LPTUNITFOG;
typedef struct tagTFOG					TFOG, *LPTFOG;
typedef struct tagTGATE					TGATE, *LPTGATE;
typedef struct tagTITEMMAGIC			TITEMMAGIC, *LPTITEMMAGIC;
typedef struct tagTPET					TPET, *LPTPET;
typedef struct tagTITEMATTR				TITEMATTR, *LPTITEMATTR;
typedef struct tagTITEMGRADE			TITEMGRADE, *LPTITEMGRADE;
typedef struct tagTITEMGRADEVISUALKEY	TITEMGRADEVISUALKEY;
typedef struct tagTITEMGRADEVISUAL		TITEMGRADEVISUAL, *LPTITEMGRADEVISUAL;
typedef struct tagTHELP							THELP, *LPTHELP;
typedef struct tagTHELPPAGE					THELPPAGE, *LPTHELPPAGE;
typedef struct tagTGODTOWER				TGODTOWER, *LPTGODTOWER;
typedef struct tagTGODBALL				TGODBALL, *LPTGODBALL;
typedef struct tagTMONSHOP				TMONSHOP, *LPTMONSHOP;
typedef struct tagTPORTALREGION			TPORTALREGION, *LPTPORTALREGION;
typedef struct tagTAUCTIONTREE			TAUCTIONTREE, *LPTAUCTIONTREE;
typedef struct tagTMANTLECOORD			TMANTLECOORD, *LPTMANTLECOORD;
typedef struct tagTMANTLECOORDINFO			TMANTLECOORDINFO, *LPTMANTLECOORDINFO;
typedef struct tagTMANTLEDETAILKEY			TMANTLEDETAILKEY, *LPTMANTLEDETAILKEY;
typedef struct tagTMANTLECOORDKEY			TMANTLECOORDKEY, *LPTMANTLECOORDKEY;
typedef struct tagTFAMETITLE					TFAMETITLE, *LPTFAMETITLE;
typedef struct tagTEQUIPCREATECHAR		TEQUIPCREATECHAR, *LPTEQUIPCREATECHAR;
typedef struct tagTRPS						TRPS, *LPTRPS;

// typedef
typedef vector<CString*>									VTPSTRING, *LPTPSTRING;
typedef vector<LPTSKILLFUNCTION>						VTSKILLFUNCTION, *LPVTSKILLFUNCTION;
typedef vector<LPTACTIONDATA>							VTACTIONDATA, *LPVTACTIONDATA;
typedef vector<LPTREWARD>								VTREWARDTEMP, *LPVTREWARDTEMP;
typedef vector<LPTTERM>									VTTERMTEMP, *LPVTTERMTEMP;
typedef vector<LPTPOPUPITEM>							VTPOPUPITEM, *LPVTPOPUPITEM;
typedef vector<LPTMAPJOINT>								VTMAPJOINT, *LPVTMAPJOINT;
typedef vector<LPTFOG>									VTFOG, *LPVTFOG;
typedef vector<TITEMGRADE>								VTITEMGRADE, LPVTITEMGRADE;
typedef vector<LPTLIGHTPOS>								VTLIGHTPOS, *LPVTLIGHTPOS;
typedef vector<LPTPORTAL>								VTTPORTAL,	*LPVTTPORTAL;
typedef vector<LPTAUCTIONTREE>							VTAUCTIONTREE, *LPVTAUCTIONTREE;
typedef vector<TMANTLECOORD>					VTMANTLECOORD, *LPVTMANTLECOORD;
typedef vector<LPTHELPPAGE>						VTHELPPAGE, *LPVTHELPPAGE;

typedef map< WORD, LPTSKILL>							MAPTSKILLTEMP, *LPMAPTSKILLTEMP;
typedef map< DWORD, CString *>							MAPTSTRING, *LPMAPTSTRING;
typedef map< DWORD, LPTDETAILINFO>					MAPTDETAILINFO, *LPMAPTDETAILINFO;
typedef map< DWORD, LPTACTION>						MAPTACTION, *LPMAPTACTION;
typedef map< DWORD, LPTREGIONINFO>					MAPTREGIONINFO, *LPMAPTREGIONINFO;
typedef map< DWORD, LPVECTORDWORD>				MAPTBGM, *LPMAPTBGM;
typedef map< DWORD, LPVECTORDWORD>				MAPTENV, *LPMAPTENV;
typedef map< WORD, WORD>								MAPWORD, *LPMAPWORD;
typedef map< DWORD, LPTQUEST>							MAPTQUESTTEMP, *LPMAPTQUESTTEMP;
typedef map< DWORD, LPTQCLASS>							MAPTQCLASSTEMP, *LPMAPTQCLASSTEMP;
typedef map< DWORD, LPTPOPUPITEM>						MAPTPOPUPITEM, *LPMAPTPOPUPITEM;
typedef map< DWORD, LPTPOPUPMENU>						MAPTPOPUPMENU, *LPMAPTPOPUPMENU;
typedef map< DWORD, LPVTMAPJOINT>			MAPVTMAPJOINT, *LPMAPVTMAPJOINT;
typedef map< DWORD, LPTMINIMAP>							MAPTMINIMAP, *LPMAPTMINIMAP;
typedef map< DWORD, LPTMAPINFO>							MAPTMAPINFO, *LPMAPTMAPINFO;
typedef map< DWORD, LPD3DXVECTOR3>						MAPD3DXVECTOR3, *LPMAPD3DXVECTOR3;
typedef map< WORD, LPTPORTAL>							MAPTPORTAL, *LPMAPTPORTAL;
typedef map< WORD, LPTITEM>								MAPTITEMTEMP, *LPMAPTITEMTEMP;
typedef map< WORD, LPTITEMVISUAL>						MAPTITEMVISUAL, *LPMAPTITEMVISUAL;
typedef map< WORD, LPTITEMGRADESFX>						MAPTITEMGRADESFX, *LPMAPTITEMGRADESFX;
typedef map< WORD, LPTITEMMAGICSFX>						MAPTITEMMAGICSFX, *LPMAPTITEMMAGICSFX;
typedef map< DWORD, LPTSFXTEMP>							MAPTSFXTEMP, *LPMAPTSFXTEMP;
typedef map< WORD, LPTMONTEMP>							MAPMONTEMP, *LPMAPMONTEMP;
typedef map< WORD, LPTNPCTEMP>							MAPNPCTEMP, *LPMAPNPCTEMP;
typedef map< WORD, LPTNPC>									MAPNPC, *LPMAPNPC;
typedef map< BYTE, LPTFORMULA>							MAPTFORMULA, *LPMAPTFORMULA;
typedef map< DWORD, LPTSWITCH>							MAPTSWITCHDATA, *LPMAPTSWITCHDATA;
typedef map< DWORD, LPTSKYBOX>							MAPTSKYBOX, *LPMAPTSKYBOX;
typedef map< DWORD, LPTLIGHT>							MAPTLIGHT, *LPMAPTLIGHT;
typedef map< BYTE, TLEVEL>								MAPTLEVEL, *LPMAPTLEVEL;
typedef map< DWORD, LPTUNITFOG>							MAPTUNITFOG, *LPMAPTUNITFOG;
typedef map< DWORD, LPTGATE>							MAPTGATEDATA, *LPMAPTGATEDATA;
typedef map< DWORD, LPTITEMMAGIC >						MAPTITEMMAGIC, *LPMAPTITEMMAGIC;
typedef map< WORD, LPTPET>								MAPTPET, *LPMAPTPET;
typedef map< WORD, LPTITEMATTR>							MAPTITEMATTR, *LPMAPTITEMATTR;
typedef map< WORD, LPTQUESTITEM >						MAPTQUESTITEM, *LPMAPTQUESTITEM;
typedef map< TITEMGRADEVISUALKEY, TITEMGRADEVISUAL> MAPTITEMGRADEVISUAL, *LPMAPTITEMGRADEVISUAL;
typedef map< DWORD, LPTHELP>								MAPTHELP, *LPMAPTHELP;
typedef map< DWORD, DWORD>								MAPTHELPLINK, *LPMAPTHELPLINK;
typedef map< WORD, LPTGODTOWER>							MAPTGODTOWER, *LPMAPTGODTOWER;
typedef map< WORD, LPTGODBALL>							MAPTGODBALL, *LPMAPTGODBALL;
typedef map< DWORD, LPTMONSHOP>							MAPTMONSHOP, *LPMAPTMONSHOP;
typedef map< WORD, LPTPORTALREGION>						MAPTPORTALREGION, *LPMAPTPORTALREGION;
typedef map< TMANTLEDETAILKEY, DWORD >							MAPTMANTLEDETAIL, *LPMAPTMANTLEDETAIL;
typedef map< TMANTLECOORDKEY, LPTMANTLECOORDINFO >			MAPTMANTLECOORD, *LPMAPTMANTLECOORD;
typedef map< BYTE, LPTFAMETITLE >							MAPTFAMETITLE,	*LPMAPTFAMETITLE;
typedef map< DWORD, LPTEQUIPCREATECHAR >				MAPTEQUIPCREATECHAR, *LPMAPTEQUIPCREATECHAR;
typedef map< DWORD, CString >					MAPTDYNAMICHELP, *LPMAPTDYNAMICHELP;
typedef map< WORD, LPTRPS >					MAPTRPS, *LPMAPTRPS;



// struct
struct tagTSKILLFUNCTION
{
	BYTE m_bMethodID;		///적용방식
	BYTE m_bType;			///효과종류
	BYTE m_bFunctionID;		///효과내용
	BYTE m_bOPCode;			///수치적용
	BYTE m_bCalc;			///성능계산
	WORD m_wValue;			///초기값
	WORD m_wInc;			///증가값
};

struct tagTSKILLUPGRADEINFO
{
	BYTE m_bSkillPoint;
	BYTE m_bGroupPoint;
	BYTE m_bPrevLevel;
};

struct tagTSKILL
{
	WORD m_wSkillID;						///스킬ID
	CString m_strNAME;						///스킬이름
	WORD m_wActSkillID;						///이전성공스킬
	WORD m_wDefSkillID;						///대상이걸린버프
	WORD m_wModeID;							///태세
	DWORD m_dwClassID;						///직업코드
	BYTE m_bKind;							///특성구분
	DWORD m_dwWeaponID;						///사용무기
	DWORD m_dwDuration;						///적용시간초기값
	DWORD m_dwDurationInc;					///적용시간증가비율
	WORD m_wUseHP;							///HP소모비율
	WORD m_wUseMP;							///MP소모비율
	WORD m_wIconID;							///아이콘ID
	BYTE m_bLevel;							///요구레벨
	BYTE m_bLevelInc;						///요구레벨증가
	BYTE m_bMaxLevel;						///최대스킬레벨
	FLOAT m_fPrice;							///가격비율

	WORD m_wItemID[TSHOTTYPE_COUNT];		///발사아이템
	WORD m_wNeedItemID;						///소모아이템

	FLOAT m_fMoveDist;						///강제이동 거리
	FLOAT m_fAtkRange;						///인식 폭,반경
	FLOAT m_fBufRange;						///오라범위
	FLOAT m_fMinRange;						///최소사정거리
	FLOAT m_fMaxRange;						///최대사정거리
	DWORD m_dwSpellTick;					///발동시간
	BYTE m_bIsRide;							///버프중 탈 수 없는 스킬
	DWORD m_dwDelay;						///재사용대기
	INT m_nDelayInc;						///재사용 대기 증감비율
	DWORD m_dwGroupTick;					///계열대기
	DWORD m_dwInterval;						///반복시간
	BYTE m_bPositive;						///이로움 해로움
	BYTE m_bActive;							///패시브=0 액티브=1
	BYTE m_bDelayType;						///공속적용
	BYTE m_bLoop;							///자동반복여부
	BYTE m_bContinue;						///동작지속여부
	BYTE m_bActionID[TSKILLACTION_COUNT];	///동작

	DWORD m_dwSFX[TSKILLSFX_COUNT];			///이펙트
	DWORD m_dwInfoID;						///툴팁ID

	BYTE m_bTargetType;						///사용대상 피아
	BYTE m_bRangeType;						///대상판별
	BYTE m_bShowIcon;						///아이콘보임
	BYTE m_bShowTime;						///남은시간보임
	BYTE m_bShowCritical;					///크리티컬적용
	BYTE m_bUseInHold;						///갇힘 상태에서 사용 가능여부	

	BYTE m_bDuraSlot;						///내구감소슬롯
	BYTE m_bHitInit;						///성공율초기값
	BYTE m_bHitInc;							///성공율증가값
	BYTE m_bCanCancel;						///사용자 취소 가능 여부
	BYTE m_bStaticWhenDie;					/// 사망시 버프 유지

	LPTSKILLUPGRADEINFO m_vTUPGRADEINFO;
	VTSKILLFUNCTION m_vTFUNCTION;
	VECTORFLOAT m_vTARROWDIR;

	BYTE m_bPursuit;

	tagTSKILL()
	{
		m_bDelayType = TAD_NONE;
		m_bPursuit = FALSE;

		m_vTUPGRADEINFO = NULL;
		m_vTFUNCTION.clear();
		m_vTARROWDIR.clear();
	};

	~tagTSKILL()
	{
		while(!m_vTFUNCTION.empty())
		{
			delete m_vTFUNCTION.back();
			m_vTFUNCTION.pop_back();
		}

		if(m_vTUPGRADEINFO)
		{
			delete[] m_vTUPGRADEINFO;
			m_vTUPGRADEINFO = NULL;
		}

		m_vTARROWDIR.clear();
	};

	LPTSKILLFUNCTION FindFunction( BYTE bType, BYTE bExec )
	{
		VTSKILLFUNCTION::iterator it, end;
		it = m_vTFUNCTION.begin();
		end = m_vTFUNCTION.end();
		for(; it != end ; ++it )
		{
			if( (*it)->m_bType == bType && (*it)->m_bFunctionID == bExec )
				return (*it);
		}
		return NULL;
	}
};

struct tagTDETAILINFO
{
	CString *m_pTEXT;
	BYTE m_bCount;

	tagTDETAILINFO()
	{
		m_pTEXT = NULL;
		m_bCount = 0;
	};

	~tagTDETAILINFO()
	{
		if(m_pTEXT)
		{
			delete[] m_pTEXT;
			m_pTEXT = NULL;
		}

		m_bCount = 0;
	};
};

struct tagTACTION
{
	DWORD m_dwTSLASH;
	DWORD m_dwActID;
	DWORD m_dwAniID;

	BYTE m_bEquipMode;
};

struct tagTREGIONINFO
{
	LPVECTORDWORD m_pVTENV;
	LPVECTORDWORD m_pVTBGM;
	DWORD m_dwTENVSND_LOOP;

	CString m_strNAME;
	DWORD m_dwID;

	D3DXVECTOR3 m_vTHUMB[TCONTRY_COUNT];
	BYTE m_bContryID;
	BYTE m_bCanFly;
	WORD m_wLocalID;
	BYTE m_bCanMail;
	DWORD m_dwBGMID;
	DWORD m_dwENVID;
	BYTE m_bInfo;

	tagTREGIONINFO()
	{
		m_pVTENV = NULL;
		m_pVTBGM = NULL;
	};

	~tagTREGIONINFO()
	{
		m_pVTENV = NULL;
		m_pVTBGM = NULL;
	};
};

struct tagTACTIONDATA
{
	CString	m_strActCmd;
	BYTE 	m_bLoopAction;
	BYTE 	m_bSubAction;
	BYTE 	m_bLevel;

	BYTE 	m_bContinue;
	BYTE 	m_bCancel;
	BYTE 	m_bNavAction;
	BYTE 	m_bSkipMain;
	BYTE	m_bHideOnCapeMode;
};

struct tagTREWARD
{
	BYTE m_bType;
	DWORD m_dwID;

	BYTE m_bMethod;
	BYTE m_bCount;
	BYTE m_bProb;
};

struct tagTTERM
{
	CString m_strTermMSG;
	CString m_strFailMSG;

	BYTE m_bType;
	DWORD m_dwID;

	BYTE m_bCount;
};

struct tagTQUEST
{
	CString m_strCompleteMSG;
	CString m_strTriggerMSG;
	CString m_strSummaryMSG;
	CString m_strAcceptMSG;
	CString m_strRejectMSG;
	CString m_strNPCName;
	CString m_strReply;
	CString m_strTITLE;

	VTREWARDTEMP m_vTREWARD;
	VTTERMTEMP m_vTTERM;

	DWORD m_dwClassID;
	DWORD m_dwID;

	BYTE m_bLevel;
	BYTE m_bType;
	BYTE m_bMAIN;

	DWORD m_dwMinLevel;
	DWORD m_dwMaxLevel;

	tagTQUEST()
	{
		m_strCompleteMSG.Empty();
		m_strTriggerMSG.Empty();
		m_strSummaryMSG.Empty();
		m_strAcceptMSG.Empty();
		m_strRejectMSG.Empty();
		m_strNPCName.Empty();
		m_strReply.Empty();
		m_strTITLE.Empty();

		m_vTREWARD.clear();
		m_vTTERM.clear();

		m_dwClassID = 0;
		m_dwID = 0;

		m_bLevel = 1;
		m_bType = 0;

		m_bMAIN = FALSE;
		
		m_dwMinLevel = 0;
		m_dwMaxLevel = 0;
	};

	~tagTQUEST()
	{
		while(!m_vTREWARD.empty())
		{
			delete m_vTREWARD.back();
			m_vTREWARD.pop_back();
		}

		while(!m_vTTERM.empty())
		{
			delete m_vTTERM.back();
			m_vTTERM.pop_back();
		}
	};
};

struct tagTQCLASS
{
	CString m_strNAME;

	DWORD m_dwClassID;
	BYTE m_bMAIN;
};

struct tagTPOPUPITEM
{
	CString m_strTITLE;

	DWORD m_dwMenuID;
	BYTE m_bGhost;

	tagTPOPUPITEM()
	{
		m_strTITLE.Empty();

		m_dwMenuID = 0;
		m_bGhost = 0;
	};
};

struct tagTPOPUPMENU
{
	VTPOPUPITEM m_vTPOPUP;
	DWORD m_dwID;

	tagTPOPUPMENU()
	{
		m_vTPOPUP.clear();
		m_dwID = 0;
	};
};

struct tagTMAPJOINT
{
	CRect m_vRECT;
	BYTE m_bJOINT;

	tagTMAPJOINT()
	{
		m_vRECT.left = 0;
		m_vRECT.top = 0;
		m_vRECT.right = 0;
		m_vRECT.bottom = 0;

		m_bJOINT = 0;
	};
};

struct tagTMAPINFO
{
	MAPD3DXVECTOR3 m_mapTNODE;
	DWORD m_dwMapID;
	BYTE m_bDungeon;
	BYTE m_bNPCCALL;

	tagTMAPINFO()
	{
		m_mapTNODE.clear();
		m_dwMapID = 0;

		m_bDungeon = FALSE;
		m_bNPCCALL = FALSE;
	};

	~tagTMAPINFO()
	{
		MAPD3DXVECTOR3::iterator itTNODE;

		for( itTNODE = m_mapTNODE.begin(); itTNODE != m_mapTNODE.end(); itTNODE++)
			delete (*itTNODE).second;

		m_mapTNODE.clear();
		m_dwMapID = 0;
	};
};

struct tagTMINIMAP
{
	LPTEXTURESET m_pTEX;
	DWORD m_dwUnitID;

	FLOAT m_fSCALE;
	FLOAT m_fPosX;
	FLOAT m_fPosZ;

	BYTE m_bWorldID;
	BYTE m_bWorldMapLevel;
	DWORD m_dwWorldButtonID;

	tagTMINIMAP()
	{
		m_pTEX = NULL;

		m_fSCALE = 1.0f;
		m_fPosX = 0.0f;
		m_fPosZ = 0.0f;

		m_bWorldID = 0;
		m_dwWorldButtonID = 0;
	};

	~tagTMINIMAP()
	{
		m_pTEX = NULL;

		m_fSCALE = 1.0f;
		m_fPosX = 0.0f;
		m_fPosZ = 0.0f;

		m_bWorldID = 0;
		m_dwWorldButtonID = 0;
	};
};

struct tagTPORTAL
{
	WORD			m_wPortalID;
	CString			m_strNAME;
	DWORD			m_dwPrice;
	WORD			m_wPortalRegionID;
};

struct tagTITEM
{
	WORD	m_wItemID;							///일련번호
	BYTE	m_bType;							///종류
	BYTE	m_bKind;							///구분
	WORD	m_wAttrID;							///성능일련번호
	CString	m_strNAME;							///이름
	WORD	m_wUseValue;						///사용효과값
	DWORD	m_dwSlotID;							///장착위치
	DWORD	m_dwClassID;						///사용직업
	BYTE	m_bPrmSlotID;						///주무기장착위치
	BYTE	m_bSubSlotID;						///보조무기장착위치
	BYTE	m_bLevel;							///필요레벨
	BYTE	m_bCanRepair;						///수리여부(추가)
	DWORD	m_dwDuraMax;						///최대내구(추가)
	BYTE	m_bRefineMax;						///제련횟수(추가)
	FLOAT	m_fPriceRate;						///가격비율
	DWORD	m_dwPrice;							///기준가격
	BYTE	m_bMinRange;						///최소사정거리
	BYTE	m_bMaxRange;						///최대사정거리
	BYTE	m_bStack;							///최대수량
	BYTE	m_bSlotCount;						///슬롯갯수
	BYTE	m_bCanGamble;						///봉인 생성여부
	BYTE	m_bGambleProb;						///치환여부(추가)
	BYTE	m_bDestoryProb;						///소멸여부(추가)
	BYTE	m_bCanGrade;						///등급 가능여부
	BYTE	m_bCanMagic;						///마법 생성여부
	BYTE	m_bCanRare;							///희귀 생성여부
	WORD	m_wDelayGroupID;					///딜레이 그룹 ID
	DWORD	m_dwDelay;							///재사용대기시간
	BYTE	m_bCanTrade;						///거래,판매 가능 여부
	BYTE	m_bIsSpecial;						///캐쉬 아이템 여부
	WORD	m_wUseTime;							///사용 기간(일/시간)
	BYTE m_bUseType;									///사용 타입
	BYTE	m_bWeaponID;						///WEAPON ID
	FLOAT	m_fShotSpeed;						///SHOT SPEED
	FLOAT	m_fGravity;							///GRAVITY
	DWORD	m_dwInfoID;							///INFO ID
	BYTE	m_bSkillItemType;					///발사타입
	WORD	m_wVisual[TGRADE_LEVEL_COUNT];		///단계별 비주얼(추가)
	WORD	m_wGradeSFX;						///등급 이펙트(추가)
	WORD	m_wOptionSFX[TMAGIC_LEVEL_COUNT];	///단계별 옵션 이펙트(추가)
	BYTE	m_bCanWrap; ///밀납가능
	DWORD	m_dwAuctionCode;
	BYTE m_bCanColor;

	tagTITEM()
	{}
};

struct tagTQUESTITEM
{
	DWORD m_dwID;
	WORD m_wItemID;
	BYTE m_bGrade;
	BYTE m_bGLevel;
	DWORD m_dwDuraMax;
	DWORD m_dwDuraCur;
	BYTE m_bRefineCur;

	BYTE m_bMagic[ TMAGIC_MAX ];
	BYTE m_bValue[ TMAGIC_MAX ];
};

struct tagTITEMVISUAL
{
	WORD	m_wID;	
	DWORD	m_dwInvenID;
	DWORD	m_dwObjectID;
	DWORD	m_dwCLKID;
	DWORD	m_dwCLIID;
	DWORD	m_dwMesh[MT_COUNT];
	DWORD	m_dwPivot[MT_COUNT];
	WORD	m_wIcon;
	BYTE	m_bHideSlot;
	BYTE	m_bHidePart;
	BYTE	m_bHideRace;
	DWORD	m_dwSlashColor;
	DWORD	m_dwSlashTex;
	FLOAT	m_fSlashLen;	
	DWORD m_dwEffectFuncID[2];
	DWORD m_dwCostumeHide;
};

struct tagTITEMGRADESFX
{
	WORD	m_wID;
	WORD	m_wSFX[TGRADE_LEVEL_COUNT-1];
};

struct tagTITEMMAGICSFX
{
	WORD	m_wID;
	WORD	m_wSFX[TMAGIC_SFXKIND_COUNT];
};

struct tagTCLOTH
{
	BYTE m_bHideSlotID;
	BYTE m_bHidePartID;
	BYTE m_bHideRaceID;

	DWORD m_dwCLK;
	DWORD m_dwCL;
	DWORD m_dwMESH;
};

struct tagTSFXTEMP
{
	DWORD m_dwID;

	DWORD m_dwPosID;
	LPSFX m_pTSFX;

	tagTSFXTEMP()
	{
		m_pTSFX = NULL;

		m_dwPosID = 0;
		m_dwID = 0;
	};
};

struct tagTMONTEMP
{
	LPTPOPUPMENU m_pTPOPUP;
	CString m_strTITLE;
	CString m_strNAME;

	LPTITEM m_pTITEM[ES_COUNT];
	DWORD m_dwSpawnSND;
	DWORD m_dwOBJ;

	FLOAT m_fLOST;
	FLOAT m_fLB;
	FLOAT m_fAB;

	FLOAT m_fScaleX;
	FLOAT m_fScaleY;
	FLOAT m_fScaleZ;

	WORD m_wTSKILL[TMONSKILL_COUNT];
	WORD m_wFaceIcon;
	WORD m_wSpawnSFX;
	WORD m_wKind;

	BYTE m_bNotNockBack;
	BYTE m_bCanSelected;
	BYTE m_bCanFly;
	BYTE m_bCanAttack;
	BYTE m_bCanTame;
	BYTE m_bDrawName;
	BYTE m_bVisible;
	BYTE m_bApplyAI;

	FLOAT m_fSize;
	BYTE m_bCanDetectHidingPC;
	BYTE m_bSlidingWhenDie;
	BYTE m_bDrawNameWhenDie;

	tagTMONTEMP()
	{
		m_pTPOPUP = NULL;
		m_strTITLE.Empty();
		m_strNAME.Empty();

		for( INT i=0 ; i < ES_COUNT ; ++i )
			m_pTITEM[ i ] = NULL;

		m_dwSpawnSND = 0;
		m_dwOBJ = 0;

		 m_fLOST = 0.0f;
		 m_fLB = 0.0f;
		 m_fAB = 0.0f;

		 m_fScaleX = 0.0f;
		 m_fScaleY = 0.0f;
		 m_fScaleZ = 0.0f;

		 for( INT i=0 ; i < TMONSKILL_COUNT ; ++i )
			m_wTSKILL[ i ] = 0;

		m_wFaceIcon = 0;
		m_wSpawnSFX = 0;
		m_wKind = 0;

		m_bNotNockBack = FALSE;
		m_bCanSelected = TRUE;
		m_bCanFly = TRUE;
		m_bCanAttack = TRUE;
		m_bDrawName = TRUE;
		m_bVisible = TRUE;
		m_bApplyAI = FALSE;
		m_bCanTame = FALSE;

		m_fSize = 0.0f;
		m_bCanDetectHidingPC = FALSE;
		m_bSlidingWhenDie = TRUE;
		m_bDrawNameWhenDie = TRUE;
	}
};

struct tagTNPCTEMP
{
	WORD m_wFaceIcon;
	WORD m_wID;

	LPTITEM m_pTITEM[ES_COUNT];
	BYTE m_bActionID;
	BYTE m_bBoxAnim; 

	BYTE m_bRndActID[TNPC_RNDACT_COUNT];

	DWORD m_dwOBJ;
	DWORD m_dwSND;

	tagTNPCTEMP()
	{
		for(int i=0; i<TNPC_RNDACT_COUNT; ++i)
			m_bRndActID[i] = (BYTE)T_INVALID;
	}
};

struct tagTNPC
{
	LPTPOPUPMENU m_pTPOPUP;
	LPTNPCTEMP m_pTNPC;

	DWORD m_dwQuestID;
	DWORD m_dwHouseID;
	DWORD m_dwExecID;
	DWORD m_dwMaxHP;
	DWORD m_dwID;

	WORD m_wItemID;

	CString m_strTITLE;
	CString m_strNAME;

	BYTE m_bCollisionType;
	BYTE m_bCanSelected;
	BYTE m_bCountryID;
	BYTE m_bDrawGhost;
	BYTE m_bHouseMesh;
	BYTE m_bDrawMark;
	BYTE m_bDrawName;
	BYTE m_bNPCType;
	BYTE m_bClassID;
	BYTE m_bLevel;
	BYTE m_bLand;
	BYTE m_bMode;
	BYTE m_bCamp;

	FLOAT m_fScaleX;
	FLOAT m_fScaleY;
	FLOAT m_fScaleZ;

	FLOAT m_fSizeX;
	FLOAT m_fSizeY;
	FLOAT m_fSizeZ;
	FLOAT m_fPosX;
	FLOAT m_fPosY;
	FLOAT m_fPosZ;
	FLOAT m_fDIR;

	tagTNPC()
	{
		m_pTPOPUP = NULL;
		m_pTNPC = NULL;

		m_dwQuestID = 0;
		m_dwHouseID = 0;
		m_dwExecID = 0;
		m_dwMaxHP = 0;
		m_dwID = 0;

		m_strTITLE.Empty();
		m_strNAME.Empty();

		m_bCollisionType = 0;
		m_bNPCType = 0;
		m_bClassID = 0;
		m_wItemID = 0;
		m_bLevel = 0;
		m_bCamp = 0;

		m_bCanSelected = TRUE;
		m_bHouseMesh = FALSE;
		m_bDrawGhost = FALSE;
		m_bDrawName = TRUE;
		m_bLand = FALSE;

		m_bDrawMark = TDRAWMARK_DEFAULT;
		m_bCountryID = TCONTRY_N;
		m_bMode = MT_NORMAL;

		m_fScaleX = 1.0f;
		m_fScaleY = 1.0f;
		m_fScaleZ = 1.0f;

		m_fSizeX = 0.0f;
		m_fSizeY = 0.0f;
		m_fSizeZ = 0.0f;
		m_fPosX = 0.0f;
		m_fPosY = 0.0f;
		m_fPosZ = 0.0f;
		m_fDIR = 0.0f;
	};
};

struct tagTFORMULA
{
	DWORD m_dwInit;
	FLOAT m_fRateX;
	FLOAT m_fRateY;
};

struct tagTSWITCH
{
	LPTITEM m_pTITEM[ES_COUNT];
	DWORD m_dwSoundID;
	DWORD m_dwHouseID;
	DWORD m_dwID;

	FLOAT m_fScaleX;
	FLOAT m_fScaleY;
	FLOAT m_fScaleZ;

	FLOAT m_fPosX;
	FLOAT m_fPosY;
	FLOAT m_fPosZ;
	FLOAT m_fDIR;

	DWORD m_dwOBJ;
	WORD m_wMapID;

	BYTE m_bLockOnClose;
	BYTE m_bLockOnOpen;

	BYTE m_bCloseID;
	BYTE m_bOpenID;
	BYTE m_bHouseMesh;
};

struct tagTSKYBOX
{
	DWORD m_dwOBJ;
	DWORD m_dwCLK;
	DWORD m_dwCL;
	DWORD m_dwMESH;
	DWORD m_dwACT;
	DWORD m_dwANI;
};

struct tagTLIGHT
{
	D3DXVECTOR3 m_vDIR;

	FLOAT m_fAmbientR;
	FLOAT m_fAmbientG;
	FLOAT m_fAmbientB;

	FLOAT m_fDiffuseR;
	FLOAT m_fDiffuseG;
	FLOAT m_fDiffuseB;
};

struct tagTLEVEL
{
	BYTE m_bLevel;			/// 레벨
	DWORD m_dwCost;			/// 기준 골드
	DWORD m_dwRegCost;		/// 등록 비용
	DWORD m_dwSearchCost;	/// 검색 비용
};

struct tagTFOG
{
	BYTE m_bType;

	BYTE m_bRValue;
	BYTE m_bGValue;
	BYTE m_bBValue;

	FLOAT m_fRADIUS;
	FLOAT m_fRANGE;
	FLOAT m_fPosX;
	FLOAT m_fPosZ;

	FLOAT m_fDENSITY;
	FLOAT m_fSTART;
	FLOAT m_fEND;
};

struct tagTUNITFOG
{
	LPTFOG m_pTGLOBAL;
	VTFOG m_vTLOCAL;

	tagTUNITFOG()
	{
		m_vTLOCAL.clear();
		m_pTGLOBAL = NULL;
	};

	~tagTUNITFOG()
	{
		while(!m_vTLOCAL.empty())
		{
			delete m_vTLOCAL.back();
			m_vTLOCAL.pop_back();
		}

		if(m_pTGLOBAL)
		{
			delete m_pTGLOBAL;
			m_pTGLOBAL = NULL;
		}
	};
};

struct tagTGATE
{
	LPTITEM m_pTITEM[ES_COUNT];
	DWORD m_dwSwitchID;
	DWORD m_dwHouseID;
	DWORD m_dwID;

	DWORD m_dwCloseSFX;
	DWORD m_dwOpenSFX;

	FLOAT m_fScaleX;
	FLOAT m_fScaleY;
	FLOAT m_fScaleZ;

	FLOAT m_fPosX;
	FLOAT m_fPosY;
	FLOAT m_fPosZ;
	FLOAT m_fDIR;

	DWORD m_dwOBJ;
	WORD m_wMapID;

	BYTE m_bDeleteOnClose;
	BYTE m_bDeleteOnOpen;

	BYTE m_bCloseActID;
	BYTE m_bOpenActID;

	BYTE m_bCloseID;
	BYTE m_bOpenID;
	BYTE m_bHouseMesh;
	BYTE m_bStair;
};

struct tagTITEMMAGIC
{
	WORD	m_wID;
	CString	m_strNAME;
	BYTE	m_bSecOption;	///< 보조옵션 여부
	FLOAT	m_fUtil;		///< 유틸값 (옵션 랭킹을 정할때 사용)
	BYTE	m_bSFX;			///< 이펙트 그룹

	tagTITEMMAGIC()
	:	m_wID(0),
		m_bSecOption(TRUE),
		m_fUtil(1.0f),
		m_bSFX(0)
	{}
};

struct tagTPET
{
	WORD			m_wID;
	WORD 			m_wMonID;
	BYTE 			m_bRecallKind1;
	BYTE 			m_bRecallKind2;
	WORD 			m_wRecallValue1;
	WORD 			m_wRecallValue2;
	BYTE 			m_bConditionType;
	DWORD			m_dwConditionValue;
	WORD			m_wIcon;
};

struct tagTITEMATTR
{
	WORD	m_wID;
	BYTE	m_bGrade;
	WORD	m_wMinAP;
	WORD	m_wMaxAP;
	WORD	m_wDP;
	WORD	m_wMinMAP;
	WORD	m_wMaxMAP;
	WORD	m_wMDP;
	BYTE	m_bBlockProb;
	BYTE	m_bSpeedInc;
};

struct tagTITEMGRADE
{
	BYTE	m_bLevel;
	BYTE	m_bGrade;
	DWORD	m_dwCost;

	tagTITEMGRADE()
	{	
		m_bLevel = 0;
		m_bGrade = 0;
		m_dwCost = 0;
	}
};

struct tagTITEMGRADEVISUALKEY
{
	BYTE m_bKind;
	WORD m_wGrade;

	struct tagTITEMGRADEVISUALKEY()
	{}

	struct tagTITEMGRADEVISUALKEY( BYTE _bKind, WORD _wGrade)
		: m_bKind(_bKind),
		m_wGrade(_wGrade)
	{}

	bool operator < (const tagTITEMGRADEVISUALKEY& l) const
	{
		if( m_bKind == l.m_bKind )
		{
			return m_wGrade < l.m_wGrade;
		}
		else
			return m_bKind < l.m_bKind;
	}
};

struct tagTITEMGRADEVISUAL
{
	LPTEXTURESET m_pSkinTex;
	BYTE m_bPSTYPE;
};

struct tagTHELP
{
	DWORD m_dwCategoryID;
	VTHELPPAGE m_vPage;
};

struct tagTHELPPAGE
{
	WORD m_wPage;
	WORD m_wImage;
	CString m_strTitle;
	CString m_strText;
};

struct tagTLIGHTPOS
{
	DWORD m_dwID;

	D3DXVECTOR3 m_vPOS;
	D3DXVECTOR3 m_vDIR;
};

struct tagTGODTOWER
{
	DWORD m_dwID;

	CString m_strName;
	FLOAT m_fRot;
	DWORD m_dwOBJID;
	DWORD m_dwIconID;
	DWORD m_dwSfxAtkID;
	DWORD m_dwSfxDefID;
	DWORD m_dwSfxNorID;
};

struct tagTGODBALL
{
	DWORD m_dwID;

	CString m_strName;
	FLOAT m_fRot;
	DWORD m_dwOBJID;
	DWORD m_dwIconID;
	DWORD m_dwSfxID;
};

struct tagTMONSHOP
{
	DWORD	m_dwID;

	CString	m_strName;
	DWORD	m_dwSpawnID;
    DWORD	m_dwIcon;
};

struct tagTPORTALREGION
{
	WORD		m_wID;
	CString		m_strName;
};

struct tagTMANTLECOORD
{
	D3DXVECTOR2 m_vLeftTop;
	D3DXVECTOR2 m_vRightTop;
	D3DXVECTOR2 m_vLeftBottom;
	D3DXVECTOR2 m_vRightBottom;

	struct tagTMANTLECOORD() {};
	struct tagTMANTLECOORD( D3DXVECTOR2 vLeftTop, D3DXVECTOR2 vRightTop, D3DXVECTOR2 vLeftBottom, D3DXVECTOR2 vRightBottom )
		: m_vLeftTop(vLeftTop), m_vRightTop(vRightTop), m_vLeftBottom(vLeftBottom), m_vRightBottom(vRightBottom) {};

	static struct tagTMANTLECOORD m_vDefaultUV1;
	static struct tagTMANTLECOORD m_vDefaultUV2;
	static struct tagTMANTLECOORD m_vDefaultUV3;
	static BOOL IsDefaultCoordUV1( struct tagTMANTLECOORD& uv1 );
	static BOOL IsDefaultCoordUV2( struct tagTMANTLECOORD& uv2 );
	static BOOL IsDefaultCoordUV3( struct tagTMANTLECOORD& uv3 );

	static struct tagTMANTLECOORD m_vDefaultUV1_OLD;
	static struct tagTMANTLECOORD m_vDefaultUV2_OLD;
	static struct tagTMANTLECOORD m_vDefaultUV3_OLD;
	static BOOL IsDefaultCoordUV1_OLD( struct tagTMANTLECOORD& uv1 );
	static BOOL IsDefaultCoordUV2_OLD( struct tagTMANTLECOORD& uv2 );
	static BOOL IsDefaultCoordUV3_OLD( struct tagTMANTLECOORD& uv3 );
};

struct tagTMANTLECOORDINFO
{
	CString m_strMeshName;
	VTMANTLECOORD m_vUV1;
	VTMANTLECOORD m_vUV2;
	VTMANTLECOORD m_vUV3;
};

struct tagTMANTLEDETAILKEY
{
	BYTE m_bRaceID;
	BYTE m_bSexID;
	DWORD m_dwCond;

	struct tagTMANTLEDETAILKEY()
		: m_bRaceID(-1),
		m_bSexID(-1),
		m_dwCond(-1)
	{}

	struct tagTMANTLEDETAILKEY( BYTE bRaceID, BYTE bSexID, DWORD dwCond )
		: m_bRaceID( bRaceID ),
		m_bSexID( bSexID ),
		m_dwCond( dwCond )
	{}

	bool operator < (const struct tagTMANTLEDETAILKEY& l) const
	{
		if( m_bRaceID == l.m_bRaceID )
		{
			if( m_bSexID == l.m_bSexID )
				return m_dwCond < l.m_dwCond;
			else
				return m_bSexID < l.m_bSexID;
		}
		else
			return m_bRaceID < l.m_bRaceID;
	};
};

struct tagTMANTLECOORDKEY
{
	BYTE m_bRaceID;
	BYTE m_bSexID;
	DWORD m_dwMeshID;

	struct tagTMANTLECOORDKEY()
		: m_bRaceID(-1),
		m_bSexID(-1),
		m_dwMeshID(-1)
	{}

	struct tagTMANTLECOORDKEY( BYTE bRaceID, BYTE bSexID, DWORD dwMeshID )
		: m_bRaceID( bRaceID ),
		m_bSexID( bSexID ),
		m_dwMeshID( dwMeshID )
	{}

	bool operator < (const struct tagTMANTLECOORDKEY& l) const
	{
		if( m_bRaceID == l.m_bRaceID )
		{
			if( m_bSexID == l.m_bSexID )
				return m_dwMeshID < l.m_dwMeshID;
			else
				return m_bSexID < l.m_bSexID;
		}
		else
			return m_bRaceID < l.m_bRaceID;
	};
};

struct tagTAUCTIONTREE
{
	union	TREE_ID
	{
		struct
		{
			DWORD	KindID : 8;
			DWORD	Class : 8;
			DWORD	Depth : 8;
			DWORD	Zero : 8;
		};

		DWORD	dwValue;
	};

	TREE_ID	m_ID;
	CString	m_strName;

	tagTAUCTIONTREE()
	{
		m_ID.dwValue = 0x00000000;
		m_strName.Empty();
	}
};

struct tagTFAMETITLE
{
	CString		m_strFameName;		// 칭호
	BYTE		m_bSFX;				// SFX 사용 여부
	BYTE		m_bSFXID;			// SFX ID
};

struct tagTEQUIPCREATECHAR
{
	enum
	{
		TE_MAINWEAPON,
		TE_SUBWEAPON,
		TE_LONGWEAPON,
		TE_HEAD,
		TE_BODY,
		TE_PANTS,
		TE_HAND,
		TE_FOOT,
		TE_BACK,
		TE_COUNT
	};

	BYTE		m_bCountry;					// 국가
	BYTE		m_bClass;					// 직업
	BYTE		m_bSex;						// 성별
	WORD		m_wItemID[ TE_COUNT ];		// 아이템아이디
	WORD		m_wGrade[ TE_COUNT ];		// 강화단계
	BYTE		m_bGradeEffect[ TE_COUNT ];	// 강화이펙트
};

struct tagTRPS
{
	WORD wNeedItem;
	WORD wRewardItem1;
	BYTE bRewardCount1;
	WORD wRewardItem2;
	BYTE bRewardCount2;
	DWORD dwRewardMoney;
};