//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TQuestPath.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_DIALOG_TPATHWND_MAIN        101
#define IDR_MAINFRAME                   128
#define IDR_TQuestPathTYPE              129
#define IDS_FMT_DEF_QCLASS_NAME         129
#define IDS_ERR_LOAD_GAME               130
#define IDD_DIALOG_SCALE                130
#define IDB_BITMAP_TREEIMG              131
#define IDS_TQUEST_START_POS            131
#define IDD_DIALOG_TPATHWND_NPC         131
#define IDS_TQUEST_COMP_POS             132
#define IDD_DIALOG_TPATHWND_MON         132
#define IDB_BITMAP_CHECKIMG             132
#define IDS_FMT_OBJECTIVE_POS           133
#define IDD_DIALOG_EXPORT               133
#define IDS_NPC_NAME_NONE               134
#define IDD_DIALOG_TPATHWND_MAP         134
#define IDS_NPC_NAME_NOT_FOUND          135
#define IDD_DIALOG_TPATHWND_POS         135
#define IDS_FMT_NPC_NAME                136
#define IDD_DIALOG_IMPORT               136
#define IDS_FMT_TTERM_FILTER            137
#define IDD_DIALOG_ERRBOUND             137
#define IDS_ERR_LOAD_QUEST              138
#define IDD_DIALOG_PROGRESS             138
#define IDS_FMT_POS_DATA                139
#define IDS_ERR_SAVE_TPD                140
#define IDS_ERR_LOAD_TPD                141
#define IDS_FMT_SCALE                   142
#define IDS_FMT_POS_X                   143
#define IDS_FMT_POS_Z                   144
#define IDS_MSG_LOCK                    145
#define IDS_MSG_UNLOCK                  146
#define IDS_MSG_AUTOSET                 147
#define IDS_MSG_EXPORT                  148
#define IDS_FMT_EXPORT                  149
#define IDS_MSG_IMPORT                  150
#define IDS_FMT_MAPNAME                 151
#define IDS_FMT_UNITNAME                152
#define IDS_FMT_MEXPORT                 153
#define IDS_MSG_CLEAR_PATH              154
#define IDS_MSG_CLEAR_MAP               155
#define IDS_MSG_PATH_CLEAR              156
#define IDS_TITLE_BUILD                 157
#define IDS_MSG_BUILD_CANCEL            158
#define IDS_MSG_BUILD_TQUEST            159
#define IDS_FMT_BUILD_TMAP              160
#define IDS_TITLE_FIND_PATH             161
#define IDS_MSG_FIND_CANCEL             162
#define IDS_MSG_FIND_PATH               163
#define IDS_FMT_PATH_DATA               164
#define IDI_ICON_FOLDER                 170
#define IDI_ICON_FIND_NPC               171
#define IDI_ICON_PICK_POS               172
#define IDC_PROGRESS                    1000
#define IDC_STATIC_PERCENT              1001
#define IDC_STATIC_STATUS               1002
#define IDC_LIST_STEP                   1003
#define IDC_EDIT_NPC_NAME               1004
#define IDC_EDIT_MESSAGE                1005
#define IDC_STATIC_QUEST_ID             1006
#define IDC_LIST_MON                    1007
#define IDC_STATIC_NPC_ID               1010
#define IDC_EDIT_NPC_MAP_ID             1011
#define IDC_EDIT_NPC_POS_X              1012
#define IDC_EDIT_SCALE                  1012
#define IDC_EDIT_NPC_POS_Y              1013
#define IDC_EDIT_NPC_POS_Z              1014
#define IDC_BUTTON_SHOW_NPC             1015
#define IDC_FILTER_NPC_ID               1015
#define IDC_BUTTON_PICK_POS             1016
#define IDC_FILTER_MAP_ID               1016
#define IDC_BUTTON_AUTO_SET             1017
#define IDC_FILTER_NPC_NAME             1017
#define IDC_BUTTON_RESTORE              1018
#define IDC_EDIT_NPC_ID                 1018
#define IDC_BUTTON_APPLY                1019
#define IDC_STATIC_MON_KIND             1020
#define IDC_BUTTON_SHOW_MON             1021
#define IDC_CHECK_LOCK                  1022
#define IDC_BUTTON_CANCEL               1023
#define IDC_LIST_NPC                    1024
#define IDC_CHECK_MAP_ID                1025
#define IDC_CHECK_NPC_ID                1026
#define IDC_CHECK_NPC_NAME              1027
#define IDC_CHECK_MON_ID                1027
#define IDC_FILTER_MON_ID               1028
#define IDC_CHECK_MON_KIND              1029
#define IDC_FILTER_MON_KIND             1030
#define IDC_CHECK_MON_NAME              1031
#define IDC_FILTER_MON_NAME             1032
#define IDC_EDIT_MON_KIND               1033
#define IDC_EDIT_MON_MAP_ID             1034
#define IDC_EDIT_MON_POS_X              1035
#define IDC_EDIT_MON_POS_Y              1036
#define IDC_EDIT_MON_POS_Z              1037
#define IDC_TREE_QUEST                  1038
#define IDC_BUTTON_SEL_ALL              1039
#define IDC_BUTTON_CLEAR_ALL            1040
#define IDC_LIST_MAP                    1040
#define IDC_BUTTON_EXPORT               1041
#define IDC_LIST_UNIT                   1041
#define IDC_TREE_MAP                    1042
#define IDC_BUTTON_MSEL_ALL             1043
#define IDC_BUTTON_MCLEAR_ALL           1044
#define IDC_BUTTON_MEXPORT              1045
#define IDC_RADIO_ADD_POINT             1047
#define IDC_RADIO_DEL_POINT             1048
#define IDC_BUTTON_QUEST                1048
#define IDC_RADIO_ADD_BLOCK             1049
#define IDC_BUTTON_PATH                 1049
#define IDC_RADIO_ADD_PATH              1050
#define IDC_RADIO_DEL_LINE              1051
#define IDC_RADIO_TEST_PATH             1052
#define IDC_RADIO_MOVE_POINT            1053
#define IDC_BUTTON_CLEAR                1054
#define IDC_EDIT_BOUND                  1055
#define ID_Menu                         32772
#define ID_DB_LOAD_QUEST                32774
#define ID_DB_LOAD_GAME                 32775
#define ID_DB_LOAD_MAP                  32778
#define ID_MAP_SCALE                    32781
#define ID_DB_LOCK_ALL                  32783
#define ID_DB_AUTOSET_ALL               32785
#define ID_DB_UNLOCK_ALL                32786
#define ID_MAP_GOTO_TPOINT              32788
#define ID_FILE_EXPORT                  32789
#define ID_FILE_IMPORT                  32790
#define ID_MAP_EDITMODE                 32792
#define ID_FILE_BUILD                   32794
#define ID_MAP_IMP_ERR_BOUND            32796
#define ID_PROGRESS_UPDATE              32797
#define ID_PROGRESS_EXIT                32798

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
