#include "StdAfx.h"

BEGIN_INIT_QUERY(TInstallSvr)
	PREDEFINE_QUERY(CSPLoadService)
	PREDEFINE_QUERY(CSPRegistSegment)
	PREDEFINE_QUERY(CSPTDeleteIP)
	PREDEFINE_QUERY(CSPTGetContry)
	PREDEFINE_QUERY(CTBLCheckaddr)
	PREDEFINE_QUERY(CTBLInstallIPaddr)
	PREDEFINE_QUERY(CTBLInstallVer)
	PREDEFINE_QUERY(CTBLInstallFile)
	PREDEFINE_QUERY(CTBLSegmentCheck)
	
END_INIT_QUERY()
