//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TQuestEditor.rc
//
#define IDC_BUTTON_ADD_CLASS            2
#define IDC_BUTTON_EDIT_CLASS           3
#define IDC_BUTTON_DEL_CLASS            4
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TQUESTYPE                   129
#define IDS_FMT_DEL_CLASS_ERROR         129
#define IDD_DIALOG_QUEST                130
#define IDP_OLE_INIT_FAILED             130
#define IDB_BITMAP_TREEIMG              131
#define ID_FMT_OVERLAPMONID             131
#define IDR_POPUP                       132
#define ID_ALREADY_OPENED_TMONCHART     132
#define ID_NOT_LOADED_TMONTEMP          133
#define ID_NOT_COLLECT_QUEST            134
#define ID_SUCCESS_PRINT_SUMMARY        135
#define IDD_DIALOG_EDIT_CLASS           138
#define IDD_DIALOG_ADD_CLASS            139
#define IDD_DIALOG_FIND_QUEST           141
#define IDD_DIALOG_LIST_FIND_QUEST      142
#define IDD_DIALOG_CLASS_TITLE          143
#define IDD_DIALOG_CHGPARENT            144
#define IDC_STATIC_QUESTID              1001
#define IDC_STATIC_TYPE                 1004
#define IDC_STATIC_TRIGGERTYPE          1005
#define IDC_EDIT_TYPE                   1006
#define IDC_EDIT_TRIGGERTYPE            1007
#define IDC_STATIC_TRIGGERID            1008
#define IDC_EDIT_TRIGGERID              1009
#define IDC_STATIC_TRIGGERMSG           1010
#define IDC_EDIT_TRIGGERMSG             1011
#define IDC_STATIC_COMPLETEMSG          1012
#define IDC_EDIT_COMPLETEMSG            1013
#define IDC_STATIC_COUNTMAX             1014
#define IDC_EDIT_COUNTMAX               1015
#define IDC_STATIC_ACCEPTMSG            1016
#define IDC_STATIC_FORCERUN             1017
#define IDC_STATIC_REJECTMSG            1018
#define IDC_EDIT_FORCERUN               1019
#define IDC_LIST_CONDITION              1020
#define IDC_LIST_REWARD                 1021
#define IDC_LIST_TERM                   1022
#define IDC_BUTTON_ADDCON               1023
#define IDC_BUTTON_DELCON               1024
#define IDC_BUTTON_ADDTERM              1025
#define IDC_BUTTON_DELTERM              1026
#define IDC_BUTTON_ADDREWARD            1027
#define IDC_BUTTON_DELREWARD            1028
#define IDC_STATIC_CONTYPETEXT          1029
#define IDC_EDIT_CONTYPE                1030
#define IDC_STATIC_CONIDTEXT            1031
#define IDC_EDIT_CONID                  1032
#define IDC_STATIC_CONCOUNTTEXT         1033
#define IDC_EDIT_CONCOUNT               1034
#define IDC_STATIC_OBJECTIVETEXT        1035
#define IDC_EDIT_OBJECTIVE              1036
#define IDC_STATIC_INCOMPMSG            1037
#define IDC_EDIT_INCOMPMSG              1038
#define IDC_STATIC_TERMTYPE             1039
#define IDC_EDIT_TERMTYPE               1040
#define IDC_STATIC_TERMID               1041
#define IDC_EDIT_TERMID                 1042
#define IDC_EDIT_ACCEPTMSG              1043
#define IDC_EDIT_REJECTMSG              1044
#define IDC_STATIC_TERMCOUNT            1045
#define IDC_EDIT_COUNT                  1046
#define IDC_STATIC_REWARDTYPE           1047
#define IDC_EDIT_REWARDTYPE             1048
#define IDC_STATIC_REWARDID             1049
#define IDC_EDIT_REWARDID               1050
#define IDC_STATIC_REWARDCOUNT          1051
#define IDC_EDIT_REWARDCOUNT            1052
#define IDC_STATIC_TAKEMETHOD           1053
#define IDC_STATIC_TAKEDATA             1054
#define IDC_EDIT_TAKEMETHOD             1055
#define IDC_EDIT_TAKEDATA               1056
#define IDC_CLASS_LIST                  1057
#define IDC_STATIC_CLASS_ID             1058
#define IDC_CLASS_ID                    1059
#define IDC_STATIC_CLASS_NAME           1060
#define IDC_STATIC_SUMMARYMSG           1061
#define IDC_STATIC_NPC_NAME             1062
#define IDC_EDIT_NPC_NAME               1063
#define IDC_STATIC_PLAYER_ANSWER        1064
#define IDC_EDIT_PLAYER_ANSWER          1065
#define IDC_STATIC_LEVEL                1066
#define IDC_STATIC_CLASS_INFO           1067
#define IDC_EDIT_TRIGGERID2             1068
#define IDC_EDIT_LEVEL                  1068
#define IDC_STATIC_QUESTMOB             1069
#define IDC_STATIC_QUESTPATHMOB         1070
#define IDC_STATIC_QUESTTIME            1071
#define IDC_STATIC_REWARDTYPE6          1073
#define IDC_STATIC_TICKETID             1073
#define IDC_EDIT_SUMMARYMSG             1074
#define IDC_EDIT_QUESTMOB               1075
#define IDC_EDIT_QUESTTIME              1076
#define IDC_EDIT_QUESTPATHMOB           1077
#define IDC_EDIT_TICKETID               1078
#define IDC_LIST_CLASS                  1083
#define IDC_EDIT_NAME                   1084
#define IDC_EDIT_SEARCH_TEXT            1086
#define IDC_RADIO_SEARCHTYPE_SENTENCE   1087
#define IDC_RADIO_SEARCHTYPE_WORD       1088
#define ID_SELECT_QUEST_ITEM            1089
#define IDC_CHECK_EDIT_CONTROL_ENABLE   1090
#define IDC_CHECK_MAIN_QUEST            1091
#define IDC_CHECK_MAIN_CATEGORY         1092
#define IDC_RADIO1                      1092
#define IDC_EDIT_TITLE_CLASS            1093
#define IDC_COMBO1                      1094
#define IDC_COMBO_MAINCLASS             1094
#define IDC_STATIC_MAINQUEST            1095
#define IDC_CHECK1                      1096
#define IDC_CHECK_CONCHECK              1096
#define IDC_CHECK_SENDQ                 1097
#define IDC_EDIT_PARENTID               1098
#define IDC_LIST_FIND_QUEST             1470
#define ID_DATABASE_OPEN                32771
#define ID_DATABASE_CLOSE               32772
#define ID_QUEST_ADD                    32775
#define ID_QUEST_DELETE                 32776
#define ID_POPUP_CANCEL                 32779
#define ID_EDIT_CLASS                   32788
#define ID_QUEST_FIND                   32791
#define ID_FIND                         32792
#define ID_LOCK                         32793
#define ID_CHILD_EXPAND                 32795
#define ID_SHOW_CLASSTITLEDLG           32797
#define ID_QUEST_CHGPARENT              32799
#define ID_OPEN_TMONCHART               32801
#define ID_QUEST_PRINTSUMMARY           32803
#define ID_COPY                         32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
