 
// ?? (ID_* ? IDM_*) 
#define HID_BUTTON_ADD                          0x10003
#define HID_BUTTON_EDIT                         0x10004
#define HID_BUTTON_DEL                          0x10005
#define HID_BUTTON_EDIT2                        0x10006
#define HID_BUTTON_EDIT_COLOR                   0x10006
#define HID_VIEW_MENUBAR                        0x10082
#define HID_VIEW_WORKSPACE                      0x10083
#define HID_VIEW_PREVIEW                        0x10084
#define HID_PROGRESS_UPDATE                     0x1008B
#define HID_PROGRESS_EXIT                       0x1008D
#define HID_GRID_TOGGLE                         0x10091
#define HID_NOT_MATCH_COUNT                     0x10093
#define HID_ITEM_NEWPROJECT                     0x10096
#define HID_CANCEL                              0x1009A
#define HID_ITEM_NEWFOLDER                      0x1009C
#define HID_ITEM_ADD                            0x1009D
#define HID_ITEM_UPDATE                         0x1009E
#define HID_ITEM_DELETE                         0x1009F
#define HID_GRID_SHOW                           0x100D8
#define HID_GRID_TOP                            0x100D9
#define HID_GRID_FRONT                          0x100DA
#define HID_GRID_LEFT                           0x100DB
#define HID_GRID_PERSPECTIVE                    0x100DC
#define HID_GRID_NAVIGATE                       0x100DD
#define HID_GRID_CAMRESET                       0x100DE
#define HID_OBJ_EDIT_ATTR                       0x100EB
#define HID_BUILD                               0x10121
#define HID_GRID_SHOW_EDGE                      0x10140
#define HID_MAP_BACK                            0x10147
#define HID_MDI_NEXT                            0x10175
#define HID_BUTTON_NONHIDE                      0x105C1
#define HID_BUTTON_HIDE                         0x105C2
#define HID_BUTTON_NONFREEZE                    0x105C3
#define HID_BUTTON_FREEZE                       0x105C4
#define HID_MAKE_FAR_IMAGE                      0x10613
#define HID_IMP_OK                              0x1061F
#define HID_BUTTON_DISABLE                      0x1063A
#define HID_BUTTON_ENABLE                       0x1063C
#define HID_BUTTON_CLEAN_UNIT_OBJ               0x1063F
#define HID_BUTTON_CDATAUP                      0x1067E
#define HID_BUTTON_CDATAUP2                     0x1067F
#define HID_BUTTON_CDATADOWN                    0x1067F
#define HID_EXP_OBJ                             0x18019
#define HID_IMP_OBJ                             0x1801A
#define HID_EXP_GEO                             0x1801B
#define HID_IMP_GEO                             0x1801C
#define HID_EDITMENU                            0x1801D
#define HID_EDITFONT                            0x1801E
#define HID_FILE_MERGE                          0x1801F
#define HID_EXP_BSP                             0x18020
#define HID_IMP_BSP                             0x18021
#define HID_EXP_BSPOBJ                          0x18022
#define HID_IMP_BSPOBJ                          0x18023
#define HID_FREEZEMODE_DIALOG                   0x18024
#define HID_SELBYNAME_DIALOG                    0x18025
#define HID_HIDEMODE_DIALOG                     0x18026
#define HID_OBJECTALLLIST_DIALOG                0x18027
#define HID_EDIT_FOV                            0x18028
#define HID_HOTKEY_EDIT_TEXTURE                 0x18029
#define HID_HOTKEY_EDIT_DETAIL                  0x1802A
#define HID_HOTKEY_EDIT_HEIGHT                  0x1802B
#define HID_HOTKEY_MAKE_FLAT                    0x1802C
#define HID_HOTKEY_MAKE_SMOOTH                  0x1802D
#define HID_HOTKEY_HEIGHT_BRUSH                 0x1802E
#define HID_HOTKET_EDIT_OBJECT                  0x1802F
#define HID_GROUP_OBJECT_KEY_1                  0x18030
#define HID_GROUP_OBJECT_KEY_2                  0x18031
#define HID_GROUP_OBJECT_KEY_3                  0x18032
#define HID_GROUP_OBJECT_KEY_4                  0x18033
#define HID_GROUP_OBJECT_KEY_5                  0x18034
#define HID_GROUP_OBJECT_KEY_6                  0x18035
#define HID_GROUP_OBJECT_KEY_7                  0x18036
#define HID_GROUP_OBJECT_KEY_8                  0x18037
#define HID_GROUP_OBJECT_KEY_9                  0x18038
#define HID_GROUP_OBJECT_KEY_0                  0x18039
#define HID_SELECT_EQUALOBJ                     0x1803B
#define HID_CLEAR_SELOBJ                        0x1803D
#define HID_Menu                                0x1803F
#define HID_REGULATE_ITEM_TEX                   0x18043
#define HID_REGULATE_TEX                        0x18044
#define HID_EXTMAPITEM_REGULATE_TEX             0x18045
#define HID_EXTMAPITEM_SS                       0x18046
#define HID_RESET_VB                            0x18049
#define HID_NOTUSE_VB                           0x1804C
#define HID_BUTTON32845                         0x1804D
#define HID_MAP_ENABLEUNIT                      0x1804F
#define HID_GRID_BACKIMAGE                      0x18050
#define HID_BACKIMG_SET                         0x18053
#define HID_BACKIMG_SHOW                        0x18054
#define HID_BACKIMG_LOAD                        0x18056
#define HID_BACKIMAGE_SETBACKIMAGE              0x18057
#define HID_MENU_OPTIONSIZE                     0x1805C
#define HID_MENU_FULLSIZE                       0x1805D
#define HID_MENU_TEXHI                          0x18060
#define HID_MENU_TEXMID                         0x18061
#define HID_MENU_TEXLOW                         0x18063
#define HID_MAP_EDITDETAIL                      0x18067
#define HID_ITEM_EXPORT                         0x18069
#define HID_MENU_AUTOLOD                        0x1806C
#define HID_TOGGLE_BRUSHSHAPE                   0x18071
#define HID_EXT_BUILDTEXTURESHADOW              0x18075
#define HID_ITEM_BATCHFORMATCHANGE              0x18078
#define HID_MENU_LOCEXP                         0x18079
#define HID_MENU_LOCIMP                         0x1807A
#define HID_EXPORTITEMINFOLDER                  0x1807D
#define HID_FOLDER_LISTUP                       0x1807E
#define HID_BUTTON32896                         0x18080
#define HID_MENU_LISTUPDATE                     0x18080
#define HID_FINDER                              0x18082
#define HID_Menu32904                           0x18088
#define HID_ITEM_SCREENSHOT                     0x18089
#define HID_MENU_UPDATE_SIZE                    0x18092
#define HID_BTN_EXPLORER                        0x18095
#define HID_GRID_EXPLORER                       0x18096
#define HID_FILE_SET_TEMPPATH                   0x18098
 
// ???? (IDP_*) 
 
// ??? (IDR_*) 
#define HIDR_MANIFEST                           0x20001
#define HIDR_MAINFRAME                          0x20080
#define HIDR_GameStudioTYPE                     0x20081
#define HIDR_HIDDEN                             0x20089
#define HIDR_POPUP                              0x20095
#define HIDR_GRIDTYPE                           0x20097
#define HIDR_OBJECT                             0x20098
#define HIDR_MAPTYPE                            0x20099
#define HIDR_TEXTURE_SFX                        0x20151
#define HIDR_TEXTURE_SND                        0x20153
#define HIDR_MESH_BOX                           0x20155
#define HIDR_TEXTURE_LIGHT                      0x2015A
#define HIDR_TEXTURE_LIGHTTARGET                0x2015C
#define HIDR_SHADER_PIXEL                       0x20162
#define HIDR_PS_STAGE1                          0x20163
#define HIDR_SHADER_VERTEX                      0x20166
#define HIDR_VS_WMESH                           0x20167
#define HIDR_VS_MESH                            0x2016A
#define HIDR_VS_LVERTEX                         0x2016C
#define HIDR_PS_MODULATE                        0x2016E
#define HIDR_PS_MODULATE2X                      0x20170
#define HIDR_PS_MODULATE4X                      0x20172
#define HIDR_PS_ADD                             0x20174
#define HIDR_PS_ADDSIGNED                       0x20177
#define HIDR_PS_ADDSIGNED2X                     0x20179
#define HIDR_PS_SUBTRACT                        0x2017B
#define HIDR_PS_ADDSMOOTH                       0x2017D
#define HIDR_PS_BLENDDIFFUSEALPHA               0x2017F
#define HIDR_PS_BLENDTEXTUREALPHA               0x20181
#define HIDR_PS_BLENDFACTORALPHA                0x20183
#define HIDR_PS_BLENDTEXTUREALPHAPM             0x20185
#define HIDR_PS_BLENDCURRENTALPHA               0x20187
#define HIDR_PS_MODULATEALPHA_ADDCOLOR          0x2018A
#define HIDR_PS_MODULATECOLOR_ADDALPHA          0x2018C
#define HIDR_PS_MODULATEINVALPHA_ADDCOLOR       0x2018E
#define HIDR_PS_MODULATEINVCOLOR_ADDALPHA       0x20190
#define HIDR_PS_DOTPRODUCT3                     0x20192
#define HIDR_PS_MULTIPLYADD                     0x20194
#define HIDR_PS_LERP                            0x20196
#define HIDR_PS_SHADER                          0x20198
#define HIDR_PS_DETAILMAP                       0x2019A
#define HIDR_PS_MAP                             0x2019C
 
// ?? ?? (IDD_*) 
#define HIDD_ABOUTBOX                           0x20064
#define HIDD_ATTR_PAGE                          0x2006B
#define HIDD_DIALOG_PROGRESS                    0x20087
#define HIDD_DIALOG_ATTR                        0x20093
#define HIDD_TEXTURE                            0x20094
#define HIDD_DIALOG_ADDTEXTURE                  0x200A1
#define HIDD_DIALOG_PREVIEW                     0x200AF
#define HIDD_DIALOG_PLAYCTRL                    0x200B1
#define HIDD_PLAYCTRL_BAR                       0x200B4
#define HIDD_DIALOG_TIMESET                     0x200B6
#define HIDD_IMAGE                              0x200B9
#define HIDD_DIALOG_ADDMEDIA                    0x200BD
#define HIDD_MEDIA_BAR                          0x200C0
#define HIDD_DIALOG_ADDANIMATION                0x200C4
#define HIDD_ANIMATION                          0x200C7
#define HIDD_DIALOG_TIMESCALE                   0x200CA
#define HIDD_DIALOG_ADDMESH                     0x200CD
#define HIDD_MESH                               0x200D0
#define HIDD_OBJ_PAGE                           0x200D3
#define HIDD_OBJECT                             0x200D5
#define HIDD_DIALOG_EDITOBJ                     0x200E1
#define HIDD_SFX                                0x200E4
#define HIDD_PARTICLE                           0x200E6
#define HIDD_EXTMAP                             0x200E9
#define HIDD_DIALOG_FRAMESET                    0x200EC
#define HIDD_MAPOBJ                             0x200EF
#define HIDD_BSPMAP                             0x200F2
#define HIDD_DIALOG_ADDMAP                      0x200F5
#define HIDD_CONTROL                            0x200F8
#define HIDD_FRAME                              0x200FB
#define HIDD_DIALOG_FONT                        0x200FE
#define HIDD_DIALOG_MENU                        0x20101
#define HIDD_DIALOG_EXTMAP                      0x20103
#define HIDD_DIALOG_BUILDEM                     0x20105
#define HIDD_DIALOG_BUILD_HEIGHT                0x20107
#define HIDD_MAPSFX                             0x20109
#define HIDD_MAPSND                             0x2010B
#define HIDD_DIALOG_UPDATE                      0x2010D
#define HIDD_DIALOG_BSPMAP                      0x2010F
#define HIDD_DIALOG_BSPREBUILD                  0x20111
#define HIDD_MAPLIGHT                           0x20113
#define HIDD_DIALOG_BUILDSHADE                  0x20115
#define HIDD_DIALOG_BUILDSHADOW                 0x20117
#define HIDD_DIALOG_HIDE                        0x2019F
#define HIDD_DIALOG_FREEZE                      0x201A1
#define HIDD_DIALOG_SELBYNAME                   0x201AC
#define HIDD_DIALOG_SAVE_HEIGHTMAP              0x201B2
#define HIDD_DIALOG_SETFOV                      0x201B9
#define HIDD_DIALOG_EDITFOV                     0x201BA
#define HIDD_DIALOG_FOV                         0x201BB
#define HIDD_DIALOG_ITEM_ID_SEED                0x201BC
#define HIDD_DIALOG_SAVE_MINIMAP                0x201BD
#define HIDD_DIALOG_OBJECT_EXCHANGE             0x201BF
#define HIDD_DIALOG_IMPORT_OFFSET               0x201C5
#define HIDD_DIALOG_ADJUST_OBJ_POS              0x201C7
#define HIDD_DIALOG_LOAD_REGION_TEX             0x201C9
#define HIDD_DIALOG_FONT_EDIT_COLOR             0x201CA
#define HIDD_DIALOG_EDIT_ENABLE_UNIT            0x201CB
#define HIDD_DIALOG_EDIT_UNIT                   0x201CD
#define HIDD_DIALOG_EDIT_CLEAN_UNIT_OBJECT      0x201CE
#define HIDD_DIALOG_SETBACKIMG                  0x201D0
#define HIDD_DIALOG_DETAILTEXTURE               0x201D2
#define HIDD_DIALOG_SELECT_FORMAT               0x201D3
#define HIDD_DIALOG_ITEMFINDER                  0x201D4
#define HIDD_DIALOG_ITEMSCREENSHOT              0x201D5
#define HIDD_DIALOG_REPLACEDETTEX               0x201D6
 
// ??? ??? (IDW_*) 
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.

// Non-Client HitTest help IDs
#define HID_HT_NOWHERE                          0x40000
#define HID_HT_CAPTION                          0x40002
#define HID_HT_SIZE                             0x40004
#define HID_HT_HSCROLL                          0x40006
#define HID_HT_VSCROLL                          0x40007
#define HID_HT_MINBUTTON                        0x40008
#define HID_HT_MAXBUTTON                        0x40009
#define HID_HT_SIZE                             0x4000A // alias: ID_HT_LEFT
#define HID_HT_SIZE                             0x4000B // alias: ID_HT_RIGHT
#define HID_HT_SIZE                             0x4000C // alias: ID_HT_TOP
#define HID_HT_SIZE                             0x4000D // alias: ID_HT_TOPLEFT
#define HID_HT_SIZE                             0x4000E // alias: ID_HT_TOPRIGHT
#define HID_HT_SIZE                             0x4000F // alias: ID_HT_BOTTOM
#define HID_HT_SIZE                             0x40010 // alias: ID_HT_BOTTOMLEFT
#define HID_HT_SIZE                             0x40011 // alias: ID_HT_BOTTOMRIGHT
#define HID_HT_SIZE                             0x40012 // alias: ID_HT_BORDER
#define HID_HT_OBJECT							0x40013
#define HID_HT_CLOSE							0x40014
#define HID_HT_HELP								0x40015

// WM_SYSCOMMAND help IDs
#define HID_SC_SIZE                             0x1EF00
#define HID_SC_MOVE                             0x1EF01
#define HID_SC_MINIMIZE                         0x1EF02
#define HID_SC_MAXIMIZE                         0x1EF03
#define HID_SC_NEXTWINDOW                       0x1EF04
#define HID_SC_PREVWINDOW                       0x1EF05
#define HID_SC_CLOSE                            0x1EF06
#define HID_SC_RESTORE                          0x1EF12
#define HID_SC_TASKLIST                         0x1EF13

// File MRU and aliases
#define HID_FILE_MRU_FILE1                      0x1E110
#define HID_FILE_MRU_FILE1                      0x1E111 // aliases: MRU_2 - MRU_16
#define HID_FILE_MRU_FILE1                      0x1E112
#define HID_FILE_MRU_FILE1                      0x1E113
#define HID_FILE_MRU_FILE1                      0x1E114
#define HID_FILE_MRU_FILE1                      0x1E115
#define HID_FILE_MRU_FILE1                      0x1E116
#define HID_FILE_MRU_FILE1                      0x1E117
#define HID_FILE_MRU_FILE1                      0x1E118
#define HID_FILE_MRU_FILE1                      0x1E119
#define HID_FILE_MRU_FILE1                      0x1E11A
#define HID_FILE_MRU_FILE1                      0x1E11B
#define HID_FILE_MRU_FILE1                      0x1E11C
#define HID_FILE_MRU_FILE1                      0x1E11D
#define HID_FILE_MRU_FILE1                      0x1E11E
#define HID_FILE_MRU_FILE1                      0x1E11F

// Window menu list
#define HID_WINDOW_ALL                          0x1EF1F

// OLE menu and aliases
#define HID_OLE_VERB_1                          0x1E210
#define HID_OLE_VERB_1                          0x1E211 // aliases: VERB_2 -> VERB_16
#define HID_OLE_VERB_1                          0x1E212
#define HID_OLE_VERB_1                          0x1E213
#define HID_OLE_VERB_1                          0x1E214
#define HID_OLE_VERB_1                          0x1E215
#define HID_OLE_VERB_1                          0x1E216
#define HID_OLE_VERB_1                          0x1E217
#define HID_OLE_VERB_1                          0x1E218
#define HID_OLE_VERB_1                          0x1E219
#define HID_OLE_VERB_1                          0x1E21A
#define HID_OLE_VERB_1                          0x1E21B
#define HID_OLE_VERB_1                          0x1E21C
#define HID_OLE_VERB_1                          0x1E21D
#define HID_OLE_VERB_1                          0x1E21E
#define HID_OLE_VERB_1                          0x1E21F

// Commands (HID_*) 
#define HID_FILE_NEW                            0x1E100
#define HID_FILE_OPEN                           0x1E101
#define HID_FILE_CLOSE                          0x1E102
#define HID_FILE_SAVE                           0x1E103
#define HID_FILE_SAVE_AS                        0x1E104
#define HID_FILE_PAGE_SETUP                     0x1E105
#define HID_FILE_PRINT_SETUP                    0x1E106
#define HID_FILE_PRINT                          0x1E107
#define HID_FILE_PRINT_DIRECT                   0x1E108
#define HID_FILE_PRINT_PREVIEW                  0x1E109
#define HID_FILE_UPDATE                         0x1E10A
#define HID_FILE_SAVE_COPY_AS                   0x1E10B
#define HID_FILE_SEND_MAIL                      0x1E10C
#define HID_EDIT_CLEAR                          0x1E120
#define HID_EDIT_CLEAR_ALL                      0x1E121
#define HID_EDIT_COPY                           0x1E122
#define HID_EDIT_CUT                            0x1E123
#define HID_EDIT_FIND                           0x1E124
#define HID_EDIT_PASTE                          0x1E125
#define HID_EDIT_PASTE_LINK                     0x1E126
#define HID_EDIT_PASTE_SPECIAL                  0x1E127
#define HID_EDIT_REPEAT                         0x1E128
#define HID_EDIT_REPLACE                        0x1E129
#define HID_EDIT_SELECT_ALL                     0x1E12A
#define HID_EDIT_UNDO                           0x1E12B
#define HID_EDIT_REDO                           0x1E12C
#define HID_WINDOW_NEW                          0x1E130
#define HID_WINDOW_ARRANGE                      0x1E131
#define HID_WINDOW_CASCADE                      0x1E132
#define HID_WINDOW_TILE_HORZ                    0x1E133
#define HID_WINDOW_TILE_VERT                    0x1E134
#define HID_WINDOW_SPLIT                        0x1E135
#define HID_APP_ABOUT                           0x1E140
#define HID_APP_EXIT                            0x1E141
#define HID_HELP_INDEX                          0x1E142
#define HID_HELP_FINDER                         0x1E143
#define HID_HELP_USING                          0x1E144
#define HID_CONTEXT_HELP                        0x1E145
#define HID_NEXT_PANE                           0x1E150
#define HID_PREV_PANE                           0x1E151
#define HID_FORMAT_FONT                         0x1E160
#define HID_OLE_INSERT_NEW                      0x1E200
#define HID_OLE_EDIT_LINKS                      0x1E201
#define HID_OLE_EDIT_CONVERT                    0x1E202
#define HID_OLE_EDIT_CHANGE_ICON                0x1E203
#define HID_OLE_EDIT_PROPERTIES                 0x1E204
#define HID_VIEW_TOOLBAR                        0x1E800
#define HID_VIEW_STATUS_BAR                     0x1E801
#define HID_RECORD_FIRST                        0x1E900
#define HID_RECORD_LAST                         0x1E901
#define HID_RECORD_NEXT                         0x1E902
#define HID_RECORD_PREV                         0x1E903
#define HID_WIZBACK                             0x13023
#define HID_WIZNEXT                             0x13024
#define HID_WIZFINISH                           0x13025

// Dialogs (AFX_HIDD_*)
#define AFX_HIDD_FILEOPEN                       0x27004
#define AFX_HIDD_FILESAVE                       0x27005
#define AFX_HIDD_FONT                           0x27006
#define AFX_HIDD_COLOR                          0x27007
#define AFX_HIDD_PRINT                          0x27008
#define AFX_HIDD_PRINTSETUP                     0x27009
#define AFX_HIDD_FIND                           0x2700A
#define AFX_HIDD_REPLACE                        0x2700B
#define AFX_HIDD_NEWTYPEDLG                     0x27801
#define AFX_HIDD_PRINTDLG                       0x27802
#define AFX_HIDD_PREVIEW_TOOLBAR                0x27803
#define AFX_HIDD_PREVIEW_SHORTTOOLBAR           0x2780B
#define AFX_HIDD_INSERTOBJECT                   0x27804
#define AFX_HIDD_CHANGEICON                     0x27805
#define AFX_HIDD_CONVERT                        0x27806
#define AFX_HIDD_PASTESPECIAL                   0x27807
#define AFX_HIDD_EDITLINKS                      0x27808
#define AFX_HIDD_FILEBROWSE                     0x27809
#define AFX_HIDD_BUSY                           0x2780A
#define AFX_HIDD_OBJECTPROPERTIES               0x2780C
#define AFX_HIDD_CHANGESOURCE                   0x2780D

// Prompts/Errors (AFX_HIDP_*)
#define AFX_HIDP_NO_ERROR_AVAILABLE             0x3F020
#define AFX_HIDP_INVALID_FILENAME               0x3F100
#define AFX_HIDP_FAILED_TO_OPEN_DOC             0x3F101
#define AFX_HIDP_FAILED_TO_SAVE_DOC             0x3F102
#define AFX_HIDP_ASK_TO_SAVE                    0x3F103
#define AFX_HIDP_FAILED_TO_CREATE_DOC           0x3F104
#define AFX_HIDP_FILE_TOO_LARGE                 0x3F105
#define AFX_HIDP_FAILED_TO_START_PRINT          0x3F106
#define AFX_HIDP_FAILED_TO_LAUNCH_HELP          0x3F107
#define AFX_HIDP_INTERNAL_FAILURE               0x3F108
#define AFX_HIDP_COMMAND_FAILURE                0x3F109
#define AFX_HIDP_FAILED_MEMORY_ALLOC            0x3F10A
#define AFX_HIDP_UNREG_DONE                     0x3F10B
#define AFX_HIDP_UNREG_FAILURE                  0x3F10C
#define AFX_HIDP_DLL_LOAD_FAILED                0x3F10D
#define AFX_HIDP_DLL_BAD_VERSION                0x3F10E
#define AFX_HIDP_PARSE_INT                      0x3F110
#define AFX_HIDP_PARSE_REAL                     0x3F111
#define AFX_HIDP_PARSE_INT_RANGE                0x3F112
#define AFX_HIDP_PARSE_REAL_RANGE               0x3F113
#define AFX_HIDP_PARSE_STRING_SIZE              0x3F114
#define AFX_HIDP_PARSE_RADIO_BUTTON             0x3F115
#define AFX_HIDP_PARSE_BYTE                     0x3F116
#define AFX_HIDP_PARSE_UINT                     0x3F117
#define AFX_HIDP_PARSE_DATETIME                 0x3F118
#define AFX_HIDP_PARSE_CURRENCY                 0x3F119
#define AFX_HIDP_FAILED_INVALID_FORMAT          0x3F120
#define AFX_HIDP_FAILED_INVALID_PATH            0x3F121
#define AFX_HIDP_FAILED_DISK_FULL               0x3F122
#define AFX_HIDP_FAILED_ACCESS_READ             0x3F123
#define AFX_HIDP_FAILED_ACCESS_WRITE            0x3F124
#define AFX_HIDP_FAILED_IO_ERROR_READ           0x3F125
#define AFX_HIDP_FAILED_IO_ERROR_WRITE          0x3F126
#define AFX_HIDP_STATIC_OBJECT                  0x3F180
#define AFX_HIDP_FAILED_TO_CONNECT              0x3F181
#define AFX_HIDP_SERVER_BUSY                    0x3F182
#define AFX_HIDP_BAD_VERB                       0x3F183
#define AFX_HIDP_FAILED_TO_NOTIFY               0x3F185
#define AFX_HIDP_FAILED_TO_LAUNCH               0x3F186
#define AFX_HIDP_ASK_TO_UPDATE                  0x3F187
#define AFX_HIDP_FAILED_TO_UPDATE               0x3F188
#define AFX_HIDP_FAILED_TO_REGISTER             0x3F189
#define AFX_HIDP_FAILED_TO_AUTO_REGISTER        0x3F18A
#define AFX_HIDP_FAILED_TO_CONVERT              0x3F18B
#define AFX_HIDP_GET_NOT_SUPPORTED              0x3F18C
#define AFX_HIDP_SET_NOT_SUPPORTED              0x3F18D
#define AFX_HIDP_ASK_TO_DISCARD                 0x3F18E
#define AFX_HIDP_FAILED_TO_CREATE               0x3F18F
#define AFX_HIDP_FAILED_MAPI_LOAD               0x3F190
#define AFX_HIDP_INVALID_MAPI_DLL               0x3F191
#define AFX_HIDP_FAILED_MAPI_SEND               0x3F192
#define AFX_HIDP_FILE_NONE                      0x3F1A0
#define AFX_HIDP_FILE_GENERIC                   0x3F1A1
#define AFX_HIDP_FILE_NOT_FOUND                 0x3F1A2
#define AFX_HIDP_FILE_BAD_PATH                  0x3F1A3
#define AFX_HIDP_FILE_TOO_MANY_OPEN             0x3F1A4
#define AFX_HIDP_FILE_ACCESS_DENIED             0x3F1A5
#define AFX_HIDP_FILE_INVALID_FILE              0x3F1A6
#define AFX_HIDP_FILE_REMOVE_CURRENT            0x3F1A7
#define AFX_HIDP_FILE_DIR_FULL                  0x3F1A8
#define AFX_HIDP_FILE_BAD_SEEK                  0x3F1A9
#define AFX_HIDP_FILE_HARD_IO                   0x3F1AA
#define AFX_HIDP_FILE_SHARING                   0x3F1AB
#define AFX_HIDP_FILE_LOCKING                   0x3F1AC
#define AFX_HIDP_FILE_DISKFULL                  0x3F1AD
#define AFX_HIDP_FILE_EOF                       0x3F1AE
#define AFX_HIDP_ARCH_NONE                      0x3F1B0
#define AFX_HIDP_ARCH_GENERIC                   0x3F1B1
#define AFX_HIDP_ARCH_READONLY                  0x3F1B2
#define AFX_HIDP_ARCH_ENDOFFILE                 0x3F1B3
#define AFX_HIDP_ARCH_WRITEONLY                 0x3F1B4
#define AFX_HIDP_ARCH_BADINDEX                  0x3F1B5
#define AFX_HIDP_ARCH_BADCLASS                  0x3F1B6
#define AFX_HIDP_ARCH_BADSCHEMA                 0x3F1B7
#define AFX_HIDP_SQL_CONNECT_FAIL               0x3F281
#define AFX_HIDP_SQL_RECORDSET_FORWARD_ONLY     0x3F282
#define AFX_HIDP_SQL_EMPTY_COLUMN_LIST          0x3F283
#define AFX_HIDP_SQL_FIELD_SCHEMA_MISMATCH      0x3F284
#define AFX_HIDP_SQL_ILLEGAL_MODE               0x3F285
#define AFX_HIDP_SQL_MULTIPLE_ROWS_AFFECTED     0x3F286
#define AFX_HIDP_SQL_NO_CURRENT_RECORD          0x3F287
#define AFX_HIDP_SQL_NO_ROWS_AFFECTED           0x3F288
#define AFX_HIDP_SQL_RECORDSET_READONLY         0x3F289
#define AFX_HIDP_SQL_SQL_NO_TOTAL               0x3F28A
#define AFX_HIDP_SQL_ODBC_LOAD_FAILED           0x3F28B
#define AFX_HIDP_SQL_DYNASET_NOT_SUPPORTED      0x3F28C
#define AFX_HIDP_SQL_SNAPSHOT_NOT_SUPPORTED     0x3F28D
#define AFX_HIDP_SQL_API_CONFORMANCE            0x3F28E
#define AFX_HIDP_SQL_SQL_CONFORMANCE            0x3F28F
#define AFX_HIDP_SQL_NO_DATA_FOUND              0x3F290
#define AFX_HIDP_SQL_ROW_UPDATE_NOT_SUPPORTED   0x3F291
#define AFX_HIDP_SQL_ODBC_V2_REQUIRED           0x3F292
#define AFX_HIDP_SQL_NO_POSITIONED_UPDATES      0x3F293
#define AFX_HIDP_SQL_LOCK_MODE_NOT_SUPPORTED    0x3F294
#define AFX_HIDP_SQL_DATA_TRUNCATED             0x3F295
#define AFX_HIDP_SQL_ROW_FETCH                  0x3F296
#define AFX_HIDP_SQL_INCORRECT_ODBC             0x3F297
#define AFX_HIDP_SQL_UPDATE_DELETE_FAILED       0x3F298
#define AFX_HIDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED	0x3F299
#define AFX_HIDP_SQL_FIELD_NOT_FOUND            0x3F29A
#define AFX_HIDP_SQL_BOOKMARKS_NOT_SUPPORTED    0x3F29B
#define AFX_HIDP_SQL_BOOKMARKS_NOT_ENABLED      0x3F29C
#define AFX_HIDP_DAO_ENGINE_INITIALIZATION      0x3F2B0
#define AFX_HIDP_DAO_DFX_BIND                   0x3F2B1
#define AFX_HIDP_DAO_OBJECT_NOT_OPEN            0x3F2B2
#define AFX_HIDP_DAO_ROWTOOSHORT                0x3F2B3
#define AFX_HIDP_DAO_BADBINDINFO                0x3F2B4
#define AFX_HIDP_DAO_COLUMNUNAVAILABLE          0x3F2B5

// Frame Controls (AFX_HIDW_*)
#define AFX_HIDW_TOOLBAR                        0x5E800
#define AFX_HIDW_STATUS_BAR                     0x5E801
#define AFX_HIDW_PREVIEW_BAR                    0x5E802
#define AFX_HIDW_RESIZE_BAR                     0x5E803
#define AFX_HIDW_DOCKBAR_TOP                    0x5E81B
#define AFX_HIDW_DOCKBAR_LEFT                   0x5E81C
#define AFX_HIDW_DOCKBAR_RIGHT                  0x5E81D
#define AFX_HIDW_DOCKBAR_BOTTOM                 0x5E81E
#define AFX_HIDW_DOCKBAR_FLOAT                  0x5E81F

/////////////////////////////////////////////////////////////////////////////
