//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LogTool.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LOGTOOL_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDR_TRAICON                     128
#define IDR_TRAICON3                    128
#define IDR_MENU                        147
#define IDR_TOOLBAR                     148
#define IDD_DIALOG_SEARCH               152
#define IDR_POPUP                       153
#define IDD_DIALOG_SEARCH_CHINESS       154
#define IDD_LOGTOOL_DIALOG_CHINESS      155
#define IDR_MENU_CHINESS                156
#define IDD_DIALOG_CONNECT              157
#define IDD_DIALOG_DETAIL               158
#define IDR_POPUP_DEVELOPER             161
#define IDD_DIALOG_RESTORE              162
#define IDR_ACCELERATOR                 163
#define IDR_TRAICON2                    166
#define IDC_LIST                        1000
#define IDC_BUTTON_SEARCH               1001
#define IDC_STATIC_MSG                  1002
#define IDC_BUTTON_PREV                 1003
#define IDC_DATETIMEPICKER              1004
#define IDC_BUTTON_NEXT                 1004
#define IDC_EDIT_FROM                   1005
#define IDC_BUTTON_ALL                  1005
#define IDC_EDIT_TO                     1007
#define IDC_EDIT_ITEM                   1008
#define IDC_EDIT_IDTO                   1008
#define IDC_CHECK_DATE                  1009
#define IDC_CHECK_FROM                  1010
#define IDC_CHECK_ACTION                1011
#define IDC_CHECK_TO                    1012
#define IDC_CHECK_ITEM                  1013
#define IDC_CHECK_LOCATION              1014
#define IDC_COMBO_ACTION                1015
#define IDC_COMBO_LOCATION              1016
#define IDC_COMBO_CONNECT               1016
#define IDC_EDIT_X                      1017
#define IDC_LIST_DETAIL                 1017
#define IDC_EDIT_Y                      1018
#define IDC_CHECK_COORDINATE            1019
#define IDC_CHECK_MAPID                 1020
#define IDC_EDIT_MAPID                  1021
#define IDC_CHECK_TIME                  1022
#define IDC_EDIT_TIMEFROM               1023
#define IDC_EDIT_TIMETO                 1024
#define IDC_COMBO_ITEMTYPE              1025
#define IDC_DATETIME                    1026
#define IDC_CHECK_IDFROM                1027
#define IDC_DATETIME2                   1029
#define IDC_COMBO_ITEM                  1030
#define IDC_COMBO_ITEM2                 1031
#define IDC_STATIC_SERVER               1031
#define IDC_EDIT_SEQNUM                 1032
#define IDC_EDIT_ACCID                  1032
#define IDC_EDIT_UNIQNUM                1033
#define IDC_EDIT_CHARID                 1033
#define IDC_EDIT_BASENUM                1034
#define IDC_EDIT_RESTORER               1034
#define IDC_CHECK_SEQNUM                1035
#define IDC_CHECK_RESTORE               1035
#define IDC_CHECK_UNIQNUM               1036
#define IDC_ACCOUNT                     1036
#define IDC_CHECK_BASENUM               1037
#define IDC_PASSWORD                    1037
#define IDC_CHECK_KEY1                  1038
#define IDC_CHECK_KEY2                  1039
#define IDC_CHECK_KEY3                  1040
#define IDC_CHECK_KEY4                  1041
#define IDC_CHECK_KEY5                  1042
#define IDC_EDIT_KEY1                   1043
#define IDC_EDIT_KEY2                   1044
#define IDC_EDIT_KEY3                   1045
#define IDC_EDIT_KEY4                   1046
#define IDC_EDIT_KEY5                   1047
#define IDC_CHECK_KEY6                  1048
#define IDC_CHECK_KEY7                  1049
#define IDC_EDIT_KEY6                   1050
#define IDC_EDIT_KEY7                   1051
#define IDC_CHECK_IP                    1052
#define IDC_EDIT_IP                     1053
#define IDC_CHECK_DK1                   1054
#define IDC_EDIT_DK1                    1055
#define IDC_CHECK_DK2                   1056
#define IDC_EDIT_DK2                    1057
#define IDC_CHECK_DK3                   1058
#define IDC_EDIT_DK3                    1059
#define IDC_CHECK_DK4                   1060
#define IDC_EDIT_DK4                    1061
#define IDC_CHECK_DK5                   1062
#define IDC_EDIT_DK5                    1063
#define IDC_CHECK_DK6                   1064
#define IDC_EDIT_DK6                    1065
#define IDC_CHECK_DK7                   1066
#define IDC_EDIT_DK7                    1067
#define IDC_LIST_ACTION                 1068
#define IDC_ACTION_INSERT               1069
#define IDC_ACTION_DELETE               1070
#define IDC_LIST_CHAR                   1071
#define IDC_CHAR_INSERT                 1072
#define IDC_CHAR_DELETE                 1073
#define IDC_CHECK_LOG                   1074
#define IDC_EDIT_LOG                    1075
#define IDC_CHECK_DK8                   1076
#define IDC_CHECK_DK9                   1077
#define IDC_EDIT_DK8                    1078
#define IDC_EDIT_DK9                    1079
#define ID_TOOLBARBUTTON1               32771
#define ID_TOOLBAR_CONNECT              32771
#define ID_TOOLBARBUTTON2               32772
#define ID_TOOLBAR_SAVE                 32772
#define ID_TOOLBARBUTTON3               32773
#define ID_TOOLBAR_SEARCH               32773
#define ID_CONNECT                      32774
#define ID_FUNCTION                     32775
#define ID_SEARCH                       32775
#define ID_INFO                         32776
#define ID_SAVE                         32777
#define ID_QUIT                         32778
#define ID_POPUP_SEARCH                 32779
#define ID_POPUP_RESTORE                32780
#define ID_ACCEL_SELECTALL              32781
#define ID_ACCEL_CONNECT                32782
#define ID_ACCEL_SAVE                   -32753
#define ID_ACCEL_QUIT                   32784
#define ID_ACCEL_SEARCH                 32785
#define ID_ACCEL_COPY                   32786
#define ID_MENU_SAVELOGCOLUMN           32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
