// UnitDlg.cpp : 구현 파일입니다.
//

#include "stdafx.h"
#include "TPathTime.h"
#include "UnitDlg.h"


DWORD CUnitDlg::m_vControl[TUNITCOUNT_X][TUNITCOUNT_Z] = {{
	IDC_BUTTON_UNIT_00,
	IDC_BUTTON_UNIT_01,
	IDC_BUTTON_UNIT_02,
	IDC_BUTTON_UNIT_03,
	IDC_BUTTON_UNIT_04,
	IDC_BUTTON_UNIT_05,
	IDC_BUTTON_UNIT_06,
	IDC_BUTTON_UNIT_07}, {
	IDC_BUTTON_UNIT_10,
	IDC_BUTTON_UNIT_11,
	IDC_BUTTON_UNIT_12,
	IDC_BUTTON_UNIT_13,
	IDC_BUTTON_UNIT_14,
	IDC_BUTTON_UNIT_15,
	IDC_BUTTON_UNIT_16,
	IDC_BUTTON_UNIT_17}, {
	IDC_BUTTON_UNIT_20,
	IDC_BUTTON_UNIT_21,
	IDC_BUTTON_UNIT_22,
	IDC_BUTTON_UNIT_23,
	IDC_BUTTON_UNIT_24,
	IDC_BUTTON_UNIT_25,
	IDC_BUTTON_UNIT_26,
	IDC_BUTTON_UNIT_27}, {
	IDC_BUTTON_UNIT_30,
	IDC_BUTTON_UNIT_31,
	IDC_BUTTON_UNIT_32,
	IDC_BUTTON_UNIT_33,
	IDC_BUTTON_UNIT_34,
	IDC_BUTTON_UNIT_35,
	IDC_BUTTON_UNIT_36,
	IDC_BUTTON_UNIT_37}, {
	IDC_BUTTON_UNIT_40,
	IDC_BUTTON_UNIT_41,
	IDC_BUTTON_UNIT_42,
	IDC_BUTTON_UNIT_43,
	IDC_BUTTON_UNIT_44,
	IDC_BUTTON_UNIT_45,
	IDC_BUTTON_UNIT_46,
	IDC_BUTTON_UNIT_47}, {
	IDC_BUTTON_UNIT_50,
	IDC_BUTTON_UNIT_51,
	IDC_BUTTON_UNIT_52,
	IDC_BUTTON_UNIT_53,
	IDC_BUTTON_UNIT_54,
	IDC_BUTTON_UNIT_55,
	IDC_BUTTON_UNIT_56,
	IDC_BUTTON_UNIT_57}, {
	IDC_BUTTON_UNIT_60,
	IDC_BUTTON_UNIT_61,
	IDC_BUTTON_UNIT_62,
	IDC_BUTTON_UNIT_63,
	IDC_BUTTON_UNIT_64,
	IDC_BUTTON_UNIT_65,
	IDC_BUTTON_UNIT_66,
	IDC_BUTTON_UNIT_67}};

// CUnitDlg 대화 상자입니다.

IMPLEMENT_DYNAMIC(CUnitDlg, CDialog)
CUnitDlg::CUnitDlg(CWnd* pParent /*=NULL*/)
	: CDialog(CUnitDlg::IDD, pParent)
{
	m_wUnitID = 0;
}

CUnitDlg::~CUnitDlg()
{
}

void CUnitDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
}


BEGIN_MESSAGE_MAP(CUnitDlg, CDialog)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_00, OnBnClickedButtonUnit00)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_01, OnBnClickedButtonUnit01)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_02, OnBnClickedButtonUnit02)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_03, OnBnClickedButtonUnit03)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_04, OnBnClickedButtonUnit04)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_05, OnBnClickedButtonUnit05)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_06, OnBnClickedButtonUnit06)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_07, OnBnClickedButtonUnit07)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_10, OnBnClickedButtonUnit10)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_11, OnBnClickedButtonUnit11)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_12, OnBnClickedButtonUnit12)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_13, OnBnClickedButtonUnit13)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_14, OnBnClickedButtonUnit14)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_15, OnBnClickedButtonUnit15)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_16, OnBnClickedButtonUnit16)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_17, OnBnClickedButtonUnit17)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_20, OnBnClickedButtonUnit20)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_21, OnBnClickedButtonUnit21)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_22, OnBnClickedButtonUnit22)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_23, OnBnClickedButtonUnit23)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_24, OnBnClickedButtonUnit24)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_25, OnBnClickedButtonUnit25)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_26, OnBnClickedButtonUnit26)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_27, OnBnClickedButtonUnit27)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_30, OnBnClickedButtonUnit30)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_31, OnBnClickedButtonUnit31)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_32, OnBnClickedButtonUnit32)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_33, OnBnClickedButtonUnit33)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_34, OnBnClickedButtonUnit34)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_35, OnBnClickedButtonUnit35)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_36, OnBnClickedButtonUnit36)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_37, OnBnClickedButtonUnit37)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_40, OnBnClickedButtonUnit40)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_41, OnBnClickedButtonUnit41)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_42, OnBnClickedButtonUnit42)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_43, OnBnClickedButtonUnit43)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_44, OnBnClickedButtonUnit44)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_45, OnBnClickedButtonUnit45)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_46, OnBnClickedButtonUnit46)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_47, OnBnClickedButtonUnit47)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_50, OnBnClickedButtonUnit50)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_51, OnBnClickedButtonUnit51)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_52, OnBnClickedButtonUnit52)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_53, OnBnClickedButtonUnit53)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_54, OnBnClickedButtonUnit54)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_55, OnBnClickedButtonUnit55)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_56, OnBnClickedButtonUnit56)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_57, OnBnClickedButtonUnit57)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_60, OnBnClickedButtonUnit60)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_61, OnBnClickedButtonUnit61)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_62, OnBnClickedButtonUnit62)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_63, OnBnClickedButtonUnit63)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_64, OnBnClickedButtonUnit64)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_65, OnBnClickedButtonUnit65)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_66, OnBnClickedButtonUnit66)
	ON_BN_CLICKED(IDC_BUTTON_UNIT_67, OnBnClickedButtonUnit67)
END_MESSAGE_MAP()

#define FN_UNIT_CLICKED( x, y)			void CUnitDlg::OnBnClickedButtonUnit##x##y()\
{\
	m_wUnitID = MAKEWORD( BYTE(x), BYTE(y));\
	UpdateUNIT();\
}

FN_UNIT_CLICKED( 0, 0)
FN_UNIT_CLICKED( 0, 1)
FN_UNIT_CLICKED( 0, 2)
FN_UNIT_CLICKED( 0, 3)
FN_UNIT_CLICKED( 0, 4)
FN_UNIT_CLICKED( 0, 5)
FN_UNIT_CLICKED( 0, 6)
FN_UNIT_CLICKED( 0, 7)
FN_UNIT_CLICKED( 1, 0)
FN_UNIT_CLICKED( 1, 1)
FN_UNIT_CLICKED( 1, 2)
FN_UNIT_CLICKED( 1, 3)
FN_UNIT_CLICKED( 1, 4)
FN_UNIT_CLICKED( 1, 5)
FN_UNIT_CLICKED( 1, 6)
FN_UNIT_CLICKED( 1, 7)
FN_UNIT_CLICKED( 2, 0)
FN_UNIT_CLICKED( 2, 1)
FN_UNIT_CLICKED( 2, 2)
FN_UNIT_CLICKED( 2, 3)
FN_UNIT_CLICKED( 2, 4)
FN_UNIT_CLICKED( 2, 5)
FN_UNIT_CLICKED( 2, 6)
FN_UNIT_CLICKED( 2, 7)
FN_UNIT_CLICKED( 3, 0)
FN_UNIT_CLICKED( 3, 1)
FN_UNIT_CLICKED( 3, 2)
FN_UNIT_CLICKED( 3, 3)
FN_UNIT_CLICKED( 3, 4)
FN_UNIT_CLICKED( 3, 5)
FN_UNIT_CLICKED( 3, 6)
FN_UNIT_CLICKED( 3, 7)
FN_UNIT_CLICKED( 4, 0)
FN_UNIT_CLICKED( 4, 1)
FN_UNIT_CLICKED( 4, 2)
FN_UNIT_CLICKED( 4, 3)
FN_UNIT_CLICKED( 4, 4)
FN_UNIT_CLICKED( 4, 5)
FN_UNIT_CLICKED( 4, 6)
FN_UNIT_CLICKED( 4, 7)
FN_UNIT_CLICKED( 5, 0)
FN_UNIT_CLICKED( 5, 1)
FN_UNIT_CLICKED( 5, 2)
FN_UNIT_CLICKED( 5, 3)
FN_UNIT_CLICKED( 5, 4)
FN_UNIT_CLICKED( 5, 5)
FN_UNIT_CLICKED( 5, 6)
FN_UNIT_CLICKED( 5, 7)
FN_UNIT_CLICKED( 6, 0)
FN_UNIT_CLICKED( 6, 1)
FN_UNIT_CLICKED( 6, 2)
FN_UNIT_CLICKED( 6, 3)
FN_UNIT_CLICKED( 6, 4)
FN_UNIT_CLICKED( 6, 5)
FN_UNIT_CLICKED( 6, 6)
FN_UNIT_CLICKED( 6, 7)


// CUnitDlg 메시지 처리기입니다.

BOOL CUnitDlg::OnInitDialog()
{
	CDialog::OnInitDialog();

	HICON hIcon = AfxGetApp()->LoadIcon(IDR_MAINFRAME);
	SetIcon( hIcon, FALSE);
	SetIcon( hIcon, TRUE);
	UpdateUNIT();

	return TRUE;
}

void CUnitDlg::UpdateUNIT()
{
	for( BYTE i=0; i<TUNITCOUNT_Z; i++)
		for( BYTE j=0; j<TUNITCOUNT_X; j++)
		{
			CButton *pTBUTTON = (CButton *) GetDlgItem(m_vControl[j][i]);
			pTBUTTON->SetCheck( m_wUnitID == MAKEWORD( j, i) ? BST_CHECKED : BST_UNCHECKED);
		}
}
