#ifndef __TCMLTAG_H
#define __TCMLTAG_H

#include "ItemBase.h"
#include "TCML.h"

#define MTAG_OPENBRACE				_T("<")
#define MTAG_CLOSEBRACE				_T(">")
#define MTAG_COMMA					_T(",")
#define MTAG_EQUAL					_T("=")
#define MTAG_SLASH					_T("/")
#define MTAG_SPACE					_T(" ")
#define MTAG_QUOTATION				_T("\"")
#define MTAG_TAB					_T("\t")
#define MTAG_NEWLINE				_T("\n")

#define HTAG_TCML					_T("TCML")
#define HTAG_HEAD					_T("HEAD")
#define HTAG_DEFINE					_T("DEFINE")
#define HTAG_FRAME					_T("FRAME")
#define HTAG_BUTTON					_T("BUTTON")
#define HTAG_SCROLL					_T("SCROLL")
#define HTAG_EDIT					_T("EDIT")
#define HTAG_LIST					_T("LIST")
#define HTAG_COMBO					_T("COMBO")
#define HTAG_GAUGE					_T("GAUGE")
#define HTAG_IMAGELIST				_T("IMAGELIST")
#define HTAG_COMPONENT				_T("COMPONENT")
#define	HTAG_METER					_T("METER")
#define HTAG_TABCTRL				_T("TABCTRL")

#define ATAG_ID						_T("ID")
#define ATAG_DEFAULT				_T("DEFAULT")
#define ATAG_DISABLE				_T("DISABLE")
#define ATAG_TEXT					_T("TEXT")
#define ATAG_HMARGINE				_T("HMARGINE")
#define ATAG_VMARGINE				_T("VMARGINE")
#define ATAG_POSX					_T("POSX")
#define ATAG_POSY					_T("POSY")
#define ATAG_WIDTH					_T("WIDTH")
#define ATAG_HEIGHT					_T("HEIGHT")
#define ATAG_ALIGN					_T("ALIGN")
#define ATAG_ENABLE					_T("ENABLE")
#define ATAG_FONT					_T("FONT")
#define ATAG_TIPFONT				_T("TIPFONT")
#define ATAG_COLOR					_T("COLOR")
#define ATAG_LCLICK					_T("LCLICK")
#define ATAG_RCLICK					_T("RCLICK")
#define ATAG_DBLCLICK				_T("DBLCLICK")
#define ATAG_LINEUP					_T("LINEUP")
#define ATAG_LINEDOWN				_T("LINEDOWN")
#define ATAG_VSCROLL				_T("VSCROLL")
#define ATAG_HSCROLL				_T("HSCROLL")
#define ATAG_SEL_CHANGE				_T("SELCHANGE")
#define ATAG_TAB_ACTIVE				_T("TABACTIVE")
#define ATAG_ENTER					_T("ENTER")
#define ATAG_ESC					_T("ESC")
#define ATAG_FACENAME				_T("FACENAME")
#define ATAG_ESCAPEMENT				_T("ESCAPEMENT")
#define ATAG_ORIENTATION			_T("ORIENTATION")
#define ATAG_WEIGHT					_T("WEIGHT")
#define ATAG_ITALIC					_T("ITALIC")
#define ATAG_UNDERLINE				_T("UNDERLINE")
#define ATAG_STRIKEOUT				_T("STRIKEOUT")
#define ATAG_CHARSET				_T("CHARSET")
#define ATAG_OUTPRECISION			_T("OUTPRECISION")
#define ATAG_CLIPPRECISION			_T("CLIPPRECISION")
#define ATAG_QUALITY				_T("QUALITY")
#define ATAG_PITCHANDFAMILY			_T("PITCHANDFAMILY")
#define ATAG_FACECLR				_T("FACECLR")
#define ATAG_METER_SUPERLEVEL		_T("SUPERLEVEL")
#define ATAG_TOOLTIP				_T("TOOLTIP")
#define ATAG_SOUND					_T("SOUND")
#define ATAG_SOUND_DOWN				_T("SOUND_DOWN")
#define ATAG_SOUND_HOVER			_T("SOUND_HOVER")
#define ATAG_BUTTON_STATEBUTTON		_T("STATEBUTTON")
#define ATAG_EDIT_PASSWORD			_T("PASSWORD")

#define TAG_BUTTON_DOWN				_T("DOWN")
#define TAG_BUTTON_UP				_T("UP")
#define TAG_BUTTON_HOVER			_T("HOVER")
#define TAG_SCROLL_UL				_T("UL")
#define TAG_SCROLL_DR				_T("DR")
#define TAG_SCROLL_SCROLL			_T("BAR")
#define TAG_EDIT_CARET				_T("CARET")
#define TAG_LIST_ITEM				_T("ITEM")
#define TAG_LIST_VERTICAL			_T("VERTICAL")
#define TAG_COMBO_DROP				_T("DROP")
#define TAG_COMBO_DOWNLIST			_T("DOWNLIST")
#define TAG_GAUGE_BAR				_T("BAR")
#define TAG_METER_SUB				_T("SUB")
#define TAG_METER_SUPER				_T("SUPER")

#define DUPLICATION_NAME_COUNT		74

CString g_strDuplicationName[DUPLICATION_NAME_COUNT] = {
	HTAG_TCML,
	HTAG_HEAD,
	HTAG_DEFINE,
	HTAG_FRAME,
	HTAG_BUTTON,
	HTAG_SCROLL,
	HTAG_EDIT,
	HTAG_LIST,
	HTAG_COMBO,
	HTAG_GAUGE,
	HTAG_IMAGELIST,
	HTAG_COMPONENT,
	HTAG_METER,
	HTAG_TABCTRL,
	ATAG_ID,
	ATAG_DEFAULT,
	ATAG_DISABLE,
	ATAG_TEXT,
	ATAG_HMARGINE,
	ATAG_VMARGINE,
	ATAG_POSX,
	ATAG_POSY,
	ATAG_WIDTH,
	ATAG_HEIGHT,
	ATAG_ALIGN,
	ATAG_ENABLE,
	ATAG_FONT,
	ATAG_TIPFONT,
	ATAG_COLOR,
	ATAG_LCLICK,
	ATAG_RCLICK,
	ATAG_DBLCLICK,
	ATAG_LINEUP,
	ATAG_LINEDOWN,
	ATAG_VSCROLL,
	ATAG_HSCROLL,
	ATAG_SEL_CHANGE,
	ATAG_TAB_ACTIVE,
	ATAG_ENTER,
	ATAG_ESC,
	ATAG_FACENAME,
	ATAG_ESCAPEMENT,
	ATAG_ORIENTATION,
	ATAG_WEIGHT,
	ATAG_ITALIC,
	ATAG_UNDERLINE,
	ATAG_STRIKEOUT,
	ATAG_CHARSET,
	ATAG_OUTPRECISION,
	ATAG_CLIPPRECISION,
	ATAG_QUALITY,
	ATAG_PITCHANDFAMILY,
	ATAG_FACECLR,
	ATAG_METER_SUPERLEVEL,
	ATAG_TOOLTIP,
	ATAG_SOUND,
	ATAG_SOUND_DOWN,
	ATAG_SOUND_HOVER,
	ATAG_BUTTON_STATEBUTTON,
	ATAG_EDIT_PASSWORD,
	TAG_BUTTON_DOWN,
	TAG_BUTTON_UP,
	TAG_BUTTON_HOVER,
	TAG_SCROLL_UL,
	TAG_SCROLL_DR,
	TAG_SCROLL_SCROLL,
	TAG_EDIT_CARET,
	TAG_LIST_ITEM,
	TAG_LIST_VERTICAL,
	TAG_COMBO_DROP,
	TAG_COMBO_DOWNLIST,
	TAG_GAUGE_BAR,
	TAG_METER_SUB,
	TAG_METER_SUPER	
};

#endif // __TCMLTAG_H
